/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popup;

import constant.ConstReg;
import constant.Img;
import elcM.FrElcM;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import tools.ShiftPoint;
import up.StartApp;

/**
 *
 * @author branko.scekic
 */
public class PumpeFrScreen extends javax.swing.JFrame {

    /**
     * Creates new form PumpeScreen
     */
    public PumpeFrScreen(int x,int y, String title, String opis, FrElcM pumpa, Img img) {
        initComponents();
        this.pumpa = pumpa;
        this.img = img;
        jLabelNaziv.setText(opis);
        this.setTitle(title);
        this.setLocation(x-85, y-55);
        startScreenRefresh();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNaziv = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jToggleButtonOn = new javax.swing.JToggleButton();
        jToggleButtonOff = new javax.swing.JToggleButton();
        jButtonIzvrsi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonMinus01 = new javax.swing.JButton();
        jButtonMinus10 = new javax.swing.JButton();
        jButtonMInus100 = new javax.swing.JButton();
        jButtonPlus01 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonPlus100 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jLabelFrekfrencija = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabelNaziv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNaziv.setText("Naziv pumpe");

        jCheckBox1.setText("AUR  ");

        jToggleButtonOn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jToggleButtonOn.setText("Uključi");
        jToggleButtonOn.setEnabled(false);
        jToggleButtonOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOnActionPerformed(evt);
            }
        });

        jToggleButtonOff.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jToggleButtonOff.setText("Isključi");
        jToggleButtonOff.setEnabled(false);
        jToggleButtonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOffActionPerformed(evt);
            }
        });

        jButtonIzvrsi.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButtonIzvrsi.setForeground(new java.awt.Color(255, 0, 51));
        jButtonIzvrsi.setText("Izvrsi");
        jButtonIzvrsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzvrsiActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Otkaži");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonExit.setText("Izlaz");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonMinus01.setText("-0.1");
        jButtonMinus01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinus01ActionPerformed(evt);
            }
        });

        jButtonMinus10.setText("-1");
        jButtonMinus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinus10ActionPerformed(evt);
            }
        });

        jButtonMInus100.setText("-10");
        jButtonMInus100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMInus100ActionPerformed(evt);
            }
        });

        jButtonPlus01.setText("+0.1");
        jButtonPlus01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlus01ActionPerformed(evt);
            }
        });

        jButton1.setText("+1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonPlus100.setText("+10");
        jButtonPlus100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlus100ActionPerformed(evt);
            }
        });

        jButton0.setText("0%  ");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton50.setText("50%");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });

        jButton100.setText("100%");
        jButton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton100ActionPerformed(evt);
            }
        });

        jLabelFrekfrencija.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelFrekfrencija.setForeground(new java.awt.Color(255, 51, 102));
        jLabelFrekfrencija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFrekfrencija.setText("00.0 %");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonIzvrsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButtonOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButtonOff, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMinus01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFrekfrencija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPlus01))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMInus100, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPlus100, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMinus10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton100, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMinus01)
                    .addComponent(jButtonPlus01)
                    .addComponent(jLabelFrekfrencija))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMinus10)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMInus100)
                    .addComponent(jButtonPlus100))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton0)
                    .addComponent(jButton50)
                    .addComponent(jButton100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButtonOn, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jToggleButtonOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonIzvrsi, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOnActionPerformed
        offset = pumpa.getPcUkljuci();
        jToggleButtonOff.setSelected(false);   
    }//GEN-LAST:event_jToggleButtonOnActionPerformed

    private void jButtonIzvrsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzvrsiActionPerformed
        StartApp.comm.offset = offset;
        StartApp.comm.mxValue = true;
        StartApp.comm.writeDigital = true;
        jToggleButtonOn.setSelected(false);
        jToggleButtonOff.setSelected(false);
    }//GEN-LAST:event_jButtonIzvrsiActionPerformed

    private void jToggleButtonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOffActionPerformed
        offset = pumpa.getPcIskljuci();
        jToggleButtonOn.setSelected(false);
    }//GEN-LAST:event_jToggleButtonOffActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jToggleButtonOn.setSelected(false);
        jToggleButtonOff.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        startTimer(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonMinus01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinus01ActionPerformed
        offset = pumpa.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegMinus01;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonMinus01ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        offset = pumpa.getAnalogValue();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = 0;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        offset = pumpa.getAnalogValue();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = 500;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton100ActionPerformed
        offset = pumpa.getAnalogValue();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = 1000;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButton100ActionPerformed

    private void jButtonMinus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinus10ActionPerformed
        offset = pumpa.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegMinus1;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonMinus10ActionPerformed

    private void jButtonMInus100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMInus100ActionPerformed
        offset = pumpa.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegMinus10;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonMInus100ActionPerformed

    private void jButtonPlus01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlus01ActionPerformed
        offset = pumpa.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegPlus01;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonPlus01ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        offset = pumpa.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegPlus1;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPlus100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlus100ActionPerformed
        offset = pumpa.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegPlus10;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonPlus100ActionPerformed

     public void startTimer(boolean start){
        if(start){
            timer.start();
        }else{
            timer.stop();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonIzvrsi;
    private javax.swing.JButton jButtonMInus100;
    private javax.swing.JButton jButtonMinus01;
    private javax.swing.JButton jButtonMinus10;
    private javax.swing.JButton jButtonPlus01;
    private javax.swing.JButton jButtonPlus100;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabelFrekfrencija;
    private javax.swing.JLabel jLabelNaziv;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButtonOff;
    private javax.swing.JToggleButton jToggleButtonOn;
    // End of variables declaration//GEN-END:variables

    private final FrElcM pumpa;
    private int offset;
    private final Img img;
    private Timer timer;

    private void startScreenRefresh() {
        timer = new Timer(100, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) { 
                jToggleButtonOn.setEnabled(pumpa.getVrednosti().isEnableOn());
                jToggleButtonOff.setEnabled(pumpa.getVrednosti().isEnableOff());
                int a = pumpa.getVrednosti().getAnalognaVrednost();
                jLabelFrekfrencija.setText(ShiftPoint.shiftonePoint(a,1) + " %");     
                disposeTimer();
            }
        });

    }
    
    public void disposeTimer(){
        if(!this.isShowing()){
            timer.stop();
        }
    }
}
