/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popup;

import constant.Img;
import dbService.PumpeUpTimeService;
import elcM.ElcM;
import field.merenja.Merenja;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import up.StartApp;
import static utilise.MousePoint.GetMousePoint;
import static utilise.MousePoint.GetMousePointCentarDisplay;

/**
 *
 * @author branko.scekic
 */
public class PumpeSaZastitomScreen extends javax.swing.JFrame {

    /**
     * Creates new form PumpeScreen
     *
     * @param x
     * @param y
     * @param title
     * @param opis
     * @param pumpa
     * @param img
     * @param pumpeUpTimeService
     * @param merenja
     */
    public PumpeSaZastitomScreen(int x, int y, 
            String title, String opis, 
            ElcM pumpa, Img img, 
            Merenja merenja) {
        initComponents();
        this.pumpa = pumpa;
        this.img = img;
        jLabelNaziv.setText(opis);
        this.setTitle(title);
        this.setLocation(x - 85, y - 45);
        this.merenja = merenja;
        startScreenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNaziv = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabelStanje = new javax.swing.JLabel();
        jToggleButtonOn = new javax.swing.JToggleButton();
        jToggleButtonOff = new javax.swing.JToggleButton();
        jButtonIzvrsi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        vremeRada = new javax.swing.JLabel();
        jButtonOdrzavanje = new javax.swing.JButton();
        jButtonNivoi = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabelNaziv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNaziv.setText("Naziv pumpe");

        jCheckBox1.setText("AUR  ");

        jLabel1.setText("Lokalno        Iskljuceno        Daljinski");

        jLabelStanje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStanje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/screen/pumpa iskljucena.png"))); // NOI18N

        jToggleButtonOn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jToggleButtonOn.setText("Uključi");
        jToggleButtonOn.setEnabled(false);
        jToggleButtonOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOnActionPerformed(evt);
            }
        });

        jToggleButtonOff.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jToggleButtonOff.setText("Isključi");
        jToggleButtonOff.setEnabled(false);
        jToggleButtonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOffActionPerformed(evt);
            }
        });

        jButtonIzvrsi.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButtonIzvrsi.setForeground(new java.awt.Color(255, 0, 51));
        jButtonIzvrsi.setText("Izvrsi");
        jButtonIzvrsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzvrsiActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Otkaži");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        vremeRada.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        vremeRada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButtonOdrzavanje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/service.png"))); // NOI18N
        jButtonOdrzavanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdrzavanjeActionPerformed(evt);
            }
        });

        jButtonNivoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/NivoZastita.png"))); // NOI18N
        jButtonNivoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNivoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(vremeRada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonOdrzavanje, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelStanje, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonNivoi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButtonIzvrsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jToggleButtonOn))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jToggleButtonOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelNaziv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vremeRada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStanje, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOdrzavanje)
                    .addComponent(jButtonNivoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButtonOn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIzvrsi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleButtonOff, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jButtonExit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonExit.setText("Izlaz");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOnActionPerformed
        offset = pumpa.getPcUkljuci();
        jToggleButtonOff.setSelected(false);
        stanje = true;
    }//GEN-LAST:event_jToggleButtonOnActionPerformed

    
    
    private void jButtonIzvrsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzvrsiActionPerformed
        StartApp.comm.offset = offset;
        StartApp.comm.mxValue = true;
        StartApp.comm.writeDigital = true;
        jToggleButtonOn.setSelected(false);
        jToggleButtonOff.setSelected(false);
        if (stanje) {
            //pumpa.getTimeWork().start();
        } else if (!stanje) {
            //pumpa.getTimeWork().stop();
            //pumpeUpTimeService.updatePumpaRadniSati(pumpa.getTehnoloskaOznaka(), pumpa.getTimeWork().getHours(), pumpa.getTimeWork().getMinutes());
        }
    }//GEN-LAST:event_jButtonIzvrsiActionPerformed

    private void jToggleButtonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOffActionPerformed
        offset = pumpa.getPcIskljuci();
        jToggleButtonOn.setSelected(false);
        stanje = false;
    }//GEN-LAST:event_jToggleButtonOffActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jToggleButtonOn.setSelected(false);
        jToggleButtonOff.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        startTimer(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonOdrzavanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdrzavanjeActionPerformed
        if(pumpaOdrzavanjeScreen!=null){
            pumpaOdrzavanjeScreen.dispose();
        }
        Point p = GetMousePointCentarDisplay(MouseInfo.getPointerInfo().getLocation());
        pumpaOdrzavanjeScreen = new PumpaOdrzavanjeScreen(p, pumpa.getTehnoloskaOznaka());
        pumpaOdrzavanjeScreen.setVisible(true);
    }//GEN-LAST:event_jButtonOdrzavanjeActionPerformed

    private void jButtonNivoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNivoiActionPerformed
        Point p = GetMousePoint(MouseInfo.getPointerInfo().getLocation());
        boolean show = true;
        if (pumpaZastitaScreen == null) {
            pumpaZastitaScreen = new PumpaZastitaScreen(p, pumpa.getTehnoloskaOznaka(), merenja);
            //show = false;
        } 
        //else {
        //    prozor.dispose();
        //    prozor = new RegulacioniVentilElMotorScreen(p.x, p.y, grupa, opis, ventil, protok);
        //}
        pumpaZastitaScreen.startTimer(show);
        pumpaZastitaScreen.setLocation(p);
        pumpaZastitaScreen.setVisible(show);
    }//GEN-LAST:event_jButtonNivoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonIzvrsi;
    private javax.swing.JButton jButtonNivoi;
    private javax.swing.JButton jButtonOdrzavanje;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNaziv;
    private javax.swing.JLabel jLabelStanje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButtonOff;
    private javax.swing.JToggleButton jToggleButtonOn;
    private javax.swing.JLabel vremeRada;
    // End of variables declaration//GEN-END:variables

    private final ElcM pumpa;
    private int offset;
    private final Img img;
    private boolean stanje = false;
    private final Merenja merenja;
    private PumpaOdrzavanjeScreen pumpaOdrzavanjeScreen;
    private PumpaZastitaScreen pumpaZastitaScreen;
    private Timer timer;
 
     public void startTimer(boolean start){
        if(start){
            timer.start();
        }else{
            timer.stop();
        }
    }

    private void startScreenRefresh() {
        timer = new Timer(100, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                jToggleButtonOn.setEnabled(pumpa.getVrednosti().isEnableOn());
                jToggleButtonOff.setEnabled(pumpa.getVrednosti().isEnableOff());
                img.getStanjePumpeImg(jLabelStanje, pumpa.getVrednosti().isLokalno(), pumpa.getVrednosti().isDaljinski());
                disposeTimer();
                //vremeRada.setText(pumpa.getTimeWork().getHoursString() + ":" + pumpa.getTimeWork().getMinutesString());
            }
        });
    }
    
    public void disposeTimer(){
        if(!this.isShowing()){
            timer.stop();
        }
    }
}
