/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popup;

import field.merenja.Protok;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import tools.ShiftPoint;
import up.StartApp;
import static utilise.MousePoint.GetMousePoint;
import valve.reg.RegulacioniElMotVentil;

/**
 *
 * @author branko.scekic
 */
public class RegulacioniVentilElMotorImagPolozajScreen extends javax.swing.JFrame {

    /**
     * Creates new form RegulacioniVentil
     * @param x
     * @param y
     * @param title
     * @param opis
     * @param ventil
     * @param protok
     */
    public RegulacioniVentilElMotorImagPolozajScreen(int x, int y, String title, String opis, RegulacioniElMotVentil ventil, Protok protok) {
        initComponents();
        this.ventil = ventil;
        this.protok = protok;
        jLabelNaziv.setText(opis);
        this.setTitle(title);
        this.setLocation(x - 85, y - 45);
        jProgressBar1.setMinimum(this.protok.getProtok().getMin());
        jProgressBar1.setMinimum(this.protok.getProtok().getMax());
        jLabelMin.setText(Integer.toHexString(this.protok.getProtok().getMin()));
        jLabelMax.setText(ShiftPoint.shiftonePoint(this.protok.getProtok().getMax(), this.protok.getProtok().getBrDec()));
        this.setVisible(true);
        startScreenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNaziv = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jButtonImpulsZatvori = new javax.swing.JButton();
        jButtonMinus10 = new javax.swing.JButton();
        jButtonPlus1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonZatvori = new javax.swing.JButton();
        jButtonOvori = new javax.swing.JButton();
        jLabelProcenat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelProtok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMax = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabelNaziv.setBackground(new java.awt.Color(51, 255, 51));
        jLabelNaziv.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNaziv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNaziv.setText("Naziv ventila");

        jProgressBar1.setMaximum(1000);

        jButton2.setText("Izađi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonImpulsZatvori.setText("Z");
        jButtonImpulsZatvori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonImpulsZatvoriMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonImpulsZatvoriMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonImpulsZatvoriMouseReleased(evt);
            }
        });

        jButtonMinus10.setText("Stop");
        jButtonMinus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinus10ActionPerformed(evt);
            }
        });

        jButtonPlus1.setText("O");
        jButtonPlus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonPlus1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonPlus1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButtonPlus1MouseReleased(evt);
            }
        });

        jButtonZatvori.setText("Zatvori");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        jButtonOvori.setText("Otvori");
        jButtonOvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOvoriActionPerformed(evt);
            }
        });

        jLabelProcenat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProcenat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProcenat.setText("***");

        jLabel2.setText("Protok: ");

        jLabelProtok.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtok.setText("***");

        jLabel1.setText("min:");

        jLabelMin.setText("***");

        jLabel3.setText("max:");

        jLabelMax.setText("***");

        jButton1.setText("Zadavanje vremena");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonImpulsZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabelProcenat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelProtok, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonMinus10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonOvori, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNaziv)
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProtok))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMin)
                    .addComponent(jLabel3)
                    .addComponent(jLabelMax))
                .addGap(1, 1, 1)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImpulsZatvori)
                    .addComponent(jButtonPlus1)
                    .addComponent(jLabelProcenat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOvori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMinus10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        startTimer(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonMinus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinus10ActionPerformed
        stop(ventil.getPcOtvori());
    }//GEN-LAST:event_jButtonMinus10ActionPerformed

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
        brPokusaja = 0;
        openClose(true, ventil.getPcZatvori());
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    private void jButtonOvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOvoriActionPerformed
        brPokusaja = 0;
        openClose(true, ventil.getPcOtvori());
    }//GEN-LAST:event_jButtonOvoriActionPerformed

    private void jButtonImpulsZatvoriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImpulsZatvoriMouseExited
        openClose(false, ventil.getPcZatvori());
    }//GEN-LAST:event_jButtonImpulsZatvoriMouseExited

    private void jButtonImpulsZatvoriMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImpulsZatvoriMouseReleased
        openClose(false, ventil.getPcZatvori());
    }//GEN-LAST:event_jButtonImpulsZatvoriMouseReleased

    private void jButtonPlus1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlus1MouseExited
        openClose(false, ventil.getPcOtvori());
    }//GEN-LAST:event_jButtonPlus1MouseExited

    private void jButtonPlus1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlus1MouseReleased
        openClose(false, ventil.getPcOtvori());
    }//GEN-LAST:event_jButtonPlus1MouseReleased

    private void jButtonImpulsZatvoriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImpulsZatvoriMousePressed
        openClose(true, ventil.getPcZatvori());
    }//GEN-LAST:event_jButtonImpulsZatvoriMousePressed

    private void jButtonPlus1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlus1MousePressed
        openClose(true, ventil.getPcOtvori());
    }//GEN-LAST:event_jButtonPlus1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Point p = GetMousePoint(MouseInfo.getPointerInfo().getLocation());
        boolean show = true;
        if (vremeScreen == null) {
            vremeScreen = new VremeVentilScreen(p, ventil.getTehnoloskaOznaka(), ventil);
            //show = false;
        } 
        //else {
        //    prozor.dispose();
        //    prozor = new RegulacioniVentilElMotorScreen(p.x, p.y, grupa, opis, ventil, protok);
        //}
        vremeScreen.setLocation(p);
        vremeScreen.setVisible(show);
    }//GEN-LAST:event_jButton1ActionPerformed

    private final RegulacioniElMotVentil ventil;
    private final Protok protok;
    private int brPokusaja=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonImpulsZatvori;
    private javax.swing.JButton jButtonMinus10;
    private javax.swing.JButton jButtonOvori;
    private javax.swing.JButton jButtonPlus1;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMax;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelNaziv;
    private javax.swing.JLabel jLabelProcenat;
    private javax.swing.JLabel jLabelProtok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private  Timer timer;
    private  VremeVentilScreen vremeScreen;
    
    private void startScreenRefresh() {
        timer = new Timer(100, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                int a = ventil.getVrednosti().getPolozajVrednost();
                jLabelProcenat.setText(ShiftPoint.shiftonePoint(a, ventil.getBrDecimala()) + " %");
                jProgressBar1.setMinimum(protok.getProtok().getMin());
                jProgressBar1.setMaximum(protok.getProtok().getMax());
                jProgressBar1.setValue(protok.getProtok().getVrednostRegistra());
                jLabelProtok.setText(Integer.toString(protok.getProtok().getVrednostRegistra()) + " m3/h");
                jLabelMin.setText(Integer.toString(protok.getProtok().getMin()));
                jLabelMax.setText(Integer.toString(protok.getProtok().getMax()));
                openCloseStop(ventil.getVrednosti().getOtvoren(), ventil.getPcOtvori(), ventil.getVrednosti().getZatvoren(), ventil.getPcZatvori());
                disposeTimer();
            }
        });
    }

    private void openCloseStop(boolean otvoren,int adresaOtvaranje, boolean zatvoren, int adresaZatvaranje) {
        
        if (otvoren && brPokusaja==0) {
            brPokusaja ++;
            openClose(false, adresaOtvaranje);
        }
        if(zatvoren && brPokusaja==0){
            brPokusaja ++;
            openClose(false, adresaZatvaranje);
        }
        if(!otvoren && !zatvoren){
            brPokusaja = 0;
        }
        
    }

    private void openClose(boolean open, int adr) {
        StartApp.comm.offset = adr;
        StartApp.comm.writeDigital = true;
        StartApp.comm.mxValue = open;
    }
    
    private void stop(int adr){
        StartApp.comm.offset = adr;
        StartApp.comm.writeDigitals = true;
        boolean[] vr = {false, false};
        StartApp.comm.mxValues = vr;
    }
    
    public void startTimer(boolean start){
        if(start){
            timer.start();
        }else{
            timer.stop();
        }
    }
    
    public void disposeTimer(){
        if(!this.isShowing()){
            timer.stop();
        }
    }
}
