/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popup;

import constant.ConstReg;
import field.merenja.Protok;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import tools.ShiftPoint;
import up.StartApp;
import valve.reg.RegulacioniVentili;


/**
 *
 * @author branko.scekic
 */
public class RegulacioniVentilScreen extends javax.swing.JFrame {

    /**
     * Creates new form RegulacioniVentil
     * @param x
     * @param y
     * @param title
     * @param opis
     * @param ventil
     * @param protok
     */
    public RegulacioniVentilScreen(int x,int y, String title, String opis, RegulacioniVentili ventil, Protok protok) {
        initComponents();
        this.ventil = ventil;
        this.protok = protok;
        jLabelNaziv.setText(opis);
        this.setTitle(title);
        this.setLocation(x-85, y-45);
        jProgressBar1.setMinimum(this.protok.getProtok().getMin());
        jProgressBar1.setMinimum(this.protok.getProtok().getMax());
        jLabelMin.setText(Integer.toHexString(this.protok.getProtok().getMin()));
        jLabelMax.setText(ShiftPoint.shiftonePoint(this.protok.getProtok().getMax(),this.protok.getProtok().getBrDec()));
        this.setVisible(true);
        startScreenRefresh(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNaziv = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jButtonMinus01 = new javax.swing.JButton();
        jButtonMinus1 = new javax.swing.JButton();
        jButtonMinus10 = new javax.swing.JButton();
        jButtonPlus01 = new javax.swing.JButton();
        jButtonPlus1 = new javax.swing.JButton();
        jButtonPlus10 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonZatvori = new javax.swing.JButton();
        jButtonOvori = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jLabelProcenat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelProtok = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelMax = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabelNaziv.setBackground(new java.awt.Color(51, 255, 51));
        jLabelNaziv.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNaziv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNaziv.setText("Naziv ventila");

        jProgressBar1.setMaximum(1000);

        jButton2.setText("Izađi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonMinus01.setText("-0.1");
        jButtonMinus01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinus01ActionPerformed(evt);
            }
        });

        jButtonMinus1.setText("-1");
        jButtonMinus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinus1ActionPerformed(evt);
            }
        });

        jButtonMinus10.setText("-10");
        jButtonMinus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinus10ActionPerformed(evt);
            }
        });

        jButtonPlus01.setText("+0.1");
        jButtonPlus01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlus01ActionPerformed(evt);
            }
        });

        jButtonPlus1.setText("+1");
        jButtonPlus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlus1ActionPerformed(evt);
            }
        });

        jButtonPlus10.setText("+10");
        jButtonPlus10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlus10ActionPerformed(evt);
            }
        });

        jButtonZatvori.setText("0%");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        jButtonOvori.setText("100%");
        jButtonOvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOvoriActionPerformed(evt);
            }
        });

        jButton50.setText("50%");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });

        jLabelProcenat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProcenat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProcenat.setText("***");

        jLabel2.setText("Protok: ");

        jLabelProtok.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtok.setText("***");

        jLabel1.setText("min:");

        jLabelMin.setText("***");

        jLabel3.setText("max:");

        jLabelMax.setText("***");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jButtonOvori, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonMinus10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPlus10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonMinus1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelProcenat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonPlus1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonMinus01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPlus01))
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabelNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelProtok, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNaziv)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProtok))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelMin)
                    .addComponent(jLabel3)
                    .addComponent(jLabelMax))
                .addGap(1, 1, 1)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMinus01)
                    .addComponent(jButtonPlus01))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonMinus1)
                        .addComponent(jButtonPlus1))
                    .addComponent(jLabelProcenat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMinus10)
                    .addComponent(jButtonPlus10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZatvori)
                    .addComponent(jButtonOvori)
                    .addComponent(jButton50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        startTimer(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonMinus01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinus01ActionPerformed
        offset = ventil.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegMinus01;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonMinus01ActionPerformed

    private void jButtonPlus01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlus01ActionPerformed
        offset = ventil.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegPlus01;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonPlus01ActionPerformed

    private void jButtonMinus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinus1ActionPerformed
        offset = ventil.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegMinus1;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonMinus1ActionPerformed

    private void jButtonPlus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlus1ActionPerformed
        offset = ventil.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegPlus1;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonPlus1ActionPerformed

    private void jButtonMinus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinus10ActionPerformed
        offset = ventil.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegMinus10;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonMinus10ActionPerformed

    private void jButtonPlus10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlus10ActionPerformed
        offset = ventil.getAnalogStep();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = ConstReg.RegPlus10;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonPlus10ActionPerformed

    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
        offset = ventil.getAnalogValue();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = 0;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        offset = ventil.getAnalogValue();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = 500;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButtonOvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOvoriActionPerformed
        offset = ventil.getAnalogValue();
        StartApp.comm.offset = offset;
        StartApp.comm.registerValue = 1000;
        StartApp.comm.writeRegister = true;
    }//GEN-LAST:event_jButtonOvoriActionPerformed

    
    private final RegulacioniVentili ventil;
    private int offset;
    private final Protok protok;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButtonMinus01;
    private javax.swing.JButton jButtonMinus1;
    private javax.swing.JButton jButtonMinus10;
    private javax.swing.JButton jButtonOvori;
    private javax.swing.JButton jButtonPlus01;
    private javax.swing.JButton jButtonPlus1;
    private javax.swing.JButton jButtonPlus10;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMax;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelNaziv;
    private javax.swing.JLabel jLabelProcenat;
    private javax.swing.JLabel jLabelProtok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    private  Timer timer;
    
    private void startScreenRefresh() {
        timer = new Timer(100, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                int a = ventil.getVrednosti().getPolozajVrednost();
                jLabelProcenat.setText(ShiftPoint.shiftonePoint(a,ventil.getBrDecimala()) + " %");
                jProgressBar1.setMinimum(protok.getProtok().getMin());
                jProgressBar1.setMaximum(protok.getProtok().getMax());
                jProgressBar1.setValue(protok.getProtok().getVrednostRegistra());
                jLabelProtok.setText(Integer.toString(protok.getProtok().getVrednostRegistra()) + " m3/h");
                jLabelMin.setText(Integer.toString(protok.getProtok().getMin()));
                jLabelMax.setText(Integer.toString(protok.getProtok().getMax()));
                disposeTimer();
            }
        });
    }
    
    public void startTimer(boolean start){
        if(start){
            timer.start();
        }else{
            timer.stop();
        }
    }
    
    public void disposeTimer(){
        if(!this.isShowing()){
            timer.stop();
        }
    }
}
