/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import field.merenja.bazeni.Nivoi;
import field.merenja.protoci.ProtociDemiLinije;
import field.merenja.protoci.ProtociFlokulacija;
import field.merenja.protoci.ProtociNeutralna;
import field.merenja.protoci.ProtociPescaniFilteri;
import field.merenja.rezervoari.RezervoariMerenja;
import field.pumpe.PumpeDekaFiltrKaDemi;
import field.pumpe.PumpeDekaFiltriraneKaNeutralnojIzmeni;
import field.pumpe.PumpeKaPescanimFilterima;
import field.pumpe.PumpeNeutralizacionogBazena;
import field.pumpe.PumpeOdpadnihVodaOdPranjaPescanihFiltera;
import field.pumpe.PumpeZaPranjePescanihFiltera;
import field.pumpe.ReaktorMotori;
import field.ventili.Reaktor;
import field.ventili.VentiliGrupaPumpi;
import field.ventili.VentiliKaPescanimFilterima;
import field.ventili.pescaniFilter.OtpadneVodeOdPescanihFiltera;
import graph.GraphPopUp;
import graphOld.SelectedMeasure;
import graphOld.TypeOfMeasurment;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.concurrent.ExecutorService;
import javax.swing.Timer;
import popup.AllPopUpWindow;
import static tools.Convert.intToLong;
import tools.ShiftPoint;

/**
 *
 * @author branko.scekic
 */
public class BilansFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form BalansFrame
     * @param bazeniMerenja
     * @param rezervoariMerenja
     * @param ventiliGP01
     * @param ventiliKaPescanimFilterima
     * @param pumpeDekaFiltriranaKaDemi
     * @param pumpeKaPescanimFilterima
     * @param pumpeDekaFiltriraneKaNeutralnojIzmeni
     * @param pumpeOdpadnihVodaOdPranjaPescanihFiltera
     * @param protociFlokulacija
     * @param protociNeutralna
     * @param protociDemiLinije
     * @param protociPescaniFilteri
     * @param pumpeZaPranjePescanihFiltera
     * @param pumpeNeutralizacionogBazena
     * @param otpadneVodeOdPescanihFiltera
     * @param reaktor
     * @param reaktorMotori
     * @param img
     * @param es
     * @param allPopUpWindow
     */
    public BilansFrame(
            Nivoi bazeniMerenja,
            RezervoariMerenja rezervoariMerenja,
            VentiliGrupaPumpi ventiliGP01,
            VentiliKaPescanimFilterima ventiliKaPescanimFilterima,
            PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi,
            PumpeKaPescanimFilterima pumpeKaPescanimFilterima,
            PumpeDekaFiltriraneKaNeutralnojIzmeni pumpeDekaFiltriraneKaNeutralnojIzmeni,
            PumpeOdpadnihVodaOdPranjaPescanihFiltera pumpeOdpadnihVodaOdPranjaPescanihFiltera,
            ProtociFlokulacija protociFlokulacija,
            ProtociNeutralna protociNeutralna,
            ProtociDemiLinije protociDemiLinije,
            ProtociPescaniFilteri protociPescaniFilteri,
            PumpeZaPranjePescanihFiltera pumpeZaPranjePescanihFiltera,
            PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena,
            OtpadneVodeOdPescanihFiltera otpadneVodeOdPescanihFiltera,
            Reaktor reaktor,
            ReaktorMotori reaktorMotori,
            Img img,
            
            ExecutorService es,
            AllPopUpWindow allPopUpWindow) {
        
        initComponents();
        
        
        this.bazeniMerenja = bazeniMerenja;
        this.rezervoariMerenja = rezervoariMerenja;
        this.ventiliGP01 = ventiliGP01;
        this.ventiliKaPescanimFilterima = ventiliKaPescanimFilterima;
        this.pumpeDekaFiltriranaKaDemi = pumpeDekaFiltriranaKaDemi;
        this.pumpeKaPescanimFilterima = pumpeKaPescanimFilterima;
        this.pumpeDekaFiltriraneKaNeutralnojIzmeni = pumpeDekaFiltriraneKaNeutralnojIzmeni;
        this.pumpeOdpadnihVodaOdPranjaPescanihFiltera = pumpeOdpadnihVodaOdPranjaPescanihFiltera;
        this.protociFlokulacija = protociFlokulacija;
        this.protociNeutralna = protociNeutralna;
        this.protociDemiLinije = protociDemiLinije;
        this.protociPescaniFilteri = protociPescaniFilteri;
        this.pumpeZaPranjePescanihFiltera = pumpeZaPranjePescanihFiltera;
        this.pumpeNeutralizacionogBazena = pumpeNeutralizacionogBazena;
        this.otpadneVodeOdPescanihFiltera = otpadneVodeOdPescanihFiltera;
        this.reaktor = reaktor;
        this.allPopUpWindow = allPopUpWindow;
        this.reaktorMotori = reaktorMotori;
        this.img = img;
        
        this.es=es;
        
        screenRefresh();
        setMinMax();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPumpaKaPescanimFilterimaBr1CopyBilans = new javax.swing.JLabel();
        jLabelPKPFbr1CopyBilans = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr2CopyBilans = new javax.swing.JLabel();
        jLabelPKPFbr2CopyBilans = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr3CopyBilans = new javax.swing.JLabel();
        jLabelPKPFbr3CopyBilans = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr4CopyBilans = new javax.swing.JLabel();
        jLabelPKPFbr4CopyBilans = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr5CopyBilans = new javax.swing.JLabel();
        jLabelPKPFbr5CopyBilans = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr6CopyBilans = new javax.swing.JLabel();
        jLabelPKPFbr6CopyBilans = new javax.swing.JLabel();
        jLabelProtokSiroveVodeR1CopyBilans = new javax.swing.JLabel();
        jLabelProtokSiroveVodeR2CopyBilans = new javax.swing.JLabel();
        jProgressBarDekaFiltriranaVodaCopyBalans = new javax.swing.JProgressBar();
        jLabelNivoBazenDekaFiltriraneVodeCopyBalans = new javax.swing.JLabel();
        jProgressBarKompenzacioniRezervoar500m3CopyBilans = new javax.swing.JProgressBar();
        jLabelKompenzacioniRezervoar500m3CopyBilans = new javax.swing.JLabel();
        jLabelPumpaKaNeutralnojIzmeniBr1CopyBilans = new javax.swing.JLabel();
        jLabelPumpaKaNeutralnojIzmeniBr2CopyBilans = new javax.swing.JLabel();
        jLabelPumpaKaNeutralnojIzmeniBr3CopyBilans = new javax.swing.JLabel();
        jLabelGP01kaNIVentil01CopyBilans = new javax.swing.JLabel();
        jLabelGP01kaNIVentil02CopyBilans = new javax.swing.JLabel();
        jLabelGP01kaNIVentil03CopyBilans = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr1CopyBilans = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr2CopyBilans = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr3CopyBilans = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr4CopyBilans = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr5CopyBilans = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji1CopyBilans = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji2CopyBilans = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji3CopyBilans = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji4CopyBilans = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji5CopyBilans = new javax.swing.JLabel();
        jLabelDemiRezervoarBr1CopyBilans = new javax.swing.JLabel();
        jProgressBarDemiRezervoarBr1CopyBilans = new javax.swing.JProgressBar();
        jProgressBarDemiRezervoarBr2CopyBilans = new javax.swing.JProgressBar();
        jLabelDemiRezervoarBr2CopyBilans = new javax.swing.JLabel();
        jProgressBarNeutralizacioniBazenCopyBalans = new javax.swing.JProgressBar();
        jLabelNivoNeutralizacioniCopyBilans = new javax.swing.JLabel();
        jLabelProtokNeutralnaBr3CopyBilans = new javax.swing.JLabel();
        jLabelProtokNeutralnaBr1CopyBilans = new javax.swing.JLabel();
        jLabelProtokNeutralnaBr2CopyBilans = new javax.swing.JLabel();
        jLabelProtokDemiLinijaBr1CopyBilans = new javax.swing.JLabel();
        jLabelProtokDemiLinijaBr2CopyBilans = new javax.swing.JLabel();
        jLabelProtokDemiLinijaBr3CopyBilans = new javax.swing.JLabel();
        jLabelProtokPF6CopyBilans = new javax.swing.JLabel();
        jLabelProtokPF1CopyBilans = new javax.swing.JLabel();
        jLabelProtokPF2CopyBilans = new javax.swing.JLabel();
        jLabelProtokPF3CopyBilans = new javax.swing.JLabel();
        jLabelProtokPF4CopyBilans = new javax.swing.JLabel();
        jLabelProtokPF5CopyBilans = new javax.swing.JLabel();
        jProgressBarDemiRezervoar150mCopyBilans = new javax.swing.JProgressBar();
        jLabelDemiRezervoar150mCopyBilans = new javax.swing.JLabel();
        jLabelKumulativnoR1CopyBilans = new javax.swing.JLabel();
        jLabelKumulativnoR2CopyBilans = new javax.swing.JLabel();
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilans = new javax.swing.JLabel();
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilans = new javax.swing.JLabel();
        jLabelOdPranjaPescanihFilteraBr1CopyBilans = new javax.swing.JLabel();
        jLabelOdPranjaPescanihFilteraBr2CopyBilans = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr2CopyBilans = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr1CopyBilans = new javax.swing.JLabel();
        jProgressBarOtpadneOdPranjaPescaniCopyBilans = new javax.swing.JProgressBar();
        jLabelNivoOtpadneVodePranjePFCopyBilans = new javax.swing.JLabel();
        jLabelProtokDemiLinijaOutCopyBilansBr1 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaOutCopyBilansBr2 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaOutCopyBilansBr3 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaMagistralaCopyBilans = new javax.swing.JLabel();
        jLabelImpelerReaktor1 = new javax.swing.JLabel();
        jLabelReaktorRegVentilR1Copy = new javax.swing.JLabel();
        jLabelReaktorRegVentilVrednostR1Copy = new javax.swing.JLabel();
        jLabelKumulativnoDemiLinijaMagistralaCopyBilans = new javax.swing.JLabel();
        jLabelKumulativnoNeutralnaMagistralaBilans = new javax.swing.JLabel();
        jLabelProtokNeutralnaMagistralaBilans = new javax.swing.JLabel();
        jLabelZgrtacReaktor1 = new javax.swing.JLabel();
        jProgressBarDekaNefiltriraneVodeCopyBalans = new javax.swing.JProgressBar();
        jLabelNivoDekaNefiltriranaCopyBalans = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Bilans");
        setVisible(true);
        getContentPane().setLayout(null);

        jLabelPumpaKaPescanimFilterimaBr1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr1CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr1CopyBilans);
        jLabelPumpaKaPescanimFilterimaBr1CopyBilans.setBounds(950, 80, 50, 50);

        jLabelPKPFbr1CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr1CopyBilans);
        jLabelPKPFbr1CopyBilans.setBounds(1000, 100, 40, 30);

        jLabelPumpaKaPescanimFilterimaBr2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr2CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr2CopyBilans);
        jLabelPumpaKaPescanimFilterimaBr2CopyBilans.setBounds(950, 130, 50, 50);

        jLabelPKPFbr2CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr2CopyBilans);
        jLabelPKPFbr2CopyBilans.setBounds(1000, 140, 40, 40);

        jLabelPumpaKaPescanimFilterimaBr3CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr3CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr3CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr3CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr3CopyBilans);
        jLabelPumpaKaPescanimFilterimaBr3CopyBilans.setBounds(950, 180, 50, 50);

        jLabelPKPFbr3CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr3CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr3CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr3CopyBilans);
        jLabelPKPFbr3CopyBilans.setBounds(1000, 190, 50, 40);

        jLabelPumpaKaPescanimFilterimaBr4CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr4CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr4CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr4CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr4CopyBilans);
        jLabelPumpaKaPescanimFilterimaBr4CopyBilans.setBounds(950, 230, 50, 50);

        jLabelPKPFbr4CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr4CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr4CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr4CopyBilans);
        jLabelPKPFbr4CopyBilans.setBounds(1000, 240, 50, 30);

        jLabelPumpaKaPescanimFilterimaBr5CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr5CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr5CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr5CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr5CopyBilans);
        jLabelPumpaKaPescanimFilterimaBr5CopyBilans.setBounds(950, 280, 50, 50);

        jLabelPKPFbr5CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr5CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr5CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr5CopyBilans);
        jLabelPKPFbr5CopyBilans.setBounds(1000, 290, 50, 30);

        jLabelPumpaKaPescanimFilterimaBr6CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr6CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr6CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr6CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr6CopyBilans);
        jLabelPumpaKaPescanimFilterimaBr6CopyBilans.setBounds(950, 330, 50, 50);

        jLabelPKPFbr6CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr6CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr6CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr6CopyBilans);
        jLabelPKPFbr6CopyBilans.setBounds(1000, 330, 40, 40);

        jLabelProtokSiroveVodeR1CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokSiroveVodeR1CopyBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokSiroveVodeR1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokSiroveVodeR1CopyBilans.setText("****");
        jLabelProtokSiroveVodeR1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokSiroveVodeR1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokSiroveVodeR1CopyBilans);
        jLabelProtokSiroveVodeR1CopyBilans.setBounds(160, 110, 100, 19);

        jLabelProtokSiroveVodeR2CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokSiroveVodeR2CopyBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokSiroveVodeR2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokSiroveVodeR2CopyBilans.setText("****");
        jLabelProtokSiroveVodeR2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokSiroveVodeR2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokSiroveVodeR2CopyBilans);
        jLabelProtokSiroveVodeR2CopyBilans.setBounds(170, 260, 100, 19);

        jProgressBarDekaFiltriranaVodaCopyBalans.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarDekaFiltriranaVodaCopyBalans.setOrientation(1);
        jProgressBarDekaFiltriranaVodaCopyBalans.setToolTipText("");
        jProgressBarDekaFiltriranaVodaCopyBalans.setValue(10);
        jProgressBarDekaFiltriranaVodaCopyBalans.setBorderPainted(false);
        jProgressBarDekaFiltriranaVodaCopyBalans.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarDekaFiltriranaVodaCopyBalans.setString("");
        jProgressBarDekaFiltriranaVodaCopyBalans.setStringPainted(true);
        getContentPane().add(jProgressBarDekaFiltriranaVodaCopyBalans);
        jProgressBarDekaFiltriranaVodaCopyBalans.setBounds(1480, 460, 20, 350);

        jLabelNivoBazenDekaFiltriraneVodeCopyBalans.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoBazenDekaFiltriraneVodeCopyBalans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoBazenDekaFiltriraneVodeCopyBalans.setText("+++");
        getContentPane().add(jLabelNivoBazenDekaFiltriraneVodeCopyBalans);
        jLabelNivoBazenDekaFiltriraneVodeCopyBalans.setBounds(1250, 750, 200, 30);

        jProgressBarKompenzacioniRezervoar500m3CopyBilans.setOrientation(1);
        jProgressBarKompenzacioniRezervoar500m3CopyBilans.setValue(10);
        jProgressBarKompenzacioniRezervoar500m3CopyBilans.setString("0");
        jProgressBarKompenzacioniRezervoar500m3CopyBilans.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarKompenzacioniRezervoar500m3CopyBilans);
        jProgressBarKompenzacioniRezervoar500m3CopyBilans.setBounds(710, 440, 20, 150);

        jLabelKompenzacioniRezervoar500m3CopyBilans.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKompenzacioniRezervoar500m3CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKompenzacioniRezervoar500m3CopyBilans.setText("***");
        getContentPane().add(jLabelKompenzacioniRezervoar500m3CopyBilans);
        jLabelKompenzacioniRezervoar500m3CopyBilans.setBounds(740, 550, 110, 30);

        jLabelPumpaKaNeutralnojIzmeniBr1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaNeutralnojIzmeniBr1CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaNeutralnojIzmeniBr1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaNeutralnojIzmeniBr1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaNeutralnojIzmeniBr1CopyBilans);
        jLabelPumpaKaNeutralnojIzmeniBr1CopyBilans.setBounds(1120, 530, 50, 50);

        jLabelPumpaKaNeutralnojIzmeniBr2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaNeutralnojIzmeniBr2CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaNeutralnojIzmeniBr2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaNeutralnojIzmeniBr2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaNeutralnojIzmeniBr2CopyBilans);
        jLabelPumpaKaNeutralnojIzmeniBr2CopyBilans.setBounds(1120, 480, 50, 50);

        jLabelPumpaKaNeutralnojIzmeniBr3CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaNeutralnojIzmeniBr3CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaNeutralnojIzmeniBr3CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaNeutralnojIzmeniBr3CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaNeutralnojIzmeniBr3CopyBilans);
        jLabelPumpaKaNeutralnojIzmeniBr3CopyBilans.setBounds(1120, 440, 50, 50);

        jLabelGP01kaNIVentil01CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGP01kaNIVentil01CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelGP01kaNIVentil01CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGP01kaNIVentil01CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelGP01kaNIVentil01CopyBilans);
        jLabelGP01kaNIVentil01CopyBilans.setBounds(1080, 540, 40, 26);

        jLabelGP01kaNIVentil02CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGP01kaNIVentil02CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelGP01kaNIVentil02CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGP01kaNIVentil02CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelGP01kaNIVentil02CopyBilans);
        jLabelGP01kaNIVentil02CopyBilans.setBounds(1080, 500, 40, 26);

        jLabelGP01kaNIVentil03CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGP01kaNIVentil03CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelGP01kaNIVentil03CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGP01kaNIVentil03CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelGP01kaNIVentil03CopyBilans);
        jLabelGP01kaNIVentil03CopyBilans.setBounds(1080, 460, 40, 26);

        jLabelPumpaDekaFiltrKaDeminerBr1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr1CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr1CopyBilans);
        jLabelPumpaDekaFiltrKaDeminerBr1CopyBilans.setBounds(1120, 620, 50, 50);

        jLabelPumpaDekaFiltrKaDeminerBr2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr2CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr2CopyBilans);
        jLabelPumpaDekaFiltrKaDeminerBr2CopyBilans.setBounds(1120, 660, 50, 50);

        jLabelPumpaDekaFiltrKaDeminerBr3CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr3CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr3CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr3CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr3CopyBilans);
        jLabelPumpaDekaFiltrKaDeminerBr3CopyBilans.setBounds(1120, 710, 50, 40);

        jLabelPumpaDekaFiltrKaDeminerBr4CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr4CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr4CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr4CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr4CopyBilans);
        jLabelPumpaDekaFiltrKaDeminerBr4CopyBilans.setBounds(1120, 750, 50, 40);

        jLabelPumpaDekaFiltrKaDeminerBr5CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr5CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr5CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr5CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr5CopyBilans);
        jLabelPumpaDekaFiltrKaDeminerBr5CopyBilans.setBounds(1120, 790, 50, 50);

        jLabelPumpeKaDemiLiniji1CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji1CopyBilans);
        jLabelPumpeKaDemiLiniji1CopyBilans.setBounds(1080, 640, 40, 30);

        jLabelPumpeKaDemiLiniji2CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji2CopyBilans);
        jLabelPumpeKaDemiLiniji2CopyBilans.setBounds(1080, 680, 40, 30);

        jLabelPumpeKaDemiLiniji3CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji3CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji3CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji3CopyBilans);
        jLabelPumpeKaDemiLiniji3CopyBilans.setBounds(1080, 720, 40, 30);

        jLabelPumpeKaDemiLiniji4CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji4CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji4CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji4CopyBilans);
        jLabelPumpeKaDemiLiniji4CopyBilans.setBounds(1080, 760, 40, 30);

        jLabelPumpeKaDemiLiniji5CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji5CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji5CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji5CopyBilans);
        jLabelPumpeKaDemiLiniji5CopyBilans.setBounds(1080, 800, 40, 30);

        jLabelDemiRezervoarBr1CopyBilans.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr1CopyBilans.setText("***");
        getContentPane().add(jLabelDemiRezervoarBr1CopyBilans);
        jLabelDemiRezervoarBr1CopyBilans.setBounds(240, 770, 130, 30);

        jProgressBarDemiRezervoarBr1CopyBilans.setOrientation(1);
        jProgressBarDemiRezervoarBr1CopyBilans.setValue(10);
        jProgressBarDemiRezervoarBr1CopyBilans.setString("0");
        jProgressBarDemiRezervoarBr1CopyBilans.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr1CopyBilans);
        jProgressBarDemiRezervoarBr1CopyBilans.setBounds(230, 670, 20, 140);

        jProgressBarDemiRezervoarBr2CopyBilans.setOrientation(1);
        jProgressBarDemiRezervoarBr2CopyBilans.setValue(10);
        jProgressBarDemiRezervoarBr2CopyBilans.setString("0");
        jProgressBarDemiRezervoarBr2CopyBilans.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr2CopyBilans);
        jProgressBarDemiRezervoarBr2CopyBilans.setBounds(390, 670, 20, 140);

        jLabelDemiRezervoarBr2CopyBilans.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr2CopyBilans.setText("***");
        getContentPane().add(jLabelDemiRezervoarBr2CopyBilans);
        jLabelDemiRezervoarBr2CopyBilans.setBounds(410, 770, 110, 30);

        jProgressBarNeutralizacioniBazenCopyBalans.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarNeutralizacioniBazenCopyBalans.setOrientation(1);
        jProgressBarNeutralizacioniBazenCopyBalans.setToolTipText("");
        jProgressBarNeutralizacioniBazenCopyBalans.setValue(10);
        jProgressBarNeutralizacioniBazenCopyBalans.setBorderPainted(false);
        jProgressBarNeutralizacioniBazenCopyBalans.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarNeutralizacioniBazenCopyBalans.setString("");
        jProgressBarNeutralizacioniBazenCopyBalans.setStringPainted(true);
        getContentPane().add(jProgressBarNeutralizacioniBazenCopyBalans);
        jProgressBarNeutralizacioniBazenCopyBalans.setBounds(700, 850, 20, 80);

        jLabelNivoNeutralizacioniCopyBilans.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoNeutralizacioniCopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoNeutralizacioniCopyBilans.setText("***");
        getContentPane().add(jLabelNivoNeutralizacioniCopyBilans);
        jLabelNivoNeutralizacioniCopyBilans.setBounds(790, 910, 110, 24);

        jLabelProtokNeutralnaBr3CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokNeutralnaBr3CopyBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokNeutralnaBr3CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProtokNeutralnaBr3CopyBilans.setText("***");
        jLabelProtokNeutralnaBr3CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokNeutralnaBr3CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokNeutralnaBr3CopyBilans);
        jLabelProtokNeutralnaBr3CopyBilans.setBounds(980, 410, 80, 19);

        jLabelProtokNeutralnaBr1CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokNeutralnaBr1CopyBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokNeutralnaBr1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProtokNeutralnaBr1CopyBilans.setText("***");
        jLabelProtokNeutralnaBr1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokNeutralnaBr1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokNeutralnaBr1CopyBilans);
        jLabelProtokNeutralnaBr1CopyBilans.setBounds(980, 550, 80, 19);

        jLabelProtokNeutralnaBr2CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokNeutralnaBr2CopyBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokNeutralnaBr2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProtokNeutralnaBr2CopyBilans.setText("***");
        jLabelProtokNeutralnaBr2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokNeutralnaBr2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokNeutralnaBr2CopyBilans);
        jLabelProtokNeutralnaBr2CopyBilans.setBounds(980, 480, 80, 19);

        jLabelProtokDemiLinijaBr1CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaBr1CopyBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaBr1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProtokDemiLinijaBr1CopyBilans.setText("***");
        jLabelProtokDemiLinijaBr1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokDemiLinijaBr1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokDemiLinijaBr1CopyBilans);
        jLabelProtokDemiLinijaBr1CopyBilans.setBounds(980, 630, 90, 19);

        jLabelProtokDemiLinijaBr2CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaBr2CopyBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaBr2CopyBilans.setText("***");
        jLabelProtokDemiLinijaBr2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokDemiLinijaBr2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokDemiLinijaBr2CopyBilans);
        jLabelProtokDemiLinijaBr2CopyBilans.setBounds(980, 700, 90, 19);

        jLabelProtokDemiLinijaBr3CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaBr3CopyBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaBr3CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelProtokDemiLinijaBr3CopyBilans.setText("***");
        jLabelProtokDemiLinijaBr3CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokDemiLinijaBr3CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokDemiLinijaBr3CopyBilans);
        jLabelProtokDemiLinijaBr3CopyBilans.setBounds(980, 770, 90, 19);

        jLabelProtokPF6CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF6CopyBilans.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF6CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokPF6CopyBilans.setText("***");
        jLabelProtokPF6CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokPF6CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokPF6CopyBilans);
        jLabelProtokPF6CopyBilans.setBounds(1450, 40, 80, 19);

        jLabelProtokPF1CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF1CopyBilans.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokPF1CopyBilans.setText("***");
        jLabelProtokPF1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokPF1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokPF1CopyBilans);
        jLabelProtokPF1CopyBilans.setBounds(1070, 40, 90, 19);

        jLabelProtokPF2CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF2CopyBilans.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokPF2CopyBilans.setText("***");
        jLabelProtokPF2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokPF2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokPF2CopyBilans);
        jLabelProtokPF2CopyBilans.setBounds(1140, 40, 90, 19);

        jLabelProtokPF3CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF3CopyBilans.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF3CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokPF3CopyBilans.setText("***");
        jLabelProtokPF3CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokPF3CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokPF3CopyBilans);
        jLabelProtokPF3CopyBilans.setBounds(1220, 40, 80, 19);

        jLabelProtokPF4CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF4CopyBilans.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF4CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokPF4CopyBilans.setText("***");
        jLabelProtokPF4CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokPF4CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokPF4CopyBilans);
        jLabelProtokPF4CopyBilans.setBounds(1290, 40, 90, 19);

        jLabelProtokPF5CopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF5CopyBilans.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF5CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokPF5CopyBilans.setText("***");
        jLabelProtokPF5CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokPF5CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokPF5CopyBilans);
        jLabelProtokPF5CopyBilans.setBounds(1370, 40, 80, 19);

        jProgressBarDemiRezervoar150mCopyBilans.setOrientation(1);
        jProgressBarDemiRezervoar150mCopyBilans.setValue(10);
        jProgressBarDemiRezervoar150mCopyBilans.setString("0");
        jProgressBarDemiRezervoar150mCopyBilans.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoar150mCopyBilans);
        jProgressBarDemiRezervoar150mCopyBilans.setBounds(370, 470, 20, 120);

        jLabelDemiRezervoar150mCopyBilans.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoar150mCopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoar150mCopyBilans.setText("***");
        getContentPane().add(jLabelDemiRezervoar150mCopyBilans);
        jLabelDemiRezervoar150mCopyBilans.setBounds(390, 560, 100, 30);

        jLabelKumulativnoR1CopyBilans.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelKumulativnoR1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoR1CopyBilans.setText("***");
        getContentPane().add(jLabelKumulativnoR1CopyBilans);
        jLabelKumulativnoR1CopyBilans.setBounds(100, 150, 140, 20);

        jLabelKumulativnoR2CopyBilans.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelKumulativnoR2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoR2CopyBilans.setText("***");
        getContentPane().add(jLabelKumulativnoR2CopyBilans);
        jLabelKumulativnoR2CopyBilans.setBounds(130, 300, 140, 20);

        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilans);
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilans.setBounds(1220, 310, 50, 40);

        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilans);
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilans.setBounds(1220, 360, 50, 40);

        jLabelOdPranjaPescanihFilteraBr1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOdPranjaPescanihFilteraBr1CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelOdPranjaPescanihFilteraBr1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOdPranjaPescanihFilteraBr1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelOdPranjaPescanihFilteraBr1CopyBilans);
        jLabelOdPranjaPescanihFilteraBr1CopyBilans.setBounds(1180, 310, 40, 40);

        jLabelOdPranjaPescanihFilteraBr2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOdPranjaPescanihFilteraBr2CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelOdPranjaPescanihFilteraBr2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOdPranjaPescanihFilteraBr2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelOdPranjaPescanihFilteraBr2CopyBilans);
        jLabelOdPranjaPescanihFilteraBr2CopyBilans.setBounds(1180, 360, 40, 40);

        jLabelPumpaNeutralizacioniBazenBr2CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr2CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr2CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr2CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr2CopyBilans);
        jLabelPumpaNeutralizacioniBazenBr2CopyBilans.setBounds(1030, 890, 50, 50);

        jLabelPumpaNeutralizacioniBazenBr1CopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr1CopyBilans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr1CopyBilans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr1CopyBilansMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr1CopyBilans);
        jLabelPumpaNeutralizacioniBazenBr1CopyBilans.setBounds(1030, 840, 50, 50);

        jProgressBarOtpadneOdPranjaPescaniCopyBilans.setOrientation(1);
        jProgressBarOtpadneOdPranjaPescaniCopyBilans.setValue(10);
        jProgressBarOtpadneOdPranjaPescaniCopyBilans.setBorderPainted(false);
        getContentPane().add(jProgressBarOtpadneOdPranjaPescaniCopyBilans);
        jProgressBarOtpadneOdPranjaPescaniCopyBilans.setBounds(1410, 270, 20, 150);

        jLabelNivoOtpadneVodePranjePFCopyBilans.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoOtpadneVodePranjePFCopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoOtpadneVodePranjePFCopyBilans.setText("+++");
        getContentPane().add(jLabelNivoOtpadneVodePranjePFCopyBilans);
        jLabelNivoOtpadneVodePranjePFCopyBilans.setBounds(1290, 390, 130, 20);

        jLabelProtokDemiLinijaOutCopyBilansBr1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaOutCopyBilansBr1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaOutCopyBilansBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaOutCopyBilansBr1.setText("***");
        jLabelProtokDemiLinijaOutCopyBilansBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokDemiLinijaOutCopyBilansBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokDemiLinijaOutCopyBilansBr1);
        jLabelProtokDemiLinijaOutCopyBilansBr1.setBounds(690, 610, 100, 19);

        jLabelProtokDemiLinijaOutCopyBilansBr2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaOutCopyBilansBr2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaOutCopyBilansBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaOutCopyBilansBr2.setText("***");
        jLabelProtokDemiLinijaOutCopyBilansBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokDemiLinijaOutCopyBilansBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokDemiLinijaOutCopyBilansBr2);
        jLabelProtokDemiLinijaOutCopyBilansBr2.setBounds(690, 690, 100, 19);

        jLabelProtokDemiLinijaOutCopyBilansBr3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaOutCopyBilansBr3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaOutCopyBilansBr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaOutCopyBilansBr3.setText("***");
        jLabelProtokDemiLinijaOutCopyBilansBr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelProtokDemiLinijaOutCopyBilansBr3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelProtokDemiLinijaOutCopyBilansBr3);
        jLabelProtokDemiLinijaOutCopyBilansBr3.setBounds(690, 760, 100, 19);

        jLabelProtokDemiLinijaMagistralaCopyBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaMagistralaCopyBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaMagistralaCopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaMagistralaCopyBilans.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaMagistralaCopyBilans);
        jLabelProtokDemiLinijaMagistralaCopyBilans.setBounds(570, 610, 110, 19);

        jLabelImpelerReaktor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImpelerReaktor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        getContentPane().add(jLabelImpelerReaktor1);
        jLabelImpelerReaktor1.setBounds(290, 140, 50, 50);

        jLabelReaktorRegVentilR1Copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReaktorRegVentilR1Copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelReaktorRegVentilR1Copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReaktorRegVentilR1CopyMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelReaktorRegVentilR1Copy);
        jLabelReaktorRegVentilR1Copy.setBounds(230, 120, 40, 30);

        jLabelReaktorRegVentilVrednostR1Copy.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelReaktorRegVentilVrednostR1Copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReaktorRegVentilVrednostR1Copy.setText("***");
        getContentPane().add(jLabelReaktorRegVentilVrednostR1Copy);
        jLabelReaktorRegVentilVrednostR1Copy.setBounds(230, 150, 40, 19);

        jLabelKumulativnoDemiLinijaMagistralaCopyBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoDemiLinijaMagistralaCopyBilans.setText("***");
        getContentPane().add(jLabelKumulativnoDemiLinijaMagistralaCopyBilans);
        jLabelKumulativnoDemiLinijaMagistralaCopyBilans.setBounds(550, 590, 150, 20);

        jLabelKumulativnoNeutralnaMagistralaBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoNeutralnaMagistralaBilans.setText("***");
        getContentPane().add(jLabelKumulativnoNeutralnaMagistralaBilans);
        jLabelKumulativnoNeutralnaMagistralaBilans.setBounds(720, 380, 150, 20);

        jLabelProtokNeutralnaMagistralaBilans.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokNeutralnaMagistralaBilans.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokNeutralnaMagistralaBilans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokNeutralnaMagistralaBilans.setText("***");
        getContentPane().add(jLabelProtokNeutralnaMagistralaBilans);
        jLabelProtokNeutralnaMagistralaBilans.setBounds(740, 400, 110, 19);

        jLabelZgrtacReaktor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelZgrtacReaktor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        getContentPane().add(jLabelZgrtacReaktor1);
        jLabelZgrtacReaktor1.setBounds(340, 180, 50, 50);

        jProgressBarDekaNefiltriraneVodeCopyBalans.setOrientation(1);
        getContentPane().add(jProgressBarDekaNefiltriraneVodeCopyBalans);
        jProgressBarDekaNefiltriraneVodeCopyBalans.setBounds(512, 99, 30, 250);

        jLabelNivoDekaNefiltriranaCopyBalans.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelNivoDekaNefiltriranaCopyBalans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoDekaNefiltriranaCopyBalans.setText("***");
        getContentPane().add(jLabelNivoDekaNefiltriranaCopyBalans);
        jLabelNivoDekaNefiltriranaCopyBalans.setBounds(581, 306, 150, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/statImg/6 Protoci i nivoi.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1750, 970);

        setBounds(170, 35, 1754, 1008);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPumpaKaPescanimFilterimaBr1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr1CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaPF01();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr1CopyBilansMouseClicked

    private void jLabelPKPFbr1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr1CopyBilansMouseClicked
        allPopUpWindow.ProzorPKPFbr1(); 
    }//GEN-LAST:event_jLabelPKPFbr1CopyBilansMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr2CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaPF02();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr2CopyBilansMouseClicked

    private void jLabelPKPFbr2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr2CopyBilansMouseClicked
        allPopUpWindow.ProzorPKPFbr2(); 
    }//GEN-LAST:event_jLabelPKPFbr2CopyBilansMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr3CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr3CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaPF03();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr3CopyBilansMouseClicked

    private void jLabelPKPFbr3CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr3CopyBilansMouseClicked
        allPopUpWindow.ProzorPKPFbr3(); 
    }//GEN-LAST:event_jLabelPKPFbr3CopyBilansMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr4CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr4CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaPF04(); 
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr4CopyBilansMouseClicked

    private void jLabelPKPFbr4CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr4CopyBilansMouseClicked
        allPopUpWindow.ProzorPKPFbr4(); 
    }//GEN-LAST:event_jLabelPKPFbr4CopyBilansMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr5CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr5CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaPF05();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr5CopyBilansMouseClicked

    private void jLabelPKPFbr5CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr5CopyBilansMouseClicked
        allPopUpWindow.ProzorPKPFbr5(); 
    }//GEN-LAST:event_jLabelPKPFbr5CopyBilansMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr6CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr6CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaPF06();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr6CopyBilansMouseClicked

    private void jLabelPKPFbr6CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr6CopyBilansMouseClicked
        allPopUpWindow.ProzorPKPFbr6(); 
    }//GEN-LAST:event_jLabelPKPFbr6CopyBilansMouseClicked

    private void jLabelProtokSiroveVodeR1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokSiroveVodeR1CopyBilansMouseClicked
        //showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_sirovavodaureaktor1, "Protok u reaktor br 1");
        GraphPopUp up = new GraphPopUp(TypeOfMeasurment.Flow, SelectedMeasure.f_sirovavodaureaktor1, "Protok u reaktor br 1");
    }//GEN-LAST:event_jLabelProtokSiroveVodeR1CopyBilansMouseClicked

    private void jLabelProtokSiroveVodeR2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokSiroveVodeR2CopyBilansMouseClicked
        //showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_sirovavodaureaktor2, "Protok u reaktor br 2");
    }//GEN-LAST:event_jLabelProtokSiroveVodeR2CopyBilansMouseClicked

    private void jLabelPumpaKaNeutralnojIzmeniBr1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaNeutralnojIzmeniBr1CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaNI01();
    }//GEN-LAST:event_jLabelPumpaKaNeutralnojIzmeniBr1CopyBilansMouseClicked

    private void jLabelPumpaKaNeutralnojIzmeniBr2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaNeutralnojIzmeniBr2CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaNI02();
    }//GEN-LAST:event_jLabelPumpaKaNeutralnojIzmeniBr2CopyBilansMouseClicked

    private void jLabelPumpaKaNeutralnojIzmeniBr3CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaNeutralnojIzmeniBr3CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaNI03();
    }//GEN-LAST:event_jLabelPumpaKaNeutralnojIzmeniBr3CopyBilansMouseClicked

    private void jLabelGP01kaNIVentil01CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGP01kaNIVentil01CopyBilansMouseClicked
        allPopUpWindow.ProzorGP01kaNeutralnojJonskoj01();
    }//GEN-LAST:event_jLabelGP01kaNIVentil01CopyBilansMouseClicked

    private void jLabelGP01kaNIVentil02CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGP01kaNIVentil02CopyBilansMouseClicked
        allPopUpWindow.ProzorGP01kaNeutralnojJonskoj02();
    }//GEN-LAST:event_jLabelGP01kaNIVentil02CopyBilansMouseClicked

    private void jLabelGP01kaNIVentil03CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGP01kaNIVentil03CopyBilansMouseClicked
        allPopUpWindow.ProzorGP01kaNeutralnojJonskoj03();
    }//GEN-LAST:event_jLabelGP01kaNIVentil03CopyBilansMouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr1CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama01();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr1CopyBilansMouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr2CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama02();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr2CopyBilansMouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr3CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr3CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama03();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr3CopyBilansMouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr4CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr4CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama04();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr4CopyBilansMouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr5CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr5CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama05();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr5CopyBilansMouseClicked

    private void jLabelPumpeKaDemiLiniji1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji1CopyBilansMouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr1();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji1CopyBilansMouseClicked

    private void jLabelPumpeKaDemiLiniji2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji2CopyBilansMouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr2();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji2CopyBilansMouseClicked

    private void jLabelPumpeKaDemiLiniji3CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji3CopyBilansMouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr3();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji3CopyBilansMouseClicked

    private void jLabelPumpeKaDemiLiniji4CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji4CopyBilansMouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr4();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji4CopyBilansMouseClicked

    private void jLabelPumpeKaDemiLiniji5CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji5CopyBilansMouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr5();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji5CopyBilansMouseClicked

    private void jLabelProtokNeutralnaBr3CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokNeutralnaBr3CopyBilansMouseClicked
        //showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_ni3, "Protok u NI br 3");
    }//GEN-LAST:event_jLabelProtokNeutralnaBr3CopyBilansMouseClicked

    private void jLabelProtokNeutralnaBr1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokNeutralnaBr1CopyBilansMouseClicked
       // showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_ni1, "Protok u NI br 1");
    }//GEN-LAST:event_jLabelProtokNeutralnaBr1CopyBilansMouseClicked

    private void jLabelProtokNeutralnaBr2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokNeutralnaBr2CopyBilansMouseClicked
       // showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_ni2, "Protok u NI br 2");
    }//GEN-LAST:event_jLabelProtokNeutralnaBr2CopyBilansMouseClicked

    private void jLabelProtokDemiLinijaBr1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokDemiLinijaBr1CopyBilansMouseClicked
        ///showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_ulazdl1, "Protok na ulazu DL br 1");
    }//GEN-LAST:event_jLabelProtokDemiLinijaBr1CopyBilansMouseClicked

    private void jLabelProtokDemiLinijaBr2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokDemiLinijaBr2CopyBilansMouseClicked
        //showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_ulazdl2, "Protok na ulazu DL br 2");
    }//GEN-LAST:event_jLabelProtokDemiLinijaBr2CopyBilansMouseClicked

    private void jLabelProtokDemiLinijaBr3CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokDemiLinijaBr3CopyBilansMouseClicked
       // showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_ulazdl3, "Protok na ulazu DL br 3");
    }//GEN-LAST:event_jLabelProtokDemiLinijaBr3CopyBilansMouseClicked

    private void jLabelProtokPF6CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokPF6CopyBilansMouseClicked
       // showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_pf6, "Protok u PF br 6");
    }//GEN-LAST:event_jLabelProtokPF6CopyBilansMouseClicked

    private void jLabelProtokPF1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokPF1CopyBilansMouseClicked
        //showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_pf1, "Protok u PF br 1");
    }//GEN-LAST:event_jLabelProtokPF1CopyBilansMouseClicked

    private void jLabelProtokPF2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokPF2CopyBilansMouseClicked
      /// showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_pf2, "Protok u PF br 2");
    }//GEN-LAST:event_jLabelProtokPF2CopyBilansMouseClicked

    private void jLabelProtokPF3CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokPF3CopyBilansMouseClicked
       // showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_pf3, "Protok u PF br 3");
    }//GEN-LAST:event_jLabelProtokPF3CopyBilansMouseClicked

    private void jLabelProtokPF4CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokPF4CopyBilansMouseClicked
        //showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_pf4, "Protok u PF br 4");
    }//GEN-LAST:event_jLabelProtokPF4CopyBilansMouseClicked

    private void jLabelProtokPF5CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokPF5CopyBilansMouseClicked
       // showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_pf5, "Protok u PF br 5");
    }//GEN-LAST:event_jLabelProtokPF5CopyBilansMouseClicked

    private void jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaOtpadneOdPranjaPescanihFilteraBr1();
    }//GEN-LAST:event_jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilansMouseClicked

    private void jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaOtpadneOdPranjaPescanihFilteraBr2();
    }//GEN-LAST:event_jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilansMouseClicked

    private void jLabelOdPranjaPescanihFilteraBr1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOdPranjaPescanihFilteraBr1CopyBilansMouseClicked
        allPopUpWindow.ProzorOtpadneVodeOdPescanihFiltera1();
    }//GEN-LAST:event_jLabelOdPranjaPescanihFilteraBr1CopyBilansMouseClicked

    private void jLabelOdPranjaPescanihFilteraBr2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOdPranjaPescanihFilteraBr2CopyBilansMouseClicked
        allPopUpWindow.ProzorOtpadneVodeOdPescanihFiltera2();
    }//GEN-LAST:event_jLabelOdPranjaPescanihFilteraBr2CopyBilansMouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr2CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr2CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr2();
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr2CopyBilansMouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr1CopyBilansMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr1CopyBilansMouseClicked
        allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr1();
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr1CopyBilansMouseClicked

    private void jLabelProtokDemiLinijaOutCopyBilansBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokDemiLinijaOutCopyBilansBr1MouseClicked
        //showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_izlazdl1, "Protok na izlazu DL br 1");
    }//GEN-LAST:event_jLabelProtokDemiLinijaOutCopyBilansBr1MouseClicked

    private void jLabelProtokDemiLinijaOutCopyBilansBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokDemiLinijaOutCopyBilansBr2MouseClicked
        //showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_izlazdl2, "Protok na izlazu DL br 2");
    }//GEN-LAST:event_jLabelProtokDemiLinijaOutCopyBilansBr2MouseClicked

    private void jLabelProtokDemiLinijaOutCopyBilansBr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelProtokDemiLinijaOutCopyBilansBr3MouseClicked
        //showGraphicScreen(TypeOfMeasurment.Flow, SelectedMeasure.f_izlazdl3, "Protok na izlazu DL br 3");
    }//GEN-LAST:event_jLabelProtokDemiLinijaOutCopyBilansBr3MouseClicked

    private void jLabelReaktorRegVentilR1CopyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReaktorRegVentilR1CopyMouseClicked
        allPopUpWindow.ProzorR1SV();
    }//GEN-LAST:event_jLabelReaktorRegVentilR1CopyMouseClicked
    
    
    
    
    
 /*
    //G R A F I C I
    private void showGraphicScreen(TypeOfMeasurment type, SelectedMeasure measure, String opis) {
        MerenjaGraphScreen graphScreen = new MerenjaGraphScreen(this.merenjeProtokaService, this.merenjeNivoaService, this.merenjePritiskaService ,fileHandler);
        Point p = MousePoint.GetMousePoint();
        graphScreen.setTypeOfMeasure(p.x, p.y, type, measure, opis);
        es.submit(graphScreen);
    }
    */
   
    
    private final Img img;
    
   
    //ovo je za thread kada budem grafikone uzimao od merenja
    private final ExecutorService es;
    

    private final VentiliGrupaPumpi ventiliGP01;
    private final VentiliKaPescanimFilterima ventiliKaPescanimFilterima;
    private final PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi;
    private final PumpeKaPescanimFilterima pumpeKaPescanimFilterima;
    private final PumpeDekaFiltriraneKaNeutralnojIzmeni pumpeDekaFiltriraneKaNeutralnojIzmeni;
    private final PumpeOdpadnihVodaOdPranjaPescanihFiltera pumpeOdpadnihVodaOdPranjaPescanihFiltera;
    private final ProtociFlokulacija protociFlokulacija;
    private final Nivoi bazeniMerenja;
    private final RezervoariMerenja rezervoariMerenja;
    private final ProtociNeutralna protociNeutralna;
    private final ProtociDemiLinije protociDemiLinije;
    private final ProtociPescaniFilteri protociPescaniFilteri;
    private final AllPopUpWindow allPopUpWindow;
    public Timer timer;
    private final PumpeZaPranjePescanihFiltera pumpeZaPranjePescanihFiltera;
    private final PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena;
    private final OtpadneVodeOdPescanihFiltera otpadneVodeOdPescanihFiltera;
    private final Reaktor reaktor;
    private final ReaktorMotori reaktorMotori;

    
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDemiRezervoar150mCopyBilans;
    private javax.swing.JLabel jLabelDemiRezervoarBr1CopyBilans;
    private javax.swing.JLabel jLabelDemiRezervoarBr2CopyBilans;
    private javax.swing.JLabel jLabelGP01kaNIVentil01CopyBilans;
    private javax.swing.JLabel jLabelGP01kaNIVentil02CopyBilans;
    private javax.swing.JLabel jLabelGP01kaNIVentil03CopyBilans;
    private javax.swing.JLabel jLabelImpelerReaktor1;
    private javax.swing.JLabel jLabelKompenzacioniRezervoar500m3CopyBilans;
    private javax.swing.JLabel jLabelKumulativnoDemiLinijaMagistralaCopyBilans;
    private javax.swing.JLabel jLabelKumulativnoNeutralnaMagistralaBilans;
    private javax.swing.JLabel jLabelKumulativnoR1CopyBilans;
    private javax.swing.JLabel jLabelKumulativnoR2CopyBilans;
    private javax.swing.JLabel jLabelNivoBazenDekaFiltriraneVodeCopyBalans;
    private javax.swing.JLabel jLabelNivoDekaNefiltriranaCopyBalans;
    private javax.swing.JLabel jLabelNivoNeutralizacioniCopyBilans;
    private javax.swing.JLabel jLabelNivoOtpadneVodePranjePFCopyBilans;
    private javax.swing.JLabel jLabelOdPranjaPescanihFilteraBr1CopyBilans;
    private javax.swing.JLabel jLabelOdPranjaPescanihFilteraBr2CopyBilans;
    private javax.swing.JLabel jLabelPKPFbr1CopyBilans;
    private javax.swing.JLabel jLabelPKPFbr2CopyBilans;
    private javax.swing.JLabel jLabelPKPFbr3CopyBilans;
    private javax.swing.JLabel jLabelPKPFbr4CopyBilans;
    private javax.swing.JLabel jLabelPKPFbr5CopyBilans;
    private javax.swing.JLabel jLabelPKPFbr6CopyBilans;
    private javax.swing.JLabel jLabelProtokDemiLinijaBr1CopyBilans;
    private javax.swing.JLabel jLabelProtokDemiLinijaBr2CopyBilans;
    private javax.swing.JLabel jLabelProtokDemiLinijaBr3CopyBilans;
    private javax.swing.JLabel jLabelProtokDemiLinijaMagistralaCopyBilans;
    private javax.swing.JLabel jLabelProtokDemiLinijaOutCopyBilansBr1;
    private javax.swing.JLabel jLabelProtokDemiLinijaOutCopyBilansBr2;
    private javax.swing.JLabel jLabelProtokDemiLinijaOutCopyBilansBr3;
    private javax.swing.JLabel jLabelProtokNeutralnaBr1CopyBilans;
    private javax.swing.JLabel jLabelProtokNeutralnaBr2CopyBilans;
    private javax.swing.JLabel jLabelProtokNeutralnaBr3CopyBilans;
    private javax.swing.JLabel jLabelProtokNeutralnaMagistralaBilans;
    private javax.swing.JLabel jLabelProtokPF1CopyBilans;
    private javax.swing.JLabel jLabelProtokPF2CopyBilans;
    private javax.swing.JLabel jLabelProtokPF3CopyBilans;
    private javax.swing.JLabel jLabelProtokPF4CopyBilans;
    private javax.swing.JLabel jLabelProtokPF5CopyBilans;
    private javax.swing.JLabel jLabelProtokPF6CopyBilans;
    private javax.swing.JLabel jLabelProtokSiroveVodeR1CopyBilans;
    private javax.swing.JLabel jLabelProtokSiroveVodeR2CopyBilans;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr1CopyBilans;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr2CopyBilans;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr3CopyBilans;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr4CopyBilans;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr5CopyBilans;
    private javax.swing.JLabel jLabelPumpaKaNeutralnojIzmeniBr1CopyBilans;
    private javax.swing.JLabel jLabelPumpaKaNeutralnojIzmeniBr2CopyBilans;
    private javax.swing.JLabel jLabelPumpaKaNeutralnojIzmeniBr3CopyBilans;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr1CopyBilans;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr2CopyBilans;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr3CopyBilans;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr4CopyBilans;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr5CopyBilans;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr6CopyBilans;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr1CopyBilans;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr2CopyBilans;
    private javax.swing.JLabel jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilans;
    private javax.swing.JLabel jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilans;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji1CopyBilans;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji2CopyBilans;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji3CopyBilans;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji4CopyBilans;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji5CopyBilans;
    private javax.swing.JLabel jLabelReaktorRegVentilR1Copy;
    private javax.swing.JLabel jLabelReaktorRegVentilVrednostR1Copy;
    private javax.swing.JLabel jLabelZgrtacReaktor1;
    private javax.swing.JProgressBar jProgressBarDekaFiltriranaVodaCopyBalans;
    private javax.swing.JProgressBar jProgressBarDekaNefiltriraneVodeCopyBalans;
    private javax.swing.JProgressBar jProgressBarDemiRezervoar150mCopyBilans;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr1CopyBilans;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr2CopyBilans;
    private javax.swing.JProgressBar jProgressBarKompenzacioniRezervoar500m3CopyBilans;
    private javax.swing.JProgressBar jProgressBarNeutralizacioniBazenCopyBalans;
    private javax.swing.JProgressBar jProgressBarOtpadneOdPranjaPescaniCopyBilans;
    // End of variables declaration//GEN-END:variables
    
    public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                //Date date = new Date();
                refreshPKPF();
                refreshPFmerenja();
                refreshVentiliGP();
                refreshBazeniMerenja();
                refreshPumpeFiltriraneVodeKaDemineralizaciji();
                refreshPumpeKaPescanimFilterima();
                refreshPumpeDekaFiltriraneKaNeutralnojIzmeni();
                refreshPumpeOtpadnihVodaOdPranjaPescanihFiltera();
                refreshRezervoariMerenja();
                refreshProtoci();
                refreshPumpeNeutralizacionogBazena();
                refreshOtpadneVodeOdPescanihFiltera();
                refreshReaktorMotori();
                           

                //System.out.println(date.getTime());
                //System.out.println("_____________");
            }
        });
    }
    
    
    
   private void setMinMax() {
       
        jProgressBarOtpadneOdPranjaPescaniCopyBilans.setMinimum(bazeniMerenja.getBazenOtpadneVodeOdPranjaPescanihFiltera().getMin());
        jProgressBarOtpadneOdPranjaPescaniCopyBilans.setMaximum(bazeniMerenja.getBazenOtpadneVodeOdPranjaPescanihFiltera().getMax());
        jProgressBarOtpadneOdPranjaPescaniCopyBilans.setForeground(Color.ORANGE);

        jProgressBarDekaNefiltriraneVodeCopyBalans.setMinimum(bazeniMerenja.getBazenDekaNefiltriraneVode().getMin());
        jProgressBarDekaNefiltriraneVodeCopyBalans.setMaximum(bazeniMerenja.getBazenDekaNefiltriraneVode().getMax());
        jProgressBarDekaNefiltriraneVodeCopyBalans.setForeground(Color.ORANGE);

        jProgressBarDekaFiltriranaVodaCopyBalans.setMinimum(bazeniMerenja.getBazenDekaFiltriraneVode().getMin());
        jProgressBarDekaFiltriranaVodaCopyBalans.setMaximum(bazeniMerenja.getBazenDekaFiltriraneVode().getMax());
        jProgressBarDekaFiltriranaVodaCopyBalans.setForeground(Color.ORANGE);

        jProgressBarNeutralizacioniBazenCopyBalans.setMinimum(bazeniMerenja.getBazenNeutralizacioni().getMin());
        jProgressBarNeutralizacioniBazenCopyBalans.setMaximum(bazeniMerenja.getBazenNeutralizacioni().getMax());
        jProgressBarNeutralizacioniBazenCopyBalans.setForeground(Color.ORANGE);

        jProgressBarDemiRezervoarBr1CopyBilans.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMin());
        jProgressBarDemiRezervoarBr1CopyBilans.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMax());
        jProgressBarDemiRezervoarBr1CopyBilans.setForeground(Color.ORANGE);
  
        jProgressBarDemiRezervoarBr2CopyBilans.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMin());
        jProgressBarDemiRezervoarBr2CopyBilans.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMax());
        jProgressBarDemiRezervoarBr2CopyBilans.setForeground(Color.ORANGE);

        jProgressBarDemiRezervoar150mCopyBilans.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMin());
        jProgressBarDemiRezervoar150mCopyBilans.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMax());
        jProgressBarDemiRezervoar150mCopyBilans.setForeground(Color.ORANGE);
   
        jProgressBarKompenzacioniRezervoar500m3CopyBilans.setMinimum(rezervoariMerenja.getNivoRezervoarKompenzacioni500m3().getMin());
        jProgressBarKompenzacioniRezervoar500m3CopyBilans.setMaximum(rezervoariMerenja.getNivoRezervoarKompenzacioni500m3().getMax());
        jProgressBarKompenzacioniRezervoar500m3CopyBilans.setForeground(Color.ORANGE);

    }

    private void refreshPKPF() {
        img.setImgHorizontalno(jLabelPKPFbr1CopyBilans, ventiliKaPescanimFilterima.getAPKPF_PotisBr1());
        img.setImgHorizontalno(jLabelPKPFbr2CopyBilans, ventiliKaPescanimFilterima.getAPKPF_PotisBr2());
        img.setImgHorizontalno(jLabelPKPFbr3CopyBilans, ventiliKaPescanimFilterima.getAPKPF_PotisBr3());
        img.setImgHorizontalno(jLabelPKPFbr4CopyBilans, ventiliKaPescanimFilterima.getAPKPF_PotisBr4());
        img.setImgHorizontalno(jLabelPKPFbr5CopyBilans, ventiliKaPescanimFilterima.getAPKPF_PotisBr5());
        img.setImgHorizontalno(jLabelPKPFbr6CopyBilans, ventiliKaPescanimFilterima.getAPKPF_PotisBr6());   
    }


   
    private void refreshOtpadneVodeOdPescanihFiltera() {
        img.setImgHorizontalno(jLabelOdPranjaPescanihFilteraBr1CopyBilans, otpadneVodeOdPescanihFiltera.getVent01());
        img.setImgHorizontalno(jLabelOdPranjaPescanihFilteraBr2CopyBilans, otpadneVodeOdPescanihFiltera.getVent02());
    }

    private void refreshPFmerenja() {

        jLabelKumulativnoR1CopyBilans.setText(intToLong(protociFlokulacija.getProtokSiroveVodeR1().getKumulativnoVisiVrednost(), protociFlokulacija.getProtokSiroveVodeR1().getKumulativnoNiziVrednost()));
        jLabelKumulativnoR2CopyBilans.setText(intToLong(protociFlokulacija.getProtokSiroveVodeR2().getKumulativnoVisiVrednost(), protociFlokulacija.getProtokSiroveVodeR2().getKumulativnoNiziVrednost()));
 
    }

   
    
    private void refreshVentiliGP() {
        img.setImgHorizontalno(jLabelPumpeKaDemiLiniji1CopyBilans, ventiliGP01.getGP01_potisDemi1());
        img.setImgHorizontalno(jLabelPumpeKaDemiLiniji2CopyBilans, ventiliGP01.getGP01_potisDemi2());
        img.setImgHorizontalno(jLabelPumpeKaDemiLiniji3CopyBilans, ventiliGP01.getGP01_potisDemi3());
        img.setImgHorizontalno(jLabelPumpeKaDemiLiniji4CopyBilans, ventiliGP01.getGP01_potisDemi4());
        img.setImgHorizontalno(jLabelPumpeKaDemiLiniji5CopyBilans, ventiliGP01.getGP01_potisDemi5());

        img.setImgHorizontalno(jLabelGP01kaNIVentil01CopyBilans, ventiliGP01.getGP01_potisJonska1());
        img.setImgHorizontalno(jLabelGP01kaNIVentil02CopyBilans, ventiliGP01.getGP01_potisJonska2());
        img.setImgHorizontalno(jLabelGP01kaNIVentil03CopyBilans, ventiliGP01.getGP01_potisJonska3());
    }

   

    private void refreshBazeniMerenja() {
        int a = bazeniMerenja.getBazenDekaFiltriraneVode().getVrednostRegistra();
        jLabelNivoBazenDekaFiltriraneVodeCopyBalans.setText("L= " + Integer.toString(a) + " cm");
        jProgressBarDekaFiltriranaVodaCopyBalans.setValue(a);

        int b = bazeniMerenja.getBazenOtpadneVodeOdPranjaPescanihFiltera().getVrednostRegistra();
        jProgressBarOtpadneOdPranjaPescaniCopyBilans.setValue(b);
        jLabelNivoOtpadneVodePranjePFCopyBilans.setText("L= " + Integer.toString(b) + " cm");

        int c = bazeniMerenja.getBazenDekaNefiltriraneVode().getVrednostRegistra();
        jProgressBarDekaNefiltriraneVodeCopyBalans.setValue(c);
        jLabelNivoDekaNefiltriranaCopyBalans.setText("L= " + Integer.toString(c) + " cm");

        int d = bazeniMerenja.getBazenNeutralizacioni().getVrednostRegistra();
        jProgressBarNeutralizacioniBazenCopyBalans.setValue(d);
        jLabelNivoNeutralizacioniCopyBilans.setText("L= " + Integer.toString(d) + " cm");
        
    }

    

    private void refreshProtoci() {
        jLabelProtokNeutralnaBr1CopyBilans.setText(Integer.toString(protociNeutralna.getProtokNJ1().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokNeutralnaBr2CopyBilans.setText(Integer.toString(protociNeutralna.getProtokNJ2().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokNeutralnaBr3CopyBilans.setText(Integer.toString(protociNeutralna.getProtokNJ3().getProtok().getVrednostRegistra()) + " m3/h");

    
        jLabelProtokDemiLinijaBr1CopyBilans.setText(Integer.toString(protociDemiLinije.getProtokDL1in().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokDemiLinijaBr2CopyBilans.setText(Integer.toString(protociDemiLinije.getProtokDL2in().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokDemiLinijaBr3CopyBilans.setText(Integer.toString(protociDemiLinije.getProtokDL3in().getProtok().getVrednostRegistra()) + " m3/h");

        jLabelProtokDemiLinijaOutCopyBilansBr1.setText(Integer.toString(protociDemiLinije.getProtokDL1out().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokDemiLinijaOutCopyBilansBr2.setText(Integer.toString(protociDemiLinije.getProtokDL2out().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokDemiLinijaOutCopyBilansBr3.setText(Integer.toString(protociDemiLinije.getProtokDL3out().getProtok().getVrednostRegistra()) + " m3/h");

        jLabelProtokDemiLinijaMagistralaCopyBilans.setText(Integer.toString(protociDemiLinije.getProtokMagistralniVod().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoDemiLinijaMagistralaCopyBilans.setText(intToLong(protociDemiLinije.getProtokMagistralniVod().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokMagistralniVod().getKumulativnoNiziVrednost()));

        jLabelProtokPF1CopyBilans.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF1().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF1().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF2CopyBilans.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF2().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF2().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF3CopyBilans.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF3().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF3().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF4CopyBilans.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF4().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF4().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF5CopyBilans.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF5().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF5().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF6CopyBilans.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF6().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF6().getProtok().getBrDec()) + " m3/h");

        jLabelProtokSiroveVodeR1CopyBilans.setText("R1= " + Integer.toString(protociFlokulacija.getProtokSiroveVodeR1().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokSiroveVodeR2CopyBilans.setText("R2= " + Integer.toString(protociFlokulacija.getProtokSiroveVodeR2().getProtok().getVrednostRegistra()) + " m3/h");

        jLabelProtokNeutralnaMagistralaBilans.setText(Integer.toString(protociNeutralna.getMagistralniVod().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoNeutralnaMagistralaBilans.setText(intToLong(protociNeutralna.getMagistralniVod().getKumulativnoVisiVrednost(), protociNeutralna.getMagistralniVod().getKumulativnoNiziVrednost()));

    }

    private void refreshPumpeFiltriraneVodeKaDemineralizaciji() {
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr1CopyBilans, pumpeDekaFiltriranaKaDemi.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr2CopyBilans, pumpeDekaFiltriranaKaDemi.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr3CopyBilans, pumpeDekaFiltriranaKaDemi.getPumpaBr3().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr4CopyBilans, pumpeDekaFiltriranaKaDemi.getPumpaBr4().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr5CopyBilans, pumpeDekaFiltriranaKaDemi.getPumpaBr5().getVrednosti().isUkljucen());
    }

   

    private void refreshPumpeKaPescanimFilterima() {

        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr1CopyBilans, pumpeKaPescanimFilterima.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr2CopyBilans, pumpeKaPescanimFilterima.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr3CopyBilans, pumpeKaPescanimFilterima.getPumpaBr3().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr4CopyBilans, pumpeKaPescanimFilterima.getPumpaBr4().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr5CopyBilans, pumpeKaPescanimFilterima.getPumpaBr5().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr6CopyBilans, pumpeKaPescanimFilterima.getPumpaBr6().getVrednosti().isUkljucen());

    }

   

    private void refreshPumpeNeutralizacionogBazena() {
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr2CopyBilans, pumpeNeutralizacionogBazena.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr1CopyBilans, pumpeNeutralizacionogBazena.getPumpaBr1().getVrednosti().isUkljucen());
    }


    private void refreshPumpeDekaFiltriraneKaNeutralnojIzmeni() {
        img.setPumpIcon(jLabelPumpaKaNeutralnojIzmeniBr1CopyBilans, pumpeDekaFiltriraneKaNeutralnojIzmeni.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaNeutralnojIzmeniBr2CopyBilans, pumpeDekaFiltriraneKaNeutralnojIzmeni.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaNeutralnojIzmeniBr3CopyBilans, pumpeDekaFiltriraneKaNeutralnojIzmeni.getPumpaBr3().getVrednosti().isUkljucen());
    }

    private void refreshPumpeOtpadnihVodaOdPranjaPescanihFiltera() {
        img.setPumpIcon(jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1CopyBilans, pumpeOdpadnihVodaOdPranjaPescanihFiltera.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2CopyBilans, pumpeOdpadnihVodaOdPranjaPescanihFiltera.getPumpaBr2().getVrednosti().isUkljucen());
    }

   

    

    private void refreshReaktorMotori() {
        img.setImgHorizontalno(jLabelReaktorRegVentilR1Copy, reaktor.getUlazSirVodeR1().getVrednosti().getOtvoren(), reaktor.getUlazSirVodeR1().getVrednosti().getZatvoren());
        img.setPumpIcon(jLabelImpelerReaktor1, reaktorMotori.getImpelerReaktorBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelZgrtacReaktor1, reaktorMotori.getZgrtacReaktorBr1().getVrednosti().isUkljucen());

    }

    private void refreshRezervoariMerenja() {
        int a = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getVrednostRegistra();
        jProgressBarDemiRezervoarBr1CopyBilans.setValue(a);
        jLabelDemiRezervoarBr1CopyBilans.setText("L= " + Integer.toString(a) + " cm");

        int b = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getVrednostRegistra();
        jProgressBarDemiRezervoarBr2CopyBilans.setValue(a);
        jLabelDemiRezervoarBr2CopyBilans.setText("L= " + Integer.toString(b) + " cm");

        int c = rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getVrednostRegistra();
        jProgressBarDemiRezervoar150mCopyBilans.setValue(c);
        jLabelDemiRezervoar150mCopyBilans.setText("L= " + Integer.toString(c) + " cm");

        int d = rezervoariMerenja.getNivoRezervoarKompenzacioni500m3().getVrednostRegistra();
        jProgressBarKompenzacioniRezervoar500m3CopyBilans.setValue(d);
        jLabelKompenzacioniRezervoar500m3CopyBilans.setText("L= " + Integer.toString(d) + " cm");
    }

}
