/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import field.merenja.bazeni.Nivoi;
import field.merenja.demiLinije.DemiLinijaMerenjaKonstruktor;
import field.merenja.protoci.ProtociDemiLinije;
import field.merenja.protoci.ProtociPretovarnaRampa;
import field.merenja.rezervoari.RezervoariMerenja;
import field.merenja.temperature.Temperature;
import field.pumpe.PumpeDekaFiltrKaDemi;
import field.pumpe.PumpeNeutralizacionogBazena;
import field.ventili.DemiLinije;
import field.ventili.VentiliGrupaPumpi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import popup.AllPopUpWindow;
import tools.AnalogToDigital;
import static utilise.Convert.intToLong;
import tools.ShiftPoint;

/**
 *
 * @author branko.scekic
 */
public class DemiAllFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DemiAllFrame
     * @param protociDemiLinije
     * @param protociPretovarnaRampa
     * @param bazeniMerenja
     * @param rezervoariMerenja
     * @param demiLinijeMerenja
     * @param ventiliGP01
     * @param pumpeDekaFiltriranaKaDemi
     * @param pumpeNeutralizacionogBazena
     * @param demiLinije
     * @param img
     * @param temperature
     * @param allPopUpWindow
     */
    public DemiAllFrame(ProtociDemiLinije protociDemiLinije,
            ProtociPretovarnaRampa protociPretovarnaRampa,
            Nivoi bazeniMerenja, 
            RezervoariMerenja rezervoariMerenja, 
            DemiLinijaMerenjaKonstruktor demiLinijeMerenja,
            VentiliGrupaPumpi ventiliGP01,
            PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi,
            PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena,
            DemiLinije demiLinije,
            Img img,
            Temperature temperature,
            AllPopUpWindow allPopUpWindow) {
        initComponents();
        this.allPopUpWindow = allPopUpWindow;
        this.rezervoariMerenja = rezervoariMerenja;
        this.protociPretovarnaRampa = protociPretovarnaRampa;
        this.bazeniMerenja = bazeniMerenja;
        this.demiLinijeMerenja = demiLinijeMerenja;
        this.ventiliGP01 = ventiliGP01;
        this.pumpeDekaFiltriranaKaDemi = pumpeDekaFiltriranaKaDemi;
        this.pumpeNeutralizacionogBazena = pumpeNeutralizacionogBazena;
        this.demiLinije = demiLinije;
        this.temperature = temperature;
        this.protociDemiLinije = protociDemiLinije;
        this.img = img;
        
        setMinMax();
        screenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPumpeKaDemiLiniji01 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji02 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji03 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji04 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji05 = new javax.swing.JLabel();
        jLabelDL1JKKFRegVentilCopyDLVrednost = new javax.swing.JLabel();
        jLabelNivoNeutralizacioni = new javax.swing.JLabel();
        jProgressBarNeutralizacioniBazen = new javax.swing.JProgressBar();
        jProgressBarDekaFiltriranaVodaCopyDL = new javax.swing.JProgressBar();
        jLabelNivoBazenDekaFiltriraneVodeCopyDL = new javax.swing.JLabel();
        jLabelDL1JKKFRegVentilCopyDL = new javax.swing.JLabel();
        jLabelDL2JKKFRegVentilCopyDL = new javax.swing.JLabel();
        jLabelDL2JKKFRegVentilCopyDLVrednost = new javax.swing.JLabel();
        jLabelDL3JKKFRegVentilCopyDL = new javax.swing.JLabel();
        jLabelDL3JKKFRegVentilCopyDLVrednost = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr01 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr02 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr03 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr04 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr05 = new javax.swing.JLabel();
        jProgressBarDemiRezervoarBr1 = new javax.swing.JProgressBar();
        jLabelDemiRezervoarBr1 = new javax.swing.JLabel();
        jProgressBarDemiRezervoarBr2 = new javax.swing.JProgressBar();
        jLabelDemiRezervoarBr2 = new javax.swing.JLabel();
        jProgressBarDemiRezervoar150m3 = new javax.swing.JProgressBar();
        jLabelDemiRezervoar150m3 = new javax.swing.JLabel();
        jLabelKumulativnoDL1CopyDL = new javax.swing.JLabel();
        jLabelKumulativnoDL2CopyDL = new javax.swing.JLabel();
        jLabelKumulativnoDL3CopyDL = new javax.swing.JLabel();
        jLabelEventDL1 = new javax.swing.JLabel();
        jLabelEventDL2 = new javax.swing.JLabel();
        jLabelEventDL3 = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr1 = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr2 = new javax.swing.JLabel();
        jLabelKumulativnoDemiLinijaMagistrala = new javax.swing.JLabel();
        jLabelProtokDemiLinijaMagistrala = new javax.swing.JLabel();
        jLabelKumulativnoOutDLCopyBr1 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaOutCopyBr1 = new javax.swing.JLabel();
        jLabelKumulativnoOutDLCopyBr2 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaOutCopyBr2 = new javax.swing.JLabel();
        jLabelKumulativnoOutDLCopyBr3 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaOutCopyBr3 = new javax.swing.JLabel();
        jLabelPretovarnaLuzina = new javax.swing.JLabel();
        jLabelPretovarnaKumulativnoLuzina = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabelPretovarnaKiselina = new javax.swing.JLabel();
        jLabelPretovarnaKumulativnoKiselina = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelPritisakInJKKCopyDL1 = new javax.swing.JLabel();
        jLabelPritisakOutJKKCopyDL1 = new javax.swing.JLabel();
        jLabelPritisakInSBACopyDL1 = new javax.swing.JLabel();
        jLabelPritisakOutSBACopyDL1 = new javax.swing.JLabel();
        jLabelPritisakInJBACopyDL1 = new javax.swing.JLabel();
        jLabelPritisakOutJBACopyDL1 = new javax.swing.JLabel();
        jLabelPritisakInMFCopyDL1 = new javax.swing.JLabel();
        jLabelPritisakOutMFCopyDL1 = new javax.swing.JLabel();
        jLabelPritisakInJKKCopyDL2 = new javax.swing.JLabel();
        jLabelPritisakOutJKKCopyDL2 = new javax.swing.JLabel();
        jLabelPritisakInSBACopyDL2 = new javax.swing.JLabel();
        jLabelTemperaturaLuzine = new javax.swing.JLabel();
        jLabelPritisakOutSBACopyDL2 = new javax.swing.JLabel();
        jLabelTemperaturaDemiVode150m3 = new javax.swing.JLabel();
        jLabelPritisakInJBACopyDL2 = new javax.swing.JLabel();
        jLabelPritisakOutJBACopyDL2 = new javax.swing.JLabel();
        jLabelPritisakInMFCopyDL2 = new javax.swing.JLabel();
        jLabelPritisakOutMFCopyDL2 = new javax.swing.JLabel();
        jLabelPritisakInJKKCopyDL3 = new javax.swing.JLabel();
        jLabelPritisakOutJKKCopyDL3 = new javax.swing.JLabel();
        jLabelPritisakInSBACopyDL3 = new javax.swing.JLabel();
        jLabelPritisakOutSBACopyDL3 = new javax.swing.JLabel();
        jLabelPritisakInJBACopyDL3 = new javax.swing.JLabel();
        jLabelPritisakOutJBACopyDL3 = new javax.swing.JLabel();
        jLabelPritisakInMFCopyDL3 = new javax.swing.JLabel();
        jLabelPritisakOutMFCopyDL3 = new javax.swing.JLabel();
        vodljivostSBA1 = new javax.swing.JLabel();
        vodljivostJBA1 = new javax.swing.JLabel();
        vodljivostMF1 = new javax.swing.JLabel();
        vodljivostSBA2 = new javax.swing.JLabel();
        vodljivostJBA2 = new javax.swing.JLabel();
        vodljivostMF2 = new javax.swing.JLabel();
        vodljivostKolektor = new javax.swing.JLabel();
        vodljivostMF3 = new javax.swing.JLabel();
        vodljivostJBA3 = new javax.swing.JLabel();
        vodljivostSBA3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabelPumpeKaDemiLiniji01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji01);
        jLabelPumpeKaDemiLiniji01.setBounds(180, 680, 26, 40);

        jLabelPumpeKaDemiLiniji02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji02);
        jLabelPumpeKaDemiLiniji02.setBounds(270, 680, 30, 40);

        jLabelPumpeKaDemiLiniji03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji03);
        jLabelPumpeKaDemiLiniji03.setBounds(360, 680, 26, 40);

        jLabelPumpeKaDemiLiniji04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji04);
        jLabelPumpeKaDemiLiniji04.setBounds(450, 680, 30, 40);

        jLabelPumpeKaDemiLiniji05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji05);
        jLabelPumpeKaDemiLiniji05.setBounds(540, 680, 30, 40);

        jLabelDL1JKKFRegVentilCopyDLVrednost.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelDL1JKKFRegVentilCopyDLVrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL1JKKFRegVentilCopyDLVrednost.setText("***");
        getContentPane().add(jLabelDL1JKKFRegVentilCopyDLVrednost);
        jLabelDL1JKKFRegVentilCopyDLVrednost.setBounds(570, 100, 40, 19);

        jLabelNivoNeutralizacioni.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoNeutralizacioni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoNeutralizacioni.setText("***");
        getContentPane().add(jLabelNivoNeutralizacioni);
        jLabelNivoNeutralizacioni.setBounds(760, 900, 130, 24);

        jProgressBarNeutralizacioniBazen.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarNeutralizacioniBazen.setOrientation(1);
        jProgressBarNeutralizacioniBazen.setToolTipText("");
        jProgressBarNeutralizacioniBazen.setValue(10);
        jProgressBarNeutralizacioniBazen.setBorderPainted(false);
        jProgressBarNeutralizacioniBazen.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarNeutralizacioniBazen.setString("");
        jProgressBarNeutralizacioniBazen.setStringPainted(true);
        getContentPane().add(jProgressBarNeutralizacioniBazen);
        jProgressBarNeutralizacioniBazen.setBounds(660, 840, 20, 90);

        jProgressBarDekaFiltriranaVodaCopyDL.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarDekaFiltriranaVodaCopyDL.setOrientation(1);
        jProgressBarDekaFiltriranaVodaCopyDL.setToolTipText("");
        jProgressBarDekaFiltriranaVodaCopyDL.setValue(10);
        jProgressBarDekaFiltriranaVodaCopyDL.setBorderPainted(false);
        jProgressBarDekaFiltriranaVodaCopyDL.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarDekaFiltriranaVodaCopyDL.setString("");
        jProgressBarDekaFiltriranaVodaCopyDL.setStringPainted(true);
        getContentPane().add(jProgressBarDekaFiltriranaVodaCopyDL);
        jProgressBarDekaFiltriranaVodaCopyDL.setBounds(150, 840, 20, 90);

        jLabelNivoBazenDekaFiltriraneVodeCopyDL.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoBazenDekaFiltriraneVodeCopyDL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoBazenDekaFiltriraneVodeCopyDL.setText("+++");
        getContentPane().add(jLabelNivoBazenDekaFiltriraneVodeCopyDL);
        jLabelNivoBazenDekaFiltriraneVodeCopyDL.setBounds(280, 910, 200, 20);

        jLabelDL1JKKFRegVentilCopyDL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL1JKKFRegVentilCopyDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL1JKKFRegVentilCopyDL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL1JKKFRegVentilCopyDLMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL1JKKFRegVentilCopyDL);
        jLabelDL1JKKFRegVentilCopyDL.setBounds(570, 110, 40, 40);

        jLabelDL2JKKFRegVentilCopyDL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL2JKKFRegVentilCopyDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL2JKKFRegVentilCopyDL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL2JKKFRegVentilCopyDLMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL2JKKFRegVentilCopyDL);
        jLabelDL2JKKFRegVentilCopyDL.setBounds(570, 320, 40, 30);

        jLabelDL2JKKFRegVentilCopyDLVrednost.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelDL2JKKFRegVentilCopyDLVrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL2JKKFRegVentilCopyDLVrednost.setText("***");
        getContentPane().add(jLabelDL2JKKFRegVentilCopyDLVrednost);
        jLabelDL2JKKFRegVentilCopyDLVrednost.setBounds(570, 290, 40, 19);

        jLabelDL3JKKFRegVentilCopyDL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL3JKKFRegVentilCopyDL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL3JKKFRegVentilCopyDL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL3JKKFRegVentilCopyDLMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL3JKKFRegVentilCopyDL);
        jLabelDL3JKKFRegVentilCopyDL.setBounds(570, 520, 40, 30);

        jLabelDL3JKKFRegVentilCopyDLVrednost.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelDL3JKKFRegVentilCopyDLVrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL3JKKFRegVentilCopyDLVrednost.setText("***");
        getContentPane().add(jLabelDL3JKKFRegVentilCopyDLVrednost);
        jLabelDL3JKKFRegVentilCopyDLVrednost.setBounds(570, 500, 40, 19);

        jLabelPumpaDekaFiltrKaDeminerBr01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr01);
        jLabelPumpaDekaFiltrKaDeminerBr01.setBounds(170, 720, 50, 50);

        jLabelPumpaDekaFiltrKaDeminerBr02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr02);
        jLabelPumpaDekaFiltrKaDeminerBr02.setBounds(260, 720, 50, 50);

        jLabelPumpaDekaFiltrKaDeminerBr03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr03);
        jLabelPumpaDekaFiltrKaDeminerBr03.setBounds(350, 720, 50, 50);

        jLabelPumpaDekaFiltrKaDeminerBr04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr04);
        jLabelPumpaDekaFiltrKaDeminerBr04.setBounds(440, 720, 50, 50);

        jLabelPumpaDekaFiltrKaDeminerBr05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr05);
        jLabelPumpaDekaFiltrKaDeminerBr05.setBounds(530, 720, 50, 50);

        jProgressBarDemiRezervoarBr1.setOrientation(1);
        jProgressBarDemiRezervoarBr1.setValue(10);
        jProgressBarDemiRezervoarBr1.setString("0");
        jProgressBarDemiRezervoarBr1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr1);
        jProgressBarDemiRezervoarBr1.setBounds(1040, 770, 20, 160);

        jLabelDemiRezervoarBr1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr1.setText("***");
        getContentPane().add(jLabelDemiRezervoarBr1);
        jLabelDemiRezervoarBr1.setBounds(1070, 890, 130, 30);

        jProgressBarDemiRezervoarBr2.setOrientation(1);
        jProgressBarDemiRezervoarBr2.setValue(10);
        jProgressBarDemiRezervoarBr2.setString("0");
        jProgressBarDemiRezervoarBr2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr2);
        jProgressBarDemiRezervoarBr2.setBounds(1250, 770, 20, 160);

        jLabelDemiRezervoarBr2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr2.setText("***");
        getContentPane().add(jLabelDemiRezervoarBr2);
        jLabelDemiRezervoarBr2.setBounds(1280, 890, 130, 30);

        jProgressBarDemiRezervoar150m3.setOrientation(1);
        jProgressBarDemiRezervoar150m3.setValue(10);
        jProgressBarDemiRezervoar150m3.setString("0");
        jProgressBarDemiRezervoar150m3.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoar150m3);
        jProgressBarDemiRezervoar150m3.setBounds(1500, 560, 20, 120);

        jLabelDemiRezervoar150m3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoar150m3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoar150m3.setText("***");
        getContentPane().add(jLabelDemiRezervoar150m3);
        jLabelDemiRezervoar150m3.setBounds(1510, 650, 110, 30);

        jLabelKumulativnoDL1CopyDL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoDL1CopyDL.setText("***");
        getContentPane().add(jLabelKumulativnoDL1CopyDL);
        jLabelKumulativnoDL1CopyDL.setBounds(630, 110, 150, 20);

        jLabelKumulativnoDL2CopyDL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoDL2CopyDL.setText("***");
        getContentPane().add(jLabelKumulativnoDL2CopyDL);
        jLabelKumulativnoDL2CopyDL.setBounds(630, 320, 150, 20);

        jLabelKumulativnoDL3CopyDL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoDL3CopyDL.setText("***");
        getContentPane().add(jLabelKumulativnoDL3CopyDL);
        jLabelKumulativnoDL3CopyDL.setBounds(630, 530, 150, 20);

        jLabelEventDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEventDL1);
        jLabelEventDL1.setBounds(610, 190, 570, 30);

        jLabelEventDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEventDL2);
        jLabelEventDL2.setBounds(620, 360, 570, 60);

        jLabelEventDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEventDL3);
        jLabelEventDL3.setBounds(620, 570, 570, 50);

        jLabelPumpaNeutralizacioniBazenBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr1);
        jLabelPumpaNeutralizacioniBazenBr1.setBounds(720, 790, 50, 50);

        jLabelPumpaNeutralizacioniBazenBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr2);
        jLabelPumpaNeutralizacioniBazenBr2.setBounds(800, 790, 50, 50);

        jLabelKumulativnoDemiLinijaMagistrala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoDemiLinijaMagistrala.setText("***");
        getContentPane().add(jLabelKumulativnoDemiLinijaMagistrala);
        jLabelKumulativnoDemiLinijaMagistrala.setBounds(1210, 550, 150, 20);

        jLabelProtokDemiLinijaMagistrala.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaMagistrala.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaMagistrala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaMagistrala.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaMagistrala);
        jLabelProtokDemiLinijaMagistrala.setBounds(1230, 580, 100, 19);

        jLabelKumulativnoOutDLCopyBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoOutDLCopyBr1.setText("***");
        getContentPane().add(jLabelKumulativnoOutDLCopyBr1);
        jLabelKumulativnoOutDLCopyBr1.setBounds(1120, 130, 150, 20);

        jLabelProtokDemiLinijaOutCopyBr1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaOutCopyBr1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaOutCopyBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaOutCopyBr1.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaOutCopyBr1);
        jLabelProtokDemiLinijaOutCopyBr1.setBounds(1150, 280, 100, 19);

        jLabelKumulativnoOutDLCopyBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoOutDLCopyBr2.setText("***");
        getContentPane().add(jLabelKumulativnoOutDLCopyBr2);
        jLabelKumulativnoOutDLCopyBr2.setBounds(1120, 330, 150, 20);

        jLabelProtokDemiLinijaOutCopyBr2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaOutCopyBr2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaOutCopyBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaOutCopyBr2.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaOutCopyBr2);
        jLabelProtokDemiLinijaOutCopyBr2.setBounds(1150, 480, 100, 19);

        jLabelKumulativnoOutDLCopyBr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoOutDLCopyBr3.setText("***");
        getContentPane().add(jLabelKumulativnoOutDLCopyBr3);
        jLabelKumulativnoOutDLCopyBr3.setBounds(1110, 530, 150, 20);

        jLabelProtokDemiLinijaOutCopyBr3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaOutCopyBr3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaOutCopyBr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaOutCopyBr3.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaOutCopyBr3);
        jLabelProtokDemiLinijaOutCopyBr3.setBounds(1150, 680, 100, 19);

        jLabelPretovarnaLuzina.setForeground(new java.awt.Color(204, 0, 0));
        jLabelPretovarnaLuzina.setText("jLabel31");
        getContentPane().add(jLabelPretovarnaLuzina);
        jLabelPretovarnaLuzina.setBounds(1450, 40, 130, 14);

        jLabelPretovarnaKumulativnoLuzina.setText("jLabel32");
        getContentPane().add(jLabelPretovarnaKumulativnoLuzina);
        jLabelPretovarnaKumulativnoLuzina.setBounds(1450, 70, 150, 14);

        jLabel31.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Pretovarna stanica");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel31.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(jLabel31);
        jLabel31.setBounds(200, 10, 190, 100);

        jLabelPretovarnaKiselina.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPretovarnaKiselina.setText("jLabel31");
        getContentPane().add(jLabelPretovarnaKiselina);
        jLabelPretovarnaKiselina.setBounds(210, 40, 150, 14);

        jLabelPretovarnaKumulativnoKiselina.setText("jLabel32");
        getContentPane().add(jLabelPretovarnaKumulativnoKiselina);
        jLabelPretovarnaKumulativnoKiselina.setBounds(210, 80, 150, 14);

        jLabel30.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Pretovarna stanica");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(jLabel30);
        jLabel30.setBounds(1440, 10, 170, 100);

        jLabelPritisakInJKKCopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJKKCopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJKKCopyDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJKKCopyDL1);
        jLabelPritisakInJKKCopyDL1.setBounds(620, 150, 90, 30);

        jLabelPritisakOutJKKCopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJKKCopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJKKCopyDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJKKCopyDL1);
        jLabelPritisakOutJKKCopyDL1.setBounds(620, 220, 90, 30);

        jLabelPritisakInSBACopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInSBACopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInSBACopyDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakInSBACopyDL1);
        jLabelPritisakInSBACopyDL1.setBounds(780, 150, 90, 30);

        jLabelPritisakOutSBACopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutSBACopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutSBACopyDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutSBACopyDL1);
        jLabelPritisakOutSBACopyDL1.setBounds(780, 230, 90, 30);

        jLabelPritisakInJBACopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJBACopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJBACopyDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJBACopyDL1);
        jLabelPritisakInJBACopyDL1.setBounds(940, 150, 90, 30);

        jLabelPritisakOutJBACopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJBACopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJBACopyDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJBACopyDL1);
        jLabelPritisakOutJBACopyDL1.setBounds(940, 230, 90, 30);

        jLabelPritisakInMFCopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInMFCopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInMFCopyDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakInMFCopyDL1);
        jLabelPritisakInMFCopyDL1.setBounds(1090, 150, 90, 30);

        jLabelPritisakOutMFCopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutMFCopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutMFCopyDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutMFCopyDL1);
        jLabelPritisakOutMFCopyDL1.setBounds(1090, 230, 90, 30);

        jLabelPritisakInJKKCopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJKKCopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJKKCopyDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJKKCopyDL2);
        jLabelPritisakInJKKCopyDL2.setBounds(620, 360, 90, 30);

        jLabelPritisakOutJKKCopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJKKCopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJKKCopyDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJKKCopyDL2);
        jLabelPritisakOutJKKCopyDL2.setBounds(620, 430, 90, 30);

        jLabelPritisakInSBACopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInSBACopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInSBACopyDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakInSBACopyDL2);
        jLabelPritisakInSBACopyDL2.setBounds(780, 360, 90, 30);

        jLabelTemperaturaLuzine.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelTemperaturaLuzine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTemperaturaLuzine.setText("jLabel15");
        getContentPane().add(jLabelTemperaturaLuzine);
        jLabelTemperaturaLuzine.setBounds(1460, 170, 110, 20);

        jLabelPritisakOutSBACopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutSBACopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutSBACopyDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutSBACopyDL2);
        jLabelPritisakOutSBACopyDL2.setBounds(780, 430, 90, 30);

        jLabelTemperaturaDemiVode150m3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelTemperaturaDemiVode150m3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTemperaturaDemiVode150m3.setText("jLabel15");
        getContentPane().add(jLabelTemperaturaDemiVode150m3);
        jLabelTemperaturaDemiVode150m3.setBounds(1500, 530, 120, 30);

        jLabelPritisakInJBACopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJBACopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJBACopyDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJBACopyDL2);
        jLabelPritisakInJBACopyDL2.setBounds(940, 360, 90, 30);

        jLabelPritisakOutJBACopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJBACopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJBACopyDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJBACopyDL2);
        jLabelPritisakOutJBACopyDL2.setBounds(940, 430, 90, 30);

        jLabelPritisakInMFCopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInMFCopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInMFCopyDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakInMFCopyDL2);
        jLabelPritisakInMFCopyDL2.setBounds(1090, 360, 90, 30);

        jLabelPritisakOutMFCopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutMFCopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutMFCopyDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutMFCopyDL2);
        jLabelPritisakOutMFCopyDL2.setBounds(1090, 430, 90, 30);

        jLabelPritisakInJKKCopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJKKCopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJKKCopyDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJKKCopyDL3);
        jLabelPritisakInJKKCopyDL3.setBounds(620, 560, 90, 30);

        jLabelPritisakOutJKKCopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJKKCopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJKKCopyDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJKKCopyDL3);
        jLabelPritisakOutJKKCopyDL3.setBounds(620, 640, 90, 30);

        jLabelPritisakInSBACopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInSBACopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInSBACopyDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakInSBACopyDL3);
        jLabelPritisakInSBACopyDL3.setBounds(780, 560, 90, 30);

        jLabelPritisakOutSBACopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutSBACopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutSBACopyDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutSBACopyDL3);
        jLabelPritisakOutSBACopyDL3.setBounds(780, 640, 90, 30);

        jLabelPritisakInJBACopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJBACopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJBACopyDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJBACopyDL3);
        jLabelPritisakInJBACopyDL3.setBounds(940, 560, 90, 30);

        jLabelPritisakOutJBACopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJBACopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJBACopyDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJBACopyDL3);
        jLabelPritisakOutJBACopyDL3.setBounds(940, 640, 90, 30);

        jLabelPritisakInMFCopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInMFCopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInMFCopyDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakInMFCopyDL3);
        jLabelPritisakInMFCopyDL3.setBounds(1090, 560, 90, 30);

        jLabelPritisakOutMFCopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutMFCopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutMFCopyDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutMFCopyDL3);
        jLabelPritisakOutMFCopyDL3.setBounds(1090, 640, 90, 30);

        vodljivostSBA1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostSBA1.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostSBA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostSBA1.setText("jLabel15");
        getContentPane().add(vodljivostSBA1);
        vodljivostSBA1.setBounds(780, 250, 90, 30);

        vodljivostJBA1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostJBA1.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostJBA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostJBA1.setText("jLabel15");
        getContentPane().add(vodljivostJBA1);
        vodljivostJBA1.setBounds(940, 250, 90, 30);

        vodljivostMF1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostMF1.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostMF1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostMF1.setText("jLabel15");
        getContentPane().add(vodljivostMF1);
        vodljivostMF1.setBounds(1090, 250, 90, 30);

        vodljivostSBA2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostSBA2.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostSBA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostSBA2.setText("jLabel15");
        getContentPane().add(vodljivostSBA2);
        vodljivostSBA2.setBounds(780, 450, 90, 30);

        vodljivostJBA2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostJBA2.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostJBA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostJBA2.setText("jLabel15");
        getContentPane().add(vodljivostJBA2);
        vodljivostJBA2.setBounds(940, 450, 90, 30);

        vodljivostMF2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostMF2.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostMF2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostMF2.setText("jLabel15");
        getContentPane().add(vodljivostMF2);
        vodljivostMF2.setBounds(1090, 450, 90, 30);

        vodljivostKolektor.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostKolektor.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostKolektor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostKolektor.setText("jLabel15");
        getContentPane().add(vodljivostKolektor);
        vodljivostKolektor.setBounds(1310, 700, 130, 30);

        vodljivostMF3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostMF3.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostMF3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostMF3.setText("jLabel15");
        getContentPane().add(vodljivostMF3);
        vodljivostMF3.setBounds(1090, 660, 90, 30);

        vodljivostJBA3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostJBA3.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostJBA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostJBA3.setText("jLabel15");
        getContentPane().add(vodljivostJBA3);
        vodljivostJBA3.setBounds(940, 660, 90, 30);

        vodljivostSBA3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostSBA3.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostSBA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostSBA3.setText("jLabel15");
        getContentPane().add(vodljivostSBA3);
        vodljivostSBA3.setBounds(780, 660, 90, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/statImg/4 demineralizacija  zajedno.jpg"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 1740, 970);

        setBounds(170, 35, 1757, 1002);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPumpeKaDemiLiniji01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji01MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr1();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji01MouseClicked

    private void jLabelPumpeKaDemiLiniji02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji02MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr2();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji02MouseClicked

    private void jLabelPumpeKaDemiLiniji03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji03MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr3();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji03MouseClicked

    private void jLabelPumpeKaDemiLiniji04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji04MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr4();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji04MouseClicked

    private void jLabelPumpeKaDemiLiniji05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji05MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr5();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji05MouseClicked

    private void jLabelDL1JKKFRegVentilCopyDLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL1JKKFRegVentilCopyDLMouseClicked
        allPopUpWindow.ProzorDL01JKKF01();
    }//GEN-LAST:event_jLabelDL1JKKFRegVentilCopyDLMouseClicked

    private void jLabelDL2JKKFRegVentilCopyDLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL2JKKFRegVentilCopyDLMouseClicked
        allPopUpWindow.ProzorDL02JKKF01();
    }//GEN-LAST:event_jLabelDL2JKKFRegVentilCopyDLMouseClicked

    private void jLabelDL3JKKFRegVentilCopyDLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL3JKKFRegVentilCopyDLMouseClicked
        allPopUpWindow.ProzorDL03JKKF01();
    }//GEN-LAST:event_jLabelDL3JKKFRegVentilCopyDLMouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr01MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama01();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr01MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr02MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama02();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr02MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr03MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama03();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr03MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr04MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama04();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr04MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr05MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama05();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr05MouseClicked

    private void jLabelEventDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventDL1MouseClicked
        
    }//GEN-LAST:event_jLabelEventDL1MouseClicked

    private void jLabelEventDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventDL2MouseClicked
        
    }//GEN-LAST:event_jLabelEventDL2MouseClicked

    private void jLabelEventDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventDL3MouseClicked
        
    }//GEN-LAST:event_jLabelEventDL3MouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr1MouseClicked
        allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr1();
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr1MouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr2MouseClicked
        allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr2();
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabelDL1JKKFRegVentilCopyDL;
    private javax.swing.JLabel jLabelDL1JKKFRegVentilCopyDLVrednost;
    private javax.swing.JLabel jLabelDL2JKKFRegVentilCopyDL;
    private javax.swing.JLabel jLabelDL2JKKFRegVentilCopyDLVrednost;
    private javax.swing.JLabel jLabelDL3JKKFRegVentilCopyDL;
    private javax.swing.JLabel jLabelDL3JKKFRegVentilCopyDLVrednost;
    private javax.swing.JLabel jLabelDemiRezervoar150m3;
    private javax.swing.JLabel jLabelDemiRezervoarBr1;
    private javax.swing.JLabel jLabelDemiRezervoarBr2;
    private javax.swing.JLabel jLabelEventDL1;
    private javax.swing.JLabel jLabelEventDL2;
    private javax.swing.JLabel jLabelEventDL3;
    private javax.swing.JLabel jLabelKumulativnoDL1CopyDL;
    private javax.swing.JLabel jLabelKumulativnoDL2CopyDL;
    private javax.swing.JLabel jLabelKumulativnoDL3CopyDL;
    private javax.swing.JLabel jLabelKumulativnoDemiLinijaMagistrala;
    private javax.swing.JLabel jLabelKumulativnoOutDLCopyBr1;
    private javax.swing.JLabel jLabelKumulativnoOutDLCopyBr2;
    private javax.swing.JLabel jLabelKumulativnoOutDLCopyBr3;
    private javax.swing.JLabel jLabelNivoBazenDekaFiltriraneVodeCopyDL;
    private javax.swing.JLabel jLabelNivoNeutralizacioni;
    private javax.swing.JLabel jLabelPretovarnaKiselina;
    private javax.swing.JLabel jLabelPretovarnaKumulativnoKiselina;
    private javax.swing.JLabel jLabelPretovarnaKumulativnoLuzina;
    private javax.swing.JLabel jLabelPretovarnaLuzina;
    private javax.swing.JLabel jLabelPritisakInJBACopyDL1;
    private javax.swing.JLabel jLabelPritisakInJBACopyDL2;
    private javax.swing.JLabel jLabelPritisakInJBACopyDL3;
    private javax.swing.JLabel jLabelPritisakInJKKCopyDL1;
    private javax.swing.JLabel jLabelPritisakInJKKCopyDL2;
    private javax.swing.JLabel jLabelPritisakInJKKCopyDL3;
    private javax.swing.JLabel jLabelPritisakInMFCopyDL1;
    private javax.swing.JLabel jLabelPritisakInMFCopyDL2;
    private javax.swing.JLabel jLabelPritisakInMFCopyDL3;
    private javax.swing.JLabel jLabelPritisakInSBACopyDL1;
    private javax.swing.JLabel jLabelPritisakInSBACopyDL2;
    private javax.swing.JLabel jLabelPritisakInSBACopyDL3;
    private javax.swing.JLabel jLabelPritisakOutJBACopyDL1;
    private javax.swing.JLabel jLabelPritisakOutJBACopyDL2;
    private javax.swing.JLabel jLabelPritisakOutJBACopyDL3;
    private javax.swing.JLabel jLabelPritisakOutJKKCopyDL1;
    private javax.swing.JLabel jLabelPritisakOutJKKCopyDL2;
    private javax.swing.JLabel jLabelPritisakOutJKKCopyDL3;
    private javax.swing.JLabel jLabelPritisakOutMFCopyDL1;
    private javax.swing.JLabel jLabelPritisakOutMFCopyDL2;
    private javax.swing.JLabel jLabelPritisakOutMFCopyDL3;
    private javax.swing.JLabel jLabelPritisakOutSBACopyDL1;
    private javax.swing.JLabel jLabelPritisakOutSBACopyDL2;
    private javax.swing.JLabel jLabelPritisakOutSBACopyDL3;
    private javax.swing.JLabel jLabelProtokDemiLinijaMagistrala;
    private javax.swing.JLabel jLabelProtokDemiLinijaOutCopyBr1;
    private javax.swing.JLabel jLabelProtokDemiLinijaOutCopyBr2;
    private javax.swing.JLabel jLabelProtokDemiLinijaOutCopyBr3;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr01;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr02;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr03;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr04;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr05;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr1;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr2;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji01;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji02;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji03;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji04;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji05;
    private javax.swing.JLabel jLabelTemperaturaDemiVode150m3;
    private javax.swing.JLabel jLabelTemperaturaLuzine;
    private javax.swing.JProgressBar jProgressBarDekaFiltriranaVodaCopyDL;
    private javax.swing.JProgressBar jProgressBarDemiRezervoar150m3;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr1;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr2;
    private javax.swing.JProgressBar jProgressBarNeutralizacioniBazen;
    private javax.swing.JLabel vodljivostJBA1;
    private javax.swing.JLabel vodljivostJBA2;
    private javax.swing.JLabel vodljivostJBA3;
    private javax.swing.JLabel vodljivostKolektor;
    private javax.swing.JLabel vodljivostMF1;
    private javax.swing.JLabel vodljivostMF2;
    private javax.swing.JLabel vodljivostMF3;
    private javax.swing.JLabel vodljivostSBA1;
    private javax.swing.JLabel vodljivostSBA2;
    private javax.swing.JLabel vodljivostSBA3;
    // End of variables declaration//GEN-END:variables
    
    private final ProtociDemiLinije protociDemiLinije;
    private final ProtociPretovarnaRampa protociPretovarnaRampa;
    private final Nivoi bazeniMerenja;
    private final RezervoariMerenja rezervoariMerenja;
    private final DemiLinijaMerenjaKonstruktor demiLinijeMerenja;
    private final DemiLinije demiLinije;
    private final VentiliGrupaPumpi ventiliGP01;
    private final PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi;
    private final PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena;
    private final Temperature temperature;
    private final AllPopUpWindow allPopUpWindow;
    public Timer timer;
    private final Img img;
    
    public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                //Date date = new Date();
                refreshDLmerenja();
                refreshDLVentili();
                refreshVentiliGP();
                refreshBazeniMerenja();
                refreshPumpeFiltriraneVodeKaDemineralizaciji();
                refreshRezervoariMerenja();
                refreshProtoci();
                refreshPumpeNeutralizacionogBazena();
                refreshTemperature();
                //System.out.println(date.getTime());
                //System.out.println("_____________");
            }
        });
    }
    
    private void setMinMax() {
        jProgressBarDekaFiltriranaVodaCopyDL.setMinimum(bazeniMerenja.getBazenDekaFiltriraneVode().getMin());
        jProgressBarDekaFiltriranaVodaCopyDL.setMaximum(bazeniMerenja.getBazenDekaFiltriraneVode().getMax());
        jProgressBarDekaFiltriranaVodaCopyDL.setForeground(Color.ORANGE);

        jProgressBarNeutralizacioniBazen.setMinimum(bazeniMerenja.getBazenNeutralizacioni().getMin());
        jProgressBarNeutralizacioniBazen.setMaximum(bazeniMerenja.getBazenNeutralizacioni().getMax());
        jProgressBarNeutralizacioniBazen.setForeground(Color.ORANGE);

        jProgressBarDemiRezervoarBr1.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMin());
        jProgressBarDemiRezervoarBr1.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMax());
        jProgressBarDemiRezervoarBr1.setForeground(Color.ORANGE);

        jProgressBarDemiRezervoarBr2.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMin());
        jProgressBarDemiRezervoarBr2.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMax());
        jProgressBarDemiRezervoarBr2.setForeground(Color.ORANGE);
 
        jProgressBarDemiRezervoar150m3.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMin());
        jProgressBarDemiRezervoar150m3.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMax());
        jProgressBarDemiRezervoar150m3.setForeground(Color.ORANGE);
    }

   
    

    private void refreshDLmerenja() {

        jLabelPritisakInJKKCopyDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLjkkfIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija01().getPritisakDLjkkfIn().getBrDec()) + " bar");
        jLabelPritisakOutJKKCopyDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLjkkfOut().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija01().getPritisakDLjkkfOut().getBrDec()) + " bar");
        jLabelPritisakInSBACopyDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLsbafIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija01().getPritisakDLsbafIn().getBrDec()) + " bar");
        jLabelPritisakOutSBACopyDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLsbafOut().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija01().getPritisakDLsbafOut().getBrDec()) + " bar");
        jLabelPritisakInJBACopyDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLjbafIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija01().getPritisakDLjbafIn().getBrDec()) + " bar");
        jLabelPritisakOutJBACopyDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLjbafOut().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija01().getPritisakDLjbafOut().getBrDec()) + " bar");
        jLabelPritisakInMFCopyDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLmfIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija01().getPritisakDLmfIn().getBrDec()) + " bar");
        jLabelPritisakOutMFCopyDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLmfOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getPritisakDLmfOut().getBrDec()) + " bar");

        jLabelPritisakInJKKCopyDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLjkkfIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija02().getPritisakDLjkkfIn().getBrDec()) + " bar");
        jLabelPritisakOutJKKCopyDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLjkkfOut().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija02().getPritisakDLjkkfOut().getBrDec()) + " bar");
        jLabelPritisakInSBACopyDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLsbafIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija02().getPritisakDLsbafIn().getBrDec()) + " bar");
        jLabelPritisakOutSBACopyDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLsbafOut().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija02().getPritisakDLsbafOut().getBrDec()) + " bar");
        jLabelPritisakInJBACopyDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLjbafIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija02().getPritisakDLjbafIn().getBrDec()) + " bar");
        jLabelPritisakOutJBACopyDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLjbafOut().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija02().getPritisakDLjbafOut().getBrDec()) + " bar");
        jLabelPritisakInMFCopyDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLmfIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija02().getPritisakDLmfIn().getBrDec()) + " bar");
        jLabelPritisakOutMFCopyDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLmfOut().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija02().getPritisakDLmfOut().getBrDec()) + " bar");

        jLabelPritisakInJKKCopyDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLjkkfIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLjkkfIn().getBrDec()) + " bar");
        jLabelPritisakOutJKKCopyDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLjkkfOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLjkkfOut().getBrDec()) + " bar");
        jLabelPritisakInSBACopyDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLsbafIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLsbafIn().getBrDec()) + " bar");
        jLabelPritisakOutSBACopyDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLsbafOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLsbafOut().getBrDec()) + " bar");
        jLabelPritisakInJBACopyDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLjbafIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLjbafIn().getBrDec()) + " bar");
        jLabelPritisakOutJBACopyDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLjbafOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLjbafOut().getBrDec()) + " bar");
        jLabelPritisakInMFCopyDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLmfIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLmfIn().getBrDec()) + " bar");
        jLabelPritisakOutMFCopyDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLmfOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLmfOut().getBrDec()) + " bar");
        
        vodljivostSBA1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getVodljivostSBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getVodljivostSBA().getBrDec()) + " μS/cm");
        vodljivostJBA1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getVodljivostJBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getVodljivostJBA().getBrDec()) + " μS/cm");
        vodljivostMF1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getVodljivostMF().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getVodljivostMF().getBrDec()) + " μS/cm");
        
         vodljivostSBA2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getVodljivostSBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getVodljivostSBA().getBrDec()) + " μS/cm");
        vodljivostJBA2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getVodljivostJBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getVodljivostJBA().getBrDec()) + " μS/cm");
        vodljivostMF2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getVodljivostMF().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getVodljivostMF().getBrDec()) + " μS/cm");
        
        vodljivostSBA3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getVodljivostSBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getVodljivostSBA().getBrDec()) + " μS/cm");
        vodljivostJBA3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getVodljivostJBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getVodljivostJBA().getBrDec()) + " μS/cm");
        vodljivostMF3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getVodljivostMF().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getVodljivostMF().getBrDec()) + " μS/cm");
        
        vodljivostKolektor.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getVodljivostKolektor().getVrednostRegistra(),
                demiLinijeMerenja.getVodljivostKolektor().getBrDec()) + " μS/cm");
        
    }

    private void refreshVentiliGP() {
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji01, ventiliGP01.getGP01_potisDemi1());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji02, ventiliGP01.getGP01_potisDemi2());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji03, ventiliGP01.getGP01_potisDemi3());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji04, ventiliGP01.getGP01_potisDemi4());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji05, ventiliGP01.getGP01_potisDemi5());
    }
 
    
    private void refreshDLVentili() {
         try {
            int a = demiLinije.getJkkf01().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelDL1JKKFRegVentilCopyDL, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelDL1JKKFRegVentilCopyDLVrednost.setText(ShiftPoint.shiftonePoint(a, demiLinije.getJkkf01().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
   
        
        try {
            int a = demiLinije.getJkkf02().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelDL2JKKFRegVentilCopyDL, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelDL2JKKFRegVentilCopyDLVrednost.setText(ShiftPoint.shiftonePoint(a, demiLinije.getJkkf02().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
       
        
        try {
            int a = demiLinije.getJkkf03().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelDL3JKKFRegVentilCopyDL, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelDL3JKKFRegVentilCopyDLVrednost.setText(ShiftPoint.shiftonePoint(a, demiLinije.getJkkf03().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
      
    }

    
    
    private void refreshBazeniMerenja() {
        int a = bazeniMerenja.getBazenDekaFiltriraneVode().getVrednostRegistra();
        jLabelNivoBazenDekaFiltriraneVodeCopyDL.setText("L= " + Integer.toString(a) + " cm");
        jProgressBarDekaFiltriranaVodaCopyDL.setValue(a);

        /*
        int b = bazeniMerenja.getBazenOtpadneVodeOdPranjaPescanihFiltera().getVrednostRegistra();
        jProgressBarOtpadneOdPranjaPescani.setValue(b);
        jLabelNivoOtpadneVodePranjePF.setText("L= " + Integer.toString(b) + " cm");

        int c = bazeniMerenja.getBazenDekaNefiltriraneVode().getVrednostRegistra();
        jProgressBarDekaNefiltriraneVode.setValue(c);
        jLabelNivoDekaNefiltrirana.setText("L= " + Integer.toString(c) + " cm");
*/
        int d = bazeniMerenja.getBazenNeutralizacioni().getVrednostRegistra();
        jProgressBarNeutralizacioniBazen.setValue(d);
        jLabelNivoNeutralizacioni.setText("L= " + Integer.toString(d) + " cm");
        
    }

    

    private void refreshProtoci() {
        
        jLabelProtokDemiLinijaOutCopyBr1.setText(Integer.toString(protociDemiLinije.getProtokDL1out().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokDemiLinijaOutCopyBr2.setText(Integer.toString(protociDemiLinije.getProtokDL2out().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokDemiLinijaOutCopyBr3.setText(Integer.toString(protociDemiLinije.getProtokDL3out().getProtok().getVrednostRegistra()) + " m3/h");

       
     

        jLabelKumulativnoOutDLCopyBr1.setText(intToLong(protociDemiLinije.getProtokDL1out().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL1out().getKumulativnoNiziVrednost()));
        jLabelKumulativnoOutDLCopyBr2.setText(intToLong(protociDemiLinije.getProtokDL2out().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL2out().getKumulativnoNiziVrednost()));
        jLabelKumulativnoOutDLCopyBr3.setText(intToLong(protociDemiLinije.getProtokDL3out().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL3out().getKumulativnoNiziVrednost()));

        

        jLabelProtokDemiLinijaMagistrala.setText(Integer.toString(protociDemiLinije.getProtokMagistralniVod().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoDemiLinijaMagistrala.setText(intToLong(protociDemiLinije.getProtokMagistralniVod().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokMagistralniVod().getKumulativnoNiziVrednost()));
 

        jLabelKumulativnoDL1CopyDL.setText(intToLong(protociDemiLinije.getProtokDL1in().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL1in().getKumulativnoNiziVrednost()));
        jLabelKumulativnoDL2CopyDL.setText(intToLong(protociDemiLinije.getProtokDL2in().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL2in().getKumulativnoNiziVrednost()));
        jLabelKumulativnoDL3CopyDL.setText(intToLong(protociDemiLinije.getProtokDL3in().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL3in().getKumulativnoNiziVrednost()));

 
        jLabelPretovarnaLuzina.setText(Integer.toString(protociPretovarnaRampa.getProtokLuzine().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelPretovarnaKiselina.setText(Integer.toString(protociPretovarnaRampa.getProtokKiseline().getProtok().getVrednostRegistra()) + " m3/h");

        jLabelPretovarnaKumulativnoLuzina.setText(intToLong(protociPretovarnaRampa.getProtokLuzine().getKumulativnoVisiVrednost(), protociPretovarnaRampa.getProtokLuzine().getKumulativnoNiziVrednost()));
        jLabelPretovarnaKumulativnoKiselina.setText(intToLong(protociPretovarnaRampa.getProtokKiseline().getKumulativnoVisiVrednost(), protociPretovarnaRampa.getProtokKiseline().getKumulativnoNiziVrednost()));

    }

    private void refreshPumpeFiltriraneVodeKaDemineralizaciji() {
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr01, pumpeDekaFiltriranaKaDemi.getPumpaBr1().getVrednosti().isUkljucen());

        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr02, pumpeDekaFiltriranaKaDemi.getPumpaBr2().getVrednosti().isUkljucen());

        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr03, pumpeDekaFiltriranaKaDemi.getPumpaBr3().getVrednosti().isUkljucen());

        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr04, pumpeDekaFiltriranaKaDemi.getPumpaBr4().getVrednosti().isUkljucen());

        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr05, pumpeDekaFiltriranaKaDemi.getPumpaBr5().getVrednosti().isUkljucen());

       
    }

   

    

    private void refreshPumpeNeutralizacionogBazena() {
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr1, pumpeNeutralizacionogBazena.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr2, pumpeNeutralizacionogBazena.getPumpaBr2().getVrednosti().isUkljucen());
    }

   

    private void refreshRezervoariMerenja() {
        int a = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getVrednostRegistra();
        jProgressBarDemiRezervoarBr1.setValue(a);
        jLabelDemiRezervoarBr1.setText("L= " + Integer.toString(a) + " cm");

        int b = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getVrednostRegistra();
        jProgressBarDemiRezervoarBr2.setValue(a);
        jLabelDemiRezervoarBr2.setText("L= " + Integer.toString(b) + " cm");

        int c = rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getVrednostRegistra();
        jProgressBarDemiRezervoar150m3.setValue(c);
        jLabelDemiRezervoar150m3.setText("L= " + Integer.toString(c) + " cm");
    }   
    
    private void refreshTemperature(){
        jLabelTemperaturaLuzine.setText(ShiftPoint.shiftonePoint(temperature.getTempLuzineRezervoar13a03().getVrednostRegistra(), 
                temperature.getTempLuzineRezervoar13a03().getBrDec()) + " C*");
        
        jLabelTemperaturaDemiVode150m3.setText(ShiftPoint.shiftonePoint(temperature.getTempDemiVodeRezervoar150m3().getVrednostRegistra(), 
                temperature.getTempDemiVodeRezervoar150m3().getBrDec()) + " C*");
    }
}
