/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import field.merenja.bazeni.Nivoi;
import field.merenja.demiLinije.DemiLinijaMerenjaKonstruktor;
import field.merenja.protoci.ProtociDemiLinije;
import field.merenja.rezervoari.RezervoariMerenja;
import field.pumpe.PumpeDekaFiltrKaDemi;
import field.pumpe.PumpeNeutralizacionogBazena;
import field.ventili.DemiLinije;
import field.ventili.VentiliGrupaPumpi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import popup.AllPopUpWindow;
import tools.AnalogToDigital;
import tools.Convert;
import tools.ShiftPoint;

/**
 *
 * @author branko.scekic
 */
public class DemiL2Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DemiL2Frame
     * @param allPopUpWindow
     */
    public DemiL2Frame(ProtociDemiLinije protociDemiLinije, Nivoi bazeniMerenja, 
            RezervoariMerenja rezervoariMerenja, 
            DemiLinijaMerenjaKonstruktor demiLinijeMerenja, VentiliGrupaPumpi ventiliGP01, 
            DemiLinije demiLinije, PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi, 
            PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena,
            Img img, AllPopUpWindow allPopUpWindow) {
        
        initComponents();
        this.protociDemiLinije = protociDemiLinije;
        this.pumpeDekaFiltriranaKaDemi = pumpeDekaFiltriranaKaDemi;
        this.pumpeNeutralizacionogBazena = pumpeNeutralizacionogBazena;
        this.bazeniMerenja = bazeniMerenja;
        this.rezervoariMerenja = rezervoariMerenja;
        this.demiLinijeMerenja = demiLinijeMerenja;
        this.ventiliGP01 = ventiliGP01;
        this.demiLinije = demiLinije;
        this.allPopUpWindow = allPopUpWindow;
        this.img = img;
        
        setMinMax();
        screenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDL2JKKFRegVentil01 = new javax.swing.JLabel();
        jLabelDL2JKKFRegVentil01Vrednost = new javax.swing.JLabel();
        jLabelDL02JKKFventil03 = new javax.swing.JLabel();
        jLabelDL02JKKFventil04 = new javax.swing.JLabel();
        jLabelDL02JKKFventil05 = new javax.swing.JLabel();
        jLabelDL02JKKFventil06 = new javax.swing.JLabel();
        jLabelDL02JKKFventil07 = new javax.swing.JLabel();
        jLabelDL02JKKFventil08 = new javax.swing.JLabel();
        jLabelDL02JKKFventil09 = new javax.swing.JLabel();
        jLabelDL02JKKFventil10 = new javax.swing.JLabel();
        jLabelDL02JKKFventil11 = new javax.swing.JLabel();
        jLabelDL02JKKFventil12 = new javax.swing.JLabel();
        jLabelDL02SBAFventil01 = new javax.swing.JLabel();
        jLabelDL02SBAFventil02 = new javax.swing.JLabel();
        jLabelDL02SBAFventil03 = new javax.swing.JLabel();
        jLabelDL02SBAFventil04 = new javax.swing.JLabel();
        jLabelDL02SBAFventil05 = new javax.swing.JLabel();
        jLabelDL02SBAFventil06 = new javax.swing.JLabel();
        jLabelDL02JBAFventil01 = new javax.swing.JLabel();
        jLabelDL02JBAFventil02 = new javax.swing.JLabel();
        jLabelDL02JBAFventil03 = new javax.swing.JLabel();
        jLabelDL02JBAFventil04 = new javax.swing.JLabel();
        jLabelDL02JBAFventil05 = new javax.swing.JLabel();
        jLabelDL02JBAFventil06 = new javax.swing.JLabel();
        jLabelDL02JBAFventil07 = new javax.swing.JLabel();
        jLabelDL02JBAFventil08 = new javax.swing.JLabel();
        jLabelDL02MFventil01 = new javax.swing.JLabel();
        jLabelDL02MFventil02 = new javax.swing.JLabel();
        jLabelDL02MFventil03 = new javax.swing.JLabel();
        jLabelDL02MFventil04 = new javax.swing.JLabel();
        jLabelDL02MFventil05 = new javax.swing.JLabel();
        jLabelDL02MFventil06 = new javax.swing.JLabel();
        jLabelDL02MFventil07 = new javax.swing.JLabel();
        jLabelDL02MFventil08 = new javax.swing.JLabel();
        jLabelDL02MFventil10 = new javax.swing.JLabel();
        jLabelDL02MFventil11 = new javax.swing.JLabel();
        jLabelNivoBazenDekaFiltriraneVodeCopyDL02 = new javax.swing.JLabel();
        jProgressBarDekaFiltriranaVodaCopyDL02 = new javax.swing.JProgressBar();
        jLabelNivoNeutralizacioniCopyDL02 = new javax.swing.JLabel();
        jProgressBarNeutralizacioniBazenCopyDL02 = new javax.swing.JProgressBar();
        jLabelPumpeKaDemiLiniji01CopyDL2 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji02CopyDL2 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji03CopyDL2 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji04CopyDL2 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji05CopyDL2 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2 = new javax.swing.JLabel();
        jProgressBarDemiRezervoarBr1CopyDL2 = new javax.swing.JProgressBar();
        jLabelDemiRezervoarBr1CopyDL2 = new javax.swing.JLabel();
        jProgressBarDemiRezervoarBr2CopyDL2 = new javax.swing.JProgressBar();
        jLabelDemiRezervoarBr2CopyDL2 = new javax.swing.JLabel();
        jProgressBarDemiRezervoar150mCopyDL2 = new javax.swing.JProgressBar();
        jLabelDemiRezervoar150mCopyDL2 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaInBr2 = new javax.swing.JLabel();
        jLabelKumulativnoInDL2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr1CopyDL2 = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr2CopyDL2 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaOutBr2 = new javax.swing.JLabel();
        jLabelKumulativnoOutDL2 = new javax.swing.JLabel();
        jLabelKumulativnoDemiLinijaMagistrala2 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaMagistrala2 = new javax.swing.JLabel();
        jLabelPritisakInJKKDL2 = new javax.swing.JLabel();
        jLabelPritisakOutJKKDL2 = new javax.swing.JLabel();
        jLabelPritisakInSBADL2 = new javax.swing.JLabel();
        jLabelPritisakOutSBADL2 = new javax.swing.JLabel();
        jLabelPritisakInJBADL2 = new javax.swing.JLabel();
        jLabelPritisakOutJBADL2 = new javax.swing.JLabel();
        jLabelPritisakInMFDL2 = new javax.swing.JLabel();
        jLabelPritisakOutMFDL2 = new javax.swing.JLabel();
        vodljivostSBA = new javax.swing.JLabel();
        vodljivostJBA = new javax.swing.JLabel();
        vodljivostMF = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabelDL2JKKFRegVentil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL2JKKFRegVentil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL2JKKFRegVentil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL2JKKFRegVentil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL2JKKFRegVentil01);
        jLabelDL2JKKFRegVentil01.setBounds(280, 420, 50, 40);

        jLabelDL2JKKFRegVentil01Vrednost.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelDL2JKKFRegVentil01Vrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL2JKKFRegVentil01Vrednost.setText("***");
        getContentPane().add(jLabelDL2JKKFRegVentil01Vrednost);
        jLabelDL2JKKFRegVentil01Vrednost.setBounds(280, 460, 50, 19);

        jLabelDL02JKKFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JKKFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil03);
        jLabelDL02JKKFventil03.setBounds(370, 420, 50, 40);

        jLabelDL02JKKFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JKKFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil04);
        jLabelDL02JKKFventil04.setBounds(470, 420, 40, 40);

        jLabelDL02JKKFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL02JKKFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil05);
        jLabelDL02JKKFventil05.setBounds(240, 480, 40, 40);

        jLabelDL02JKKFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JKKFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil06);
        jLabelDL02JKKFventil06.setBounds(470, 370, 40, 30);

        jLabelDL02JKKFventil07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JKKFventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil07);
        jLabelDL02JKKFventil07.setBounds(370, 510, 50, 40);

        jLabelDL02JKKFventil08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JKKFventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil08);
        jLabelDL02JKKFventil08.setBounds(370, 370, 50, 40);

        jLabelDL02JKKFventil09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL02JKKFventil09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil09MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil09);
        jLabelDL02JKKFventil09.setBounds(286, 320, 40, 50);

        jLabelDL02JKKFventil10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JKKFventil10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil10);
        jLabelDL02JKKFventil10.setBounds(370, 470, 50, 30);

        jLabelDL02JKKFventil11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JKKFventil11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil11);
        jLabelDL02JKKFventil11.setBounds(470, 510, 40, 40);

        jLabelDL02JKKFventil12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JKKFventil12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL02JKKFventil12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JKKFventil12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JKKFventil12);
        jLabelDL02JKKFventil12.setBounds(560, 490, 40, 60);

        jLabelDL02SBAFventil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02SBAFventil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02SBAFventil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02SBAFventil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02SBAFventil01);
        jLabelDL02SBAFventil01.setBounds(690, 420, 40, 40);

        jLabelDL02SBAFventil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02SBAFventil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02SBAFventil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02SBAFventil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02SBAFventil02);
        jLabelDL02SBAFventil02.setBounds(690, 470, 40, 30);

        jLabelDL02SBAFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02SBAFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02SBAFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02SBAFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02SBAFventil03);
        jLabelDL02SBAFventil03.setBounds(780, 370, 40, 30);

        jLabelDL02SBAFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02SBAFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02SBAFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02SBAFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02SBAFventil04);
        jLabelDL02SBAFventil04.setBounds(790, 470, 50, 30);

        jLabelDL02SBAFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02SBAFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02SBAFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02SBAFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02SBAFventil05);
        jLabelDL02SBAFventil05.setBounds(760, 520, 50, 30);

        jLabelDL02SBAFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02SBAFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL02SBAFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02SBAFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02SBAFventil06);
        jLabelDL02SBAFventil06.setBounds(880, 490, 26, 50);

        jLabelDL02JBAFventil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JBAFventil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JBAFventil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JBAFventil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JBAFventil01);
        jLabelDL02JBAFventil01.setBounds(990, 420, 40, 40);

        jLabelDL02JBAFventil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JBAFventil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JBAFventil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JBAFventil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JBAFventil02);
        jLabelDL02JBAFventil02.setBounds(1080, 430, 50, 30);

        jLabelDL02JBAFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JBAFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JBAFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JBAFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JBAFventil03);
        jLabelDL02JBAFventil03.setBounds(990, 470, 40, 30);

        jLabelDL02JBAFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JBAFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JBAFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JBAFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JBAFventil04);
        jLabelDL02JBAFventil04.setBounds(1090, 370, 40, 30);

        jLabelDL02JBAFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JBAFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JBAFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JBAFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JBAFventil05);
        jLabelDL02JBAFventil05.setBounds(1000, 370, 40, 30);

        jLabelDL02JBAFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JBAFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JBAFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JBAFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JBAFventil06);
        jLabelDL02JBAFventil06.setBounds(990, 550, 40, 30);

        jLabelDL02JBAFventil07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JBAFventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02JBAFventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JBAFventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JBAFventil07);
        jLabelDL02JBAFventil07.setBounds(1070, 520, 40, 40);

        jLabelDL02JBAFventil08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02JBAFventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL02JBAFventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02JBAFventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02JBAFventil08);
        jLabelDL02JBAFventil08.setBounds(1170, 500, 30, 50);

        jLabelDL02MFventil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02MFventil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil01);
        jLabelDL02MFventil01.setBounds(1300, 430, 50, 30);

        jLabelDL02MFventil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02MFventil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil02);
        jLabelDL02MFventil02.setBounds(1390, 430, 40, 30);

        jLabelDL02MFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02MFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil03);
        jLabelDL02MFventil03.setBounds(1300, 470, 50, 40);

        jLabelDL02MFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02MFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil04);
        jLabelDL02MFventil04.setBounds(1390, 370, 50, 30);

        jLabelDL02MFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02MFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil05);
        jLabelDL02MFventil05.setBounds(1400, 470, 40, 40);

        jLabelDL02MFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02MFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil06);
        jLabelDL02MFventil06.setBounds(1290, 370, 60, 30);

        jLabelDL02MFventil07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL02MFventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil07);
        jLabelDL02MFventil07.setBounds(1220, 500, 26, 50);

        jLabelDL02MFventil08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02MFventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil08);
        jLabelDL02MFventil08.setBounds(1300, 520, 50, 40);

        jLabelDL02MFventil10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL02MFventil10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil10);
        jLabelDL02MFventil10.setBounds(1380, 520, 40, 40);

        jLabelDL02MFventil11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL02MFventil11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL02MFventil11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL02MFventil11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL02MFventil11);
        jLabelDL02MFventil11.setBounds(1470, 490, 30, 50);

        jLabelNivoBazenDekaFiltriraneVodeCopyDL02.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoBazenDekaFiltriraneVodeCopyDL02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoBazenDekaFiltriraneVodeCopyDL02.setText("+++");
        jLabelNivoBazenDekaFiltriraneVodeCopyDL02.setBorder(null);
        getContentPane().add(jLabelNivoBazenDekaFiltriraneVodeCopyDL02);
        jLabelNivoBazenDekaFiltriraneVodeCopyDL02.setBounds(380, 910, 200, 20);

        jProgressBarDekaFiltriranaVodaCopyDL02.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarDekaFiltriranaVodaCopyDL02.setOrientation(1);
        jProgressBarDekaFiltriranaVodaCopyDL02.setToolTipText("");
        jProgressBarDekaFiltriranaVodaCopyDL02.setValue(10);
        jProgressBarDekaFiltriranaVodaCopyDL02.setBorderPainted(false);
        jProgressBarDekaFiltriranaVodaCopyDL02.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarDekaFiltriranaVodaCopyDL02.setString("");
        jProgressBarDekaFiltriranaVodaCopyDL02.setStringPainted(true);
        getContentPane().add(jProgressBarDekaFiltriranaVodaCopyDL02);
        jProgressBarDekaFiltriranaVodaCopyDL02.setBounds(300, 840, 20, 90);

        jLabelNivoNeutralizacioniCopyDL02.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoNeutralizacioniCopyDL02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoNeutralizacioniCopyDL02.setText("***");
        jLabelNivoNeutralizacioniCopyDL02.setBorder(null);
        getContentPane().add(jLabelNivoNeutralizacioniCopyDL02);
        jLabelNivoNeutralizacioniCopyDL02.setBounds(770, 900, 130, 24);

        jProgressBarNeutralizacioniBazenCopyDL02.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarNeutralizacioniBazenCopyDL02.setOrientation(1);
        jProgressBarNeutralizacioniBazenCopyDL02.setToolTipText("");
        jProgressBarNeutralizacioniBazenCopyDL02.setValue(10);
        jProgressBarNeutralizacioniBazenCopyDL02.setBorderPainted(false);
        jProgressBarNeutralizacioniBazenCopyDL02.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarNeutralizacioniBazenCopyDL02.setString("");
        jProgressBarNeutralizacioniBazenCopyDL02.setStringPainted(true);
        getContentPane().add(jProgressBarNeutralizacioniBazenCopyDL02);
        jProgressBarNeutralizacioniBazenCopyDL02.setBounds(710, 840, 20, 90);

        jLabelPumpeKaDemiLiniji01CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji01CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji01CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji01CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji01CopyDL2);
        jLabelPumpeKaDemiLiniji01CopyDL2.setBounds(320, 670, 40, 40);

        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2);
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2.setBounds(310, 720, 60, 50);

        jLabelPumpeKaDemiLiniji02CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji02CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji02CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji02CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji02CopyDL2);
        jLabelPumpeKaDemiLiniji02CopyDL2.setBounds(390, 670, 40, 40);

        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2);
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2.setBounds(380, 710, 60, 60);

        jLabelPumpeKaDemiLiniji03CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji03CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji03CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji03CopyDL2);
        jLabelPumpeKaDemiLiniji03CopyDL2.setBounds(470, 670, 26, 40);

        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2);
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2.setBounds(460, 720, 50, 50);

        jLabelPumpeKaDemiLiniji04CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji04CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji04CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji04CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji04CopyDL2);
        jLabelPumpeKaDemiLiniji04CopyDL2.setBounds(540, 670, 30, 40);

        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2);
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2.setBounds(530, 710, 50, 60);

        jLabelPumpeKaDemiLiniji05CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji05CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji05CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji05CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji05CopyDL2);
        jLabelPumpeKaDemiLiniji05CopyDL2.setBounds(610, 670, 40, 40);

        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2);
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2.setBounds(600, 720, 60, 50);

        jProgressBarDemiRezervoarBr1CopyDL2.setOrientation(1);
        jProgressBarDemiRezervoarBr1CopyDL2.setValue(10);
        jProgressBarDemiRezervoarBr1CopyDL2.setString("0");
        jProgressBarDemiRezervoarBr1CopyDL2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr1CopyDL2);
        jProgressBarDemiRezervoarBr1CopyDL2.setBounds(1010, 770, 20, 160);

        jLabelDemiRezervoarBr1CopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr1CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr1CopyDL2.setText("***");
        jLabelDemiRezervoarBr1CopyDL2.setBorder(null);
        getContentPane().add(jLabelDemiRezervoarBr1CopyDL2);
        jLabelDemiRezervoarBr1CopyDL2.setBounds(1020, 900, 130, 30);

        jProgressBarDemiRezervoarBr2CopyDL2.setOrientation(1);
        jProgressBarDemiRezervoarBr2CopyDL2.setValue(10);
        jProgressBarDemiRezervoarBr2CopyDL2.setString("0");
        jProgressBarDemiRezervoarBr2CopyDL2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr2CopyDL2);
        jProgressBarDemiRezervoarBr2CopyDL2.setBounds(1200, 770, 20, 160);

        jLabelDemiRezervoarBr2CopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr2CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr2CopyDL2.setText("***");
        jLabelDemiRezervoarBr2CopyDL2.setBorder(null);
        getContentPane().add(jLabelDemiRezervoarBr2CopyDL2);
        jLabelDemiRezervoarBr2CopyDL2.setBounds(1220, 900, 130, 30);

        jProgressBarDemiRezervoar150mCopyDL2.setOrientation(1);
        jProgressBarDemiRezervoar150mCopyDL2.setValue(10);
        jProgressBarDemiRezervoar150mCopyDL2.setString("0");
        jProgressBarDemiRezervoar150mCopyDL2.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoar150mCopyDL2);
        jProgressBarDemiRezervoar150mCopyDL2.setBounds(910, 650, 20, 120);

        jLabelDemiRezervoar150mCopyDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoar150mCopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoar150mCopyDL2.setText("***");
        jLabelDemiRezervoar150mCopyDL2.setBorder(null);
        getContentPane().add(jLabelDemiRezervoar150mCopyDL2);
        jLabelDemiRezervoar150mCopyDL2.setBounds(910, 740, 110, 30);

        jLabelProtokDemiLinijaInBr2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaInBr2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaInBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaInBr2.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaInBr2);
        jLabelProtokDemiLinijaInBr2.setBounds(210, 660, 100, 19);

        jLabelKumulativnoInDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoInDL2.setText("***");
        getContentPane().add(jLabelKumulativnoInDL2);
        jLabelKumulativnoInDL2.setBounds(180, 680, 150, 20);

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel21.setText("BR 2");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(1110, 30, 140, 50);

        jLabelPumpaNeutralizacioniBazenBr1CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr1CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr1CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr1CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr1CopyDL2);
        jLabelPumpaNeutralizacioniBazenBr1CopyDL2.setBounds(760, 790, 50, 50);

        jLabelPumpaNeutralizacioniBazenBr2CopyDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr2CopyDL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr2CopyDL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr2CopyDL2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr2CopyDL2);
        jLabelPumpaNeutralizacioniBazenBr2CopyDL2.setBounds(820, 790, 50, 50);

        jLabelProtokDemiLinijaOutBr2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaOutBr2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaOutBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaOutBr2.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaOutBr2);
        jLabelProtokDemiLinijaOutBr2.setBounds(1560, 420, 100, 19);

        jLabelKumulativnoOutDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoOutDL2.setText("***");
        getContentPane().add(jLabelKumulativnoOutDL2);
        jLabelKumulativnoOutDL2.setBounds(1530, 400, 150, 20);

        jLabelKumulativnoDemiLinijaMagistrala2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoDemiLinijaMagistrala2.setText("***");
        getContentPane().add(jLabelKumulativnoDemiLinijaMagistrala2);
        jLabelKumulativnoDemiLinijaMagistrala2.setBounds(1450, 750, 150, 20);

        jLabelProtokDemiLinijaMagistrala2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaMagistrala2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaMagistrala2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaMagistrala2.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaMagistrala2);
        jLabelProtokDemiLinijaMagistrala2.setBounds(1470, 730, 100, 19);

        jLabelPritisakInJKKDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJKKDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJKKDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJKKDL2);
        jLabelPritisakInJKKDL2.setBounds(350, 320, 90, 30);

        jLabelPritisakOutJKKDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJKKDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJKKDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJKKDL2);
        jLabelPritisakOutJKKDL2.setBounds(460, 320, 90, 30);

        jLabelPritisakInSBADL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInSBADL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInSBADL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakInSBADL2);
        jLabelPritisakInSBADL2.setBounds(650, 320, 90, 30);

        jLabelPritisakOutSBADL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutSBADL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutSBADL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutSBADL2);
        jLabelPritisakOutSBADL2.setBounds(760, 320, 90, 30);

        jLabelPritisakInJBADL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJBADL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJBADL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJBADL2);
        jLabelPritisakInJBADL2.setBounds(960, 320, 90, 30);

        jLabelPritisakOutJBADL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJBADL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJBADL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJBADL2);
        jLabelPritisakOutJBADL2.setBounds(1070, 320, 90, 30);

        jLabelPritisakInMFDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInMFDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInMFDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakInMFDL2);
        jLabelPritisakInMFDL2.setBounds(1270, 320, 90, 30);

        jLabelPritisakOutMFDL2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutMFDL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutMFDL2.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutMFDL2);
        jLabelPritisakOutMFDL2.setBounds(1380, 320, 90, 30);

        vodljivostSBA.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostSBA.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostSBA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostSBA.setText("jLabel15");
        getContentPane().add(vodljivostSBA);
        vodljivostSBA.setBounds(680, 590, 140, 30);

        vodljivostJBA.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostJBA.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostJBA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostJBA.setText("jLabel15");
        getContentPane().add(vodljivostJBA);
        vodljivostJBA.setBounds(970, 590, 160, 30);

        vodljivostMF.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostMF.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostMF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostMF.setText("jLabel15");
        getContentPane().add(vodljivostMF);
        vodljivostMF.setBounds(1300, 590, 140, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/statImg/Demi/DEMI linija detaljno.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(6, 0, 1730, 970);

        setBounds(170, 35, 1752, 998);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelDL2JKKFRegVentil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL2JKKFRegVentil01MouseClicked
        allPopUpWindow.ProzorDL02JKKF01();
    }//GEN-LAST:event_jLabelDL2JKKFRegVentil01MouseClicked

    private void jLabelDL02JKKFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil03MouseClicked
        allPopUpWindow.ProzorDL02JKKF03();
    }//GEN-LAST:event_jLabelDL02JKKFventil03MouseClicked

    private void jLabelDL02JKKFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil04MouseClicked
        allPopUpWindow.ProzorDL02JKKF04();
    }//GEN-LAST:event_jLabelDL02JKKFventil04MouseClicked

    private void jLabelDL02JKKFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil05MouseClicked
        allPopUpWindow.ProzorDL02JKKF05();
    }//GEN-LAST:event_jLabelDL02JKKFventil05MouseClicked

    private void jLabelDL02JKKFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil06MouseClicked
        allPopUpWindow.ProzorDL02JKKF06();
    }//GEN-LAST:event_jLabelDL02JKKFventil06MouseClicked

    private void jLabelDL02JKKFventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil07MouseClicked
       allPopUpWindow.ProzorDL02JKKF07();
    }//GEN-LAST:event_jLabelDL02JKKFventil07MouseClicked

    private void jLabelDL02JKKFventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil08MouseClicked
        allPopUpWindow.ProzorDL02JKKF08();
    }//GEN-LAST:event_jLabelDL02JKKFventil08MouseClicked

    private void jLabelDL02JKKFventil09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil09MouseClicked
        allPopUpWindow.ProzorDL02JKKF09();
    }//GEN-LAST:event_jLabelDL02JKKFventil09MouseClicked

    private void jLabelDL02JKKFventil10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil10MouseClicked
        allPopUpWindow.ProzorDL02JKKF10();
    }//GEN-LAST:event_jLabelDL02JKKFventil10MouseClicked

    private void jLabelDL02JKKFventil11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil11MouseClicked
        allPopUpWindow.ProzorDL02JKKF11();
    }//GEN-LAST:event_jLabelDL02JKKFventil11MouseClicked

    private void jLabelDL02JKKFventil12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JKKFventil12MouseClicked
        allPopUpWindow.ProzorDL02JKKF12();
    }//GEN-LAST:event_jLabelDL02JKKFventil12MouseClicked

    private void jLabelDL02SBAFventil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02SBAFventil01MouseClicked
        allPopUpWindow.ProzorDL02SBA01();
    }//GEN-LAST:event_jLabelDL02SBAFventil01MouseClicked

    private void jLabelDL02SBAFventil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02SBAFventil02MouseClicked
        allPopUpWindow.ProzorDL02SBA02();
    }//GEN-LAST:event_jLabelDL02SBAFventil02MouseClicked

    private void jLabelDL02SBAFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02SBAFventil03MouseClicked
        allPopUpWindow.ProzorDL02SBA03();
    }//GEN-LAST:event_jLabelDL02SBAFventil03MouseClicked

    private void jLabelDL02SBAFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02SBAFventil04MouseClicked
        allPopUpWindow.ProzorDL02SBA04();
    }//GEN-LAST:event_jLabelDL02SBAFventil04MouseClicked

    private void jLabelDL02SBAFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02SBAFventil05MouseClicked
        allPopUpWindow.ProzorDL02SBA05();
    }//GEN-LAST:event_jLabelDL02SBAFventil05MouseClicked

    private void jLabelDL02SBAFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02SBAFventil06MouseClicked
        allPopUpWindow.ProzorDL02SBA06();
    }//GEN-LAST:event_jLabelDL02SBAFventil06MouseClicked

    private void jLabelDL02JBAFventil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JBAFventil01MouseClicked
        allPopUpWindow.ProzorDL02JBA01();
    }//GEN-LAST:event_jLabelDL02JBAFventil01MouseClicked

    private void jLabelDL02JBAFventil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JBAFventil02MouseClicked
        allPopUpWindow.ProzorDL02JBA02();
    }//GEN-LAST:event_jLabelDL02JBAFventil02MouseClicked

    private void jLabelDL02JBAFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JBAFventil03MouseClicked
        allPopUpWindow.ProzorDL02JBA03();
    }//GEN-LAST:event_jLabelDL02JBAFventil03MouseClicked

    private void jLabelDL02JBAFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JBAFventil04MouseClicked
        allPopUpWindow.ProzorDL02JBA04();
    }//GEN-LAST:event_jLabelDL02JBAFventil04MouseClicked

    private void jLabelDL02JBAFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JBAFventil05MouseClicked
        allPopUpWindow.ProzorDL02JBA05();
    }//GEN-LAST:event_jLabelDL02JBAFventil05MouseClicked

    private void jLabelDL02JBAFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JBAFventil06MouseClicked
        allPopUpWindow.ProzorDL02JBA06();
    }//GEN-LAST:event_jLabelDL02JBAFventil06MouseClicked

    private void jLabelDL02JBAFventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JBAFventil07MouseClicked
        allPopUpWindow.ProzorDL02JBA07();
    }//GEN-LAST:event_jLabelDL02JBAFventil07MouseClicked

    private void jLabelDL02JBAFventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02JBAFventil08MouseClicked
        allPopUpWindow.ProzorDL02JBA08();
    }//GEN-LAST:event_jLabelDL02JBAFventil08MouseClicked

    private void jLabelDL02MFventil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil01MouseClicked
        allPopUpWindow.ProzorDL02MF01();
    }//GEN-LAST:event_jLabelDL02MFventil01MouseClicked

    private void jLabelDL02MFventil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil02MouseClicked
        allPopUpWindow.ProzorDL02MF02();
    }//GEN-LAST:event_jLabelDL02MFventil02MouseClicked

    private void jLabelDL02MFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil03MouseClicked
        allPopUpWindow.ProzorDL02MF03();
    }//GEN-LAST:event_jLabelDL02MFventil03MouseClicked

    private void jLabelDL02MFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil04MouseClicked
        allPopUpWindow.ProzorDL02MF04();
    }//GEN-LAST:event_jLabelDL02MFventil04MouseClicked

    private void jLabelDL02MFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil05MouseClicked
        allPopUpWindow.ProzorDL02MF05();
    }//GEN-LAST:event_jLabelDL02MFventil05MouseClicked

    private void jLabelDL02MFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil06MouseClicked
        allPopUpWindow.ProzorDL02MF06();
    }//GEN-LAST:event_jLabelDL02MFventil06MouseClicked

    private void jLabelDL02MFventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil07MouseClicked
        allPopUpWindow.ProzorDL02MF07();
    }//GEN-LAST:event_jLabelDL02MFventil07MouseClicked

    private void jLabelDL02MFventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil08MouseClicked
        allPopUpWindow.ProzorDL02MF08();
    }//GEN-LAST:event_jLabelDL02MFventil08MouseClicked

    private void jLabelDL02MFventil10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil10MouseClicked
        allPopUpWindow.ProzorDL02MF10();
    }//GEN-LAST:event_jLabelDL02MFventil10MouseClicked

    private void jLabelDL02MFventil11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL02MFventil11MouseClicked
        allPopUpWindow.ProzorDL02MF11();
    }//GEN-LAST:event_jLabelDL02MFventil11MouseClicked

    private void jLabelPumpeKaDemiLiniji01CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji01CopyDL2MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr1();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji01CopyDL2MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama01();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2MouseClicked

    private void jLabelPumpeKaDemiLiniji02CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji02CopyDL2MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr2();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji02CopyDL2MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama02();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2MouseClicked

    private void jLabelPumpeKaDemiLiniji03CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji03CopyDL2MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr3();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji03CopyDL2MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama03();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2MouseClicked

    private void jLabelPumpeKaDemiLiniji04CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji04CopyDL2MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr4();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji04CopyDL2MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama04();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2MouseClicked

    private void jLabelPumpeKaDemiLiniji05CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji05CopyDL2MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr5();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji05CopyDL2MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama05();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2MouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr1CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr1CopyDL2MouseClicked
        allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr1();
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr1CopyDL2MouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr2CopyDL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr2CopyDL2MouseClicked
        allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr2();
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr2CopyDL2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabelDL02JBAFventil01;
    private javax.swing.JLabel jLabelDL02JBAFventil02;
    private javax.swing.JLabel jLabelDL02JBAFventil03;
    private javax.swing.JLabel jLabelDL02JBAFventil04;
    private javax.swing.JLabel jLabelDL02JBAFventil05;
    private javax.swing.JLabel jLabelDL02JBAFventil06;
    private javax.swing.JLabel jLabelDL02JBAFventil07;
    private javax.swing.JLabel jLabelDL02JBAFventil08;
    private javax.swing.JLabel jLabelDL02JKKFventil03;
    private javax.swing.JLabel jLabelDL02JKKFventil04;
    private javax.swing.JLabel jLabelDL02JKKFventil05;
    private javax.swing.JLabel jLabelDL02JKKFventil06;
    private javax.swing.JLabel jLabelDL02JKKFventil07;
    private javax.swing.JLabel jLabelDL02JKKFventil08;
    private javax.swing.JLabel jLabelDL02JKKFventil09;
    private javax.swing.JLabel jLabelDL02JKKFventil10;
    private javax.swing.JLabel jLabelDL02JKKFventil11;
    private javax.swing.JLabel jLabelDL02JKKFventil12;
    private javax.swing.JLabel jLabelDL02MFventil01;
    private javax.swing.JLabel jLabelDL02MFventil02;
    private javax.swing.JLabel jLabelDL02MFventil03;
    private javax.swing.JLabel jLabelDL02MFventil04;
    private javax.swing.JLabel jLabelDL02MFventil05;
    private javax.swing.JLabel jLabelDL02MFventil06;
    private javax.swing.JLabel jLabelDL02MFventil07;
    private javax.swing.JLabel jLabelDL02MFventil08;
    private javax.swing.JLabel jLabelDL02MFventil10;
    private javax.swing.JLabel jLabelDL02MFventil11;
    private javax.swing.JLabel jLabelDL02SBAFventil01;
    private javax.swing.JLabel jLabelDL02SBAFventil02;
    private javax.swing.JLabel jLabelDL02SBAFventil03;
    private javax.swing.JLabel jLabelDL02SBAFventil04;
    private javax.swing.JLabel jLabelDL02SBAFventil05;
    private javax.swing.JLabel jLabelDL02SBAFventil06;
    private javax.swing.JLabel jLabelDL2JKKFRegVentil01;
    private javax.swing.JLabel jLabelDL2JKKFRegVentil01Vrednost;
    private javax.swing.JLabel jLabelDemiRezervoar150mCopyDL2;
    private javax.swing.JLabel jLabelDemiRezervoarBr1CopyDL2;
    private javax.swing.JLabel jLabelDemiRezervoarBr2CopyDL2;
    private javax.swing.JLabel jLabelKumulativnoDemiLinijaMagistrala2;
    private javax.swing.JLabel jLabelKumulativnoInDL2;
    private javax.swing.JLabel jLabelKumulativnoOutDL2;
    private javax.swing.JLabel jLabelNivoBazenDekaFiltriraneVodeCopyDL02;
    private javax.swing.JLabel jLabelNivoNeutralizacioniCopyDL02;
    private javax.swing.JLabel jLabelPritisakInJBADL2;
    private javax.swing.JLabel jLabelPritisakInJKKDL2;
    private javax.swing.JLabel jLabelPritisakInMFDL2;
    private javax.swing.JLabel jLabelPritisakInSBADL2;
    private javax.swing.JLabel jLabelPritisakOutJBADL2;
    private javax.swing.JLabel jLabelPritisakOutJKKDL2;
    private javax.swing.JLabel jLabelPritisakOutMFDL2;
    private javax.swing.JLabel jLabelPritisakOutSBADL2;
    private javax.swing.JLabel jLabelProtokDemiLinijaInBr2;
    private javax.swing.JLabel jLabelProtokDemiLinijaMagistrala2;
    private javax.swing.JLabel jLabelProtokDemiLinijaOutBr2;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr1CopyDL2;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr2CopyDL2;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji01CopyDL2;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji02CopyDL2;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji03CopyDL2;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji04CopyDL2;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji05CopyDL2;
    private javax.swing.JProgressBar jProgressBarDekaFiltriranaVodaCopyDL02;
    private javax.swing.JProgressBar jProgressBarDemiRezervoar150mCopyDL2;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr1CopyDL2;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr2CopyDL2;
    private javax.swing.JProgressBar jProgressBarNeutralizacioniBazenCopyDL02;
    private javax.swing.JLabel vodljivostJBA;
    private javax.swing.JLabel vodljivostMF;
    private javax.swing.JLabel vodljivostSBA;
    // End of variables declaration//GEN-END:variables
    private final Img img;
    private final AllPopUpWindow allPopUpWindow;
    private final ProtociDemiLinije protociDemiLinije;
    private final Nivoi bazeniMerenja;
    private final RezervoariMerenja rezervoariMerenja;
    private final DemiLinijaMerenjaKonstruktor demiLinijeMerenja;
    private final VentiliGrupaPumpi ventiliGP01;
    private final PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi;
    private final PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena;
    private final DemiLinije demiLinije;
    public Timer timer;
    
    
    public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                //Date date = new Date();
                refreshDLmerenja();
                refreshDL02();
                refreshVentiliGP();
                refreshBazeniMerenja();
                refreshPumpeFiltriraneVodeKaDemineralizaciji();refreshRezervoariMerenja();    
                refreshProtoci();
                refreshPumpeNeutralizacionogBazena();

                //System.out.println(date.getTime());
                //System.out.println("_____________");
            }
        });
    }
    
    private void setMinMax() {
        jProgressBarDekaFiltriranaVodaCopyDL02.setMinimum(bazeniMerenja.getBazenDekaFiltriraneVode().getMin());
        jProgressBarDekaFiltriranaVodaCopyDL02.setMaximum(bazeniMerenja.getBazenDekaFiltriraneVode().getMax());
        jProgressBarDekaFiltriranaVodaCopyDL02.setForeground(Color.ORANGE);

        jProgressBarNeutralizacioniBazenCopyDL02.setMinimum(bazeniMerenja.getBazenNeutralizacioni().getMin());
        jProgressBarNeutralizacioniBazenCopyDL02.setMaximum(bazeniMerenja.getBazenNeutralizacioni().getMax());
        jProgressBarNeutralizacioniBazenCopyDL02.setForeground(Color.ORANGE);
  
        jProgressBarDemiRezervoarBr1CopyDL2.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMin());
        jProgressBarDemiRezervoarBr1CopyDL2.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMax());
        jProgressBarDemiRezervoarBr1CopyDL2.setForeground(Color.ORANGE);
      
        jProgressBarDemiRezervoarBr2CopyDL2.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMin());
        jProgressBarDemiRezervoarBr2CopyDL2.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMax());
        jProgressBarDemiRezervoarBr2CopyDL2.setForeground(Color.ORANGE);

        jProgressBarDemiRezervoar150mCopyDL2.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMin());
        jProgressBarDemiRezervoar150mCopyDL2.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMax());
        jProgressBarDemiRezervoar150mCopyDL2.setForeground(Color.ORANGE);
    }


    private void refreshDLmerenja() {
        jLabelPritisakInJKKDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLjkkfIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija02().getPritisakDLjkkfIn().getBrDec()) + " bar");
        jLabelPritisakOutJKKDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLjkkfOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getPritisakDLjkkfOut().getBrDec()) + " bar");
        jLabelPritisakInSBADL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLsbafIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getPritisakDLsbafIn().getBrDec()) + " bar");
        jLabelPritisakOutSBADL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLsbafOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getPritisakDLsbafOut().getBrDec()) + " bar");
        jLabelPritisakInJBADL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLjbafIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getPritisakDLjbafIn().getBrDec()) + " bar");
        jLabelPritisakOutJBADL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLjbafOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getPritisakDLjbafOut().getBrDec()) + " bar");
        jLabelPritisakInMFDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLmfIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getPritisakDLmfIn().getBrDec()) + " bar");
        jLabelPritisakOutMFDL2.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getPritisakDLmfOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getPritisakDLmfOut().getBrDec()) + " bar");
        
        
        vodljivostSBA.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getVodljivostSBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getVodljivostSBA().getBrDec()) + " μS/cm");
        vodljivostJBA.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getVodljivostJBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getVodljivostJBA().getBrDec()) + " μS/cm");
        vodljivostMF.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija02().getVodljivostMF().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija02().getVodljivostMF().getBrDec()) + " μS/cm");

    }


    private void refreshVentiliGP() {
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji01CopyDL2, ventiliGP01.getGP01_potisDemi1());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji02CopyDL2, ventiliGP01.getGP01_potisDemi2());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji03CopyDL2, ventiliGP01.getGP01_potisDemi3());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji04CopyDL2, ventiliGP01.getGP01_potisDemi4());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji05CopyDL2, ventiliGP01.getGP01_potisDemi5());

    }

    

    
    private void refreshDL02() {
        try {
            int a = demiLinije.getJkkf02().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelDL2JKKFRegVentil01, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelDL2JKKFRegVentil01Vrednost.setText(ShiftPoint.shiftonePoint(a, demiLinije.getJkkf02().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
        img.setImgHorizontalno(jLabelDL02JKKFventil03, demiLinije.getJkkf02().getVent03());
        img.setImgHorizontalno(jLabelDL02JKKFventil04, demiLinije.getJkkf02().getVent04());
        img.setImgVertikalno(jLabelDL02JKKFventil05, demiLinije.getJkkf02().getVent05());
        img.setImgHorizontalno(jLabelDL02JKKFventil06, demiLinije.getJkkf02().getVent06());
        img.setImgHorizontalno(jLabelDL02JKKFventil07, demiLinije.getJkkf02().getVent07());
        img.setImgHorizontalno(jLabelDL02JKKFventil08, demiLinije.getJkkf02().getVent08());
        img.setImgVertikalno(jLabelDL02JKKFventil09, demiLinije.getJkkf02().getVent09());
        img.setImgHorizontalno(jLabelDL02JKKFventil10, demiLinije.getJkkf02().getVent10());
        img.setImgHorizontalno(jLabelDL02JKKFventil11, demiLinije.getJkkf02().getVent11());
        img.setImgVertikalno(jLabelDL02JKKFventil12, demiLinije.getJkkf02().getVent12());

        img.setImgHorizontalno(jLabelDL02SBAFventil01, demiLinije.getSbaf02().getVent01());
        img.setImgHorizontalno(jLabelDL02SBAFventil02, demiLinije.getSbaf02().getVent02());
        img.setImgHorizontalno(jLabelDL02SBAFventil03, demiLinije.getSbaf02().getVent03());
        img.setImgHorizontalno(jLabelDL02SBAFventil04, demiLinije.getSbaf02().getVent04());
        img.setImgHorizontalno(jLabelDL02SBAFventil05, demiLinije.getSbaf02().getVent05());
        img.setImgVertikalno(jLabelDL02SBAFventil06, demiLinije.getSbaf02().getVent06());

        img.setImgHorizontalno(jLabelDL02JBAFventil01, demiLinije.getJbaf02().getVent01());
        img.setImgHorizontalno(jLabelDL02JBAFventil02, demiLinije.getJbaf02().getVent02());
        img.setImgHorizontalno(jLabelDL02JBAFventil03, demiLinije.getJbaf02().getVent03());
        img.setImgHorizontalno(jLabelDL02JBAFventil04, demiLinije.getJbaf02().getVent04());
        img.setImgHorizontalno(jLabelDL02JBAFventil05, demiLinije.getJbaf02().getVent05());
        img.setImgHorizontalno(jLabelDL02JBAFventil06, demiLinije.getJbaf02().getVent06());
        img.setImgHorizontalno(jLabelDL02JBAFventil07, demiLinije.getJbaf02().getVent07());
        img.setImgVertikalno(jLabelDL02JBAFventil08, demiLinije.getJbaf02().getVent08());

        img.setImgHorizontalno(jLabelDL02MFventil01, demiLinije.getMf02().getVent01());
        img.setImgHorizontalno(jLabelDL02MFventil02, demiLinije.getMf02().getVent02());
        img.setImgHorizontalno(jLabelDL02MFventil03, demiLinije.getMf02().getVent03());
        img.setImgHorizontalno(jLabelDL02MFventil04, demiLinije.getMf02().getVent04());
        img.setImgHorizontalno(jLabelDL02MFventil05, demiLinije.getMf02().getVent05());
        img.setImgHorizontalno(jLabelDL02MFventil06, demiLinije.getMf02().getVent06());
        img.setImgVertikalno(jLabelDL02MFventil07, demiLinije.getMf02().getVent07());
        img.setImgHorizontalno(jLabelDL02MFventil08, demiLinije.getMf02().getVent08());
        img.setImgHorizontalno(jLabelDL02MFventil10, demiLinije.getMf02().getVent10());
        img.setImgVertikalno(jLabelDL02MFventil11, demiLinije.getMf02().getVent11());
    }

   

    
    

    private void refreshBazeniMerenja() {
        int a = bazeniMerenja.getBazenDekaFiltriraneVode().getVrednostRegistra();
        jLabelNivoBazenDekaFiltriraneVodeCopyDL02.setText("L= " + Integer.toString(a) + " cm");
        jProgressBarDekaFiltriranaVodaCopyDL02.setValue(a);

        int d = bazeniMerenja.getBazenNeutralizacioni().getVrednostRegistra();
        jProgressBarNeutralizacioniBazenCopyDL02.setValue(d);
        jLabelNivoNeutralizacioniCopyDL02.setText("L= " + Integer.toString(d) + " cm");
    }

    

    private void refreshProtoci() {
       
        jLabelProtokDemiLinijaInBr2.setText(Integer.toString(protociDemiLinije.getProtokDL2in().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokDemiLinijaOutBr2.setText(Integer.toString(protociDemiLinije.getProtokDL2out().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoOutDL2.setText(Convert.intToLong(protociDemiLinije.getProtokDL2out().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL2out().getKumulativnoNiziVrednost()));    
        jLabelProtokDemiLinijaMagistrala2.setText(Integer.toString(protociDemiLinije.getProtokMagistralniVod().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoDemiLinijaMagistrala2.setText(Convert.intToLong(protociDemiLinije.getProtokMagistralniVod().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokMagistralniVod().getKumulativnoNiziVrednost()));
        jLabelKumulativnoInDL2.setText(Convert.intToLong(protociDemiLinije.getProtokDL2in().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL2in().getKumulativnoNiziVrednost()));
       
    }

    private void refreshPumpeFiltriraneVodeKaDemineralizaciji() {
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr1CopyDL2, pumpeDekaFiltriranaKaDemi.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr2CopyDL2, pumpeDekaFiltriranaKaDemi.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr3CopyDL2, pumpeDekaFiltriranaKaDemi.getPumpaBr3().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr4CopyDL2, pumpeDekaFiltriranaKaDemi.getPumpaBr4().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr5CopyDL2, pumpeDekaFiltriranaKaDemi.getPumpaBr5().getVrednosti().isUkljucen());
    }

    
   
    private void refreshPumpeNeutralizacionogBazena() {
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr1CopyDL2, pumpeNeutralizacionogBazena.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr2CopyDL2, pumpeNeutralizacionogBazena.getPumpaBr2().getVrednosti().isUkljucen());
    }

    
   

   

    private void refreshRezervoariMerenja() {
        int a = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getVrednostRegistra();
        jProgressBarDemiRezervoarBr1CopyDL2.setValue(a);
        jLabelDemiRezervoarBr1CopyDL2.setText("L= " + Integer.toString(a) + " cm");

        int b = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getVrednostRegistra();
        jProgressBarDemiRezervoarBr2CopyDL2.setValue(a);
        jLabelDemiRezervoarBr2CopyDL2.setText("L= " + Integer.toString(b) + " cm");

        int c = rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getVrednostRegistra();
        jProgressBarDemiRezervoar150mCopyDL2.setValue(c);
        jLabelDemiRezervoar150mCopyDL2.setText("L= " + Integer.toString(c) + " cm");



    }

    
      
}