/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import field.merenja.bazeni.Nivoi;
import field.merenja.demiLinije.DemiLinijaMerenjaKonstruktor;
import field.merenja.protoci.ProtociDemiLinije;
import field.merenja.rezervoari.RezervoariMerenja;
import field.pumpe.PumpeDekaFiltrKaDemi;
import field.pumpe.PumpeNeutralizacionogBazena;
import field.ventili.DemiLinije;
import field.ventili.VentiliGrupaPumpi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import popup.AllPopUpWindow;
import tools.AnalogToDigital;
import utilise.Convert;
import tools.ShiftPoint;

/**
 *
 * @author branko.scekic
 */
public class DemiL3Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DemiL3Frame
     * @param protociDemiLinije
     * @param bazeniMerenja
     * @param rezervoariMerenja
     * @param demiLinijeMerenja
     * @param ventiliGP01
     * @param allPopUpWindow
     * @param demiLinije
     * @param pumpeNeutralizacionogBazena
     * @param img
     * @param pumpeDekaFiltriranaKaDemi
     */
    public DemiL3Frame(ProtociDemiLinije protociDemiLinije, Nivoi bazeniMerenja, 
            RezervoariMerenja rezervoariMerenja, 
            DemiLinijaMerenjaKonstruktor demiLinijeMerenja, VentiliGrupaPumpi ventiliGP01, 
            DemiLinije demiLinije, PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi, 
            PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena,
            Img img, AllPopUpWindow allPopUpWindow) {
        
        initComponents();
        this.protociDemiLinije = protociDemiLinije;
        this.pumpeDekaFiltriranaKaDemi = pumpeDekaFiltriranaKaDemi;
        this.pumpeNeutralizacionogBazena = pumpeNeutralizacionogBazena;
        this.bazeniMerenja = bazeniMerenja;
        this.rezervoariMerenja = rezervoariMerenja;
        this.demiLinijeMerenja = demiLinijeMerenja;
        this.ventiliGP01 = ventiliGP01;
        this.demiLinije = demiLinije;
        this.allPopUpWindow = allPopUpWindow;
        this.img = img;
        
        setMinMax();
        screenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDL3JKKFRegVentil01 = new javax.swing.JLabel();
        jLabelDL3JKKFRegVentil01Vrednost = new javax.swing.JLabel();
        jLabelDL03JKKFventil03 = new javax.swing.JLabel();
        jLabelDL03JKKFventil04 = new javax.swing.JLabel();
        jLabelDL03JKKFventil05 = new javax.swing.JLabel();
        jLabelDL03JKKFventil06 = new javax.swing.JLabel();
        jLabelDL03JKKFventil07 = new javax.swing.JLabel();
        jLabelDL03JKKFventil08 = new javax.swing.JLabel();
        jLabelDL03JKKFventil09 = new javax.swing.JLabel();
        jLabelDL03JKKFventil10 = new javax.swing.JLabel();
        jLabelDL03JKKFventil11 = new javax.swing.JLabel();
        jLabelDL03JKKFventil12 = new javax.swing.JLabel();
        jLabelDL03SBAFventil01 = new javax.swing.JLabel();
        jLabelDL03SBAFventil02 = new javax.swing.JLabel();
        jLabelDL03SBAFventil03 = new javax.swing.JLabel();
        jLabelDL03SBAFventil04 = new javax.swing.JLabel();
        jLabelDL03SBAFventil05 = new javax.swing.JLabel();
        jLabelDL03SBAFventil06 = new javax.swing.JLabel();
        jLabelDL03JBAFventil01 = new javax.swing.JLabel();
        jLabelDL03JBAFventil02 = new javax.swing.JLabel();
        jLabelDL03JBAFventil03 = new javax.swing.JLabel();
        jLabelDL03JBAFventil04 = new javax.swing.JLabel();
        jLabelDL03JBAFventil05 = new javax.swing.JLabel();
        jLabelDL03JBAFventil06 = new javax.swing.JLabel();
        jLabelDL03JBAFventil07 = new javax.swing.JLabel();
        jLabelDL03JBAFventil08 = new javax.swing.JLabel();
        jLabelDL03MFventil01 = new javax.swing.JLabel();
        jLabelDL03MFventil02 = new javax.swing.JLabel();
        jLabelDL03MFventil03 = new javax.swing.JLabel();
        jLabelDL03MFventil04 = new javax.swing.JLabel();
        jLabelDL03MFventil05 = new javax.swing.JLabel();
        jLabelDL03MFventil06 = new javax.swing.JLabel();
        jLabelDL03MFventil07 = new javax.swing.JLabel();
        jLabelDL03MFventil08 = new javax.swing.JLabel();
        jLabelDL03MFventil10 = new javax.swing.JLabel();
        jLabelDL03MFventil11 = new javax.swing.JLabel();
        jLabelNivoBazenDekaFiltriraneVodeCopyDL03 = new javax.swing.JLabel();
        jProgressBarDekaFiltriranaVodaCopyDL03 = new javax.swing.JProgressBar();
        jLabelNivoNeutralizacioniCopyDL03 = new javax.swing.JLabel();
        jProgressBarNeutralizacioniBazenCopyDL03 = new javax.swing.JProgressBar();
        jLabelPumpeKaDemiLiniji01CopyDL3 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji02CopyDL3 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji03CopyDL3 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji04CopyDL3 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji05CopyDL3 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3 = new javax.swing.JLabel();
        jProgressBarDemiRezervoarBr1CopyDL3 = new javax.swing.JProgressBar();
        jLabelDemiRezervoarBr1CopyDL3 = new javax.swing.JLabel();
        jProgressBarDemiRezervoarBr2CopyDL3 = new javax.swing.JProgressBar();
        jLabelDemiRezervoarBr2CopyDL3 = new javax.swing.JLabel();
        jProgressBarDemiRezervoar150mCopyDL3 = new javax.swing.JProgressBar();
        jLabelDemiRezervoar150mCopyDL3 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaInBr3 = new javax.swing.JLabel();
        jLabelKumulativnoInDL3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr1CopyDL3 = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr2CopyDL3 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaOutBr3 = new javax.swing.JLabel();
        jLabelKumulativnoOutDL3 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaMagistrala3 = new javax.swing.JLabel();
        jLabelKumulativnoDemiLinijaMagistrala3 = new javax.swing.JLabel();
        jLabelPritisakInJKKDL3 = new javax.swing.JLabel();
        jLabelPritisakOutJKKDL3 = new javax.swing.JLabel();
        jLabelPritisakInSBADL3 = new javax.swing.JLabel();
        jLabelPritisakOutSBADL3 = new javax.swing.JLabel();
        jLabelPritisakInJBADL3 = new javax.swing.JLabel();
        jLabelPritisakOutJBADL3 = new javax.swing.JLabel();
        jLabelPritisakInMFDL3 = new javax.swing.JLabel();
        jLabelPritisakOutMFDL3 = new javax.swing.JLabel();
        vodljivostSBA = new javax.swing.JLabel();
        vodljivostJBA = new javax.swing.JLabel();
        vodljivostMF = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabelDL3JKKFRegVentil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL3JKKFRegVentil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL3JKKFRegVentil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL3JKKFRegVentil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL3JKKFRegVentil01);
        jLabelDL3JKKFRegVentil01.setBounds(280, 420, 40, 40);

        jLabelDL3JKKFRegVentil01Vrednost.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelDL3JKKFRegVentil01Vrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL3JKKFRegVentil01Vrednost.setText("***");
        getContentPane().add(jLabelDL3JKKFRegVentil01Vrednost);
        jLabelDL3JKKFRegVentil01Vrednost.setBounds(280, 460, 40, 19);

        jLabelDL03JKKFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JKKFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil03);
        jLabelDL03JKKFventil03.setBounds(370, 420, 50, 40);

        jLabelDL03JKKFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JKKFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil04);
        jLabelDL03JKKFventil04.setBounds(460, 430, 50, 30);

        jLabelDL03JKKFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL03JKKFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil05);
        jLabelDL03JKKFventil05.setBounds(240, 470, 30, 60);

        jLabelDL03JKKFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JKKFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil06);
        jLabelDL03JKKFventil06.setBounds(460, 370, 50, 30);

        jLabelDL03JKKFventil07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JKKFventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil07);
        jLabelDL03JKKFventil07.setBounds(380, 520, 40, 26);

        jLabelDL03JKKFventil08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JKKFventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil08);
        jLabelDL03JKKFventil08.setBounds(370, 370, 50, 30);

        jLabelDL03JKKFventil09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL03JKKFventil09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil09MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil09);
        jLabelDL03JKKFventil09.setBounds(290, 320, 26, 50);

        jLabelDL03JKKFventil10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JKKFventil10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil10);
        jLabelDL03JKKFventil10.setBounds(370, 470, 40, 30);

        jLabelDL03JKKFventil11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JKKFventil11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil11);
        jLabelDL03JKKFventil11.setBounds(460, 510, 50, 40);

        jLabelDL03JKKFventil12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JKKFventil12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL03JKKFventil12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JKKFventil12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JKKFventil12);
        jLabelDL03JKKFventil12.setBounds(560, 500, 26, 50);

        jLabelDL03SBAFventil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03SBAFventil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03SBAFventil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03SBAFventil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03SBAFventil01);
        jLabelDL03SBAFventil01.setBounds(680, 420, 50, 40);

        jLabelDL03SBAFventil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03SBAFventil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03SBAFventil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03SBAFventil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03SBAFventil02);
        jLabelDL03SBAFventil02.setBounds(680, 470, 50, 30);

        jLabelDL03SBAFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03SBAFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03SBAFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03SBAFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03SBAFventil03);
        jLabelDL03SBAFventil03.setBounds(770, 370, 50, 26);

        jLabelDL03SBAFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03SBAFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03SBAFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03SBAFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03SBAFventil04);
        jLabelDL03SBAFventil04.setBounds(790, 470, 40, 30);

        jLabelDL03SBAFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03SBAFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03SBAFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03SBAFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03SBAFventil05);
        jLabelDL03SBAFventil05.setBounds(760, 520, 40, 30);

        jLabelDL03SBAFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03SBAFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL03SBAFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03SBAFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03SBAFventil06);
        jLabelDL03SBAFventil06.setBounds(870, 500, 30, 40);

        jLabelDL03JBAFventil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JBAFventil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JBAFventil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JBAFventil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JBAFventil01);
        jLabelDL03JBAFventil01.setBounds(990, 420, 40, 40);

        jLabelDL03JBAFventil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JBAFventil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JBAFventil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JBAFventil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JBAFventil02);
        jLabelDL03JBAFventil02.setBounds(1080, 430, 40, 26);

        jLabelDL03JBAFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JBAFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JBAFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JBAFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JBAFventil03);
        jLabelDL03JBAFventil03.setBounds(990, 470, 40, 30);

        jLabelDL03JBAFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JBAFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JBAFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JBAFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JBAFventil04);
        jLabelDL03JBAFventil04.setBounds(1080, 370, 40, 30);

        jLabelDL03JBAFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JBAFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JBAFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JBAFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JBAFventil05);
        jLabelDL03JBAFventil05.setBounds(990, 370, 40, 30);

        jLabelDL03JBAFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JBAFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JBAFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JBAFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JBAFventil06);
        jLabelDL03JBAFventil06.setBounds(990, 550, 40, 30);

        jLabelDL03JBAFventil07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JBAFventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03JBAFventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JBAFventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JBAFventil07);
        jLabelDL03JBAFventil07.setBounds(1060, 526, 60, 30);

        jLabelDL03JBAFventil08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03JBAFventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL03JBAFventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03JBAFventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03JBAFventil08);
        jLabelDL03JBAFventil08.setBounds(1170, 500, 26, 50);

        jLabelDL03MFventil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03MFventil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil01);
        jLabelDL03MFventil01.setBounds(1290, 430, 50, 26);

        jLabelDL03MFventil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03MFventil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil02);
        jLabelDL03MFventil02.setBounds(1390, 430, 40, 26);

        jLabelDL03MFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03MFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil03);
        jLabelDL03MFventil03.setBounds(1290, 470, 50, 40);

        jLabelDL03MFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03MFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil04);
        jLabelDL03MFventil04.setBounds(1390, 370, 40, 40);

        jLabelDL03MFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03MFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil05);
        jLabelDL03MFventil05.setBounds(1390, 470, 50, 40);

        jLabelDL03MFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03MFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil06);
        jLabelDL03MFventil06.setBounds(1290, 370, 50, 40);

        jLabelDL03MFventil07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL03MFventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil07);
        jLabelDL03MFventil07.setBounds(1210, 500, 26, 50);

        jLabelDL03MFventil08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03MFventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil08);
        jLabelDL03MFventil08.setBounds(1290, 520, 50, 40);

        jLabelDL03MFventil10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL03MFventil10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil10);
        jLabelDL03MFventil10.setBounds(1380, 520, 40, 40);

        jLabelDL03MFventil11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL03MFventil11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL03MFventil11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL03MFventil11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL03MFventil11);
        jLabelDL03MFventil11.setBounds(1460, 490, 40, 50);

        jLabelNivoBazenDekaFiltriraneVodeCopyDL03.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoBazenDekaFiltriraneVodeCopyDL03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoBazenDekaFiltriraneVodeCopyDL03.setText("+++");
        jLabelNivoBazenDekaFiltriraneVodeCopyDL03.setBorder(null);
        getContentPane().add(jLabelNivoBazenDekaFiltriraneVodeCopyDL03);
        jLabelNivoBazenDekaFiltriraneVodeCopyDL03.setBounds(380, 910, 200, 20);

        jProgressBarDekaFiltriranaVodaCopyDL03.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarDekaFiltriranaVodaCopyDL03.setOrientation(1);
        jProgressBarDekaFiltriranaVodaCopyDL03.setToolTipText("");
        jProgressBarDekaFiltriranaVodaCopyDL03.setValue(10);
        jProgressBarDekaFiltriranaVodaCopyDL03.setBorderPainted(false);
        jProgressBarDekaFiltriranaVodaCopyDL03.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarDekaFiltriranaVodaCopyDL03.setString("");
        jProgressBarDekaFiltriranaVodaCopyDL03.setStringPainted(true);
        getContentPane().add(jProgressBarDekaFiltriranaVodaCopyDL03);
        jProgressBarDekaFiltriranaVodaCopyDL03.setBounds(300, 840, 20, 90);

        jLabelNivoNeutralizacioniCopyDL03.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoNeutralizacioniCopyDL03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoNeutralizacioniCopyDL03.setText("***");
        jLabelNivoNeutralizacioniCopyDL03.setBorder(null);
        getContentPane().add(jLabelNivoNeutralizacioniCopyDL03);
        jLabelNivoNeutralizacioniCopyDL03.setBounds(770, 900, 130, 24);

        jProgressBarNeutralizacioniBazenCopyDL03.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarNeutralizacioniBazenCopyDL03.setOrientation(1);
        jProgressBarNeutralizacioniBazenCopyDL03.setToolTipText("");
        jProgressBarNeutralizacioniBazenCopyDL03.setValue(10);
        jProgressBarNeutralizacioniBazenCopyDL03.setBorderPainted(false);
        jProgressBarNeutralizacioniBazenCopyDL03.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarNeutralizacioniBazenCopyDL03.setString("");
        jProgressBarNeutralizacioniBazenCopyDL03.setStringPainted(true);
        getContentPane().add(jProgressBarNeutralizacioniBazenCopyDL03);
        jProgressBarNeutralizacioniBazenCopyDL03.setBounds(710, 840, 20, 90);

        jLabelPumpeKaDemiLiniji01CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji01CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji01CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji01CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji01CopyDL3);
        jLabelPumpeKaDemiLiniji01CopyDL3.setBounds(320, 670, 30, 40);

        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3);
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3.setBounds(300, 710, 60, 60);

        jLabelPumpeKaDemiLiniji02CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji02CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji02CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji02CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji02CopyDL3);
        jLabelPumpeKaDemiLiniji02CopyDL3.setBounds(390, 670, 30, 40);

        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3);
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3.setBounds(380, 710, 50, 60);

        jLabelPumpeKaDemiLiniji03CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji03CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji03CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji03CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji03CopyDL3);
        jLabelPumpeKaDemiLiniji03CopyDL3.setBounds(460, 670, 40, 40);

        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3);
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3.setBounds(450, 710, 50, 60);

        jLabelPumpeKaDemiLiniji04CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji04CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji04CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji04CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji04CopyDL3);
        jLabelPumpeKaDemiLiniji04CopyDL3.setBounds(530, 670, 40, 40);

        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3);
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3.setBounds(520, 710, 60, 60);

        jLabelPumpeKaDemiLiniji05CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji05CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji05CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji05CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji05CopyDL3);
        jLabelPumpeKaDemiLiniji05CopyDL3.setBounds(610, 670, 30, 40);

        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3);
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3.setBounds(590, 710, 60, 60);

        jProgressBarDemiRezervoarBr1CopyDL3.setOrientation(1);
        jProgressBarDemiRezervoarBr1CopyDL3.setValue(10);
        jProgressBarDemiRezervoarBr1CopyDL3.setString("0");
        jProgressBarDemiRezervoarBr1CopyDL3.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr1CopyDL3);
        jProgressBarDemiRezervoarBr1CopyDL3.setBounds(1000, 770, 20, 160);

        jLabelDemiRezervoarBr1CopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr1CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr1CopyDL3.setText("***");
        jLabelDemiRezervoarBr1CopyDL3.setBorder(null);
        getContentPane().add(jLabelDemiRezervoarBr1CopyDL3);
        jLabelDemiRezervoarBr1CopyDL3.setBounds(1010, 900, 130, 30);

        jProgressBarDemiRezervoarBr2CopyDL3.setOrientation(1);
        jProgressBarDemiRezervoarBr2CopyDL3.setValue(10);
        jProgressBarDemiRezervoarBr2CopyDL3.setString("0");
        jProgressBarDemiRezervoarBr2CopyDL3.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr2CopyDL3);
        jProgressBarDemiRezervoarBr2CopyDL3.setBounds(1190, 770, 20, 160);

        jLabelDemiRezervoarBr2CopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr2CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr2CopyDL3.setText("***");
        jLabelDemiRezervoarBr2CopyDL3.setBorder(null);
        getContentPane().add(jLabelDemiRezervoarBr2CopyDL3);
        jLabelDemiRezervoarBr2CopyDL3.setBounds(1190, 900, 130, 30);

        jProgressBarDemiRezervoar150mCopyDL3.setOrientation(1);
        jProgressBarDemiRezervoar150mCopyDL3.setValue(10);
        jProgressBarDemiRezervoar150mCopyDL3.setString("0");
        jProgressBarDemiRezervoar150mCopyDL3.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoar150mCopyDL3);
        jProgressBarDemiRezervoar150mCopyDL3.setBounds(900, 650, 20, 120);

        jLabelDemiRezervoar150mCopyDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoar150mCopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoar150mCopyDL3.setText("***");
        jLabelDemiRezervoar150mCopyDL3.setBorder(null);
        getContentPane().add(jLabelDemiRezervoar150mCopyDL3);
        jLabelDemiRezervoar150mCopyDL3.setBounds(900, 740, 110, 30);

        jLabelProtokDemiLinijaInBr3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaInBr3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaInBr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaInBr3.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaInBr3);
        jLabelProtokDemiLinijaInBr3.setBounds(200, 660, 100, 19);

        jLabelKumulativnoInDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoInDL3.setText("***");
        getContentPane().add(jLabelKumulativnoInDL3);
        jLabelKumulativnoInDL3.setBounds(170, 680, 150, 20);

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel22.setText("BR 3");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(1110, 30, 140, 50);

        jLabelPumpaNeutralizacioniBazenBr1CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr1CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr1CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr1CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr1CopyDL3);
        jLabelPumpaNeutralizacioniBazenBr1CopyDL3.setBounds(750, 790, 50, 50);

        jLabelPumpaNeutralizacioniBazenBr2CopyDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr2CopyDL3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr2CopyDL3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr2CopyDL3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr2CopyDL3);
        jLabelPumpaNeutralizacioniBazenBr2CopyDL3.setBounds(820, 790, 50, 50);

        jLabelProtokDemiLinijaOutBr3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaOutBr3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaOutBr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaOutBr3.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaOutBr3);
        jLabelProtokDemiLinijaOutBr3.setBounds(1560, 450, 100, 19);

        jLabelKumulativnoOutDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoOutDL3.setText("***");
        getContentPane().add(jLabelKumulativnoOutDL3);
        jLabelKumulativnoOutDL3.setBounds(1520, 420, 150, 20);

        jLabelProtokDemiLinijaMagistrala3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaMagistrala3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaMagistrala3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaMagistrala3.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaMagistrala3);
        jLabelProtokDemiLinijaMagistrala3.setBounds(1500, 750, 100, 19);

        jLabelKumulativnoDemiLinijaMagistrala3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoDemiLinijaMagistrala3.setText("***");
        getContentPane().add(jLabelKumulativnoDemiLinijaMagistrala3);
        jLabelKumulativnoDemiLinijaMagistrala3.setBounds(1470, 730, 150, 20);

        jLabelPritisakInJKKDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJKKDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJKKDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJKKDL3);
        jLabelPritisakInJKKDL3.setBounds(340, 320, 90, 30);

        jLabelPritisakOutJKKDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJKKDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJKKDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJKKDL3);
        jLabelPritisakOutJKKDL3.setBounds(450, 320, 90, 30);

        jLabelPritisakInSBADL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInSBADL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInSBADL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakInSBADL3);
        jLabelPritisakInSBADL3.setBounds(640, 320, 90, 30);

        jLabelPritisakOutSBADL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutSBADL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutSBADL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutSBADL3);
        jLabelPritisakOutSBADL3.setBounds(750, 320, 90, 30);

        jLabelPritisakInJBADL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJBADL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJBADL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJBADL3);
        jLabelPritisakInJBADL3.setBounds(950, 320, 90, 30);

        jLabelPritisakOutJBADL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJBADL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJBADL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJBADL3);
        jLabelPritisakOutJBADL3.setBounds(1060, 320, 90, 30);

        jLabelPritisakInMFDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInMFDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInMFDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakInMFDL3);
        jLabelPritisakInMFDL3.setBounds(1260, 320, 90, 30);

        jLabelPritisakOutMFDL3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutMFDL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutMFDL3.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutMFDL3);
        jLabelPritisakOutMFDL3.setBounds(1370, 320, 90, 30);

        vodljivostSBA.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostSBA.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostSBA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostSBA.setText("jLabel15");
        getContentPane().add(vodljivostSBA);
        vodljivostSBA.setBounds(670, 590, 140, 30);

        vodljivostJBA.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostJBA.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostJBA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostJBA.setText("jLabel15");
        getContentPane().add(vodljivostJBA);
        vodljivostJBA.setBounds(970, 590, 150, 30);

        vodljivostMF.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostMF.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostMF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostMF.setText("jLabel15");
        getContentPane().add(vodljivostMF);
        vodljivostMF.setBounds(1290, 590, 140, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/statImg/Demi/DEMI linija detaljno.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1740, 970);

        setBounds(170, 35, 1716, 996);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelDL3JKKFRegVentil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL3JKKFRegVentil01MouseClicked
        allPopUpWindow.ProzorDL03JKKF01();
    }//GEN-LAST:event_jLabelDL3JKKFRegVentil01MouseClicked

    private void jLabelDL03JKKFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil03MouseClicked
        allPopUpWindow.ProzorDL03JKKF03();
    }//GEN-LAST:event_jLabelDL03JKKFventil03MouseClicked

    private void jLabelDL03JKKFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil04MouseClicked
        allPopUpWindow.ProzorDL03JKKF04();
    }//GEN-LAST:event_jLabelDL03JKKFventil04MouseClicked

    private void jLabelDL03JKKFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil05MouseClicked
        allPopUpWindow.ProzorDL03JKKF05();
    }//GEN-LAST:event_jLabelDL03JKKFventil05MouseClicked

    private void jLabelDL03JKKFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil06MouseClicked
        allPopUpWindow.ProzorDL03JKKF06();
    }//GEN-LAST:event_jLabelDL03JKKFventil06MouseClicked

    private void jLabelDL03JKKFventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil07MouseClicked
       allPopUpWindow.ProzorDL03JKKF07();
    }//GEN-LAST:event_jLabelDL03JKKFventil07MouseClicked

    private void jLabelDL03JKKFventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil08MouseClicked
       allPopUpWindow.ProzorDL03JKKF08();
    }//GEN-LAST:event_jLabelDL03JKKFventil08MouseClicked

    private void jLabelDL03JKKFventil09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil09MouseClicked
       allPopUpWindow.ProzorDL03JKKF09();
    }//GEN-LAST:event_jLabelDL03JKKFventil09MouseClicked

    private void jLabelDL03JKKFventil10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil10MouseClicked
       allPopUpWindow.ProzorDL03JKKF10();
    }//GEN-LAST:event_jLabelDL03JKKFventil10MouseClicked

    private void jLabelDL03JKKFventil11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil11MouseClicked
        allPopUpWindow.ProzorDL03JKKF11();
    }//GEN-LAST:event_jLabelDL03JKKFventil11MouseClicked

    private void jLabelDL03JKKFventil12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JKKFventil12MouseClicked
       allPopUpWindow.ProzorDL03JKKF12();
    }//GEN-LAST:event_jLabelDL03JKKFventil12MouseClicked

    private void jLabelDL03SBAFventil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03SBAFventil01MouseClicked
        allPopUpWindow.ProzorDL03SBA01();
    }//GEN-LAST:event_jLabelDL03SBAFventil01MouseClicked

    private void jLabelDL03SBAFventil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03SBAFventil02MouseClicked
       allPopUpWindow.ProzorDL03SBA02();
    }//GEN-LAST:event_jLabelDL03SBAFventil02MouseClicked

    private void jLabelDL03SBAFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03SBAFventil03MouseClicked
        allPopUpWindow.ProzorDL03SBA03();
    }//GEN-LAST:event_jLabelDL03SBAFventil03MouseClicked

    private void jLabelDL03SBAFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03SBAFventil04MouseClicked
       allPopUpWindow.ProzorDL03SBA04();
    }//GEN-LAST:event_jLabelDL03SBAFventil04MouseClicked

    private void jLabelDL03SBAFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03SBAFventil05MouseClicked
        allPopUpWindow.ProzorDL03SBA05();
    }//GEN-LAST:event_jLabelDL03SBAFventil05MouseClicked

    private void jLabelDL03SBAFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03SBAFventil06MouseClicked
       allPopUpWindow.ProzorDL03SBA06();
    }//GEN-LAST:event_jLabelDL03SBAFventil06MouseClicked

    private void jLabelDL03JBAFventil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JBAFventil01MouseClicked
        allPopUpWindow.ProzorDL03JBA01();
    }//GEN-LAST:event_jLabelDL03JBAFventil01MouseClicked

    private void jLabelDL03JBAFventil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JBAFventil02MouseClicked
       allPopUpWindow.ProzorDL03JBA02();
    }//GEN-LAST:event_jLabelDL03JBAFventil02MouseClicked

    private void jLabelDL03JBAFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JBAFventil03MouseClicked
       allPopUpWindow.ProzorDL03JBA03();
    }//GEN-LAST:event_jLabelDL03JBAFventil03MouseClicked

    private void jLabelDL03JBAFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JBAFventil04MouseClicked
       allPopUpWindow.ProzorDL03JBA04();
    }//GEN-LAST:event_jLabelDL03JBAFventil04MouseClicked

    private void jLabelDL03JBAFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JBAFventil05MouseClicked
       allPopUpWindow.ProzorDL03JBA05();
    }//GEN-LAST:event_jLabelDL03JBAFventil05MouseClicked

    private void jLabelDL03JBAFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JBAFventil06MouseClicked
       allPopUpWindow.ProzorDL03JBA06();
    }//GEN-LAST:event_jLabelDL03JBAFventil06MouseClicked

    private void jLabelDL03JBAFventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JBAFventil07MouseClicked
        allPopUpWindow.ProzorDL03JBA07();
    }//GEN-LAST:event_jLabelDL03JBAFventil07MouseClicked

    private void jLabelDL03JBAFventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03JBAFventil08MouseClicked
       allPopUpWindow.ProzorDL03JBA08();
    }//GEN-LAST:event_jLabelDL03JBAFventil08MouseClicked

    private void jLabelDL03MFventil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil01MouseClicked
        allPopUpWindow.ProzorDL03MF01();
    }//GEN-LAST:event_jLabelDL03MFventil01MouseClicked

    private void jLabelDL03MFventil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil02MouseClicked
        allPopUpWindow.ProzorDL03MF02();
    }//GEN-LAST:event_jLabelDL03MFventil02MouseClicked

    private void jLabelDL03MFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil03MouseClicked
        allPopUpWindow.ProzorDL03MF03();
    }//GEN-LAST:event_jLabelDL03MFventil03MouseClicked

    private void jLabelDL03MFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil04MouseClicked
      allPopUpWindow.ProzorDL03MF04();
    }//GEN-LAST:event_jLabelDL03MFventil04MouseClicked

    private void jLabelDL03MFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil05MouseClicked
       allPopUpWindow.ProzorDL03MF05();
    }//GEN-LAST:event_jLabelDL03MFventil05MouseClicked

    private void jLabelDL03MFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil06MouseClicked
        allPopUpWindow.ProzorDL03MF06();
    }//GEN-LAST:event_jLabelDL03MFventil06MouseClicked

    private void jLabelDL03MFventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil07MouseClicked
        allPopUpWindow.ProzorDL03MF07();
    }//GEN-LAST:event_jLabelDL03MFventil07MouseClicked

    private void jLabelDL03MFventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil08MouseClicked
        allPopUpWindow.ProzorDL03MF08();
    }//GEN-LAST:event_jLabelDL03MFventil08MouseClicked

    private void jLabelDL03MFventil10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil10MouseClicked
        allPopUpWindow.ProzorDL03MF10();
    }//GEN-LAST:event_jLabelDL03MFventil10MouseClicked

    private void jLabelDL03MFventil11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL03MFventil11MouseClicked
        allPopUpWindow.ProzorDL03MF11();
    }//GEN-LAST:event_jLabelDL03MFventil11MouseClicked

    private void jLabelPumpeKaDemiLiniji01CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji01CopyDL3MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr1();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji01CopyDL3MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama01();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3MouseClicked

    private void jLabelPumpeKaDemiLiniji02CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji02CopyDL3MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr2();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji02CopyDL3MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama02();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3MouseClicked

    private void jLabelPumpeKaDemiLiniji03CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji03CopyDL3MouseClicked
         allPopUpWindow.ProzorPKDemiLinijamaBr3();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji03CopyDL3MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3MouseClicked
         allPopUpWindow.ProzorPumpaKaDemiLinijama03();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3MouseClicked

    private void jLabelPumpeKaDemiLiniji04CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji04CopyDL3MouseClicked
         allPopUpWindow.ProzorPKDemiLinijamaBr4();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji04CopyDL3MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama04();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3MouseClicked

    private void jLabelPumpeKaDemiLiniji05CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji05CopyDL3MouseClicked
         allPopUpWindow.ProzorPKDemiLinijamaBr5();
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji05CopyDL3MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3MouseClicked
       allPopUpWindow.ProzorPumpaKaDemiLinijama05();
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3MouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr1CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr1CopyDL3MouseClicked
         allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr1();
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr1CopyDL3MouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr2CopyDL3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr2CopyDL3MouseClicked
       allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr2();
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr2CopyDL3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabelDL03JBAFventil01;
    private javax.swing.JLabel jLabelDL03JBAFventil02;
    private javax.swing.JLabel jLabelDL03JBAFventil03;
    private javax.swing.JLabel jLabelDL03JBAFventil04;
    private javax.swing.JLabel jLabelDL03JBAFventil05;
    private javax.swing.JLabel jLabelDL03JBAFventil06;
    private javax.swing.JLabel jLabelDL03JBAFventil07;
    private javax.swing.JLabel jLabelDL03JBAFventil08;
    private javax.swing.JLabel jLabelDL03JKKFventil03;
    private javax.swing.JLabel jLabelDL03JKKFventil04;
    private javax.swing.JLabel jLabelDL03JKKFventil05;
    private javax.swing.JLabel jLabelDL03JKKFventil06;
    private javax.swing.JLabel jLabelDL03JKKFventil07;
    private javax.swing.JLabel jLabelDL03JKKFventil08;
    private javax.swing.JLabel jLabelDL03JKKFventil09;
    private javax.swing.JLabel jLabelDL03JKKFventil10;
    private javax.swing.JLabel jLabelDL03JKKFventil11;
    private javax.swing.JLabel jLabelDL03JKKFventil12;
    private javax.swing.JLabel jLabelDL03MFventil01;
    private javax.swing.JLabel jLabelDL03MFventil02;
    private javax.swing.JLabel jLabelDL03MFventil03;
    private javax.swing.JLabel jLabelDL03MFventil04;
    private javax.swing.JLabel jLabelDL03MFventil05;
    private javax.swing.JLabel jLabelDL03MFventil06;
    private javax.swing.JLabel jLabelDL03MFventil07;
    private javax.swing.JLabel jLabelDL03MFventil08;
    private javax.swing.JLabel jLabelDL03MFventil10;
    private javax.swing.JLabel jLabelDL03MFventil11;
    private javax.swing.JLabel jLabelDL03SBAFventil01;
    private javax.swing.JLabel jLabelDL03SBAFventil02;
    private javax.swing.JLabel jLabelDL03SBAFventil03;
    private javax.swing.JLabel jLabelDL03SBAFventil04;
    private javax.swing.JLabel jLabelDL03SBAFventil05;
    private javax.swing.JLabel jLabelDL03SBAFventil06;
    private javax.swing.JLabel jLabelDL3JKKFRegVentil01;
    private javax.swing.JLabel jLabelDL3JKKFRegVentil01Vrednost;
    private javax.swing.JLabel jLabelDemiRezervoar150mCopyDL3;
    private javax.swing.JLabel jLabelDemiRezervoarBr1CopyDL3;
    private javax.swing.JLabel jLabelDemiRezervoarBr2CopyDL3;
    private javax.swing.JLabel jLabelKumulativnoDemiLinijaMagistrala3;
    private javax.swing.JLabel jLabelKumulativnoInDL3;
    private javax.swing.JLabel jLabelKumulativnoOutDL3;
    private javax.swing.JLabel jLabelNivoBazenDekaFiltriraneVodeCopyDL03;
    private javax.swing.JLabel jLabelNivoNeutralizacioniCopyDL03;
    private javax.swing.JLabel jLabelPritisakInJBADL3;
    private javax.swing.JLabel jLabelPritisakInJKKDL3;
    private javax.swing.JLabel jLabelPritisakInMFDL3;
    private javax.swing.JLabel jLabelPritisakInSBADL3;
    private javax.swing.JLabel jLabelPritisakOutJBADL3;
    private javax.swing.JLabel jLabelPritisakOutJKKDL3;
    private javax.swing.JLabel jLabelPritisakOutMFDL3;
    private javax.swing.JLabel jLabelPritisakOutSBADL3;
    private javax.swing.JLabel jLabelProtokDemiLinijaInBr3;
    private javax.swing.JLabel jLabelProtokDemiLinijaMagistrala3;
    private javax.swing.JLabel jLabelProtokDemiLinijaOutBr3;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr1CopyDL3;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr2CopyDL3;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji01CopyDL3;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji02CopyDL3;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji03CopyDL3;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji04CopyDL3;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji05CopyDL3;
    private javax.swing.JProgressBar jProgressBarDekaFiltriranaVodaCopyDL03;
    private javax.swing.JProgressBar jProgressBarDemiRezervoar150mCopyDL3;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr1CopyDL3;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr2CopyDL3;
    private javax.swing.JProgressBar jProgressBarNeutralizacioniBazenCopyDL03;
    private javax.swing.JLabel vodljivostJBA;
    private javax.swing.JLabel vodljivostMF;
    private javax.swing.JLabel vodljivostSBA;
    // End of variables declaration//GEN-END:variables

   private final Img img;
    private final AllPopUpWindow allPopUpWindow;
    private final ProtociDemiLinije protociDemiLinije;
    private final Nivoi bazeniMerenja;
    private final RezervoariMerenja rezervoariMerenja;
    private final DemiLinijaMerenjaKonstruktor demiLinijeMerenja;
    private final VentiliGrupaPumpi ventiliGP01;
    private final PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi;
    private final PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena;
    private final DemiLinije demiLinije;
    public Timer timer;
    
    
    public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                //Date date = new Date();
                refreshDLmerenja();
                refreshDL03();
                refreshVentiliGP();
                refreshBazeniMerenja();
                refreshPumpeFiltriraneVodeKaDemineralizaciji();refreshRezervoariMerenja();    
                refreshProtoci();
                refreshPumpeNeutralizacionogBazena();

                //System.out.println(date.getTime());
                //System.out.println("_____________");
            }
        });
    }
    
    private void setMinMax() {
        jProgressBarDekaFiltriranaVodaCopyDL03.setMinimum(bazeniMerenja.getBazenDekaFiltriraneVode().getMin());
        jProgressBarDekaFiltriranaVodaCopyDL03.setMaximum(bazeniMerenja.getBazenDekaFiltriraneVode().getMax());
        jProgressBarDekaFiltriranaVodaCopyDL03.setForeground(Color.ORANGE);

        jProgressBarNeutralizacioniBazenCopyDL03.setMinimum(bazeniMerenja.getBazenNeutralizacioni().getMin());
        jProgressBarNeutralizacioniBazenCopyDL03.setMaximum(bazeniMerenja.getBazenNeutralizacioni().getMax());
        jProgressBarNeutralizacioniBazenCopyDL03.setForeground(Color.ORANGE);
  
        jProgressBarDemiRezervoarBr1CopyDL3.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMin());
        jProgressBarDemiRezervoarBr1CopyDL3.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMax());
        jProgressBarDemiRezervoarBr1CopyDL3.setForeground(Color.ORANGE);
      
        jProgressBarDemiRezervoarBr2CopyDL3.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMin());
        jProgressBarDemiRezervoarBr2CopyDL3.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMax());
        jProgressBarDemiRezervoarBr2CopyDL3.setForeground(Color.ORANGE);

        jProgressBarDemiRezervoar150mCopyDL3.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMin());
        jProgressBarDemiRezervoar150mCopyDL3.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMax());
        jProgressBarDemiRezervoar150mCopyDL3.setForeground(Color.ORANGE);
    }


    private void refreshDLmerenja() {
        jLabelPritisakInJKKDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLjkkfIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija03().getPritisakDLjkkfIn().getBrDec()) + " bar");
        jLabelPritisakOutJKKDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLjkkfOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLjkkfOut().getBrDec()) + " bar");
        jLabelPritisakInSBADL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLsbafIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLsbafIn().getBrDec()) + " bar");
        jLabelPritisakOutSBADL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLsbafOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLsbafOut().getBrDec()) + " bar");
        jLabelPritisakInJBADL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLjbafIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLjbafIn().getBrDec()) + " bar");
        jLabelPritisakOutJBADL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLjbafOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLjbafOut().getBrDec()) + " bar");
        jLabelPritisakInMFDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLmfIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLmfIn().getBrDec()) + " bar");
        jLabelPritisakOutMFDL3.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getPritisakDLmfOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getPritisakDLmfOut().getBrDec()) + " bar");
        
        vodljivostSBA.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getVodljivostSBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getVodljivostSBA().getBrDec()) + " μS/cm");
        vodljivostJBA.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getVodljivostJBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getVodljivostJBA().getBrDec()) + " μS/cm");
        vodljivostMF.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija03().getVodljivostMF().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija03().getVodljivostMF().getBrDec()) + " μS/cm");

    }


    private void refreshVentiliGP() {
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji01CopyDL3, ventiliGP01.getGP01_potisDemi1());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji02CopyDL3, ventiliGP01.getGP01_potisDemi2());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji03CopyDL3, ventiliGP01.getGP01_potisDemi3());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji04CopyDL3, ventiliGP01.getGP01_potisDemi4());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji05CopyDL3, ventiliGP01.getGP01_potisDemi5());

    }

    

    
    private void refreshDL03() {
        try {
            int a = demiLinije.getJkkf03().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelDL3JKKFRegVentil01, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelDL3JKKFRegVentil01Vrednost.setText(ShiftPoint.shiftonePoint(a, demiLinije.getJkkf03().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
        img.setImgHorizontalno(jLabelDL03JKKFventil03, demiLinije.getJkkf03().getVent03());
        img.setImgHorizontalno(jLabelDL03JKKFventil04, demiLinije.getJkkf03().getVent04());
        img.setImgVertikalno(jLabelDL03JKKFventil05, demiLinije.getJkkf03().getVent05());
        img.setImgHorizontalno(jLabelDL03JKKFventil06, demiLinije.getJkkf03().getVent06());
        img.setImgHorizontalno(jLabelDL03JKKFventil07, demiLinije.getJkkf03().getVent07());
        img.setImgHorizontalno(jLabelDL03JKKFventil08, demiLinije.getJkkf03().getVent08());
        img.setImgVertikalno(jLabelDL03JKKFventil09, demiLinije.getJkkf03().getVent09());
        img.setImgHorizontalno(jLabelDL03JKKFventil10, demiLinije.getJkkf03().getVent10());
        img.setImgHorizontalno(jLabelDL03JKKFventil11, demiLinije.getJkkf03().getVent11());
        img.setImgVertikalno(jLabelDL03JKKFventil12, demiLinije.getJkkf03().getVent12());

        img.setImgHorizontalno(jLabelDL03SBAFventil01, demiLinije.getSbaf03().getVent01());
        img.setImgHorizontalno(jLabelDL03SBAFventil02, demiLinije.getSbaf03().getVent02());
        img.setImgHorizontalno(jLabelDL03SBAFventil03, demiLinije.getSbaf03().getVent03());
        img.setImgHorizontalno(jLabelDL03SBAFventil04, demiLinije.getSbaf03().getVent04());
        img.setImgHorizontalno(jLabelDL03SBAFventil05, demiLinije.getSbaf03().getVent05());
        img.setImgVertikalno(jLabelDL03SBAFventil06, demiLinije.getSbaf03().getVent06());

        img.setImgHorizontalno(jLabelDL03JBAFventil01, demiLinije.getJbaf03().getVent01());
        img.setImgHorizontalno(jLabelDL03JBAFventil02, demiLinije.getJbaf03().getVent02());
        img.setImgHorizontalno(jLabelDL03JBAFventil03, demiLinije.getJbaf03().getVent03());
        img.setImgHorizontalno(jLabelDL03JBAFventil04, demiLinije.getJbaf03().getVent04());
        img.setImgHorizontalno(jLabelDL03JBAFventil05, demiLinije.getJbaf03().getVent05());
        img.setImgHorizontalno(jLabelDL03JBAFventil06, demiLinije.getJbaf03().getVent06());
        img.setImgHorizontalno(jLabelDL03JBAFventil07, demiLinije.getJbaf03().getVent07());
        img.setImgVertikalno(jLabelDL03JBAFventil08, demiLinije.getJbaf03().getVent08());

        img.setImgHorizontalno(jLabelDL03MFventil01, demiLinije.getMf03().getVent01());
        img.setImgHorizontalno(jLabelDL03MFventil02, demiLinije.getMf03().getVent02());
        img.setImgHorizontalno(jLabelDL03MFventil03, demiLinije.getMf03().getVent03());
        img.setImgHorizontalno(jLabelDL03MFventil04, demiLinije.getMf03().getVent04());
        img.setImgHorizontalno(jLabelDL03MFventil05, demiLinije.getMf03().getVent05());
        img.setImgHorizontalno(jLabelDL03MFventil06, demiLinije.getMf03().getVent06());
        img.setImgVertikalno(jLabelDL03MFventil07, demiLinije.getMf03().getVent07());
        img.setImgHorizontalno(jLabelDL03MFventil08, demiLinije.getMf03().getVent08());
        img.setImgHorizontalno(jLabelDL03MFventil10, demiLinije.getMf03().getVent10());
        img.setImgVertikalno(jLabelDL03MFventil11, demiLinije.getMf03().getVent11());
    }

    private void refreshBazeniMerenja() {
        int a = bazeniMerenja.getBazenDekaFiltriraneVode().getVrednostRegistra();
        jLabelNivoBazenDekaFiltriraneVodeCopyDL03.setText("L= " + Integer.toString(a) + " cm");
        jProgressBarDekaFiltriranaVodaCopyDL03.setValue(a);

        int d = bazeniMerenja.getBazenNeutralizacioni().getVrednostRegistra();
        jProgressBarNeutralizacioniBazenCopyDL03.setValue(d);
        jLabelNivoNeutralizacioniCopyDL03.setText("L= " + Integer.toString(d) + " cm");
    }

    

    private void refreshProtoci() {
        jLabelProtokDemiLinijaInBr3.setText(Integer.toString(protociDemiLinije.getProtokDL3in().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokDemiLinijaOutBr3.setText(Integer.toString(protociDemiLinije.getProtokDL3out().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoOutDL3.setText(Convert.intToLong(protociDemiLinije.getProtokDL3out().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL3out().getKumulativnoNiziVrednost()));    
        jLabelProtokDemiLinijaMagistrala3.setText(Integer.toString(protociDemiLinije.getProtokMagistralniVod().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoDemiLinijaMagistrala3.setText(Convert.intToLong(protociDemiLinije.getProtokMagistralniVod().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokMagistralniVod().getKumulativnoNiziVrednost()));
        jLabelKumulativnoInDL3.setText(Convert.intToLong(protociDemiLinije.getProtokDL3in().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokDL3in().getKumulativnoNiziVrednost()));
    }

    private void refreshPumpeFiltriraneVodeKaDemineralizaciji() {
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr1CopyDL3, pumpeDekaFiltriranaKaDemi.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr2CopyDL3, pumpeDekaFiltriranaKaDemi.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr3CopyDL3, pumpeDekaFiltriranaKaDemi.getPumpaBr3().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr4CopyDL3, pumpeDekaFiltriranaKaDemi.getPumpaBr4().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr5CopyDL3, pumpeDekaFiltriranaKaDemi.getPumpaBr5().getVrednosti().isUkljucen());
    }

    
   
    private void refreshPumpeNeutralizacionogBazena() {
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr1CopyDL3, pumpeNeutralizacionogBazena.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr2CopyDL3, pumpeNeutralizacionogBazena.getPumpaBr2().getVrednosti().isUkljucen());
    }

    
   

   

    private void refreshRezervoariMerenja() {
        int a = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getVrednostRegistra();
        jProgressBarDemiRezervoarBr1CopyDL3.setValue(a);
        jLabelDemiRezervoarBr1CopyDL3.setText("L= " + Integer.toString(a) + " cm");

        int b = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getVrednostRegistra();
        jProgressBarDemiRezervoarBr2CopyDL3.setValue(a);
        jLabelDemiRezervoarBr2CopyDL3.setText("L= " + Integer.toString(b) + " cm");

        int c = rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getVrednostRegistra();
        jProgressBarDemiRezervoar150mCopyDL3.setValue(c);
        jLabelDemiRezervoar150mCopyDL3.setText("L= " + Integer.toString(c) + " cm");



    }
}