/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import field.merenja.bazeni.Nivoi;
import field.merenja.demiLinije.DemiLinijaMerenjaKonstruktor;
import field.merenja.protoci.ProtociDemiLinije;
import field.merenja.rezervoari.RezervoariMerenja;
import field.pumpe.PumpeDekaFiltrKaDemi;
import field.pumpe.PumpeNeutralizacionogBazena;
import field.ventili.DemiLinije;
import field.ventili.VentiliGrupaPumpi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import popup.AllPopUpWindow;
import tools.AnalogToDigital;
import tools.ShiftPoint;
import utilise.Convert;

/**
 *
 * @author branko.scekic
 */
public class DemiL1Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DemiL1Frame
     * @param protociDemiLinije
     * @param bazeniMerenja
     * @param rezervoariMerenja
     * @param demiLinijeMerenja
     * @param ventiliGP01
     * @param demiLinije
     * @param pumpeDekaFiltriranaKaDemi
     * @param img
     * @param pumpeNeutralizacionogBazena
     * @param allPopUpWindow
     */
    public DemiL1Frame(ProtociDemiLinije protociDemiLinije, Nivoi bazeniMerenja, 
            RezervoariMerenja rezervoariMerenja, 
            DemiLinijaMerenjaKonstruktor demiLinijeMerenja, VentiliGrupaPumpi ventiliGP01, 
            DemiLinije demiLinije, PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi, 
            PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena,
            Img img, AllPopUpWindow allPopUpWindow) {
        
        initComponents();
        this.protociDemiLinije = protociDemiLinije;
        this.pumpeDekaFiltriranaKaDemi = pumpeDekaFiltriranaKaDemi;
        this.pumpeNeutralizacionogBazena = pumpeNeutralizacionogBazena;
        this.bazeniMerenja = bazeniMerenja;
        this.rezervoariMerenja = rezervoariMerenja;
        this.demiLinijeMerenja = demiLinijeMerenja;
        this.ventiliGP01 = ventiliGP01;
        this.demiLinije = demiLinije;
        this.allPopUpWindow = allPopUpWindow;
        this.img = img;
        
        setMinMax();
        screenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDL1JKKFRegVentil01 = new javax.swing.JLabel();
        jLabelDL1JKKFRegVentil01Vrednost = new javax.swing.JLabel();
        jLabelDL01JKKFventil03 = new javax.swing.JLabel();
        jLabelDL01JKKFventil04 = new javax.swing.JLabel();
        jLabelDL01JKKFventil05 = new javax.swing.JLabel();
        jLabelDL01JKKFventil06 = new javax.swing.JLabel();
        jLabelDL01JKKFventil07 = new javax.swing.JLabel();
        jLabelDL01JKKFventil08 = new javax.swing.JLabel();
        jLabelDL01JKKFventil09 = new javax.swing.JLabel();
        jLabelDL01JKKFventil10 = new javax.swing.JLabel();
        jLabelDL01JKKFventil11 = new javax.swing.JLabel();
        jLabelDL01JKKFventil12 = new javax.swing.JLabel();
        jLabelDL01SBAFventil01 = new javax.swing.JLabel();
        jLabelDL01SBAFventil02 = new javax.swing.JLabel();
        jLabelDL01SBAFventil03 = new javax.swing.JLabel();
        jLabelDL01SBAFventil04 = new javax.swing.JLabel();
        jLabelDL01SBAFventil05 = new javax.swing.JLabel();
        jLabelDL01SBAFventil06 = new javax.swing.JLabel();
        jLabelDL01JBAFventil01 = new javax.swing.JLabel();
        jLabelDL01JBAFventil02 = new javax.swing.JLabel();
        jLabelDL01JBAFventil03 = new javax.swing.JLabel();
        jLabelDL01JBAFventil04 = new javax.swing.JLabel();
        jLabelDL01JBAFventil05 = new javax.swing.JLabel();
        jLabelDL01JBAFventil06 = new javax.swing.JLabel();
        jLabelDL01JBAFventil07 = new javax.swing.JLabel();
        jLabelDL01JBAFventil08 = new javax.swing.JLabel();
        jLabelDL01MFventil01 = new javax.swing.JLabel();
        jLabelDL01MFventil02 = new javax.swing.JLabel();
        jLabelDL01MFventil03 = new javax.swing.JLabel();
        jLabelDL01MFventil04 = new javax.swing.JLabel();
        jLabelDL01MFventil05 = new javax.swing.JLabel();
        jLabelDL01MFventil06 = new javax.swing.JLabel();
        jLabelDL01MFventil07 = new javax.swing.JLabel();
        jLabelDL01MFventil08 = new javax.swing.JLabel();
        jLabelDL01MFventil10 = new javax.swing.JLabel();
        jLabelDL01MFventil11 = new javax.swing.JLabel();
        jLabelNivoBazenDekaFiltriraneVodeCopyDL01 = new javax.swing.JLabel();
        jProgressBarDekaFiltriranaVodaCopyDL01 = new javax.swing.JProgressBar();
        jLabelNivoNeutralizacioniCopyDL01 = new javax.swing.JLabel();
        jProgressBarNeutralizacioniBazenCopyDL01 = new javax.swing.JProgressBar();
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji01CopyDL1 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji02CopyDL1 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji05CopyDL1 = new javax.swing.JLabel();
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji04CopyDL1 = new javax.swing.JLabel();
        jLabelPumpeKaDemiLiniji03CopyDL1 = new javax.swing.JLabel();
        jProgressBarDemiRezervoarBr1CopyDL1 = new javax.swing.JProgressBar();
        jLabelDemiRezervoarBr1CopyDL1 = new javax.swing.JLabel();
        jProgressBarDemiRezervoarBr2CopyDL1 = new javax.swing.JProgressBar();
        jLabelDemiRezervoarBr2CopyDL1 = new javax.swing.JLabel();
        jProgressBarDemiRezervoar150mCopyDL1 = new javax.swing.JProgressBar();
        jLabelDemiRezervoar150mCopyDL1 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaInBr1 = new javax.swing.JLabel();
        jLabelKumulativnoInDL1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr1CopyDL1 = new javax.swing.JLabel();
        jLabelPumpaNeutralizacioniBazenBr2CopyDL1 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaOutBr1 = new javax.swing.JLabel();
        jLabelKumulativnoOutDL1 = new javax.swing.JLabel();
        jLabelKumulativnoDemiLinijaMagistrala1 = new javax.swing.JLabel();
        jLabelProtokDemiLinijaMagistrala1 = new javax.swing.JLabel();
        jLabelPritisakInJKKDL1 = new javax.swing.JLabel();
        jLabelPritisakOutJKKDL1 = new javax.swing.JLabel();
        jLabelPritisakInSBADL1 = new javax.swing.JLabel();
        jLabelPritisakOutSBADL1 = new javax.swing.JLabel();
        jLabelPritisakInJBADL1 = new javax.swing.JLabel();
        jLabelPritisakOutJBADL1 = new javax.swing.JLabel();
        jLabelPritisakOutMFDL1 = new javax.swing.JLabel();
        jLabelPritisakInMFDL1 = new javax.swing.JLabel();
        vodljivostJBA = new javax.swing.JLabel();
        vodljivostSBA = new javax.swing.JLabel();
        vodljivostMF = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabelDL1JKKFRegVentil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL1JKKFRegVentil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL1JKKFRegVentil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL1JKKFRegVentil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL1JKKFRegVentil01);
        jLabelDL1JKKFRegVentil01.setBounds(280, 420, 50, 40);

        jLabelDL1JKKFRegVentil01Vrednost.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelDL1JKKFRegVentil01Vrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL1JKKFRegVentil01Vrednost.setText("***");
        getContentPane().add(jLabelDL1JKKFRegVentil01Vrednost);
        jLabelDL1JKKFRegVentil01Vrednost.setBounds(280, 460, 40, 19);

        jLabelDL01JKKFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JKKFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil03);
        jLabelDL01JKKFventil03.setBounds(380, 420, 40, 40);

        jLabelDL01JKKFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JKKFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil04);
        jLabelDL01JKKFventil04.setBounds(470, 420, 40, 40);

        jLabelDL01JKKFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL01JKKFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil05);
        jLabelDL01JKKFventil05.setBounds(240, 480, 40, 40);

        jLabelDL01JKKFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JKKFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil06);
        jLabelDL01JKKFventil06.setBounds(470, 370, 40, 30);

        jLabelDL01JKKFventil07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JKKFventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil07);
        jLabelDL01JKKFventil07.setBounds(380, 510, 40, 40);

        jLabelDL01JKKFventil08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JKKFventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil08);
        jLabelDL01JKKFventil08.setBounds(370, 370, 50, 30);

        jLabelDL01JKKFventil09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL01JKKFventil09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil09MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil09);
        jLabelDL01JKKFventil09.setBounds(290, 320, 40, 50);

        jLabelDL01JKKFventil10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JKKFventil10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil10);
        jLabelDL01JKKFventil10.setBounds(380, 470, 50, 30);

        jLabelDL01JKKFventil11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JKKFventil11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil11);
        jLabelDL01JKKFventil11.setBounds(460, 510, 60, 40);

        jLabelDL01JKKFventil12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JKKFventil12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL01JKKFventil12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JKKFventil12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JKKFventil12);
        jLabelDL01JKKFventil12.setBounds(570, 500, 30, 50);

        jLabelDL01SBAFventil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01SBAFventil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01SBAFventil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01SBAFventil01);
        jLabelDL01SBAFventil01.setBounds(690, 420, 40, 40);

        jLabelDL01SBAFventil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01SBAFventil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01SBAFventil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01SBAFventil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01SBAFventil02);
        jLabelDL01SBAFventil02.setBounds(690, 470, 40, 30);

        jLabelDL01SBAFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01SBAFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01SBAFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01SBAFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01SBAFventil03);
        jLabelDL01SBAFventil03.setBounds(780, 370, 40, 30);

        jLabelDL01SBAFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01SBAFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01SBAFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01SBAFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01SBAFventil04);
        jLabelDL01SBAFventil04.setBounds(790, 470, 50, 30);

        jLabelDL01SBAFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01SBAFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01SBAFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01SBAFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01SBAFventil05);
        jLabelDL01SBAFventil05.setBounds(760, 520, 50, 30);

        jLabelDL01SBAFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01SBAFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL01SBAFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01SBAFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01SBAFventil06);
        jLabelDL01SBAFventil06.setBounds(880, 490, 26, 50);

        jLabelDL01JBAFventil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JBAFventil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JBAFventil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JBAFventil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JBAFventil01);
        jLabelDL01JBAFventil01.setBounds(980, 430, 60, 30);

        jLabelDL01JBAFventil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JBAFventil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JBAFventil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JBAFventil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JBAFventil02);
        jLabelDL01JBAFventil02.setBounds(1080, 430, 50, 30);

        jLabelDL01JBAFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JBAFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JBAFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JBAFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JBAFventil03);
        jLabelDL01JBAFventil03.setBounds(990, 470, 40, 30);

        jLabelDL01JBAFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JBAFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JBAFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JBAFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JBAFventil04);
        jLabelDL01JBAFventil04.setBounds(1080, 370, 50, 30);

        jLabelDL01JBAFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JBAFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JBAFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JBAFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JBAFventil05);
        jLabelDL01JBAFventil05.setBounds(990, 370, 50, 30);

        jLabelDL01JBAFventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JBAFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JBAFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JBAFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JBAFventil06);
        jLabelDL01JBAFventil06.setBounds(990, 550, 40, 26);

        jLabelDL01JBAFventil07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JBAFventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01JBAFventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JBAFventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JBAFventil07);
        jLabelDL01JBAFventil07.setBounds(1080, 520, 40, 40);

        jLabelDL01JBAFventil08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01JBAFventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL01JBAFventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01JBAFventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01JBAFventil08);
        jLabelDL01JBAFventil08.setBounds(1170, 500, 40, 50);

        jLabelDL01MFventil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01MFventil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01MFventil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil01);
        jLabelDL01MFventil01.setBounds(1300, 430, 40, 30);

        jLabelDL01MFventil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01MFventil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01MFventil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil02);
        jLabelDL01MFventil02.setBounds(1390, 430, 40, 30);

        jLabelDL01MFventil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01MFventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01MFventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil03);
        jLabelDL01MFventil03.setBounds(1300, 470, 40, 40);

        jLabelDL01MFventil04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01MFventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01MFventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil04);
        jLabelDL01MFventil04.setBounds(1390, 370, 50, 30);

        jLabelDL01MFventil05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01MFventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01MFventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil05);
        jLabelDL01MFventil05.setBounds(1400, 470, 40, 40);

        jLabelDL01MFventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01MFventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil06);
        jLabelDL01MFventil06.setBounds(1300, 360, 40, 50);

        jLabelDL01MFventil07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01MFventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL01MFventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil07);
        jLabelDL01MFventil07.setBounds(1216, 500, 30, 50);

        jLabelDL01MFventil08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01MFventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01MFventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil08);
        jLabelDL01MFventil08.setBounds(1300, 520, 40, 40);

        jLabelDL01MFventil10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01MFventil10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelDL01MFventil10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil10);
        jLabelDL01MFventil10.setBounds(1380, 520, 40, 40);

        jLabelDL01MFventil11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDL01MFventil11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelDL01MFventil11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDL01MFventil11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelDL01MFventil11);
        jLabelDL01MFventil11.setBounds(1470, 500, 26, 40);

        jLabelNivoBazenDekaFiltriraneVodeCopyDL01.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoBazenDekaFiltriraneVodeCopyDL01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoBazenDekaFiltriraneVodeCopyDL01.setText("+++");
        jLabelNivoBazenDekaFiltriraneVodeCopyDL01.setBorder(null);
        getContentPane().add(jLabelNivoBazenDekaFiltriraneVodeCopyDL01);
        jLabelNivoBazenDekaFiltriraneVodeCopyDL01.setBounds(390, 910, 200, 20);

        jProgressBarDekaFiltriranaVodaCopyDL01.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarDekaFiltriranaVodaCopyDL01.setOrientation(1);
        jProgressBarDekaFiltriranaVodaCopyDL01.setToolTipText("");
        jProgressBarDekaFiltriranaVodaCopyDL01.setValue(10);
        jProgressBarDekaFiltriranaVodaCopyDL01.setBorderPainted(false);
        jProgressBarDekaFiltriranaVodaCopyDL01.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarDekaFiltriranaVodaCopyDL01.setString("");
        jProgressBarDekaFiltriranaVodaCopyDL01.setStringPainted(true);
        getContentPane().add(jProgressBarDekaFiltriranaVodaCopyDL01);
        jProgressBarDekaFiltriranaVodaCopyDL01.setBounds(300, 840, 20, 90);

        jLabelNivoNeutralizacioniCopyDL01.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoNeutralizacioniCopyDL01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoNeutralizacioniCopyDL01.setText("***");
        jLabelNivoNeutralizacioniCopyDL01.setBorder(null);
        getContentPane().add(jLabelNivoNeutralizacioniCopyDL01);
        jLabelNivoNeutralizacioniCopyDL01.setBounds(790, 900, 130, 24);

        jProgressBarNeutralizacioniBazenCopyDL01.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarNeutralizacioniBazenCopyDL01.setOrientation(1);
        jProgressBarNeutralizacioniBazenCopyDL01.setToolTipText("");
        jProgressBarNeutralizacioniBazenCopyDL01.setValue(10);
        jProgressBarNeutralizacioniBazenCopyDL01.setBorderPainted(false);
        jProgressBarNeutralizacioniBazenCopyDL01.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarNeutralizacioniBazenCopyDL01.setString("");
        jProgressBarNeutralizacioniBazenCopyDL01.setStringPainted(true);
        getContentPane().add(jProgressBarNeutralizacioniBazenCopyDL01);
        jProgressBarNeutralizacioniBazenCopyDL01.setBounds(710, 840, 20, 90);

        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1);
        jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1.setBounds(310, 720, 60, 50);

        jLabelPumpeKaDemiLiniji01CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji01CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji01CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji01CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji01CopyDL1);
        jLabelPumpeKaDemiLiniji01CopyDL1.setBounds(320, 670, 40, 40);

        jLabelPumpeKaDemiLiniji02CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji02CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji02CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji02CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji02CopyDL1);
        jLabelPumpeKaDemiLiniji02CopyDL1.setBounds(390, 670, 40, 40);

        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1);
        jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1.setBounds(390, 720, 50, 50);

        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1);
        jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1.setBounds(460, 720, 50, 50);

        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1);
        jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1.setBounds(530, 720, 50, 50);

        jLabelPumpeKaDemiLiniji05CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji05CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji05CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji05CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji05CopyDL1);
        jLabelPumpeKaDemiLiniji05CopyDL1.setBounds(610, 670, 40, 40);

        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1);
        jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1.setBounds(600, 720, 60, 50);

        jLabelPumpeKaDemiLiniji04CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpeKaDemiLiniji04CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji04CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji04CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji04CopyDL1);
        jLabelPumpeKaDemiLiniji04CopyDL1.setBounds(540, 670, 40, 40);

        jLabelPumpeKaDemiLiniji03CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPumpeKaDemiLiniji03CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpeKaDemiLiniji03CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpeKaDemiLiniji03CopyDL1);
        jLabelPumpeKaDemiLiniji03CopyDL1.setBounds(470, 670, 26, 40);

        jProgressBarDemiRezervoarBr1CopyDL1.setOrientation(1);
        jProgressBarDemiRezervoarBr1CopyDL1.setValue(10);
        jProgressBarDemiRezervoarBr1CopyDL1.setString("0");
        jProgressBarDemiRezervoarBr1CopyDL1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr1CopyDL1);
        jProgressBarDemiRezervoarBr1CopyDL1.setBounds(1010, 770, 20, 160);

        jLabelDemiRezervoarBr1CopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr1CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr1CopyDL1.setText("***");
        jLabelDemiRezervoarBr1CopyDL1.setBorder(null);
        getContentPane().add(jLabelDemiRezervoarBr1CopyDL1);
        jLabelDemiRezervoarBr1CopyDL1.setBounds(1020, 900, 130, 30);

        jProgressBarDemiRezervoarBr2CopyDL1.setOrientation(1);
        jProgressBarDemiRezervoarBr2CopyDL1.setValue(10);
        jProgressBarDemiRezervoarBr2CopyDL1.setString("0");
        jProgressBarDemiRezervoarBr2CopyDL1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoarBr2CopyDL1);
        jProgressBarDemiRezervoarBr2CopyDL1.setBounds(1200, 770, 20, 160);

        jLabelDemiRezervoarBr2CopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoarBr2CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoarBr2CopyDL1.setText("***");
        jLabelDemiRezervoarBr2CopyDL1.setBorder(null);
        getContentPane().add(jLabelDemiRezervoarBr2CopyDL1);
        jLabelDemiRezervoarBr2CopyDL1.setBounds(1210, 900, 130, 30);

        jProgressBarDemiRezervoar150mCopyDL1.setOrientation(1);
        jProgressBarDemiRezervoar150mCopyDL1.setValue(10);
        jProgressBarDemiRezervoar150mCopyDL1.setString("0");
        jProgressBarDemiRezervoar150mCopyDL1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarDemiRezervoar150mCopyDL1);
        jProgressBarDemiRezervoar150mCopyDL1.setBounds(910, 650, 20, 120);

        jLabelDemiRezervoar150mCopyDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelDemiRezervoar150mCopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDemiRezervoar150mCopyDL1.setText("***");
        jLabelDemiRezervoar150mCopyDL1.setBorder(null);
        getContentPane().add(jLabelDemiRezervoar150mCopyDL1);
        jLabelDemiRezervoar150mCopyDL1.setBounds(910, 740, 110, 30);

        jLabelProtokDemiLinijaInBr1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaInBr1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaInBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaInBr1.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaInBr1);
        jLabelProtokDemiLinijaInBr1.setBounds(210, 660, 100, 19);

        jLabelKumulativnoInDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoInDL1.setText("***");
        getContentPane().add(jLabelKumulativnoInDL1);
        jLabelKumulativnoInDL1.setBounds(180, 680, 150, 20);

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel20.setText("BR 1");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1120, 30, 140, 50);

        jLabelPumpaNeutralizacioniBazenBr1CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr1CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr1CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr1CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr1CopyDL1);
        jLabelPumpaNeutralizacioniBazenBr1CopyDL1.setBounds(760, 790, 50, 50);

        jLabelPumpaNeutralizacioniBazenBr2CopyDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaNeutralizacioniBazenBr2CopyDL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaNeutralizacioniBazenBr2CopyDL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaNeutralizacioniBazenBr2CopyDL1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaNeutralizacioniBazenBr2CopyDL1);
        jLabelPumpaNeutralizacioniBazenBr2CopyDL1.setBounds(830, 790, 50, 50);

        jLabelProtokDemiLinijaOutBr1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaOutBr1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaOutBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaOutBr1.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaOutBr1);
        jLabelProtokDemiLinijaOutBr1.setBounds(1540, 420, 100, 19);

        jLabelKumulativnoOutDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoOutDL1.setText("***");
        getContentPane().add(jLabelKumulativnoOutDL1);
        jLabelKumulativnoOutDL1.setBounds(1530, 400, 120, 20);

        jLabelKumulativnoDemiLinijaMagistrala1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoDemiLinijaMagistrala1.setText("***");
        getContentPane().add(jLabelKumulativnoDemiLinijaMagistrala1);
        jLabelKumulativnoDemiLinijaMagistrala1.setBounds(1480, 730, 150, 20);

        jLabelProtokDemiLinijaMagistrala1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokDemiLinijaMagistrala1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokDemiLinijaMagistrala1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokDemiLinijaMagistrala1.setText("***");
        getContentPane().add(jLabelProtokDemiLinijaMagistrala1);
        jLabelProtokDemiLinijaMagistrala1.setBounds(1510, 750, 100, 19);

        jLabelPritisakInJKKDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJKKDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJKKDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJKKDL1);
        jLabelPritisakInJKKDL1.setBounds(350, 320, 90, 30);

        jLabelPritisakOutJKKDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJKKDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJKKDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJKKDL1);
        jLabelPritisakOutJKKDL1.setBounds(460, 320, 90, 30);

        jLabelPritisakInSBADL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInSBADL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInSBADL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakInSBADL1);
        jLabelPritisakInSBADL1.setBounds(650, 320, 90, 30);

        jLabelPritisakOutSBADL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutSBADL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutSBADL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutSBADL1);
        jLabelPritisakOutSBADL1.setBounds(760, 320, 90, 30);

        jLabelPritisakInJBADL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInJBADL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInJBADL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakInJBADL1);
        jLabelPritisakInJBADL1.setBounds(960, 320, 90, 30);

        jLabelPritisakOutJBADL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutJBADL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutJBADL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutJBADL1);
        jLabelPritisakOutJBADL1.setBounds(1070, 320, 90, 30);

        jLabelPritisakOutMFDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakOutMFDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakOutMFDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakOutMFDL1);
        jLabelPritisakOutMFDL1.setBounds(1380, 320, 90, 30);

        jLabelPritisakInMFDL1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakInMFDL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakInMFDL1.setText("jLabel15");
        getContentPane().add(jLabelPritisakInMFDL1);
        jLabelPritisakInMFDL1.setBounds(1270, 320, 90, 30);

        vodljivostJBA.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostJBA.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostJBA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostJBA.setText("jLabel15");
        getContentPane().add(vodljivostJBA);
        vodljivostJBA.setBounds(990, 590, 140, 30);

        vodljivostSBA.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostSBA.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostSBA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostSBA.setText("jLabel15");
        getContentPane().add(vodljivostSBA);
        vodljivostSBA.setBounds(680, 590, 140, 30);

        vodljivostMF.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        vodljivostMF.setForeground(new java.awt.Color(204, 0, 0));
        vodljivostMF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vodljivostMF.setText("jLabel15");
        getContentPane().add(vodljivostMF);
        vodljivostMF.setBounds(1310, 590, 130, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/statImg/Demi/DEMI linija detaljno.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(6, 0, 1730, 970);

        setBounds(170, 35, 1748, 1004);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelDL1JKKFRegVentil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL1JKKFRegVentil01MouseClicked
        allPopUpWindow.ProzorDL01JKKF01();
    }//GEN-LAST:event_jLabelDL1JKKFRegVentil01MouseClicked

    private void jLabelDL01JKKFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil03MouseClicked
        allPopUpWindow.ProzorDL01JKKF03();
    }//GEN-LAST:event_jLabelDL01JKKFventil03MouseClicked

    private void jLabelDL01JKKFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil04MouseClicked
       allPopUpWindow.ProzorDL01JKKF04();
    }//GEN-LAST:event_jLabelDL01JKKFventil04MouseClicked

    private void jLabelDL01JKKFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil05MouseClicked
       allPopUpWindow.ProzorDL01JKKF05();
    }//GEN-LAST:event_jLabelDL01JKKFventil05MouseClicked

    private void jLabelDL01JKKFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil06MouseClicked
        allPopUpWindow.ProzorDL01JKKF06();
    }//GEN-LAST:event_jLabelDL01JKKFventil06MouseClicked

    private void jLabelDL01JKKFventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil07MouseClicked
       allPopUpWindow.ProzorDL01JKKF07();
    }//GEN-LAST:event_jLabelDL01JKKFventil07MouseClicked

    private void jLabelDL01JKKFventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil08MouseClicked
        allPopUpWindow.ProzorDL01JKKF08();
    }//GEN-LAST:event_jLabelDL01JKKFventil08MouseClicked

    private void jLabelDL01JKKFventil09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil09MouseClicked
        allPopUpWindow.ProzorDL01JKKF09();
    }//GEN-LAST:event_jLabelDL01JKKFventil09MouseClicked

    private void jLabelDL01JKKFventil10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil10MouseClicked
       allPopUpWindow.ProzorDL01JKKF10();
    }//GEN-LAST:event_jLabelDL01JKKFventil10MouseClicked

    private void jLabelDL01JKKFventil11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil11MouseClicked
        allPopUpWindow.ProzorDL01JKKF11();
    }//GEN-LAST:event_jLabelDL01JKKFventil11MouseClicked

    private void jLabelDL01JKKFventil12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JKKFventil12MouseClicked
        allPopUpWindow.ProzorDL01JKKF12();
    }//GEN-LAST:event_jLabelDL01JKKFventil12MouseClicked

    private void jLabelDL01SBAFventil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01SBAFventil01MouseClicked
        allPopUpWindow.ProzorDL01SBA01();
    }//GEN-LAST:event_jLabelDL01SBAFventil01MouseClicked

    private void jLabelDL01SBAFventil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01SBAFventil02MouseClicked
        allPopUpWindow.ProzorDL01SBA02();
    }//GEN-LAST:event_jLabelDL01SBAFventil02MouseClicked

    private void jLabelDL01SBAFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01SBAFventil03MouseClicked
         allPopUpWindow.ProzorDL01SBA03();
    }//GEN-LAST:event_jLabelDL01SBAFventil03MouseClicked

    private void jLabelDL01SBAFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01SBAFventil04MouseClicked
         allPopUpWindow.ProzorDL01SBA04();
    }//GEN-LAST:event_jLabelDL01SBAFventil04MouseClicked

    private void jLabelDL01SBAFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01SBAFventil05MouseClicked
        allPopUpWindow.ProzorDL01SBA05();
    }//GEN-LAST:event_jLabelDL01SBAFventil05MouseClicked

    private void jLabelDL01SBAFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01SBAFventil06MouseClicked
        allPopUpWindow.ProzorDL01SBA06();
    }//GEN-LAST:event_jLabelDL01SBAFventil06MouseClicked

    private void jLabelDL01JBAFventil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JBAFventil01MouseClicked
        allPopUpWindow.ProzorDL01JBA01();
    }//GEN-LAST:event_jLabelDL01JBAFventil01MouseClicked

    private void jLabelDL01JBAFventil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JBAFventil02MouseClicked
        allPopUpWindow.ProzorDL01JBA02();
    }//GEN-LAST:event_jLabelDL01JBAFventil02MouseClicked

    private void jLabelDL01JBAFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JBAFventil03MouseClicked
       allPopUpWindow.ProzorDL01JBA03();
    }//GEN-LAST:event_jLabelDL01JBAFventil03MouseClicked

    private void jLabelDL01JBAFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JBAFventil04MouseClicked
        allPopUpWindow.ProzorDL01JBA04();
    }//GEN-LAST:event_jLabelDL01JBAFventil04MouseClicked

    private void jLabelDL01JBAFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JBAFventil05MouseClicked
        allPopUpWindow.ProzorDL01JBA05();
    }//GEN-LAST:event_jLabelDL01JBAFventil05MouseClicked

    private void jLabelDL01JBAFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JBAFventil06MouseClicked
       allPopUpWindow.ProzorDL01JBA06();
    }//GEN-LAST:event_jLabelDL01JBAFventil06MouseClicked

    private void jLabelDL01JBAFventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JBAFventil07MouseClicked
       allPopUpWindow.ProzorDL01JBA07();
    }//GEN-LAST:event_jLabelDL01JBAFventil07MouseClicked

    private void jLabelDL01JBAFventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01JBAFventil08MouseClicked
       allPopUpWindow.ProzorDL01JBA08();
    }//GEN-LAST:event_jLabelDL01JBAFventil08MouseClicked

    private void jLabelDL01MFventil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil01MouseClicked
       allPopUpWindow.ProzorDL01MF01();
    }//GEN-LAST:event_jLabelDL01MFventil01MouseClicked

    private void jLabelDL01MFventil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil02MouseClicked
        allPopUpWindow.ProzorDL01MF02();
    }//GEN-LAST:event_jLabelDL01MFventil02MouseClicked

    private void jLabelDL01MFventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil03MouseClicked
        allPopUpWindow.ProzorDL01MF03();
    }//GEN-LAST:event_jLabelDL01MFventil03MouseClicked

    private void jLabelDL01MFventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil04MouseClicked
       allPopUpWindow.ProzorDL01MF04();
    }//GEN-LAST:event_jLabelDL01MFventil04MouseClicked

    private void jLabelDL01MFventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil05MouseClicked
        allPopUpWindow.ProzorDL01MF05();
    }//GEN-LAST:event_jLabelDL01MFventil05MouseClicked

    private void jLabelDL01MFventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil06MouseClicked
        allPopUpWindow.ProzorDL01MF06();
    }//GEN-LAST:event_jLabelDL01MFventil06MouseClicked

    private void jLabelDL01MFventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil07MouseClicked
        allPopUpWindow.ProzorDL01MF07();
    }//GEN-LAST:event_jLabelDL01MFventil07MouseClicked

    private void jLabelDL01MFventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil08MouseClicked
        allPopUpWindow.ProzorDL01MF08();
    }//GEN-LAST:event_jLabelDL01MFventil08MouseClicked

    private void jLabelDL01MFventil10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil10MouseClicked
       allPopUpWindow.ProzorDL01MF10();
    }//GEN-LAST:event_jLabelDL01MFventil10MouseClicked

    private void jLabelDL01MFventil11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDL01MFventil11MouseClicked
        allPopUpWindow.ProzorDL01MF11();
    }//GEN-LAST:event_jLabelDL01MFventil11MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama01();  
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1MouseClicked

    private void jLabelPumpeKaDemiLiniji01CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji01CopyDL1MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr1(); 
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji01CopyDL1MouseClicked

    private void jLabelPumpeKaDemiLiniji02CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji02CopyDL1MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr2(); 
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji02CopyDL1MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama02(); 
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama03(); 
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1MouseClicked
         allPopUpWindow.ProzorPumpaKaDemiLinijama04(); 
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1MouseClicked

    private void jLabelPumpeKaDemiLiniji05CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji05CopyDL1MouseClicked
       allPopUpWindow.ProzorPKDemiLinijamaBr5(); 
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji05CopyDL1MouseClicked

    private void jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1MouseClicked
        allPopUpWindow.ProzorPumpaKaDemiLinijama05(); 
    }//GEN-LAST:event_jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1MouseClicked

    private void jLabelPumpeKaDemiLiniji04CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji04CopyDL1MouseClicked
        allPopUpWindow.ProzorPKDemiLinijamaBr4(); 
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji04CopyDL1MouseClicked

    private void jLabelPumpeKaDemiLiniji03CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpeKaDemiLiniji03CopyDL1MouseClicked
         allPopUpWindow.ProzorPKDemiLinijamaBr3(); 
    }//GEN-LAST:event_jLabelPumpeKaDemiLiniji03CopyDL1MouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr1CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr1CopyDL1MouseClicked
        allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr1(); 
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr1CopyDL1MouseClicked

    private void jLabelPumpaNeutralizacioniBazenBr2CopyDL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaNeutralizacioniBazenBr2CopyDL1MouseClicked
        allPopUpWindow.ProzorPumpaNeutralizacioniBazenBr2();
    }//GEN-LAST:event_jLabelPumpaNeutralizacioniBazenBr2CopyDL1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabelDL01JBAFventil01;
    private javax.swing.JLabel jLabelDL01JBAFventil02;
    private javax.swing.JLabel jLabelDL01JBAFventil03;
    private javax.swing.JLabel jLabelDL01JBAFventil04;
    private javax.swing.JLabel jLabelDL01JBAFventil05;
    private javax.swing.JLabel jLabelDL01JBAFventil06;
    private javax.swing.JLabel jLabelDL01JBAFventil07;
    private javax.swing.JLabel jLabelDL01JBAFventil08;
    private javax.swing.JLabel jLabelDL01JKKFventil03;
    private javax.swing.JLabel jLabelDL01JKKFventil04;
    private javax.swing.JLabel jLabelDL01JKKFventil05;
    private javax.swing.JLabel jLabelDL01JKKFventil06;
    private javax.swing.JLabel jLabelDL01JKKFventil07;
    private javax.swing.JLabel jLabelDL01JKKFventil08;
    private javax.swing.JLabel jLabelDL01JKKFventil09;
    private javax.swing.JLabel jLabelDL01JKKFventil10;
    private javax.swing.JLabel jLabelDL01JKKFventil11;
    private javax.swing.JLabel jLabelDL01JKKFventil12;
    private javax.swing.JLabel jLabelDL01MFventil01;
    private javax.swing.JLabel jLabelDL01MFventil02;
    private javax.swing.JLabel jLabelDL01MFventil03;
    private javax.swing.JLabel jLabelDL01MFventil04;
    private javax.swing.JLabel jLabelDL01MFventil05;
    private javax.swing.JLabel jLabelDL01MFventil06;
    private javax.swing.JLabel jLabelDL01MFventil07;
    private javax.swing.JLabel jLabelDL01MFventil08;
    private javax.swing.JLabel jLabelDL01MFventil10;
    private javax.swing.JLabel jLabelDL01MFventil11;
    private javax.swing.JLabel jLabelDL01SBAFventil01;
    private javax.swing.JLabel jLabelDL01SBAFventil02;
    private javax.swing.JLabel jLabelDL01SBAFventil03;
    private javax.swing.JLabel jLabelDL01SBAFventil04;
    private javax.swing.JLabel jLabelDL01SBAFventil05;
    private javax.swing.JLabel jLabelDL01SBAFventil06;
    private javax.swing.JLabel jLabelDL1JKKFRegVentil01;
    private javax.swing.JLabel jLabelDL1JKKFRegVentil01Vrednost;
    private javax.swing.JLabel jLabelDemiRezervoar150mCopyDL1;
    private javax.swing.JLabel jLabelDemiRezervoarBr1CopyDL1;
    private javax.swing.JLabel jLabelDemiRezervoarBr2CopyDL1;
    private javax.swing.JLabel jLabelKumulativnoDemiLinijaMagistrala1;
    private javax.swing.JLabel jLabelKumulativnoInDL1;
    private javax.swing.JLabel jLabelKumulativnoOutDL1;
    private javax.swing.JLabel jLabelNivoBazenDekaFiltriraneVodeCopyDL01;
    private javax.swing.JLabel jLabelNivoNeutralizacioniCopyDL01;
    private javax.swing.JLabel jLabelPritisakInJBADL1;
    private javax.swing.JLabel jLabelPritisakInJKKDL1;
    private javax.swing.JLabel jLabelPritisakInMFDL1;
    private javax.swing.JLabel jLabelPritisakInSBADL1;
    private javax.swing.JLabel jLabelPritisakOutJBADL1;
    private javax.swing.JLabel jLabelPritisakOutJKKDL1;
    private javax.swing.JLabel jLabelPritisakOutMFDL1;
    private javax.swing.JLabel jLabelPritisakOutSBADL1;
    private javax.swing.JLabel jLabelProtokDemiLinijaInBr1;
    private javax.swing.JLabel jLabelProtokDemiLinijaMagistrala1;
    private javax.swing.JLabel jLabelProtokDemiLinijaOutBr1;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1;
    private javax.swing.JLabel jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr1CopyDL1;
    private javax.swing.JLabel jLabelPumpaNeutralizacioniBazenBr2CopyDL1;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji01CopyDL1;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji02CopyDL1;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji03CopyDL1;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji04CopyDL1;
    private javax.swing.JLabel jLabelPumpeKaDemiLiniji05CopyDL1;
    private javax.swing.JProgressBar jProgressBarDekaFiltriranaVodaCopyDL01;
    private javax.swing.JProgressBar jProgressBarDemiRezervoar150mCopyDL1;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr1CopyDL1;
    private javax.swing.JProgressBar jProgressBarDemiRezervoarBr2CopyDL1;
    private javax.swing.JProgressBar jProgressBarNeutralizacioniBazenCopyDL01;
    private javax.swing.JLabel vodljivostJBA;
    private javax.swing.JLabel vodljivostMF;
    private javax.swing.JLabel vodljivostSBA;
    // End of variables declaration//GEN-END:variables
    
    private final Img img;
    private final AllPopUpWindow allPopUpWindow;
    private final ProtociDemiLinije protociDemiLinije;
    private final Nivoi bazeniMerenja;
    private final RezervoariMerenja rezervoariMerenja;
    private final DemiLinijaMerenjaKonstruktor demiLinijeMerenja;
    private final VentiliGrupaPumpi ventiliGP01;
    private final PumpeDekaFiltrKaDemi pumpeDekaFiltriranaKaDemi;
    private final PumpeNeutralizacionogBazena pumpeNeutralizacionogBazena;
    private final DemiLinije demiLinije;
    public Timer timer;
    
    
    public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                //Date date = new Date();
                refreshDLmerenja();
                refreshDL01();
                refreshVentiliGP();
                refreshBazeniMerenja();
                refreshPumpeFiltriraneVodeKaDemineralizaciji();refreshRezervoariMerenja();    
                refreshProtoci();
                refreshPumpeNeutralizacionogBazena();

                //System.out.println(date.getTime());
                //System.out.println("_____________");
            }
        });
    }
    
    
     private void setMinMax() {
        jProgressBarDekaFiltriranaVodaCopyDL01.setMinimum(bazeniMerenja.getBazenDekaFiltriraneVode().getMin());
        jProgressBarDekaFiltriranaVodaCopyDL01.setMaximum(bazeniMerenja.getBazenDekaFiltriraneVode().getMax());
        jProgressBarDekaFiltriranaVodaCopyDL01.setForeground(Color.ORANGE);

        jProgressBarNeutralizacioniBazenCopyDL01.setMinimum(bazeniMerenja.getBazenNeutralizacioni().getMin());
        jProgressBarNeutralizacioniBazenCopyDL01.setMaximum(bazeniMerenja.getBazenNeutralizacioni().getMax());
        jProgressBarNeutralizacioniBazenCopyDL01.setForeground(Color.ORANGE);
  
        jProgressBarDemiRezervoarBr1CopyDL1.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMin());
        jProgressBarDemiRezervoarBr1CopyDL1.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getMax());
        jProgressBarDemiRezervoarBr1CopyDL1.setForeground(Color.ORANGE);
      
        jProgressBarDemiRezervoarBr2CopyDL1.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMin());
        jProgressBarDemiRezervoarBr2CopyDL1.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getMax());
        jProgressBarDemiRezervoarBr2CopyDL1.setForeground(Color.ORANGE);

        jProgressBarDemiRezervoar150mCopyDL1.setMinimum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMin());
        jProgressBarDemiRezervoar150mCopyDL1.setMaximum(rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getMax());
        jProgressBarDemiRezervoar150mCopyDL1.setForeground(Color.ORANGE);
    }


    private void refreshDLmerenja() {
        jLabelPritisakInJKKDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLjkkfIn().getVrednostRegistra(), 
                demiLinijeMerenja.getDemiLinija01().getPritisakDLjkkfIn().getBrDec()) + " bar");
        jLabelPritisakOutJKKDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLjkkfOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getPritisakDLjkkfOut().getBrDec()) + " bar");
        jLabelPritisakInSBADL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLsbafIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getPritisakDLsbafIn().getBrDec()) + " bar");
        jLabelPritisakOutSBADL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLsbafOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getPritisakDLsbafOut().getBrDec()) + " bar");
        jLabelPritisakInJBADL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLjbafIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getPritisakDLjbafIn().getBrDec()) + " bar");
        jLabelPritisakOutJBADL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLjbafOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getPritisakDLjbafOut().getBrDec()) + " bar");
        jLabelPritisakInMFDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLmfIn().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getPritisakDLmfIn().getBrDec()) + " bar");
        jLabelPritisakOutMFDL1.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getPritisakDLmfOut().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getPritisakDLmfOut().getBrDec()) + " bar");
        
        
        vodljivostSBA.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getVodljivostSBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getVodljivostSBA().getBrDec()) + "  μS/cm");
        vodljivostJBA.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getVodljivostJBA().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getVodljivostJBA().getBrDec()) + " μS/cm");
        vodljivostMF.setText(ShiftPoint.shiftonePoint(demiLinijeMerenja.getDemiLinija01().getVodljivostMF().getVrednostRegistra(),
                demiLinijeMerenja.getDemiLinija01().getVodljivostMF().getBrDec()) + " μS/cm");
    }


    private void refreshVentiliGP() {
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji01CopyDL1, ventiliGP01.getGP01_potisDemi1());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji02CopyDL1, ventiliGP01.getGP01_potisDemi2());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji03CopyDL1, ventiliGP01.getGP01_potisDemi3());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji04CopyDL1, ventiliGP01.getGP01_potisDemi4());
        img.setImgVertikalno(jLabelPumpeKaDemiLiniji05CopyDL1, ventiliGP01.getGP01_potisDemi5());

    }

    

    
    private void refreshDL01() {
        try {
            int a = demiLinije.getJkkf01().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelDL1JKKFRegVentil01, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelDL1JKKFRegVentil01Vrednost.setText(ShiftPoint.shiftonePoint(a, demiLinije.getJkkf01().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
        img.setImgHorizontalno(jLabelDL01JKKFventil03, demiLinije.getJkkf01().getVent03());
        img.setImgHorizontalno(jLabelDL01JKKFventil04, demiLinije.getJkkf01().getVent04());
        img.setImgVertikalno(jLabelDL01JKKFventil05, demiLinije.getJkkf01().getVent05());
        img.setImgHorizontalno(jLabelDL01JKKFventil06, demiLinije.getJkkf01().getVent06());
        img.setImgHorizontalno(jLabelDL01JKKFventil07, demiLinije.getJkkf01().getVent07());
        img.setImgHorizontalno(jLabelDL01JKKFventil08, demiLinije.getJkkf01().getVent08());
        img.setImgVertikalno(jLabelDL01JKKFventil09, demiLinije.getJkkf01().getVent09());
        img.setImgHorizontalno(jLabelDL01JKKFventil10, demiLinije.getJkkf01().getVent10());
        img.setImgHorizontalno(jLabelDL01JKKFventil11, demiLinije.getJkkf01().getVent11());
        img.setImgVertikalno(jLabelDL01JKKFventil12, demiLinije.getJkkf01().getVent12());

        img.setImgHorizontalno(jLabelDL01SBAFventil01, demiLinije.getSbaf01().getVent01());
        img.setImgHorizontalno(jLabelDL01SBAFventil02, demiLinije.getSbaf01().getVent02());
        img.setImgHorizontalno(jLabelDL01SBAFventil03, demiLinije.getSbaf01().getVent03());
        img.setImgHorizontalno(jLabelDL01SBAFventil04, demiLinije.getSbaf01().getVent04());
        img.setImgHorizontalno(jLabelDL01SBAFventil05, demiLinije.getSbaf01().getVent05());
        img.setImgVertikalno(jLabelDL01SBAFventil06, demiLinije.getSbaf01().getVent06());

        img.setImgHorizontalno(jLabelDL01JBAFventil01, demiLinije.getJbaf01().getVent01());
        img.setImgHorizontalno(jLabelDL01JBAFventil02, demiLinije.getJbaf01().getVent02());
        img.setImgHorizontalno(jLabelDL01JBAFventil03, demiLinije.getJbaf01().getVent03());
        img.setImgHorizontalno(jLabelDL01JBAFventil04, demiLinije.getJbaf01().getVent04());
        img.setImgHorizontalno(jLabelDL01JBAFventil05, demiLinije.getJbaf01().getVent05());
        img.setImgHorizontalno(jLabelDL01JBAFventil06, demiLinije.getJbaf01().getVent06());
        img.setImgHorizontalno(jLabelDL01JBAFventil07, demiLinije.getJbaf01().getVent07());
        img.setImgVertikalno(jLabelDL01JBAFventil08, demiLinije.getJbaf01().getVent08());

        img.setImgHorizontalno(jLabelDL01MFventil01, demiLinije.getMf01().getVent01());
        img.setImgHorizontalno(jLabelDL01MFventil02, demiLinije.getMf01().getVent02());
        img.setImgHorizontalno(jLabelDL01MFventil03, demiLinije.getMf01().getVent03());
        img.setImgHorizontalno(jLabelDL01MFventil04, demiLinije.getMf01().getVent04());
        img.setImgHorizontalno(jLabelDL01MFventil05, demiLinije.getMf01().getVent05());
        img.setImgHorizontalno(jLabelDL01MFventil06, demiLinije.getMf01().getVent06());
        img.setImgVertikalno(jLabelDL01MFventil07, demiLinije.getMf01().getVent07());
        img.setImgHorizontalno(jLabelDL01MFventil08, demiLinije.getMf01().getVent08());
        img.setImgHorizontalno(jLabelDL01MFventil10, demiLinije.getMf01().getVent10());
        img.setImgVertikalno(jLabelDL01MFventil11, demiLinije.getMf01().getVent11());
    }

   

    
    

    private void refreshBazeniMerenja() {
        int a = bazeniMerenja.getBazenDekaFiltriraneVode().getVrednostRegistra();
        jLabelNivoBazenDekaFiltriraneVodeCopyDL01.setText("L= " + Integer.toString(a) + " cm");
        jProgressBarDekaFiltriranaVodaCopyDL01.setValue(a);

        int d = bazeniMerenja.getBazenNeutralizacioni().getVrednostRegistra();
        jProgressBarNeutralizacioniBazenCopyDL01.setValue(d);
        jLabelNivoNeutralizacioniCopyDL01.setText("L= " + Integer.toString(d) + " cm");
    }

    

    private void refreshProtoci() {
        
       
        jLabelProtokDemiLinijaInBr1.setText(Integer.toString(protociDemiLinije.getProtokDL1in().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoInDL1.setText(Convert.getRoundDouble(protociDemiLinije.getProtokDL1in().getKumulativnoRucno(), 2)+ " m3");
                        
        jLabelProtokDemiLinijaOutBr1.setText(Integer.toString(protociDemiLinije.getProtokDL1out().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoOutDL1.setText(Convert.getRoundDouble(protociDemiLinije.getProtokDL1out().getKumulativnoRucno(), 2)+ " m3");
        
        
        jLabelProtokDemiLinijaMagistrala1.setText(Integer.toString(protociDemiLinije.getProtokMagistralniVod().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelKumulativnoDemiLinijaMagistrala1.setText(Convert.intToLong(protociDemiLinije.getProtokMagistralniVod().getKumulativnoVisiVrednost(), protociDemiLinije.getProtokMagistralniVod().getKumulativnoNiziVrednost()));            
        
    }

    private void refreshPumpeFiltriraneVodeKaDemineralizaciji() {
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr1CopyDL1, pumpeDekaFiltriranaKaDemi.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr2CopyDL1, pumpeDekaFiltriranaKaDemi.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr3CopyDL1, pumpeDekaFiltriranaKaDemi.getPumpaBr3().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr4CopyDL1, pumpeDekaFiltriranaKaDemi.getPumpaBr4().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaDekaFiltrKaDeminerBr5CopyDL1, pumpeDekaFiltriranaKaDemi.getPumpaBr5().getVrednosti().isUkljucen());
    }

    
   
    private void refreshPumpeNeutralizacionogBazena() {
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr1CopyDL1, pumpeNeutralizacionogBazena.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaNeutralizacioniBazenBr2CopyDL1, pumpeNeutralizacionogBazena.getPumpaBr2().getVrednosti().isUkljucen());
    }



    private void refreshRezervoariMerenja() {
        int a = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br1().getVrednostRegistra();
        jProgressBarDemiRezervoarBr1CopyDL1.setValue(a);
        jLabelDemiRezervoarBr1CopyDL1.setText("L= " + Integer.toString(a) + " cm");

        int b = rezervoariMerenja.getNivoRezervoarDEMIvode1000m3br2().getVrednostRegistra();
        jProgressBarDemiRezervoarBr2CopyDL1.setValue(a);
        jLabelDemiRezervoarBr2CopyDL1.setText("L= " + Integer.toString(b) + " cm");

        int c = rezervoariMerenja.getNivoRezervoarDEMIvode150m3().getVrednostRegistra();
        jProgressBarDemiRezervoar150mCopyDL1.setValue(c);
        jLabelDemiRezervoar150mCopyDL1.setText("L= " + Integer.toString(c) + " cm");

    }

}
