/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import tools.ShiftPoint;
import up.StartApp;
import virtual.doziranje.Doziranje;

/**
 *
 * @author branko.scekic
 */
public class DoziranjeFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DoziranjeFrame
     * @param doziranje
     * @param img
     */
    public DoziranjeFrame(Doziranje doziranje, Img img) {
        initComponents();
        
        this.doziranje = doziranje;
        this.img = img;
        
        screenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel27 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabelIzabraniReaktorBr1 = new javax.swing.JLabel();
        jLabelIzabraniReaktorBr2 = new javax.swing.JLabel();
        jLabelIzabranaPumpaFeClBr1 = new javax.swing.JLabel();
        jLabelIzabranaPumpaFeClBr2 = new javax.swing.JLabel();
        jLabelIzabranaPumpaFeClBr3 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabelRezervnaPumpaFeClBr1 = new javax.swing.JLabel();
        jLabelRezervnaPumpaFeClBr2 = new javax.swing.JLabel();
        jLabelRezervnaPumpaFeClBr3 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabelIzabranaPumpaPE1 = new javax.swing.JLabel();
        jLabelIzabranaPumpaPE2 = new javax.swing.JLabel();
        jLabelIzabranaPumpaPE3 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabelIRezervnaPumpaPE1 = new javax.swing.JLabel();
        jLabelIRezervnaPumpaPE2 = new javax.swing.JLabel();
        jLabelIRezervnaPumpaPE3 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabelIzabraniSilosKrecaBr1 = new javax.swing.JLabel();
        jLabelIzabraniSilosKrecaBr2 = new javax.swing.JLabel();
        jLabelKrecEMV1 = new javax.swing.JLabel();
        jLabelKrecRastresanje1 = new javax.swing.JLabel();
        jLabelKrecMesalica1 = new javax.swing.JLabel();
        jLabelKrecEMV2 = new javax.swing.JLabel();
        jLabelKrecRastresanje2 = new javax.swing.JLabel();
        jLabelKrecMesalica2 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabelKrecEMVVremeRada = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabelKrecEMVVremePauza = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabelNapajanjeFeClPumpaBr1 = new javax.swing.JLabel();
        jLabelNapajanjeFeClPumpaBr2 = new javax.swing.JLabel();
        jLabelNapajanjeFeClPumpaBr3 = new javax.swing.JLabel();
        jLabelNapajanjePEPumpe = new javax.swing.JLabel();
        jLabelSuviKrecniDozatorBr1 = new javax.swing.JLabel();
        jLabelSuviKrecniDozatorBr2 = new javax.swing.JLabel();
        jLabelAutomatskoDoziranje = new javax.swing.JLabel();

        jPanel27.setBackground(java.awt.SystemColor.activeCaption);
        jPanel27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Izabrani reaktor:");

        jLabel32.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel32.setText("Izabrana pumpa FeCl:");

        jLabelIzabraniReaktorBr1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelIzabraniReaktorBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabraniReaktorBr1.setText("Reaktor br. 1");
        jLabelIzabraniReaktorBr1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelIzabraniReaktorBr1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabraniReaktorBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabraniReaktorBr1MouseClicked(evt);
            }
        });

        jLabelIzabraniReaktorBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabraniReaktorBr2.setText("Reaktor br. 2");
        jLabelIzabraniReaktorBr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabraniReaktorBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabraniReaktorBr2MouseClicked(evt);
            }
        });

        jLabelIzabranaPumpaFeClBr1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIzabranaPumpaFeClBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabranaPumpaFeClBr1.setText("FeCl pumpa br. 1");
        jLabelIzabranaPumpaFeClBr1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabranaPumpaFeClBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabranaPumpaFeClBr1MouseClicked(evt);
            }
        });

        jLabelIzabranaPumpaFeClBr2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIzabranaPumpaFeClBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabranaPumpaFeClBr2.setText("FeCl pumpa br. 2");
        jLabelIzabranaPumpaFeClBr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabranaPumpaFeClBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabranaPumpaFeClBr2MouseClicked(evt);
            }
        });

        jLabelIzabranaPumpaFeClBr3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIzabranaPumpaFeClBr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabranaPumpaFeClBr3.setText("FeCl pumpa br. 3");
        jLabelIzabranaPumpaFeClBr3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabranaPumpaFeClBr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabranaPumpaFeClBr3MouseClicked(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel38.setText("Rezervna pumpa FeCl:");

        jLabelRezervnaPumpaFeClBr1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelRezervnaPumpaFeClBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelRezervnaPumpaFeClBr1.setText("FeCl pumpa br. 1");
        jLabelRezervnaPumpaFeClBr1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRezervnaPumpaFeClBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRezervnaPumpaFeClBr1MouseClicked(evt);
            }
        });

        jLabelRezervnaPumpaFeClBr2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelRezervnaPumpaFeClBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelRezervnaPumpaFeClBr2.setText("FeCl pumpa br. 2");
        jLabelRezervnaPumpaFeClBr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRezervnaPumpaFeClBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRezervnaPumpaFeClBr2MouseClicked(evt);
            }
        });

        jLabelRezervnaPumpaFeClBr3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelRezervnaPumpaFeClBr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelRezervnaPumpaFeClBr3.setText("FeCl pumpa br. 3");
        jLabelRezervnaPumpaFeClBr3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelRezervnaPumpaFeClBr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRezervnaPumpaFeClBr3MouseClicked(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel42.setText("Izabrana pumpa PE:");

        jLabelIzabranaPumpaPE1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIzabranaPumpaPE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabranaPumpaPE1.setText("PE pumpa br. 1");
        jLabelIzabranaPumpaPE1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabranaPumpaPE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabranaPumpaPE1MouseClicked(evt);
            }
        });

        jLabelIzabranaPumpaPE2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIzabranaPumpaPE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabranaPumpaPE2.setText("PE pumpa br. 2");
        jLabelIzabranaPumpaPE2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabranaPumpaPE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabranaPumpaPE2MouseClicked(evt);
            }
        });

        jLabelIzabranaPumpaPE3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIzabranaPumpaPE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabranaPumpaPE3.setText("PE pumpa br. 3");
        jLabelIzabranaPumpaPE3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabranaPumpaPE3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabranaPumpaPE3MouseClicked(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel46.setText("Rezervna pumpa PE:");

        jLabelIRezervnaPumpaPE1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIRezervnaPumpaPE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIRezervnaPumpaPE1.setText("PE pumpa br. 1");
        jLabelIRezervnaPumpaPE1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIRezervnaPumpaPE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIRezervnaPumpaPE1MouseClicked(evt);
            }
        });

        jLabelIRezervnaPumpaPE2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIRezervnaPumpaPE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIRezervnaPumpaPE2.setText("PE pumpa br. 2");
        jLabelIRezervnaPumpaPE2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIRezervnaPumpaPE2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIRezervnaPumpaPE2MouseClicked(evt);
            }
        });

        jLabelIRezervnaPumpaPE3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIRezervnaPumpaPE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIRezervnaPumpaPE3.setText("PE pumpa br. 3");
        jLabelIRezervnaPumpaPE3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIRezervnaPumpaPE3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIRezervnaPumpaPE3MouseClicked(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel43.setText("Izabrani silos kreča:");

        jLabelIzabraniSilosKrecaBr1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIzabraniSilosKrecaBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabraniSilosKrecaBr1.setText("Silos br. 1");
        jLabelIzabraniSilosKrecaBr1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabraniSilosKrecaBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabraniSilosKrecaBr1MouseClicked(evt);
            }
        });

        jLabelIzabraniSilosKrecaBr2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelIzabraniSilosKrecaBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelIzabraniSilosKrecaBr2.setText("Silos br. 2");
        jLabelIzabraniSilosKrecaBr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelIzabraniSilosKrecaBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIzabraniSilosKrecaBr2MouseClicked(evt);
            }
        });

        jLabelKrecEMV1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKrecEMV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelKrecEMV1.setText("EMV");
        jLabelKrecEMV1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelKrecEMV1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKrecEMV1MouseClicked(evt);
            }
        });

        jLabelKrecRastresanje1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKrecRastresanje1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelKrecRastresanje1.setText("Rastresanje");
        jLabelKrecRastresanje1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelKrecRastresanje1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKrecRastresanje1MouseClicked(evt);
            }
        });

        jLabelKrecMesalica1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKrecMesalica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelKrecMesalica1.setText("Mešalica");
        jLabelKrecMesalica1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelKrecMesalica1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKrecMesalica1MouseClicked(evt);
            }
        });

        jLabelKrecEMV2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKrecEMV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelKrecEMV2.setText("EMV");
        jLabelKrecEMV2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelKrecEMV2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKrecEMV2MouseClicked(evt);
            }
        });

        jLabelKrecRastresanje2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKrecRastresanje2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelKrecRastresanje2.setText("Rastresanje");
        jLabelKrecRastresanje2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelKrecRastresanje2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKrecRastresanje2MouseClicked(evt);
            }
        });

        jLabelKrecMesalica2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKrecMesalica2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelKrecMesalica2.setText("Mešalica");
        jLabelKrecMesalica2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelKrecMesalica2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelKrecMesalica2MouseClicked(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel47.setText("Silos kreča br. 1");

        jLabel48.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel48.setText("Silos kreča br. 2");

        jLabel49.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel49.setText("Produvavanje EMV:");

        jLabelKrecEMVVremeRada.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKrecEMVVremeRada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKrecEMVVremeRada.setText("00.0");

        jLabel50.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel50.setText("Rad:");

        jLabel51.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel51.setText("Pauza:");

        jLabelKrecEMVVremePauza.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKrecEMVVremePauza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKrecEMVVremePauza.setText("000.0");

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Napajanje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 24))); // NOI18N

        jLabelNapajanjeFeClPumpaBr1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNapajanjeFeClPumpaBr1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNapajanjeFeClPumpaBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelNapajanjeFeClPumpaBr1.setText("FeCl pumpa br. 1");
        jLabelNapajanjeFeClPumpaBr1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelNapajanjeFeClPumpaBr1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNapajanjeFeClPumpaBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNapajanjeFeClPumpaBr1MouseClicked(evt);
            }
        });

        jLabelNapajanjeFeClPumpaBr2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNapajanjeFeClPumpaBr2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNapajanjeFeClPumpaBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelNapajanjeFeClPumpaBr2.setText("FeCl pumpa br. 2");
        jLabelNapajanjeFeClPumpaBr2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelNapajanjeFeClPumpaBr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNapajanjeFeClPumpaBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNapajanjeFeClPumpaBr2MouseClicked(evt);
            }
        });

        jLabelNapajanjeFeClPumpaBr3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNapajanjeFeClPumpaBr3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNapajanjeFeClPumpaBr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelNapajanjeFeClPumpaBr3.setText("FeCl pumpa br. 3");
        jLabelNapajanjeFeClPumpaBr3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelNapajanjeFeClPumpaBr3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNapajanjeFeClPumpaBr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNapajanjeFeClPumpaBr3MouseClicked(evt);
            }
        });

        jLabelNapajanjePEPumpe.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNapajanjePEPumpe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNapajanjePEPumpe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelNapajanjePEPumpe.setText("PE pumpe");
        jLabelNapajanjePEPumpe.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelNapajanjePEPumpe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNapajanjePEPumpe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNapajanjePEPumpeMouseClicked(evt);
            }
        });

        jLabelSuviKrecniDozatorBr1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelSuviKrecniDozatorBr1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSuviKrecniDozatorBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelSuviKrecniDozatorBr1.setText("Suvi krečni dozator br. 1");
        jLabelSuviKrecniDozatorBr1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelSuviKrecniDozatorBr1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSuviKrecniDozatorBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSuviKrecniDozatorBr1MouseClicked(evt);
            }
        });

        jLabelSuviKrecniDozatorBr2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelSuviKrecniDozatorBr2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSuviKrecniDozatorBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelSuviKrecniDozatorBr2.setText("Suvi krečni dozator br. 2");
        jLabelSuviKrecniDozatorBr2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelSuviKrecniDozatorBr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelSuviKrecniDozatorBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSuviKrecniDozatorBr2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNapajanjeFeClPumpaBr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNapajanjeFeClPumpaBr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNapajanjeFeClPumpaBr3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(jLabelNapajanjePEPumpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSuviKrecniDozatorBr1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSuviKrecniDozatorBr2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNapajanjeFeClPumpaBr1)
                    .addComponent(jLabelNapajanjeFeClPumpaBr2)
                    .addComponent(jLabelNapajanjeFeClPumpaBr3)
                    .addComponent(jLabelNapajanjePEPumpe)
                    .addComponent(jLabelSuviKrecniDozatorBr1)
                    .addComponent(jLabelSuviKrecniDozatorBr2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jLabelIzabraniReaktorBr2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIzabraniReaktorBr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIzabranaPumpaFeClBr3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIzabranaPumpaFeClBr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRezervnaPumpaFeClBr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIzabranaPumpaFeClBr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRezervnaPumpaFeClBr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRezervnaPumpaFeClBr3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIzabranaPumpaPE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIzabranaPumpaPE3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIzabranaPumpaPE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIRezervnaPumpaPE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIRezervnaPumpaPE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIRezervnaPumpaPE3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKrecEMV1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelIzabraniSilosKrecaBr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelKrecRastresanje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelKrecMesalica1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelIzabraniSilosKrecaBr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelKrecEMV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelKrecRastresanje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelKrecMesalica2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel27Layout.createSequentialGroup()
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelKrecEMVVremeRada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel27Layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelKrecEMVVremePauza, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIzabraniReaktorBr1)
                            .addComponent(jLabelIzabranaPumpaFeClBr1)
                            .addComponent(jLabelIzabranaPumpaPE1))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIzabraniReaktorBr2)
                            .addComponent(jLabelIzabranaPumpaFeClBr2)
                            .addComponent(jLabelIzabranaPumpaPE2)))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIzabraniSilosKrecaBr1)
                            .addComponent(jLabelKrecEMVVremeRada)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIzabraniSilosKrecaBr2)
                            .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelKrecEMVVremePauza)
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIzabranaPumpaFeClBr3)
                    .addComponent(jLabelIzabranaPumpaPE3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRezervnaPumpaFeClBr1)
                            .addComponent(jLabelIRezervnaPumpaPE1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRezervnaPumpaFeClBr2)
                            .addComponent(jLabelIRezervnaPumpaPE2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRezervnaPumpaFeClBr3)
                            .addComponent(jLabelIRezervnaPumpaPE3)))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jLabelKrecEMV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKrecRastresanje1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKrecMesalica1))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addComponent(jLabelKrecEMV2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKrecRastresanje2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKrecMesalica2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelAutomatskoDoziranje.setBackground(new java.awt.Color(102, 102, 102));
        jLabelAutomatskoDoziranje.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabelAutomatskoDoziranje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAutomatskoDoziranje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.doziranje/Off.png"))); // NOI18N
        jLabelAutomatskoDoziranje.setText("Automatsko doziranje u reaktore");
        jLabelAutomatskoDoziranje.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelAutomatskoDoziranje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAutomatskoDoziranje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAutomatskoDoziranjeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAutomatskoDoziranje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAutomatskoDoziranje, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(170, 35, 1642, 923);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelIzabraniReaktorBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabraniReaktorBr1MouseClicked
        doziranje(doziranje.getIzabraniReaktor(), false);
    }//GEN-LAST:event_jLabelIzabraniReaktorBr1MouseClicked

    private void jLabelIzabraniReaktorBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabraniReaktorBr2MouseClicked
        doziranje(doziranje.getIzabraniReaktor(), true);
    }//GEN-LAST:event_jLabelIzabraniReaktorBr2MouseClicked

    private void jLabelIzabranaPumpaFeClBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabranaPumpaFeClBr1MouseClicked
        doziranjeRegistri(doziranje.getIzabranaPumpaFCL(), 0);
    }//GEN-LAST:event_jLabelIzabranaPumpaFeClBr1MouseClicked

    private void jLabelIzabranaPumpaFeClBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabranaPumpaFeClBr2MouseClicked
        doziranjeRegistri(doziranje.getIzabranaPumpaFCL(), 1);
    }//GEN-LAST:event_jLabelIzabranaPumpaFeClBr2MouseClicked

    private void jLabelIzabranaPumpaFeClBr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabranaPumpaFeClBr3MouseClicked
        doziranjeRegistri(doziranje.getIzabranaPumpaFCL(), 2);
    }//GEN-LAST:event_jLabelIzabranaPumpaFeClBr3MouseClicked

    private void jLabelRezervnaPumpaFeClBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRezervnaPumpaFeClBr1MouseClicked
        doziranjeRegistri(doziranje.getRezervnaPumpaFCL(), 0);
    }//GEN-LAST:event_jLabelRezervnaPumpaFeClBr1MouseClicked

    private void jLabelRezervnaPumpaFeClBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRezervnaPumpaFeClBr2MouseClicked
        doziranjeRegistri(doziranje.getRezervnaPumpaFCL(), 1);
    }//GEN-LAST:event_jLabelRezervnaPumpaFeClBr2MouseClicked

    private void jLabelRezervnaPumpaFeClBr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRezervnaPumpaFeClBr3MouseClicked
        doziranjeRegistri(doziranje.getRezervnaPumpaFCL(), 2);
    }//GEN-LAST:event_jLabelRezervnaPumpaFeClBr3MouseClicked

    private void jLabelIzabranaPumpaPE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabranaPumpaPE1MouseClicked
        doziranjeRegistri(doziranje.getIzabranaPumpaPE(), 0);
    }//GEN-LAST:event_jLabelIzabranaPumpaPE1MouseClicked

    private void jLabelIzabranaPumpaPE2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabranaPumpaPE2MouseClicked
        doziranjeRegistri(doziranje.getIzabranaPumpaPE(), 1);
    }//GEN-LAST:event_jLabelIzabranaPumpaPE2MouseClicked

    private void jLabelIzabranaPumpaPE3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabranaPumpaPE3MouseClicked
        doziranjeRegistri(doziranje.getIzabranaPumpaPE(), 2);
    }//GEN-LAST:event_jLabelIzabranaPumpaPE3MouseClicked

    private void jLabelIRezervnaPumpaPE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIRezervnaPumpaPE1MouseClicked
        doziranjeRegistri(doziranje.getRezervnaPumpaPE(), 0);
    }//GEN-LAST:event_jLabelIRezervnaPumpaPE1MouseClicked

    private void jLabelIRezervnaPumpaPE2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIRezervnaPumpaPE2MouseClicked
        doziranjeRegistri(doziranje.getRezervnaPumpaPE(), 1);
    }//GEN-LAST:event_jLabelIRezervnaPumpaPE2MouseClicked

    private void jLabelIRezervnaPumpaPE3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIRezervnaPumpaPE3MouseClicked
        doziranjeRegistri(doziranje.getRezervnaPumpaPE(), 2);
    }//GEN-LAST:event_jLabelIRezervnaPumpaPE3MouseClicked

    private void jLabelIzabraniSilosKrecaBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabraniSilosKrecaBr1MouseClicked
        doziranje(doziranje.getIzabraniSilosKreca(), false);
    }//GEN-LAST:event_jLabelIzabraniSilosKrecaBr1MouseClicked

    private void jLabelIzabraniSilosKrecaBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIzabraniSilosKrecaBr2MouseClicked
        doziranje(doziranje.getIzabraniSilosKreca(), true);
    }//GEN-LAST:event_jLabelIzabraniSilosKrecaBr2MouseClicked

    private void jLabelKrecEMV1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKrecEMV1MouseClicked
        doziranje(doziranje.getSilos1EMV(), !doziranje.getVrednostRegistra().getSilos1EMV());
    }//GEN-LAST:event_jLabelKrecEMV1MouseClicked

    private void jLabelKrecRastresanje1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKrecRastresanje1MouseClicked
        doziranje(doziranje.getKrecSilos1Rastresac(), !doziranje.getVrednostRegistra().getKrecSilos1Rastresac());
    }//GEN-LAST:event_jLabelKrecRastresanje1MouseClicked

    private void jLabelKrecMesalica1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKrecMesalica1MouseClicked
        doziranje(doziranje.getKrecSilos1Mesalica(), !doziranje.getVrednostRegistra().getKrecSilos1Mesalica());
    }//GEN-LAST:event_jLabelKrecMesalica1MouseClicked

    private void jLabelKrecEMV2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKrecEMV2MouseClicked
        doziranje(doziranje.getSilos2EMV(), !doziranje.getVrednostRegistra().getSilos2EMV());
    }//GEN-LAST:event_jLabelKrecEMV2MouseClicked

    private void jLabelKrecRastresanje2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKrecRastresanje2MouseClicked
        doziranje(doziranje.getKrecSilos2Rastresac(), !doziranje.getVrednostRegistra().getKrecSilos2Rastresac());
    }//GEN-LAST:event_jLabelKrecRastresanje2MouseClicked

    private void jLabelKrecMesalica2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelKrecMesalica2MouseClicked
        doziranje(doziranje.getKrecSilos2Mesalica(), !doziranje.getVrednostRegistra().getKrecSilos2Mesalica());
    }//GEN-LAST:event_jLabelKrecMesalica2MouseClicked

    private void jLabelNapajanjeFeClPumpaBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNapajanjeFeClPumpaBr1MouseClicked
        doziranje(doziranje.getNapajanjeFeClPumbaBr1(), !doziranje.getVrednostRegistra().getNapajanjeFeClPumbaBr1());
    }//GEN-LAST:event_jLabelNapajanjeFeClPumpaBr1MouseClicked

    private void jLabelNapajanjeFeClPumpaBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNapajanjeFeClPumpaBr2MouseClicked
        doziranje(doziranje.getNapajanjeFeClPumbaBr2(), !doziranje.getVrednostRegistra().getNapajanjeFeClPumbaBr2());
    }//GEN-LAST:event_jLabelNapajanjeFeClPumpaBr2MouseClicked

    private void jLabelNapajanjeFeClPumpaBr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNapajanjeFeClPumpaBr3MouseClicked
        doziranje(doziranje.getNapajanjeFeClPumbaBr3(), !doziranje.getVrednostRegistra().getNapajanjeFeClPumbaBr3());
    }//GEN-LAST:event_jLabelNapajanjeFeClPumpaBr3MouseClicked

    private void jLabelNapajanjePEPumpeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNapajanjePEPumpeMouseClicked
        doziranje(doziranje.getNapajanjePEPumpe(), !doziranje.getVrednostRegistra().getNapajanjePEPumpe());
    }//GEN-LAST:event_jLabelNapajanjePEPumpeMouseClicked

    private void jLabelSuviKrecniDozatorBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSuviKrecniDozatorBr1MouseClicked
        doziranje(doziranje.getSuviKrecniDozatorBr1(), !doziranje.getVrednostRegistra().getSuviKrecniDozatorBr1());
    }//GEN-LAST:event_jLabelSuviKrecniDozatorBr1MouseClicked

    private void jLabelSuviKrecniDozatorBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSuviKrecniDozatorBr2MouseClicked
        doziranje(doziranje.getSuviKrecniDozatorBr2(), !doziranje.getVrednostRegistra().getSuviKrecniDozatorBr2());
    }//GEN-LAST:event_jLabelSuviKrecniDozatorBr2MouseClicked

    private void jLabelAutomatskoDoziranjeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAutomatskoDoziranjeMouseClicked
        doziranje(doziranje.getAutomatskoDoziranje(), !doziranje.getVrednostRegistra().getAutomatskoDoziranje());
    }//GEN-LAST:event_jLabelAutomatskoDoziranjeMouseClicked

    //Doziranje
    private void doziranje(int adr, boolean turnOnOff) {
        StartApp.comm.offset = adr;
        StartApp.comm.mxValue = turnOnOff;
        StartApp.comm.writeDigital = true;
    }
    
    private void doziranjeRegistri(int adr, int vrednost) {
        StartApp.comm.offset = adr;
        StartApp.comm.registerValue = vrednost;
        StartApp.comm.writeRegister = true;
    }
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabelAutomatskoDoziranje;
    private javax.swing.JLabel jLabelIRezervnaPumpaPE1;
    private javax.swing.JLabel jLabelIRezervnaPumpaPE2;
    private javax.swing.JLabel jLabelIRezervnaPumpaPE3;
    private javax.swing.JLabel jLabelIzabranaPumpaFeClBr1;
    private javax.swing.JLabel jLabelIzabranaPumpaFeClBr2;
    private javax.swing.JLabel jLabelIzabranaPumpaFeClBr3;
    private javax.swing.JLabel jLabelIzabranaPumpaPE1;
    private javax.swing.JLabel jLabelIzabranaPumpaPE2;
    private javax.swing.JLabel jLabelIzabranaPumpaPE3;
    private javax.swing.JLabel jLabelIzabraniReaktorBr1;
    private javax.swing.JLabel jLabelIzabraniReaktorBr2;
    private javax.swing.JLabel jLabelIzabraniSilosKrecaBr1;
    private javax.swing.JLabel jLabelIzabraniSilosKrecaBr2;
    private javax.swing.JLabel jLabelKrecEMV1;
    private javax.swing.JLabel jLabelKrecEMV2;
    private javax.swing.JLabel jLabelKrecEMVVremePauza;
    private javax.swing.JLabel jLabelKrecEMVVremeRada;
    private javax.swing.JLabel jLabelKrecMesalica1;
    private javax.swing.JLabel jLabelKrecMesalica2;
    private javax.swing.JLabel jLabelKrecRastresanje1;
    private javax.swing.JLabel jLabelKrecRastresanje2;
    private javax.swing.JLabel jLabelNapajanjeFeClPumpaBr1;
    private javax.swing.JLabel jLabelNapajanjeFeClPumpaBr2;
    private javax.swing.JLabel jLabelNapajanjeFeClPumpaBr3;
    private javax.swing.JLabel jLabelNapajanjePEPumpe;
    private javax.swing.JLabel jLabelRezervnaPumpaFeClBr1;
    private javax.swing.JLabel jLabelRezervnaPumpaFeClBr2;
    private javax.swing.JLabel jLabelRezervnaPumpaFeClBr3;
    private javax.swing.JLabel jLabelSuviKrecniDozatorBr1;
    private javax.swing.JLabel jLabelSuviKrecniDozatorBr2;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel30;
    // End of variables declaration//GEN-END:variables
    private final Doziranje doziranje;
    public Timer timer;
    private Img img;
    
    
    
    public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                //Date date = new Date();
               
               
                refreshDoziranje();
               

                //System.out.println(date.getTime());
                //System.out.println("_____________");
            }
        });
    }

    



    private void refreshDoziranje() {
        boolean izabraniReaktor = doziranje.getVrednostRegistra().getIzabraniReaktorVrednost();
        boolean izabraniSilosKreca = doziranje.getVrednostRegistra().getIzabraniSilosKrecaVrednost();
        int izabranaFeCl = doziranje.getVrednostRegistra().getIzabranaPumpaFCLVrednost();
        int rezervnaFeCl = doziranje.getVrednostRegistra().getRezervnaPumpaFCLVrednost();
        int izabranaPE = doziranje.getVrednostRegistra().getIzabranaPumpaPEVrednost();
        int rezervnaPE = doziranje.getVrednostRegistra().getRezervnaPumpaPEVrednost();

        img.setSelectedIcon(jLabelAutomatskoDoziranje, doziranje.getVrednostRegistra().getAutomatskoDoziranje());
        img.setSelectedIcon(jLabelNapajanjeFeClPumpaBr1, doziranje.getVrednostRegistra().getNapajanjeFeClPumbaBr1());
        img.setSelectedIcon(jLabelNapajanjeFeClPumpaBr2, doziranje.getVrednostRegistra().getNapajanjeFeClPumbaBr2());
        img.setSelectedIcon(jLabelNapajanjeFeClPumpaBr3, doziranje.getVrednostRegistra().getNapajanjeFeClPumbaBr3());
        img.setSelectedIcon(jLabelNapajanjePEPumpe, doziranje.getVrednostRegistra().getNapajanjePEPumpe());
        img.setSelectedIcon(jLabelSuviKrecniDozatorBr1, doziranje.getVrednostRegistra().getSuviKrecniDozatorBr1());
        img.setSelectedIcon(jLabelSuviKrecniDozatorBr2, doziranje.getVrednostRegistra().getSuviKrecniDozatorBr2());

        img.setSelectedIcon(jLabelIzabraniReaktorBr1, izabraniReaktor, 0);
        img.setSelectedIcon(jLabelIzabraniReaktorBr2, izabraniReaktor, 1);

        img.setSelectedIcon(jLabelIzabraniSilosKrecaBr1, izabraniSilosKreca, 0);
        img.setSelectedIcon(jLabelIzabraniSilosKrecaBr2, izabraniSilosKreca, 1);

        img.setSelectedIcon(jLabelIzabranaPumpaFeClBr1, izabranaFeCl, 0);
        img.setSelectedIcon(jLabelIzabranaPumpaFeClBr2, izabranaFeCl, 1);
        img.setSelectedIcon(jLabelIzabranaPumpaFeClBr3, izabranaFeCl, 2);

        img.setSelectedIcon(jLabelRezervnaPumpaFeClBr1, rezervnaFeCl, 0);
        img.setSelectedIcon(jLabelRezervnaPumpaFeClBr2, rezervnaFeCl, 1);
        img.setSelectedIcon(jLabelRezervnaPumpaFeClBr3, rezervnaFeCl, 2);

        img.setSelectedIcon(jLabelIzabranaPumpaPE1, izabranaPE, 0);
        img.setSelectedIcon(jLabelIzabranaPumpaPE2, izabranaPE, 1);
        img.setSelectedIcon(jLabelIzabranaPumpaPE3, izabranaPE, 2);

        img.setSelectedIcon(jLabelIRezervnaPumpaPE1, rezervnaPE, 0);
        img.setSelectedIcon(jLabelIRezervnaPumpaPE2, rezervnaPE, 1);
        img.setSelectedIcon(jLabelIRezervnaPumpaPE3, rezervnaPE, 2);

        jLabelKrecEMVVremeRada.setText(ShiftPoint.shiftonePoint(doziranje.getVrednostRegistra().getProduvavanjeRad(), 1));
        jLabelKrecEMVVremePauza.setText(ShiftPoint.shiftonePoint(doziranje.getVrednostRegistra().getProduvavanjePauza(), 1));

        img.setSelectedIcon(jLabelKrecEMV1, doziranje.getVrednostRegistra().getSilos1EMV());
        img.setSelectedIcon(jLabelKrecRastresanje1, doziranje.getVrednostRegistra().getKrecSilos1Rastresac());
        img.setSelectedIcon(jLabelKrecMesalica1, doziranje.getVrednostRegistra().getKrecSilos1Mesalica());
        img.setSelectedIcon(jLabelKrecEMV2, doziranje.getVrednostRegistra().getSilos2EMV());
        img.setSelectedIcon(jLabelKrecRastresanje2, doziranje.getVrednostRegistra().getKrecSilos2Rastresac());
        img.setSelectedIcon(jLabelKrecMesalica2, doziranje.getVrednostRegistra().getKrecSilos2Mesalica());
    }
}
