/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import field.merenja.bazeni.Nivoi;
import field.merenja.pescaniFilteri.PescaniFilterMerenjaKonstruktor;
import field.merenja.protoci.ProtociPescaniFilteri;
import field.pumpe.PumpeKaPescanimFilterima;
import field.pumpe.PumpeOdpadnihVodaOdPranjaPescanihFiltera;
import field.pumpe.PumpeZaPranjePescanihFiltera;
import field.ventili.PescaniFilteri;
import field.ventili.VentiliKaPescanimFilterima;
import field.ventili.pescaniFilter.OtpadneVodeOdPescanihFiltera;
import field.ventili.pescaniFilter.PranjePescanihFiltera;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import popup.AllPopUpWindow;
import tools.AnalogToDigital;
import static utilise.Convert.intToLong;
import tools.ShiftPoint;

/**
 *
 * @author branko.scekic
 */
public class FiltracijaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form FiltracijaFrame
     * @param ventiliKaPescanimFilterima
     * @param pumpeKaPescanimFilterima
     * @param pumpeOdpadnihVodaOdPranjaPescanihFiltera
     * @param pumpeZaPranjePescanihFiltera
     * @param otpadneVodeOdPescanihFiltera
     * @param protociPescaniFilteri
     * @param bazeniMerenja
     * @param pescaniFilteri
     * @param pfMerenja
     * @param pranjePescanihFiltera
     * @param img
     * @param allPopUpWindow
     */
    public FiltracijaFrame( VentiliKaPescanimFilterima ventiliKaPescanimFilterima,
                            PumpeKaPescanimFilterima pumpeKaPescanimFilterima,
                            PumpeOdpadnihVodaOdPranjaPescanihFiltera pumpeOdpadnihVodaOdPranjaPescanihFiltera,
                            PumpeZaPranjePescanihFiltera pumpeZaPranjePescanihFiltera,
                            OtpadneVodeOdPescanihFiltera otpadneVodeOdPescanihFiltera,
                            ProtociPescaniFilteri protociPescaniFilteri,
                            Nivoi bazeniMerenja,
                            PescaniFilteri pescaniFilteri,
                            PescaniFilterMerenjaKonstruktor pfMerenja,
                            PranjePescanihFiltera pranjePescanihFiltera,
                            Img img, AllPopUpWindow allPopUpWindow){
        initComponents();
        
        this.ventiliKaPescanimFilterima = ventiliKaPescanimFilterima;
        this.pumpeKaPescanimFilterima = pumpeKaPescanimFilterima;
        this.pumpeOdpadnihVodaOdPranjaPescanihFiltera = pumpeOdpadnihVodaOdPranjaPescanihFiltera;
        this.pumpeZaPranjePescanihFiltera = pumpeZaPranjePescanihFiltera;
        this.otpadneVodeOdPescanihFiltera = otpadneVodeOdPescanihFiltera;
        this.protociPescaniFilteri = protociPescaniFilteri;
        this.bazeniMerenja = bazeniMerenja;
        this.pescaniFilteri = pescaniFilteri;
        this.pfMerenja = pfMerenja;
        this.pranjePescanihFiltera = pranjePescanihFiltera;
        this.img = img;
        this.allPopUpWindow = allPopUpWindow;
        
        setMinMax();
        screenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPKPFbr1CopyPF = new javax.swing.JLabel();
        jLabelPKPFbr2CopyPF = new javax.swing.JLabel();
        jLabelPKPFbr3CopyPF = new javax.swing.JLabel();
        jLabelPKPFbr4CopyPF = new javax.swing.JLabel();
        jLabelPKPFbr5CopyPF = new javax.swing.JLabel();
        jLabelPKPFbr6CopyPF = new javax.swing.JLabel();
        jLabelPF6PritisakIn = new javax.swing.JLabel();
        jLabelPF5PritisakIn = new javax.swing.JLabel();
        jLabelPF4PritisakIn = new javax.swing.JLabel();
        jLabelPF3PritisakIn = new javax.swing.JLabel();
        jLabelPF2PritisakIn = new javax.swing.JLabel();
        jLabelPF1PritisakIn = new javax.swing.JLabel();
        jLabelPF6PritisakOut = new javax.swing.JLabel();
        jLabelPF5PritisakOut = new javax.swing.JLabel();
        jLabelPF4PritisakOut = new javax.swing.JLabel();
        jLabelPF3PritisakOut = new javax.swing.JLabel();
        jLabelPF2PritisakOut = new javax.swing.JLabel();
        jLabelPF1PritisakOut = new javax.swing.JLabel();
        jProgressBarDekaFiltriranaVoda = new javax.swing.JProgressBar();
        jProgressBarOtpadneOdPranjaPescani = new javax.swing.JProgressBar();
        jProgressBarDekaNefiltriraneVode = new javax.swing.JProgressBar();
        jLabelNivoBazenDekaFiltriraneVode = new javax.swing.JLabel();
        jLabelNivoOtpadneVodePranjePF = new javax.swing.JLabel();
        jLabelNivoDekaNefiltrirana = new javax.swing.JLabel();
        jLabelProtokPF6 = new javax.swing.JLabel();
        jLabelProtokPF5 = new javax.swing.JLabel();
        jLabelProtokPF4 = new javax.swing.JLabel();
        jLabelProtokPF3 = new javax.swing.JLabel();
        jLabelProtokPF2 = new javax.swing.JLabel();
        jLabelProtokPF1 = new javax.swing.JLabel();
        jLabelPF6RegVentil01CopyPF = new javax.swing.JLabel();
        jLabelPF6RegVentil01VrednostCopyPF = new javax.swing.JLabel();
        jLabelPF5RegVentil01CopyPF = new javax.swing.JLabel();
        jLabelPF5RegVentil01VrednostCopyPF = new javax.swing.JLabel();
        jLabelPF4RegVentil01CopyPF = new javax.swing.JLabel();
        jLabelPF4RegVentil01VrednostCopyPF = new javax.swing.JLabel();
        jLabelPF2RegVentil01CopyPF = new javax.swing.JLabel();
        jLabelPF2RegVentil01VrednostCopyPF = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr01 = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr2 = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr3 = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr4 = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr5 = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr6 = new javax.swing.JLabel();
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1 = new javax.swing.JLabel();
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2 = new javax.swing.JLabel();
        jLabelKumulativnoPF6 = new javax.swing.JLabel();
        jLabelKumulativnoPF2 = new javax.swing.JLabel();
        jLabelKumulativnoPF4 = new javax.swing.JLabel();
        jLabelKumulativnoPF5 = new javax.swing.JLabel();
        jLabelEventPF6 = new javax.swing.JLabel();
        jLabelEventPF5 = new javax.swing.JLabel();
        jLabelEventPF4 = new javax.swing.JLabel();
        jLabelEventPF3 = new javax.swing.JLabel();
        jLabelEventPF2 = new javax.swing.JLabel();
        jLabelEventPF1 = new javax.swing.JLabel();
        jLabelPumpaZaPranjePescanihFilteriaBr1 = new javax.swing.JLabel();
        jLabelPumpaZaPranjePescanihFilteriaBr2 = new javax.swing.JLabel();
        jLabelOdPranjaPescanihFilteraBr1 = new javax.swing.JLabel();
        jLabelOdPranjaPescanihFilteraBr2 = new javax.swing.JLabel();
        jLabelVentilZaPranjePescanihFilteraBr1 = new javax.swing.JLabel();
        jLabelVentilZaPranjePescanihFilteraBr2 = new javax.swing.JLabel();
        jLabelPFRegVentilIzlaz = new javax.swing.JLabel();
        jLabelPFRegVentilVrednostIzlaz = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Filtracija");
        getContentPane().setLayout(null);

        jLabelPKPFbr1CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPKPFbr1CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPKPFbr1CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr1CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr1CopyPF);
        jLabelPKPFbr1CopyPF.setBounds(1600, 540, 30, 50);

        jLabelPKPFbr2CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPKPFbr2CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPKPFbr2CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr2CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr2CopyPF);
        jLabelPKPFbr2CopyPF.setBounds(1510, 540, 40, 50);

        jLabelPKPFbr3CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPKPFbr3CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPKPFbr3CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr3CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr3CopyPF);
        jLabelPKPFbr3CopyPF.setBounds(1430, 540, 40, 50);

        jLabelPKPFbr4CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPKPFbr4CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPKPFbr4CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr4CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr4CopyPF);
        jLabelPKPFbr4CopyPF.setBounds(1350, 540, 30, 50);

        jLabelPKPFbr5CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPKPFbr5CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPKPFbr5CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr5CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr5CopyPF);
        jLabelPKPFbr5CopyPF.setBounds(1270, 540, 30, 50);

        jLabelPKPFbr6CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPKPFbr6CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPKPFbr6CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr6CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr6CopyPF);
        jLabelPKPFbr6CopyPF.setBounds(1190, 540, 30, 50);

        jLabelPF6PritisakIn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF6PritisakIn.setForeground(new java.awt.Color(0, 51, 204));
        jLabelPF6PritisakIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF6PritisakIn.setText("***");
        getContentPane().add(jLabelPF6PritisakIn);
        jLabelPF6PritisakIn.setBounds(400, 360, 100, 19);

        jLabelPF5PritisakIn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF5PritisakIn.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF5PritisakIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF5PritisakIn.setText("***");
        getContentPane().add(jLabelPF5PritisakIn);
        jLabelPF5PritisakIn.setBounds(600, 360, 100, 19);

        jLabelPF4PritisakIn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF4PritisakIn.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF4PritisakIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF4PritisakIn.setText("***");
        getContentPane().add(jLabelPF4PritisakIn);
        jLabelPF4PritisakIn.setBounds(820, 360, 100, 19);

        jLabelPF3PritisakIn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF3PritisakIn.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF3PritisakIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF3PritisakIn.setText("***");
        getContentPane().add(jLabelPF3PritisakIn);
        jLabelPF3PritisakIn.setBounds(1050, 360, 100, 19);

        jLabelPF2PritisakIn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF2PritisakIn.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF2PritisakIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF2PritisakIn.setText("***");
        getContentPane().add(jLabelPF2PritisakIn);
        jLabelPF2PritisakIn.setBounds(1270, 360, 100, 19);

        jLabelPF1PritisakIn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF1PritisakIn.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF1PritisakIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF1PritisakIn.setText("***");
        getContentPane().add(jLabelPF1PritisakIn);
        jLabelPF1PritisakIn.setBounds(1490, 360, 110, 19);

        jLabelPF6PritisakOut.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF6PritisakOut.setForeground(new java.awt.Color(0, 51, 255));
        jLabelPF6PritisakOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF6PritisakOut.setText("***");
        getContentPane().add(jLabelPF6PritisakOut);
        jLabelPF6PritisakOut.setBounds(270, 280, 80, 19);

        jLabelPF5PritisakOut.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF5PritisakOut.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF5PritisakOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF5PritisakOut.setText("***");
        getContentPane().add(jLabelPF5PritisakOut);
        jLabelPF5PritisakOut.setBounds(500, 280, 70, 19);

        jLabelPF4PritisakOut.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF4PritisakOut.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF4PritisakOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF4PritisakOut.setText("***");
        getContentPane().add(jLabelPF4PritisakOut);
        jLabelPF4PritisakOut.setBounds(710, 280, 80, 19);

        jLabelPF3PritisakOut.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF3PritisakOut.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF3PritisakOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF3PritisakOut.setText("***");
        jLabelPF3PritisakOut.setToolTipText("");
        getContentPane().add(jLabelPF3PritisakOut);
        jLabelPF3PritisakOut.setBounds(920, 280, 70, 19);

        jLabelPF2PritisakOut.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF2PritisakOut.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF2PritisakOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF2PritisakOut.setText("***");
        getContentPane().add(jLabelPF2PritisakOut);
        jLabelPF2PritisakOut.setBounds(1140, 280, 80, 19);

        jLabelPF1PritisakOut.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPF1PritisakOut.setForeground(new java.awt.Color(0, 51, 153));
        jLabelPF1PritisakOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF1PritisakOut.setText("***");
        getContentPane().add(jLabelPF1PritisakOut);
        jLabelPF1PritisakOut.setBounds(1350, 260, 90, 16);

        jProgressBarDekaFiltriranaVoda.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jProgressBarDekaFiltriranaVoda.setOrientation(1);
        jProgressBarDekaFiltriranaVoda.setToolTipText("");
        jProgressBarDekaFiltriranaVoda.setValue(10);
        jProgressBarDekaFiltriranaVoda.setBorderPainted(false);
        jProgressBarDekaFiltriranaVoda.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jProgressBarDekaFiltriranaVoda.setString("");
        jProgressBarDekaFiltriranaVoda.setStringPainted(true);
        getContentPane().add(jProgressBarDekaFiltriranaVoda);
        jProgressBarDekaFiltriranaVoda.setBounds(140, 780, 20, 150);

        jProgressBarOtpadneOdPranjaPescani.setOrientation(1);
        jProgressBarOtpadneOdPranjaPescani.setValue(10);
        jProgressBarOtpadneOdPranjaPescani.setBorderPainted(false);
        getContentPane().add(jProgressBarOtpadneOdPranjaPescani);
        jProgressBarOtpadneOdPranjaPescani.setBounds(820, 780, 20, 150);

        jProgressBarDekaNefiltriraneVode.setOrientation(1);
        jProgressBarDekaNefiltriraneVode.setValue(10);
        getContentPane().add(jProgressBarDekaNefiltriraneVode);
        jProgressBarDekaNefiltriraneVode.setBounds(1200, 780, 20, 150);

        jLabelNivoBazenDekaFiltriraneVode.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoBazenDekaFiltriraneVode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoBazenDekaFiltriraneVode.setText("+++");
        getContentPane().add(jLabelNivoBazenDekaFiltriraneVode);
        jLabelNivoBazenDekaFiltriraneVode.setBounds(340, 890, 200, 30);

        jLabelNivoOtpadneVodePranjePF.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoOtpadneVodePranjePF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoOtpadneVodePranjePF.setText("+++");
        getContentPane().add(jLabelNivoOtpadneVodePranjePF);
        jLabelNivoOtpadneVodePranjePF.setBounds(880, 900, 210, 30);

        jLabelNivoDekaNefiltrirana.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoDekaNefiltrirana.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoDekaNefiltrirana.setText("+++");
        getContentPane().add(jLabelNivoDekaNefiltrirana);
        jLabelNivoDekaNefiltrirana.setBounds(1300, 900, 220, 30);

        jLabelProtokPF6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF6.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokPF6.setText("***");
        getContentPane().add(jLabelProtokPF6);
        jLabelProtokPF6.setBounds(460, 440, 90, 16);

        jLabelProtokPF5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF5.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF5.setText("***");
        getContentPane().add(jLabelProtokPF5);
        jLabelProtokPF5.setBounds(670, 440, 90, 19);

        jLabelProtokPF4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF4.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF4.setText("***");
        getContentPane().add(jLabelProtokPF4);
        jLabelProtokPF4.setBounds(890, 440, 100, 19);

        jLabelProtokPF3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF3.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF3.setText("***");
        getContentPane().add(jLabelProtokPF3);
        jLabelProtokPF3.setBounds(1100, 440, 110, 19);

        jLabelProtokPF2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF2.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF2.setText("***");
        getContentPane().add(jLabelProtokPF2);
        jLabelProtokPF2.setBounds(1330, 440, 90, 19);

        jLabelProtokPF1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokPF1.setForeground(new java.awt.Color(255, 0, 51));
        jLabelProtokPF1.setText("***");
        getContentPane().add(jLabelProtokPF1);
        jLabelProtokPF1.setBounds(1550, 440, 80, 19);

        jLabelPF6RegVentil01CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF6RegVentil01CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPF6RegVentil01CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPF6RegVentil01CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPF6RegVentil01CopyPF);
        jLabelPF6RegVentil01CopyPF.setBounds(420, 410, 30, 40);

        jLabelPF6RegVentil01VrednostCopyPF.setText("***");
        getContentPane().add(jLabelPF6RegVentil01VrednostCopyPF);
        jLabelPF6RegVentil01VrednostCopyPF.setBounds(450, 420, 50, 14);

        jLabelPF5RegVentil01CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF5RegVentil01CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPF5RegVentil01CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPF5RegVentil01CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPF5RegVentil01CopyPF);
        jLabelPF5RegVentil01CopyPF.setBounds(634, 410, 26, 40);

        jLabelPF5RegVentil01VrednostCopyPF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPF5RegVentil01VrednostCopyPF.setText("***");
        getContentPane().add(jLabelPF5RegVentil01VrednostCopyPF);
        jLabelPF5RegVentil01VrednostCopyPF.setBounds(670, 420, 50, 14);

        jLabelPF4RegVentil01CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF4RegVentil01CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPF4RegVentil01CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPF4RegVentil01CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPF4RegVentil01CopyPF);
        jLabelPF4RegVentil01CopyPF.setBounds(850, 410, 40, 40);

        jLabelPF4RegVentil01VrednostCopyPF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPF4RegVentil01VrednostCopyPF.setText("***");
        getContentPane().add(jLabelPF4RegVentil01VrednostCopyPF);
        jLabelPF4RegVentil01VrednostCopyPF.setBounds(890, 420, 40, 14);

        jLabelPF2RegVentil01CopyPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPF2RegVentil01CopyPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelPF2RegVentil01CopyPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPF2RegVentil01CopyPFMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPF2RegVentil01CopyPF);
        jLabelPF2RegVentil01CopyPF.setBounds(1296, 410, 30, 40);

        jLabelPF2RegVentil01VrednostCopyPF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPF2RegVentil01VrednostCopyPF.setText("***");
        getContentPane().add(jLabelPF2RegVentil01VrednostCopyPF);
        jLabelPF2RegVentil01VrednostCopyPF.setBounds(1330, 420, 50, 14);

        jLabelPumpaKaPescanimFilterimaBr01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr01);
        jLabelPumpaKaPescanimFilterimaBr01.setBounds(1590, 600, 50, 50);

        jLabelPumpaKaPescanimFilterimaBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr2);
        jLabelPumpaKaPescanimFilterimaBr2.setBounds(1500, 600, 60, 50);

        jLabelPumpaKaPescanimFilterimaBr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr3);
        jLabelPumpaKaPescanimFilterimaBr3.setBounds(1420, 600, 60, 50);

        jLabelPumpaKaPescanimFilterimaBr4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr4);
        jLabelPumpaKaPescanimFilterimaBr4.setBounds(1340, 600, 50, 50);

        jLabelPumpaKaPescanimFilterimaBr5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr5);
        jLabelPumpaKaPescanimFilterimaBr5.setBounds(1260, 600, 50, 50);

        jLabelPumpaKaPescanimFilterimaBr6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr6);
        jLabelPumpaKaPescanimFilterimaBr6.setBounds(1180, 600, 50, 50);

        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1);
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1.setBounds(890, 680, 50, 40);

        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2);
        jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2.setBounds(970, 680, 60, 40);

        jLabelKumulativnoPF6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoPF6.setText("***");
        getContentPane().add(jLabelKumulativnoPF6);
        jLabelKumulativnoPF6.setBounds(330, 220, 130, 20);

        jLabelKumulativnoPF2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoPF2.setText("***");
        getContentPane().add(jLabelKumulativnoPF2);
        jLabelKumulativnoPF2.setBounds(1200, 220, 130, 20);

        jLabelKumulativnoPF4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoPF4.setText("***");
        getContentPane().add(jLabelKumulativnoPF4);
        jLabelKumulativnoPF4.setBounds(760, 220, 130, 20);

        jLabelKumulativnoPF5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoPF5.setText("***");
        getContentPane().add(jLabelKumulativnoPF5);
        jLabelKumulativnoPF5.setBounds(540, 220, 130, 20);

        jLabelEventPF6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventPF6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEventPF6);
        jLabelEventPF6.setBounds(340, 210, 100, 150);

        jLabelEventPF5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventPF5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEventPF5);
        jLabelEventPF5.setBounds(550, 210, 100, 150);

        jLabelEventPF4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventPF4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEventPF4);
        jLabelEventPF4.setBounds(770, 210, 100, 150);

        jLabelEventPF3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventPF3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEventPF3);
        jLabelEventPF3.setBounds(990, 210, 100, 150);

        jLabelEventPF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventPF2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEventPF2);
        jLabelEventPF2.setBounds(1210, 210, 100, 150);

        jLabelEventPF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEventPF1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelEventPF1);
        jLabelEventPF1.setBounds(1430, 210, 100, 150);

        jLabelPumpaZaPranjePescanihFilteriaBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaZaPranjePescanihFilteriaBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaZaPranjePescanihFilteriaBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaZaPranjePescanihFilteriaBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaZaPranjePescanihFilteriaBr1);
        jLabelPumpaZaPranjePescanihFilteriaBr1.setBounds(230, 670, 60, 60);

        jLabelPumpaZaPranjePescanihFilteriaBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaZaPranjePescanihFilteriaBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaZaPranjePescanihFilteriaBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaZaPranjePescanihFilteriaBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaZaPranjePescanihFilteriaBr2);
        jLabelPumpaZaPranjePescanihFilteriaBr2.setBounds(320, 670, 50, 60);

        jLabelOdPranjaPescanihFilteraBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOdPranjaPescanihFilteraBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelOdPranjaPescanihFilteraBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOdPranjaPescanihFilteraBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelOdPranjaPescanihFilteraBr1);
        jLabelOdPranjaPescanihFilteraBr1.setBounds(900, 610, 30, 50);

        jLabelOdPranjaPescanihFilteraBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOdPranjaPescanihFilteraBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelOdPranjaPescanihFilteraBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOdPranjaPescanihFilteraBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelOdPranjaPescanihFilteraBr2);
        jLabelOdPranjaPescanihFilteraBr2.setBounds(980, 610, 40, 50);

        jLabelVentilZaPranjePescanihFilteraBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilZaPranjePescanihFilteraBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilZaPranjePescanihFilteraBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilZaPranjePescanihFilteraBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilZaPranjePescanihFilteraBr1);
        jLabelVentilZaPranjePescanihFilteraBr1.setBounds(240, 610, 40, 40);

        jLabelVentilZaPranjePescanihFilteraBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilZaPranjePescanihFilteraBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilZaPranjePescanihFilteraBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilZaPranjePescanihFilteraBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilZaPranjePescanihFilteraBr2);
        jLabelVentilZaPranjePescanihFilteraBr2.setBounds(320, 610, 40, 40);

        jLabelPFRegVentilIzlaz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPFRegVentilIzlaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPFRegVentilIzlaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPFRegVentilIzlazMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPFRegVentilIzlaz);
        jLabelPFRegVentilIzlaz.setBounds(240, 130, 40, 30);

        jLabelPFRegVentilVrednostIzlaz.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPFRegVentilVrednostIzlaz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPFRegVentilVrednostIzlaz.setText("***");
        getContentPane().add(jLabelPFRegVentilVrednostIzlaz);
        jLabelPFRegVentilVrednostIzlaz.setBounds(240, 170, 40, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/statImg/2 peščani filteri zajedno.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setMaximumSize(new java.awt.Dimension(1742, 964));
        jLabel1.setMinimumSize(new java.awt.Dimension(1742, 964));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1742, 964));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1740, 960);

        setBounds(170, 35, 1735, 987);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPKPFbr1CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr1CopyPFMouseClicked
        allPopUpWindow.ProzorPKPFbr1();
    }//GEN-LAST:event_jLabelPKPFbr1CopyPFMouseClicked

    private void jLabelPKPFbr2CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr2CopyPFMouseClicked
        allPopUpWindow.ProzorPKPFbr2();
    }//GEN-LAST:event_jLabelPKPFbr2CopyPFMouseClicked

    private void jLabelPKPFbr3CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr3CopyPFMouseClicked
        allPopUpWindow.ProzorPKPFbr3();
    }//GEN-LAST:event_jLabelPKPFbr3CopyPFMouseClicked

    private void jLabelPKPFbr4CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr4CopyPFMouseClicked
        allPopUpWindow.ProzorPKPFbr4();
    }//GEN-LAST:event_jLabelPKPFbr4CopyPFMouseClicked

    private void jLabelPKPFbr5CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr5CopyPFMouseClicked
        allPopUpWindow.ProzorPKPFbr5();
    }//GEN-LAST:event_jLabelPKPFbr5CopyPFMouseClicked

    private void jLabelPKPFbr6CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr6CopyPFMouseClicked
        allPopUpWindow.ProzorPKPFbr6();
    }//GEN-LAST:event_jLabelPKPFbr6CopyPFMouseClicked

    private void jLabelPF6RegVentil01CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPF6RegVentil01CopyPFMouseClicked
        allPopUpWindow.ProzorPF601();
    }//GEN-LAST:event_jLabelPF6RegVentil01CopyPFMouseClicked

    private void jLabelPF5RegVentil01CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPF5RegVentil01CopyPFMouseClicked
        allPopUpWindow.ProzorPF501();
      
    }//GEN-LAST:event_jLabelPF5RegVentil01CopyPFMouseClicked

    private void jLabelPF4RegVentil01CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPF4RegVentil01CopyPFMouseClicked
        allPopUpWindow.ProzorPF401();
    }//GEN-LAST:event_jLabelPF4RegVentil01CopyPFMouseClicked

    private void jLabelPF2RegVentil01CopyPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPF2RegVentil01CopyPFMouseClicked
        allPopUpWindow.ProzorPF201();
    }//GEN-LAST:event_jLabelPF2RegVentil01CopyPFMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr01MouseClicked
        allPopUpWindow.ProzorPumpaKaPF01();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr01MouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr2MouseClicked
        allPopUpWindow.ProzorPumpaKaPF02();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr2MouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr3MouseClicked
        allPopUpWindow.ProzorPumpaKaPF03();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr3MouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr4MouseClicked
        allPopUpWindow.ProzorPumpaKaPF04();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr4MouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr5MouseClicked
        allPopUpWindow.ProzorPumpaKaPF05();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr5MouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr6MouseClicked
        allPopUpWindow.ProzorPumpaKaPF06();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr6MouseClicked

    private void jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1MouseClicked
        allPopUpWindow.ProzorPumpaOtpadneOdPranjaPescanihFilteraBr1();
    }//GEN-LAST:event_jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1MouseClicked

    private void jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2MouseClicked
        allPopUpWindow.ProzorPumpaOtpadneOdPranjaPescanihFilteraBr2();
    }//GEN-LAST:event_jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2MouseClicked

    private void jLabelEventPF6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventPF6MouseClicked
        
    }//GEN-LAST:event_jLabelEventPF6MouseClicked

    private void jLabelEventPF5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventPF5MouseClicked
       
    }//GEN-LAST:event_jLabelEventPF5MouseClicked

    private void jLabelEventPF4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventPF4MouseClicked
       
    }//GEN-LAST:event_jLabelEventPF4MouseClicked

    private void jLabelEventPF3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventPF3MouseClicked
       
    }//GEN-LAST:event_jLabelEventPF3MouseClicked

    private void jLabelEventPF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventPF2MouseClicked
        
    }//GEN-LAST:event_jLabelEventPF2MouseClicked

    private void jLabelEventPF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEventPF1MouseClicked
        
    }//GEN-LAST:event_jLabelEventPF1MouseClicked

    private void jLabelPumpaZaPranjePescanihFilteriaBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaZaPranjePescanihFilteriaBr1MouseClicked
        allPopUpWindow.ProzorPumpaZaPranjePescanihFilteraBr1();
    }//GEN-LAST:event_jLabelPumpaZaPranjePescanihFilteriaBr1MouseClicked

    private void jLabelPumpaZaPranjePescanihFilteriaBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaZaPranjePescanihFilteriaBr2MouseClicked
        allPopUpWindow.ProzorPumpaZaPranjePescanihFilteraBr2();
    }//GEN-LAST:event_jLabelPumpaZaPranjePescanihFilteriaBr2MouseClicked

    private void jLabelOdPranjaPescanihFilteraBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOdPranjaPescanihFilteraBr1MouseClicked
        allPopUpWindow.ProzorOtpadneVodeOdPescanihFiltera1();
    }//GEN-LAST:event_jLabelOdPranjaPescanihFilteraBr1MouseClicked

    private void jLabelOdPranjaPescanihFilteraBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOdPranjaPescanihFilteraBr2MouseClicked
        allPopUpWindow.ProzorOtpadneVodeOdPescanihFiltera2();
    }//GEN-LAST:event_jLabelOdPranjaPescanihFilteraBr2MouseClicked

    private void jLabelVentilZaPranjePescanihFilteraBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilZaPranjePescanihFilteraBr1MouseClicked
        allPopUpWindow.ProzorPranjePescanihFiltera1();
    }//GEN-LAST:event_jLabelVentilZaPranjePescanihFilteraBr1MouseClicked

    private void jLabelVentilZaPranjePescanihFilteraBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilZaPranjePescanihFilteraBr2MouseClicked
        allPopUpWindow.ProzorPranjePescanihFiltera2();
    }//GEN-LAST:event_jLabelVentilZaPranjePescanihFilteraBr2MouseClicked

    private void jLabelPFRegVentilIzlazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPFRegVentilIzlazMouseClicked
        allPopUpWindow.ProzorIzlazPF();
    }//GEN-LAST:event_jLabelPFRegVentilIzlazMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEventPF1;
    private javax.swing.JLabel jLabelEventPF2;
    private javax.swing.JLabel jLabelEventPF3;
    private javax.swing.JLabel jLabelEventPF4;
    private javax.swing.JLabel jLabelEventPF5;
    private javax.swing.JLabel jLabelEventPF6;
    private javax.swing.JLabel jLabelKumulativnoPF2;
    private javax.swing.JLabel jLabelKumulativnoPF4;
    private javax.swing.JLabel jLabelKumulativnoPF5;
    private javax.swing.JLabel jLabelKumulativnoPF6;
    private javax.swing.JLabel jLabelNivoBazenDekaFiltriraneVode;
    private javax.swing.JLabel jLabelNivoDekaNefiltrirana;
    private javax.swing.JLabel jLabelNivoOtpadneVodePranjePF;
    private javax.swing.JLabel jLabelOdPranjaPescanihFilteraBr1;
    private javax.swing.JLabel jLabelOdPranjaPescanihFilteraBr2;
    private javax.swing.JLabel jLabelPF1PritisakIn;
    private javax.swing.JLabel jLabelPF1PritisakOut;
    private javax.swing.JLabel jLabelPF2PritisakIn;
    private javax.swing.JLabel jLabelPF2PritisakOut;
    private javax.swing.JLabel jLabelPF2RegVentil01CopyPF;
    private javax.swing.JLabel jLabelPF2RegVentil01VrednostCopyPF;
    private javax.swing.JLabel jLabelPF3PritisakIn;
    private javax.swing.JLabel jLabelPF3PritisakOut;
    private javax.swing.JLabel jLabelPF4PritisakIn;
    private javax.swing.JLabel jLabelPF4PritisakOut;
    private javax.swing.JLabel jLabelPF4RegVentil01CopyPF;
    private javax.swing.JLabel jLabelPF4RegVentil01VrednostCopyPF;
    private javax.swing.JLabel jLabelPF5PritisakIn;
    private javax.swing.JLabel jLabelPF5PritisakOut;
    private javax.swing.JLabel jLabelPF5RegVentil01CopyPF;
    private javax.swing.JLabel jLabelPF5RegVentil01VrednostCopyPF;
    private javax.swing.JLabel jLabelPF6PritisakIn;
    private javax.swing.JLabel jLabelPF6PritisakOut;
    private javax.swing.JLabel jLabelPF6RegVentil01CopyPF;
    private javax.swing.JLabel jLabelPF6RegVentil01VrednostCopyPF;
    private javax.swing.JLabel jLabelPFRegVentilIzlaz;
    private javax.swing.JLabel jLabelPFRegVentilVrednostIzlaz;
    private javax.swing.JLabel jLabelPKPFbr1CopyPF;
    private javax.swing.JLabel jLabelPKPFbr2CopyPF;
    private javax.swing.JLabel jLabelPKPFbr3CopyPF;
    private javax.swing.JLabel jLabelPKPFbr4CopyPF;
    private javax.swing.JLabel jLabelPKPFbr5CopyPF;
    private javax.swing.JLabel jLabelPKPFbr6CopyPF;
    private javax.swing.JLabel jLabelProtokPF1;
    private javax.swing.JLabel jLabelProtokPF2;
    private javax.swing.JLabel jLabelProtokPF3;
    private javax.swing.JLabel jLabelProtokPF4;
    private javax.swing.JLabel jLabelProtokPF5;
    private javax.swing.JLabel jLabelProtokPF6;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr01;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr2;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr3;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr4;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr5;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr6;
    private javax.swing.JLabel jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1;
    private javax.swing.JLabel jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2;
    private javax.swing.JLabel jLabelPumpaZaPranjePescanihFilteriaBr1;
    private javax.swing.JLabel jLabelPumpaZaPranjePescanihFilteriaBr2;
    private javax.swing.JLabel jLabelVentilZaPranjePescanihFilteraBr1;
    private javax.swing.JLabel jLabelVentilZaPranjePescanihFilteraBr2;
    private javax.swing.JProgressBar jProgressBarDekaFiltriranaVoda;
    private javax.swing.JProgressBar jProgressBarDekaNefiltriraneVode;
    private javax.swing.JProgressBar jProgressBarOtpadneOdPranjaPescani;
    // End of variables declaration//GEN-END:variables

    
    private final VentiliKaPescanimFilterima ventiliKaPescanimFilterima;
    private final PumpeKaPescanimFilterima pumpeKaPescanimFilterima;
    private final PumpeOdpadnihVodaOdPranjaPescanihFiltera pumpeOdpadnihVodaOdPranjaPescanihFiltera;
    private final PumpeZaPranjePescanihFiltera pumpeZaPranjePescanihFiltera;
    private final OtpadneVodeOdPescanihFiltera otpadneVodeOdPescanihFiltera;
    private final ProtociPescaniFilteri protociPescaniFilteri;
    private final Nivoi bazeniMerenja;
    private final PescaniFilteri pescaniFilteri;
    private final PescaniFilterMerenjaKonstruktor pfMerenja;
    private final PranjePescanihFiltera pranjePescanihFiltera;
    private final Img img;
    public Timer timer;
    private final AllPopUpWindow allPopUpWindow;
    
    
     public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                //Date date = new Date();
                refreshPKPF();
                refreshPFmerenja();
                refreshBazeniMerenja();     
                refreshPumpeKaPescanimFilterima();
                refreshPumpeOtpadnihVodaOdPranjaPescanihFiltera();       
                refreshProtoci();
                refreshPumpeZaPranjePescanihFiltera();        
                refreshOtpadneVodeOdPescanihFiltera();
                refreshPranjePescanihFiltera();
                refreshPF2();
                refreshPF4();
                refreshPF5();
                refreshPF6();
                //System.out.println(date.getTime());
                //System.out.println("_____________");
            }
        });
    }

    private void setMinMax() {
        jProgressBarDekaFiltriranaVoda.setMinimum(bazeniMerenja.getBazenDekaFiltriraneVode().getMin());
        jProgressBarDekaFiltriranaVoda.setMaximum(bazeniMerenja.getBazenDekaFiltriraneVode().getMax());
        jProgressBarDekaFiltriranaVoda.setForeground(Color.ORANGE);

        jProgressBarOtpadneOdPranjaPescani.setMinimum(bazeniMerenja.getBazenOtpadneVodeOdPranjaPescanihFiltera().getMin());
        jProgressBarOtpadneOdPranjaPescani.setMaximum(bazeniMerenja.getBazenOtpadneVodeOdPranjaPescanihFiltera().getMax());
        jProgressBarOtpadneOdPranjaPescani.setForeground(Color.ORANGE);

        jProgressBarDekaNefiltriraneVode.setMinimum(bazeniMerenja.getBazenDekaNefiltriraneVode().getMin());
        jProgressBarDekaNefiltriraneVode.setMaximum(bazeniMerenja.getBazenDekaNefiltriraneVode().getMax());
        jProgressBarDekaNefiltriraneVode.setForeground(Color.ORANGE);
    }

    private void refreshPKPF() {
        img.setImgVertikalno(jLabelPKPFbr1CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr1());
        img.setImgVertikalno(jLabelPKPFbr2CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr2());
        img.setImgVertikalno(jLabelPKPFbr3CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr3());
        img.setImgVertikalno(jLabelPKPFbr4CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr4());
        img.setImgVertikalno(jLabelPKPFbr5CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr5());
        img.setImgVertikalno(jLabelPKPFbr6CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr6());
        refreshCopyPKPF();
        
        try { 
            int a = pescaniFilteri.getRegVentIzlazIzPescanih().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelPFRegVentilIzlaz, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelPFRegVentilVrednostIzlaz.setText(ShiftPoint.shiftonePoint(a, pescaniFilteri.getRegVentIzlazIzPescanih().getBrDecimala()));
        } catch (Exception e) {

        }
    }
    
     private void refreshPF2() {
        try {
            int a = pescaniFilteri.getPf2().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgVertikalno(jLabelPF2RegVentil01CopyPF, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelPF2RegVentil01VrednostCopyPF.setText(ShiftPoint.shiftonePoint(a, pescaniFilteri.getPf2().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
    }

    private void refreshPF4() {
        try {
            int a = pescaniFilteri.getPf4().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgVertikalno(jLabelPF4RegVentil01CopyPF, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelPF4RegVentil01VrednostCopyPF.setText(ShiftPoint.shiftonePoint(a, pescaniFilteri.getPf4().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
    }

    private void refreshPF5() {
        try {
            int a = pescaniFilteri.getPf5().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgVertikalno(jLabelPF5RegVentil01CopyPF, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelPF5RegVentil01VrednostCopyPF.setText(ShiftPoint.shiftonePoint(a, pescaniFilteri.getPf5().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
    }

    private void refreshPF6() {
        try {
            int a = pescaniFilteri.getPf6().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgVertikalno(jLabelPF6RegVentil01CopyPF, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelPF6RegVentil01VrednostCopyPF.setText(ShiftPoint.shiftonePoint(a, pescaniFilteri.getPf6().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
    }
    
   
    

    private void refreshPranjePescanihFiltera() {
        img.setImgVertikalno(jLabelVentilZaPranjePescanihFilteraBr1, pranjePescanihFiltera.getVent01());
        img.setImgVertikalno(jLabelVentilZaPranjePescanihFilteraBr2, pranjePescanihFiltera.getVent02());
    }

    private void refreshOtpadneVodeOdPescanihFiltera() {
        img.setImgVertikalno(jLabelOdPranjaPescanihFilteraBr1, otpadneVodeOdPescanihFiltera.getVent01());
        img.setImgVertikalno(jLabelOdPranjaPescanihFilteraBr2, otpadneVodeOdPescanihFiltera.getVent02());
    }

    private void refreshPFmerenja() {
        jLabelPF1PritisakIn.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakInPF1().getVrednostRegistra(), 2) + " bar");
        jLabelPF2PritisakIn.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakInPF2().getVrednostRegistra(), 2) + " bar");
        jLabelPF3PritisakIn.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakInPF3().getVrednostRegistra(), 2) + " bar");
        jLabelPF4PritisakIn.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakInPF4().getVrednostRegistra(), 2) + " bar");
        jLabelPF5PritisakIn.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakInPF5().getVrednostRegistra(), 2) + " bar");
        jLabelPF6PritisakIn.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakInPF6().getVrednostRegistra(), 2) + " bar");

        jLabelPF1PritisakOut.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakOutPF1().getVrednostRegistra(), 2) + " bar");
        jLabelPF2PritisakOut.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakOutPF2().getVrednostRegistra(), 2) + " bar");
        jLabelPF3PritisakOut.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakOutPF3().getVrednostRegistra(), 2) + " bar");
        jLabelPF4PritisakOut.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakOutPF4().getVrednostRegistra(), 2) + " bar");
        jLabelPF5PritisakOut.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakOutPF5().getVrednostRegistra(), 2) + " bar");
        jLabelPF6PritisakOut.setText(ShiftPoint.shiftonePoint(pfMerenja.getPfMerenja().getPritisakOutPF6().getVrednostRegistra(), 2) + " bar");
        
        jLabelKumulativnoPF2.setText(intToLong(protociPescaniFilteri.getProtokPF2().getKumulativnoVisiVrednost(), protociPescaniFilteri.getProtokPF2().getKumulativnoNiziVrednost()));
        jLabelKumulativnoPF4.setText(intToLong(protociPescaniFilteri.getProtokPF4().getKumulativnoVisiVrednost(), protociPescaniFilteri.getProtokPF4().getKumulativnoNiziVrednost()));
        jLabelKumulativnoPF5.setText(intToLong(protociPescaniFilteri.getProtokPF5().getKumulativnoVisiVrednost(), protociPescaniFilteri.getProtokPF5().getKumulativnoNiziVrednost()));
        jLabelKumulativnoPF6.setText(intToLong(protociPescaniFilteri.getProtokPF6().getKumulativnoVisiVrednost(), protociPescaniFilteri.getProtokPF6().getKumulativnoNiziVrednost()));

        
    }

    
    private void refreshCopyPKPF() {
        
        img.setImgVertikalno(jLabelPKPFbr1CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr1());
        img.setImgVertikalno(jLabelPKPFbr2CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr2());
        img.setImgVertikalno(jLabelPKPFbr3CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr3());
        img.setImgVertikalno(jLabelPKPFbr4CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr4());
        img.setImgVertikalno(jLabelPKPFbr5CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr5());
        img.setImgVertikalno(jLabelPKPFbr6CopyPF, ventiliKaPescanimFilterima.getAPKPF_PotisBr6());
    }

    private void refreshPumpeZaPranjePescanihFiltera() {
        img.setPumpIcon(jLabelPumpaZaPranjePescanihFilteriaBr1, pumpeZaPranjePescanihFiltera.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaZaPranjePescanihFilteriaBr2, pumpeZaPranjePescanihFiltera.getPumpaBr2().getVrednosti().isUkljucen());
    }

    private void refreshBazeniMerenja() {
        int a = bazeniMerenja.getBazenDekaFiltriraneVode().getVrednostRegistra();
        jLabelNivoBazenDekaFiltriraneVode.setText("L= " + Integer.toString(a) + " cm");
        jProgressBarDekaFiltriranaVoda.setValue(a);

        int b = bazeniMerenja.getBazenOtpadneVodeOdPranjaPescanihFiltera().getVrednostRegistra();
        jProgressBarOtpadneOdPranjaPescani.setValue(b);
        jLabelNivoOtpadneVodePranjePF.setText("L= " + Integer.toString(b) + " cm");

        int c = bazeniMerenja.getBazenDekaNefiltriraneVode().getVrednostRegistra();
        jProgressBarDekaNefiltriraneVode.setValue(c);
        jLabelNivoDekaNefiltrirana.setText("L= " + Integer.toString(c) + " cm");
 
    }

    private void refreshProtoci() {
        jLabelProtokPF1.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF1().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF1().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF2.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF2().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF2().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF3.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF3().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF3().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF4.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF4().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF4().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF5.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF5().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF5().getProtok().getBrDec()) + " m3/h");
        jLabelProtokPF6.setText(ShiftPoint.shiftonePoint(protociPescaniFilteri.getProtokPF6().getProtok().getVrednostRegistra(), protociPescaniFilteri.getProtokPF6().getProtok().getBrDec()) + " m3/h");
    }


    private void refreshPumpeKaPescanimFilterima() {
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr01, pumpeKaPescanimFilterima.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr2, pumpeKaPescanimFilterima.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr3, pumpeKaPescanimFilterima.getPumpaBr3().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr4, pumpeKaPescanimFilterima.getPumpaBr4().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr5, pumpeKaPescanimFilterima.getPumpaBr5().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr6, pumpeKaPescanimFilterima.getPumpaBr6().getVrednosti().isUkljucen());
    }

    private void refreshPumpeOtpadnihVodaOdPranjaPescanihFiltera() {
        img.setPumpIcon(jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr1, pumpeOdpadnihVodaOdPranjaPescanihFiltera.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaOtpadneOdPranjaPescanihFilteriaBr2, pumpeOdpadnihVodaOdPranjaPescanihFiltera.getPumpaBr2().getVrednosti().isUkljucen());
    }
}
