/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import field.merenja.bazeni.Nivoi;
import field.merenja.protoci.ProtociFlokulacija;
import field.odmuljenje.Odmuljenje;
import field.odmuljenje.RezimRadaEnum;
import field.pumpe.PumpeFerihlorid;
import field.pumpe.PumpeKaPescanimFilterima;
import field.pumpe.PumpePolielektrolit;
import field.ventili.Reaktor;
import field.ventili.VentiliFerihlorid;
import field.ventili.VentiliKaPescanimFilterima;
import field.ventili.VentiliPolielektrolit;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import popup.AllPopUpWindow;
import static utilise.Convert.intToLong;
import up.StartApp;


/**
 *
 * @author branko.scekic
 */
public class Flokulacija extends javax.swing.JInternalFrame {

    /**
     * Creates new form Flokulacija
     * @param pumpeFerihlorid
     * @param pumpePolielektrolit
     * @param pumpeKaPescanimFilterima
     * @param bazeniMerenja
     * @param ventiliKaPescanimFilterima
     * @param ventiliFerihlorid
     * @param ventiliPolielektrolit
     * @param protociFlokulacija
     * @param reaktor
     * @param img
     * @param allPopUpWindow
     */
    public Flokulacija( PumpeFerihlorid pumpeFerihlorid,
                        PumpePolielektrolit pumpePolielektrolit,
                        PumpeKaPescanimFilterima pumpeKaPescanimFilterima,
                        Nivoi bazeniMerenja,
                        VentiliKaPescanimFilterima ventiliKaPescanimFilterima,
                        VentiliFerihlorid ventiliFerihlorid,
                        VentiliPolielektrolit ventiliPolielektrolit,
                        ProtociFlokulacija protociFlokulacija,
                        Reaktor reaktor,
                        Img img, 
                        AllPopUpWindow allPopUpWindow) {
        initComponents();
        
        this.pumpeFerihlorid = pumpeFerihlorid;
        this.pumpePolielektrolit = pumpePolielektrolit;
        this.pumpeKaPescanimFilterima = pumpeKaPescanimFilterima;
        this.bazeniMerenja = bazeniMerenja;
        this.ventiliKaPescanimFilterima = ventiliKaPescanimFilterima;
        this.protociFlokulacija = protociFlokulacija;
        this.reaktor = reaktor;
        this.img = img;
        this.allPopUpWindow = allPopUpWindow;
        this.ventiliPolielektrolit = ventiliPolielektrolit;
        this.ventiliFerihlorid = ventiliFerihlorid;
        this.odmuljenje = new Odmuljenje();
        
        timerOdmuljenje = new java.util.Timer();
        setMinMax();
        screenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabelReaktorRegVentilR1 = new javax.swing.JLabel();
        jLabelReaktorRegVentilVrednostR1 = new javax.swing.JLabel();
        jLabelPKPFbr1 = new javax.swing.JLabel();
        jLabelPKPFbr2 = new javax.swing.JLabel();
        jLabelPKPFbr3 = new javax.swing.JLabel();
        jLabelPKPFbr4 = new javax.swing.JLabel();
        jLabelPKPFbr5 = new javax.swing.JLabel();
        jLabelPKPFbr6 = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacija = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacija = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacija = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacija = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacija = new javax.swing.JLabel();
        jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacija = new javax.swing.JLabel();
        jLabelProtokSiroveVodeR1 = new javax.swing.JLabel();
        jLabelProtokSiroveVodeR2 = new javax.swing.JLabel();
        jProgressBarDekaNefiltriraneVodeCopyFlokulacija = new javax.swing.JProgressBar();
        jLabelNivoDekaNefiltriranaCopyFlokulacija = new javax.swing.JLabel();
        jLabelPumpaFerihloridBr1 = new javax.swing.JLabel();
        jLabelPumpaFerihloridBr2 = new javax.swing.JLabel();
        jLabelPumpaFerihloridBr3 = new javax.swing.JLabel();
        jLabelPumpaPolielektrolitBr1 = new javax.swing.JLabel();
        jLabelPumpaPolielektrolitBr2 = new javax.swing.JLabel();
        jLabelPumpaPolielektrolitBr3 = new javax.swing.JLabel();
        jLabelKumulativnoR1 = new javax.swing.JLabel();
        jLabelKumulativnoR2 = new javax.swing.JLabel();
        jLabelVentilFeClpotis3 = new javax.swing.JLabel();
        jLabelVentilFeClpotis2 = new javax.swing.JLabel();
        jLabelVentilFeClpotis1 = new javax.swing.JLabel();
        jLabelVentilPEpotis3 = new javax.swing.JLabel();
        jLabelVentilPEpotis2 = new javax.swing.JLabel();
        jLabelVentilPEpotis1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonRucno = new javax.swing.JRadioButton();
        jRadioButtonAutomatski = new javax.swing.JRadioButton();
        jButtonRucnoOdmuljenje = new javax.swing.JButton();
        jRadioButtonVremenski = new javax.swing.JRadioButton();
        jRadioButtonm3 = new javax.swing.JRadioButton();
        jLabelStatImg1 = new javax.swing.JLabel();

        setTitle("Flokulacija");
        getContentPane().setLayout(null);

        jLabelReaktorRegVentilR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReaktorRegVentilR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelReaktorRegVentilR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReaktorRegVentilR1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelReaktorRegVentilR1);
        jLabelReaktorRegVentilR1.setBounds(800, 200, 40, 30);

        jLabelReaktorRegVentilVrednostR1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelReaktorRegVentilVrednostR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReaktorRegVentilVrednostR1.setText("***");
        getContentPane().add(jLabelReaktorRegVentilVrednostR1);
        jLabelReaktorRegVentilVrednostR1.setBounds(800, 230, 40, 19);

        jLabelPKPFbr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr1);
        jLabelPKPFbr1.setBounds(1350, 880, 40, 40);

        jLabelPKPFbr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr2);
        jLabelPKPFbr2.setBounds(1350, 820, 40, 40);

        jLabelPKPFbr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr3);
        jLabelPKPFbr3.setBounds(1350, 760, 40, 30);

        jLabelPKPFbr4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr4);
        jLabelPKPFbr4.setBounds(1350, 700, 40, 40);

        jLabelPKPFbr5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr5);
        jLabelPKPFbr5.setBounds(1350, 640, 40, 30);

        jLabelPKPFbr6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelPKPFbr6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKPFbr6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPKPFbr6);
        jLabelPKPFbr6.setBounds(1350, 570, 40, 40);

        jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacijaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacija);
        jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacija.setBounds(1400, 870, 50, 60);

        jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacijaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacija);
        jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacija.setBounds(1400, 810, 50, 60);

        jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacijaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacija);
        jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacija.setBounds(1400, 750, 50, 50);

        jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacijaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacija);
        jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacija.setBounds(1400, 690, 50, 60);

        jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacijaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacija);
        jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacija.setBounds(1400, 630, 50, 50);

        jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacija.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacijaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacija);
        jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacija.setBounds(1400, 560, 50, 60);

        jLabelProtokSiroveVodeR1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokSiroveVodeR1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokSiroveVodeR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokSiroveVodeR1.setText("0");
        getContentPane().add(jLabelProtokSiroveVodeR1);
        jLabelProtokSiroveVodeR1.setBounds(620, 290, 100, 19);

        jLabelProtokSiroveVodeR2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokSiroveVodeR2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokSiroveVodeR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokSiroveVodeR2.setText("0");
        getContentPane().add(jLabelProtokSiroveVodeR2);
        jLabelProtokSiroveVodeR2.setBounds(620, 360, 100, 19);

        jProgressBarDekaNefiltriraneVodeCopyFlokulacija.setOrientation(1);
        jProgressBarDekaNefiltriraneVodeCopyFlokulacija.setValue(10);
        getContentPane().add(jProgressBarDekaNefiltriraneVodeCopyFlokulacija);
        jProgressBarDekaNefiltriraneVodeCopyFlokulacija.setBounds(1210, 260, 20, 190);

        jLabelNivoDekaNefiltriranaCopyFlokulacija.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelNivoDekaNefiltriranaCopyFlokulacija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivoDekaNefiltriranaCopyFlokulacija.setText("+++");
        jLabelNivoDekaNefiltriranaCopyFlokulacija.setBorder(null);
        getContentPane().add(jLabelNivoDekaNefiltriranaCopyFlokulacija);
        jLabelNivoDekaNefiltriranaCopyFlokulacija.setBounds(1240, 410, 200, 30);

        jLabelPumpaFerihloridBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaFerihloridBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaFerihloridBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaFerihloridBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaFerihloridBr1);
        jLabelPumpaFerihloridBr1.setBounds(330, 770, 50, 50);

        jLabelPumpaFerihloridBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaFerihloridBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaFerihloridBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaFerihloridBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaFerihloridBr2);
        jLabelPumpaFerihloridBr2.setBounds(290, 770, 40, 50);

        jLabelPumpaFerihloridBr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaFerihloridBr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaFerihloridBr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaFerihloridBr3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaFerihloridBr3);
        jLabelPumpaFerihloridBr3.setBounds(240, 770, 50, 50);

        jLabelPumpaPolielektrolitBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaPolielektrolitBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaPolielektrolitBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaPolielektrolitBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaPolielektrolitBr1);
        jLabelPumpaPolielektrolitBr1.setBounds(650, 770, 40, 50);

        jLabelPumpaPolielektrolitBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaPolielektrolitBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaPolielektrolitBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaPolielektrolitBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaPolielektrolitBr2);
        jLabelPumpaPolielektrolitBr2.setBounds(600, 770, 50, 50);

        jLabelPumpaPolielektrolitBr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaPolielektrolitBr3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaPolielektrolitBr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaPolielektrolitBr3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaPolielektrolitBr3);
        jLabelPumpaPolielektrolitBr3.setBounds(560, 770, 40, 50);

        jLabelKumulativnoR1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelKumulativnoR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoR1.setText("0");
        getContentPane().add(jLabelKumulativnoR1);
        jLabelKumulativnoR1.setBounds(610, 260, 140, 20);

        jLabelKumulativnoR2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabelKumulativnoR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKumulativnoR2.setText("0");
        getContentPane().add(jLabelKumulativnoR2);
        jLabelKumulativnoR2.setBounds(610, 380, 140, 20);

        jLabelVentilFeClpotis3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilFeClpotis3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilFeClpotis3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilFeClpotis3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilFeClpotis3);
        jLabelVentilFeClpotis3.setBounds(250, 820, 30, 40);

        jLabelVentilFeClpotis2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilFeClpotis2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilFeClpotis2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilFeClpotis2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilFeClpotis2);
        jLabelVentilFeClpotis2.setBounds(290, 820, 40, 40);

        jLabelVentilFeClpotis1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilFeClpotis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilFeClpotis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilFeClpotis1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilFeClpotis1);
        jLabelVentilFeClpotis1.setBounds(330, 820, 40, 40);

        jLabelVentilPEpotis3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilPEpotis3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilPEpotis3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilPEpotis3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilPEpotis3);
        jLabelVentilPEpotis3.setBounds(566, 820, 30, 40);

        jLabelVentilPEpotis2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilPEpotis2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilPEpotis2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilPEpotis2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilPEpotis2);
        jLabelVentilPEpotis2.setBounds(610, 820, 30, 40);

        jLabelVentilPEpotis1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilPEpotis1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilPEpotis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilPEpotis1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilPEpotis1);
        jLabelVentilPEpotis1.setBounds(654, 820, 30, 40);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setCornerSize(22);
        dropShadowBorder1.setShadowColor(new java.awt.Color(204, 204, 204));
        dropShadowBorder1.setShadowSize(10);
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        jPanel1.setBorder(dropShadowBorder1);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Odmuljenje reaktor 1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 260, 20);

        buttonGroup1.add(jRadioButtonRucno);
        jRadioButtonRucno.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jRadioButtonRucno.setSelected(true);
        jRadioButtonRucno.setText("Rucno");
        jPanel1.add(jRadioButtonRucno);
        jRadioButtonRucno.setBounds(20, 40, 130, 32);

        buttonGroup1.add(jRadioButtonAutomatski);
        jRadioButtonAutomatski.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jRadioButtonAutomatski.setText("Automatski");
        jPanel1.add(jRadioButtonAutomatski);
        jRadioButtonAutomatski.setBounds(180, 40, 180, 32);

        jButtonRucnoOdmuljenje.setText("Pokreni");
        jButtonRucnoOdmuljenje.setEnabled(false);
        jButtonRucnoOdmuljenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRucnoOdmuljenjeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRucnoOdmuljenje);
        jButtonRucnoOdmuljenje.setBounds(20, 80, 90, 60);

        buttonGroup2.add(jRadioButtonVremenski);
        jRadioButtonVremenski.setText("Vremenski");
        jPanel1.add(jRadioButtonVremenski);
        jRadioButtonVremenski.setBounds(180, 80, 90, 18);

        buttonGroup2.add(jRadioButtonm3);
        jRadioButtonm3.setText("m3");
        jPanel1.add(jRadioButtonm3);
        jRadioButtonm3.setBounds(310, 80, 80, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1260, 10, 460, 230);

        jLabelStatImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/statImg/1 Flokulacija.png"))); // NOI18N
        jLabelStatImg1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabelStatImg1);
        jLabelStatImg1.setBounds(0, 0, 1720, 970);

        setBounds(170, 35, 1736, 1001);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelReaktorRegVentilR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReaktorRegVentilR1MouseClicked
        allPopUpWindow.ProzorR1SV();
    }//GEN-LAST:event_jLabelReaktorRegVentilR1MouseClicked

    private void jLabelPKPFbr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr1MouseClicked
        allPopUpWindow.ProzorPKPFbr1();
    }//GEN-LAST:event_jLabelPKPFbr1MouseClicked

    private void jLabelPKPFbr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr2MouseClicked
        allPopUpWindow.ProzorPKPFbr2();
    }//GEN-LAST:event_jLabelPKPFbr2MouseClicked

    private void jLabelPKPFbr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr3MouseClicked
        allPopUpWindow.ProzorPKPFbr3();
    }//GEN-LAST:event_jLabelPKPFbr3MouseClicked

    private void jLabelPKPFbr4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr4MouseClicked
        allPopUpWindow.ProzorPKPFbr4();
    }//GEN-LAST:event_jLabelPKPFbr4MouseClicked

    private void jLabelPKPFbr5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr5MouseClicked
        allPopUpWindow.ProzorPKPFbr5();
    }//GEN-LAST:event_jLabelPKPFbr5MouseClicked

    private void jLabelPKPFbr6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKPFbr6MouseClicked
        allPopUpWindow.ProzorPKPFbr6();
    }//GEN-LAST:event_jLabelPKPFbr6MouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacijaMouseClicked
        allPopUpWindow.ProzorPumpaKaPF01();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacijaMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacijaMouseClicked
        allPopUpWindow.ProzorPumpaKaPF02();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacijaMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacijaMouseClicked
        allPopUpWindow.ProzorPumpaKaPF03();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacijaMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacijaMouseClicked
        allPopUpWindow.ProzorPumpaKaPF04();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacijaMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacijaMouseClicked
        allPopUpWindow.ProzorPumpaKaPF05();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacijaMouseClicked

    private void jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacijaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacijaMouseClicked
        allPopUpWindow.ProzorPumpaKaPF06();
    }//GEN-LAST:event_jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacijaMouseClicked

    private void jLabelPumpaFerihloridBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaFerihloridBr1MouseClicked
        allPopUpWindow.ProzorPumpaFerihloridBr1();
    }//GEN-LAST:event_jLabelPumpaFerihloridBr1MouseClicked

    private void jLabelPumpaFerihloridBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaFerihloridBr2MouseClicked
        allPopUpWindow.ProzorPumpaFerihloridBr2();
    }//GEN-LAST:event_jLabelPumpaFerihloridBr2MouseClicked

    private void jLabelPumpaFerihloridBr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaFerihloridBr3MouseClicked
        allPopUpWindow.ProzorPumpaFerihloridBr3();
    }//GEN-LAST:event_jLabelPumpaFerihloridBr3MouseClicked

    private void jLabelPumpaPolielektrolitBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaPolielektrolitBr1MouseClicked
        
    }//GEN-LAST:event_jLabelPumpaPolielektrolitBr1MouseClicked

    private void jLabelPumpaPolielektrolitBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaPolielektrolitBr2MouseClicked
        allPopUpWindow.ProzorPumpaPolielektrolitBr2();
    }//GEN-LAST:event_jLabelPumpaPolielektrolitBr2MouseClicked

    private void jLabelPumpaPolielektrolitBr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaPolielektrolitBr3MouseClicked
        allPopUpWindow.ProzorPumpaPolielektrolitBr3();
    }//GEN-LAST:event_jLabelPumpaPolielektrolitBr3MouseClicked

    private void jLabelVentilFeClpotis3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilFeClpotis3MouseClicked
        allPopUpWindow.ProzorFeClVentil3();
    }//GEN-LAST:event_jLabelVentilFeClpotis3MouseClicked

    private void jLabelVentilFeClpotis2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilFeClpotis2MouseClicked
        allPopUpWindow.ProzorFeClVentil2();
    }//GEN-LAST:event_jLabelVentilFeClpotis2MouseClicked

    private void jLabelVentilFeClpotis1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilFeClpotis1MouseClicked
        allPopUpWindow.ProzorFeClVentil1();
    }//GEN-LAST:event_jLabelVentilFeClpotis1MouseClicked

    private void jLabelVentilPEpotis3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilPEpotis3MouseClicked
        allPopUpWindow.ProzorPEVentil3();
    }//GEN-LAST:event_jLabelVentilPEpotis3MouseClicked

    private void jLabelVentilPEpotis2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilPEpotis2MouseClicked
        allPopUpWindow.ProzorPEVentil2();
    }//GEN-LAST:event_jLabelVentilPEpotis2MouseClicked

    private void jLabelVentilPEpotis1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilPEpotis1MouseClicked
        allPopUpWindow.ProzorPEVentil1();
    }//GEN-LAST:event_jLabelVentilPEpotis1MouseClicked

    private void jButtonRucnoOdmuljenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRucnoOdmuljenjeActionPerformed
         odmuljenje.odmuljenje(RezimRadaEnum.rucni, StartApp.comm, 256, timerOdmuljenje);
    }//GEN-LAST:event_jButtonRucnoOdmuljenjeActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonRucnoOdmuljenje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelKumulativnoR1;
    private javax.swing.JLabel jLabelKumulativnoR2;
    private javax.swing.JLabel jLabelNivoDekaNefiltriranaCopyFlokulacija;
    private javax.swing.JLabel jLabelPKPFbr1;
    private javax.swing.JLabel jLabelPKPFbr2;
    private javax.swing.JLabel jLabelPKPFbr3;
    private javax.swing.JLabel jLabelPKPFbr4;
    private javax.swing.JLabel jLabelPKPFbr5;
    private javax.swing.JLabel jLabelPKPFbr6;
    private javax.swing.JLabel jLabelProtokSiroveVodeR1;
    private javax.swing.JLabel jLabelProtokSiroveVodeR2;
    private javax.swing.JLabel jLabelPumpaFerihloridBr1;
    private javax.swing.JLabel jLabelPumpaFerihloridBr2;
    private javax.swing.JLabel jLabelPumpaFerihloridBr3;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacija;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacija;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacija;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacija;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacija;
    private javax.swing.JLabel jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacija;
    private javax.swing.JLabel jLabelPumpaPolielektrolitBr1;
    private javax.swing.JLabel jLabelPumpaPolielektrolitBr2;
    private javax.swing.JLabel jLabelPumpaPolielektrolitBr3;
    private javax.swing.JLabel jLabelReaktorRegVentilR1;
    private javax.swing.JLabel jLabelReaktorRegVentilVrednostR1;
    private javax.swing.JLabel jLabelStatImg1;
    private javax.swing.JLabel jLabelVentilFeClpotis1;
    private javax.swing.JLabel jLabelVentilFeClpotis2;
    private javax.swing.JLabel jLabelVentilFeClpotis3;
    private javax.swing.JLabel jLabelVentilPEpotis1;
    private javax.swing.JLabel jLabelVentilPEpotis2;
    private javax.swing.JLabel jLabelVentilPEpotis3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBarDekaNefiltriraneVodeCopyFlokulacija;
    private javax.swing.JRadioButton jRadioButtonAutomatski;
    private javax.swing.JRadioButton jRadioButtonRucno;
    private javax.swing.JRadioButton jRadioButtonVremenski;
    private javax.swing.JRadioButton jRadioButtonm3;
    // End of variables declaration//GEN-END:variables

    private final Img img;
    
    private final PumpeFerihlorid pumpeFerihlorid;
    private final PumpePolielektrolit pumpePolielektrolit;
    private final PumpeKaPescanimFilterima pumpeKaPescanimFilterima;
    private final Nivoi bazeniMerenja;
    private final VentiliKaPescanimFilterima ventiliKaPescanimFilterima;
    private final VentiliFerihlorid ventiliFerihlorid;
    private final VentiliPolielektrolit ventiliPolielektrolit;
    private final ProtociFlokulacija protociFlokulacija;
    private final Reaktor reaktor;
    
    private final Odmuljenje odmuljenje;
        
    private final AllPopUpWindow allPopUpWindow;
    public Timer timer;
    private java.util.Timer timerOdmuljenje;

     public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                //Date date = new Date();
                refreshPKPF();
                refreshPFmerenja();
                refreshBazeniMerenja();
                refreshPumpeKaPescanimFilterima();
                refreshPumpeFerihlorid();
                refreshPumpePolielektrolit();
                refreshProtoci();
                refreshFeCl3Pe();
                refreshReaktorMotori();
                refreshOdmuljenje();

                //System.out.println(date.getTime());
                //System.out.println("_____________");
            }
        });
    }

    private void setMinMax() {
 
        jProgressBarDekaNefiltriraneVodeCopyFlokulacija.setMinimum(bazeniMerenja.getBazenDekaNefiltriraneVode().getMin());
        jProgressBarDekaNefiltriraneVodeCopyFlokulacija.setMaximum(bazeniMerenja.getBazenDekaNefiltriraneVode().getMax());
        jProgressBarDekaNefiltriraneVodeCopyFlokulacija.setForeground(Color.ORANGE);

    }
    
    private void refreshOdmuljenje(){
        if(jRadioButtonRucno.isSelected()){
            jButtonRucnoOdmuljenje.setEnabled(true);
            jRadioButtonVremenski.setEnabled(false);
            jRadioButtonm3.setEnabled(false);
        }
        
        if(jRadioButtonAutomatski.isSelected()){
            jButtonRucnoOdmuljenje.setEnabled(false);
            jRadioButtonVremenski.setEnabled(true);
            jRadioButtonm3.setEnabled(true);
        }
        
    }

    private void refreshFeCl3Pe(){
        img.setImgVertikalno(jLabelVentilPEpotis1, ventiliPolielektrolit.getPE_ventil1());
        img.setImgVertikalno(jLabelVentilPEpotis2, ventiliPolielektrolit.getPE_ventil2());
        img.setImgVertikalno(jLabelVentilPEpotis3, ventiliPolielektrolit.getPE_ventil3());
        
        img.setImgVertikalno(jLabelVentilFeClpotis1, ventiliFerihlorid.getFCl_ventil1());
        img.setImgVertikalno(jLabelVentilFeClpotis2, ventiliFerihlorid.getFCl_ventil2());
        img.setImgVertikalno(jLabelVentilFeClpotis3, ventiliFerihlorid.getFCl_ventil3());
       
    }

   

  

    private void refreshPFmerenja() {
        
        jLabelKumulativnoR1.setText(intToLong(protociFlokulacija.getProtokSiroveVodeR1().getKumulativnoVisiVrednost(), protociFlokulacija.getProtokSiroveVodeR1().getKumulativnoNiziVrednost()));
        jLabelKumulativnoR2.setText(intToLong(protociFlokulacija.getProtokSiroveVodeR2().getKumulativnoVisiVrednost(), protociFlokulacija.getProtokSiroveVodeR2().getKumulativnoNiziVrednost()));

       
    }


    private void refreshPKPF() {
        img.setImgHorizontalno(jLabelPKPFbr1, ventiliKaPescanimFilterima.getAPKPF_PotisBr1());
        img.setImgHorizontalno(jLabelPKPFbr2, ventiliKaPescanimFilterima.getAPKPF_PotisBr2());
        img.setImgHorizontalno(jLabelPKPFbr3, ventiliKaPescanimFilterima.getAPKPF_PotisBr3());
        img.setImgHorizontalno(jLabelPKPFbr4, ventiliKaPescanimFilterima.getAPKPF_PotisBr4());
        img.setImgHorizontalno(jLabelPKPFbr5, ventiliKaPescanimFilterima.getAPKPF_PotisBr5());
        img.setImgHorizontalno(jLabelPKPFbr6, ventiliKaPescanimFilterima.getAPKPF_PotisBr6());
    }

   

    private void refreshBazeniMerenja() {
        int c = bazeniMerenja.getBazenDekaNefiltriraneVode().getVrednostRegistra();
        jProgressBarDekaNefiltriraneVodeCopyFlokulacija.setValue(c);
        jLabelNivoDekaNefiltriranaCopyFlokulacija.setText("L= " + Integer.toString(c) + " cm");
    }

   

    private void refreshProtoci() {
        jLabelProtokSiroveVodeR1.setText("R1= " + Integer.toString(protociFlokulacija.getProtokSiroveVodeR1().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokSiroveVodeR2.setText("R2= " + Integer.toString(protociFlokulacija.getProtokSiroveVodeR2().getProtok().getVrednostRegistra()) + " m3/h");
    }

    

   

    private void refreshPumpeKaPescanimFilterima() {
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr1CopyFlokulacija, pumpeKaPescanimFilterima.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr2CopyFlokulacija, pumpeKaPescanimFilterima.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr3CopyFlokulacija, pumpeKaPescanimFilterima.getPumpaBr3().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr4CopyFlokulacija, pumpeKaPescanimFilterima.getPumpaBr4().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr5CopyFlokulacija, pumpeKaPescanimFilterima.getPumpaBr5().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaPescanimFilterimaBr6CopyFlokulacija, pumpeKaPescanimFilterima.getPumpaBr6().getVrednosti().isUkljucen());
    }


    private void refreshPumpeFerihlorid() {
        img.getStanjeFrPumpeImg(jLabelPumpaFerihloridBr1, pumpeFerihlorid.getPumpaBr1().getVrednosti().isRun(), pumpeFerihlorid.getPumpaBr1().getVrednosti().isPower());
        img.getStanjeFrPumpeImg(jLabelPumpaFerihloridBr2, pumpeFerihlorid.getPumpaBr2().getVrednosti().isRun(), pumpeFerihlorid.getPumpaBr2().getVrednosti().isPower());
        img.getStanjeFrPumpeImg(jLabelPumpaFerihloridBr3, pumpeFerihlorid.getPumpaBr3().getVrednosti().isRun(), pumpeFerihlorid.getPumpaBr3().getVrednosti().isPower());

    }

    private void refreshPumpePolielektrolit() {
        img.getStanjeFrPumpeImg(jLabelPumpaPolielektrolitBr1, pumpePolielektrolit.getPumpaBr1().getVrednosti().isRun(), pumpePolielektrolit.getPumpaBr1().getVrednosti().isPower());
        img.getStanjeFrPumpeImg(jLabelPumpaPolielektrolitBr2, pumpePolielektrolit.getPumpaBr2().getVrednosti().isRun(), pumpePolielektrolit.getPumpaBr2().getVrednosti().isPower());
        img.getStanjeFrPumpeImg(jLabelPumpaPolielektrolitBr3, pumpePolielektrolit.getPumpaBr3().getVrednosti().isRun(), pumpePolielektrolit.getPumpaBr3().getVrednosti().isPower());
    }

    private void refreshReaktorMotori() {
        img.setImgHorizontalno(jLabelReaktorRegVentilR1, reaktor.getUlazSirVodeR1().getVrednosti().getOtvoren(), reaktor.getUlazSirVodeR1().getVrednosti().getZatvoren());
    }
    
}
