/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import field.merenja.neutralnaJonska.NeutralnaJonskaMerenjaKonstruktor;
import field.merenja.protoci.ProtociNeutralna;
import field.merenja.rezervoari.RezervoariMerenja;
import field.pumpe.PumpeDekaFiltriraneKaNeutralnojIzmeni;
import field.ventili.JonskaIzmena;
import field.ventili.VentiliGrupaPumpi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import popup.AllPopUpWindow;
import tools.AnalogToDigital;
import static tools.Convert.intToLong;
import tools.ShiftPoint;

/**
 *
 * @author branko.scekic
 */
public class OmeksavanjeFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form OmeksavanjeFrame
     * @param protociNeutralna
     * @param rezervoariMerenja
     * @param njMerenja
     * @param ventiliGP01
     * @param pumpeDekaFiltriraneKaNeutralnojIzmeni
     * @param jonskaIzmena
     * @param allPopUpWindow
     * @param img
     */
    public OmeksavanjeFrame(ProtociNeutralna protociNeutralna, 
            RezervoariMerenja rezervoariMerenja, NeutralnaJonskaMerenjaKonstruktor njMerenja,
            VentiliGrupaPumpi ventiliGP01,
            PumpeDekaFiltriraneKaNeutralnojIzmeni pumpeDekaFiltriraneKaNeutralnojIzmeni,
            JonskaIzmena jonskaIzmena,
            AllPopUpWindow allPopUpWindow, Img img) {
        
        initComponents();
        
        this.protociNeutralna = protociNeutralna;
        this.rezervoariMerenja = rezervoariMerenja;
        this.njMerenja = njMerenja;
        this.ventiliGP01 = ventiliGP01;
        this.pumpeDekaFiltriraneKaNeutralnojIzmeni = pumpeDekaFiltriraneKaNeutralnojIzmeni;
        this.jonskaIzmena = jonskaIzmena;
        this.allPopUpWindow = allPopUpWindow;
        this.img = img;
        
        screenRefresh();
        setMinMax();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGP01kaNIVentil01 = new javax.swing.JLabel();
        jLabelGP01kaNIVentil02 = new javax.swing.JLabel();
        jLabelGP01kaNIVentil03 = new javax.swing.JLabel();
        jLabelPumpaKaNeutralnojIzmeniBr01 = new javax.swing.JLabel();
        jLabelPumpaKaNeutralnojIzmeniBr02 = new javax.swing.JLabel();
        jLabelPumpaKaNeutralnojIzmeniBr03 = new javax.swing.JLabel();
        jProgressBarKompenzacioniRezervoar500m3 = new javax.swing.JProgressBar();
        jLabelKompenzacioniRezervoar500m3 = new javax.swing.JLabel();
        jLabelNJ3RegVent01 = new javax.swing.JLabel();
        jLabelNJ3RegVent01Vrednost = new javax.swing.JLabel();
        jLabelNJ3Ventil07 = new javax.swing.JLabel();
        jLabelNJ3Ventil03 = new javax.swing.JLabel();
        jLabelNJ3Ventil05 = new javax.swing.JLabel();
        jLabelNJ3Ventil08 = new javax.swing.JLabel();
        jLabelNJ3Ventil04 = new javax.swing.JLabel();
        jLabelNJ3Ventil09 = new javax.swing.JLabel();
        jLabelNJ3Ventil06 = new javax.swing.JLabel();
        jLabelNJ3Ventil10 = new javax.swing.JLabel();
        jLabelNJ2RegVent01 = new javax.swing.JLabel();
        jLabelNJ2RegVent01Vrednost = new javax.swing.JLabel();
        jLabelNJ2Ventil07 = new javax.swing.JLabel();
        jLabelNJ2Ventil03 = new javax.swing.JLabel();
        jLabelNJ2Ventil05 = new javax.swing.JLabel();
        jLabelNJ2Ventil08 = new javax.swing.JLabel();
        jLabelNJ2Ventil04 = new javax.swing.JLabel();
        jLabelNJ2Ventil06 = new javax.swing.JLabel();
        jLabelNJ2Ventil09 = new javax.swing.JLabel();
        jLabelNJ2Ventil10 = new javax.swing.JLabel();
        jLabelNJ1RegVent01 = new javax.swing.JLabel();
        jLabelNJ1RegVent01Vrednost = new javax.swing.JLabel();
        jLabelNJ1Ventil07 = new javax.swing.JLabel();
        jLabelNJ1Ventil03 = new javax.swing.JLabel();
        jLabelNJ1Ventil05 = new javax.swing.JLabel();
        jLabelNJ1Ventil08 = new javax.swing.JLabel();
        jLabelNJ1Ventil09 = new javax.swing.JLabel();
        jLabelNJ1Ventil04 = new javax.swing.JLabel();
        jLabelNJ1Ventil06 = new javax.swing.JLabel();
        jLabelNJ1Ventil10 = new javax.swing.JLabel();
        jLabelProtokNeutralnaBr2 = new javax.swing.JLabel();
        jLabelProtokNeutralnaBr3 = new javax.swing.JLabel();
        jLabelProtokNeutralnaBr1 = new javax.swing.JLabel();
        jLabelNeutralnaBr1Kumulativno = new javax.swing.JLabel();
        jLabelNeutralnaBr2Kumulativno = new javax.swing.JLabel();
        jLabelNeutralnaBr3Kumulativno = new javax.swing.JLabel();
        jLabelPritisakIInzmena4 = new javax.swing.JLabel();
        jLabelPritisakIOutzmena4 = new javax.swing.JLabel();
        jLabelPritisakIInzmena5 = new javax.swing.JLabel();
        jLabelPritisakIOutzmena5 = new javax.swing.JLabel();
        jLabelPritisakIInzmena6 = new javax.swing.JLabel();
        jLabelPritisakIOutzmena6 = new javax.swing.JLabel();
        jLabelKumulativnoMagistralniVod = new javax.swing.JLabel();
        jLabelProtokNeutralnaMagistralniVod = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabelGP01kaNIVentil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGP01kaNIVentil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelGP01kaNIVentil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGP01kaNIVentil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelGP01kaNIVentil01);
        jLabelGP01kaNIVentil01.setBounds(1410, 760, 30, 50);

        jLabelGP01kaNIVentil02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGP01kaNIVentil02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelGP01kaNIVentil02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGP01kaNIVentil02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelGP01kaNIVentil02);
        jLabelGP01kaNIVentil02.setBounds(1300, 760, 30, 50);

        jLabelGP01kaNIVentil03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGP01kaNIVentil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelGP01kaNIVentil03.setToolTipText("");
        jLabelGP01kaNIVentil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGP01kaNIVentil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelGP01kaNIVentil03);
        jLabelGP01kaNIVentil03.setBounds(1190, 760, 40, 40);

        jLabelPumpaKaNeutralnojIzmeniBr01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaNeutralnojIzmeniBr01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaNeutralnojIzmeniBr01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaNeutralnojIzmeniBr01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaNeutralnojIzmeniBr01);
        jLabelPumpaKaNeutralnojIzmeniBr01.setBounds(1400, 810, 50, 50);

        jLabelPumpaKaNeutralnojIzmeniBr02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaNeutralnojIzmeniBr02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaNeutralnojIzmeniBr02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaNeutralnojIzmeniBr02MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaNeutralnojIzmeniBr02);
        jLabelPumpaKaNeutralnojIzmeniBr02.setBounds(1290, 810, 50, 50);

        jLabelPumpaKaNeutralnojIzmeniBr03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPumpaKaNeutralnojIzmeniBr03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pumpe/pump_off.png"))); // NOI18N
        jLabelPumpaKaNeutralnojIzmeniBr03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPumpaKaNeutralnojIzmeniBr03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPumpaKaNeutralnojIzmeniBr03);
        jLabelPumpaKaNeutralnojIzmeniBr03.setBounds(1180, 810, 50, 50);

        jProgressBarKompenzacioniRezervoar500m3.setOrientation(1);
        jProgressBarKompenzacioniRezervoar500m3.setValue(10);
        jProgressBarKompenzacioniRezervoar500m3.setString("0");
        jProgressBarKompenzacioniRezervoar500m3.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jProgressBarKompenzacioniRezervoar500m3);
        jProgressBarKompenzacioniRezervoar500m3.setBounds(200, 700, 20, 230);

        jLabelKompenzacioniRezervoar500m3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelKompenzacioniRezervoar500m3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKompenzacioniRezervoar500m3.setText("***");
        jLabelKompenzacioniRezervoar500m3.setBorder(null);
        getContentPane().add(jLabelKompenzacioniRezervoar500m3);
        jLabelKompenzacioniRezervoar500m3.setBounds(270, 900, 130, 30);

        jLabelNJ3RegVent01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNJ3RegVent01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ3RegVent01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ3RegVent01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ3RegVent01);
        jLabelNJ3RegVent01.setBounds(240, 440, 50, 30);

        jLabelNJ3RegVent01Vrednost.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelNJ3RegVent01Vrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNJ3RegVent01Vrednost.setText("***");
        getContentPane().add(jLabelNJ3RegVent01Vrednost);
        jLabelNJ3RegVent01Vrednost.setBounds(240, 470, 50, 19);

        jLabelNJ3Ventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ3Ventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ3Ventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ3Ventil07);
        jLabelNJ3Ventil07.setBounds(350, 380, 50, 40);

        jLabelNJ3Ventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ3Ventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ3Ventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ3Ventil03);
        jLabelNJ3Ventil03.setBounds(350, 440, 50, 30);

        jLabelNJ3Ventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ3Ventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ3Ventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ3Ventil05);
        jLabelNJ3Ventil05.setBounds(370, 510, 40, 26);

        jLabelNJ3Ventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ3Ventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ3Ventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ3Ventil08);
        jLabelNJ3Ventil08.setBounds(370, 540, 40, 30);

        jLabelNJ3Ventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ3Ventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ3Ventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ3Ventil04);
        jLabelNJ3Ventil04.setBounds(450, 450, 40, 40);

        jLabelNJ3Ventil09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ3Ventil09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ3Ventil09MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ3Ventil09);
        jLabelNJ3Ventil09.setBounds(480, 540, 40, 30);

        jLabelNJ3Ventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ3Ventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ3Ventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ3Ventil06);
        jLabelNJ3Ventil06.setBounds(480, 380, 40, 40);

        jLabelNJ3Ventil10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNJ3Ventil10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelNJ3Ventil10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ3Ventil10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ3Ventil10);
        jLabelNJ3Ventil10.setBounds(580, 280, 30, 50);

        jLabelNJ2RegVent01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ2RegVent01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ2RegVent01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ2RegVent01);
        jLabelNJ2RegVent01.setBounds(670, 440, 40, 30);

        jLabelNJ2RegVent01Vrednost.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelNJ2RegVent01Vrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNJ2RegVent01Vrednost.setText("***");
        getContentPane().add(jLabelNJ2RegVent01Vrednost);
        jLabelNJ2RegVent01Vrednost.setBounds(660, 470, 50, 19);

        jLabelNJ2Ventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ2Ventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ2Ventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ2Ventil07);
        jLabelNJ2Ventil07.setBounds(750, 380, 40, 40);

        jLabelNJ2Ventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ2Ventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ2Ventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ2Ventil03);
        jLabelNJ2Ventil03.setBounds(760, 440, 50, 40);

        jLabelNJ2Ventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ2Ventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ2Ventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ2Ventil05);
        jLabelNJ2Ventil05.setBounds(770, 510, 40, 30);

        jLabelNJ2Ventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ2Ventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ2Ventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ2Ventil08);
        jLabelNJ2Ventil08.setBounds(770, 540, 40, 30);

        jLabelNJ2Ventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ2Ventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ2Ventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ2Ventil04);
        jLabelNJ2Ventil04.setBounds(860, 460, 40, 30);

        jLabelNJ2Ventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ2Ventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ2Ventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ2Ventil06);
        jLabelNJ2Ventil06.setBounds(880, 380, 40, 40);

        jLabelNJ2Ventil09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ2Ventil09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ2Ventil09MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ2Ventil09);
        jLabelNJ2Ventil09.setBounds(880, 540, 40, 30);

        jLabelNJ2Ventil10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNJ2Ventil10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelNJ2Ventil10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ2Ventil10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ2Ventil10);
        jLabelNJ2Ventil10.setBounds(980, 280, 40, 40);

        jLabelNJ1RegVent01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ1RegVent01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ1RegVent01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ1RegVent01);
        jLabelNJ1RegVent01.setBounds(1080, 440, 50, 40);

        jLabelNJ1RegVent01Vrednost.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelNJ1RegVent01Vrednost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNJ1RegVent01Vrednost.setText("***");
        getContentPane().add(jLabelNJ1RegVent01Vrednost);
        jLabelNJ1RegVent01Vrednost.setBounds(1070, 480, 50, 19);

        jLabelNJ1Ventil07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ1Ventil07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ1Ventil07MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ1Ventil07);
        jLabelNJ1Ventil07.setBounds(1170, 390, 50, 30);

        jLabelNJ1Ventil03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ1Ventil03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ1Ventil03MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ1Ventil03);
        jLabelNJ1Ventil03.setBounds(1170, 440, 40, 40);

        jLabelNJ1Ventil05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ1Ventil05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ1Ventil05MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ1Ventil05);
        jLabelNJ1Ventil05.setBounds(1180, 510, 50, 30);

        jLabelNJ1Ventil08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ1Ventil08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ1Ventil08MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ1Ventil08);
        jLabelNJ1Ventil08.setBounds(1180, 540, 40, 30);

        jLabelNJ1Ventil09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ1Ventil09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ1Ventil09MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ1Ventil09);
        jLabelNJ1Ventil09.setBounds(1290, 540, 50, 30);

        jLabelNJ1Ventil04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ1Ventil04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ1Ventil04MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ1Ventil04);
        jLabelNJ1Ventil04.setBounds(1260, 460, 40, 30);

        jLabelNJ1Ventil06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNJ1Ventil06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelNJ1Ventil06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ1Ventil06MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ1Ventil06);
        jLabelNJ1Ventil06.setBounds(1290, 380, 50, 40);

        jLabelNJ1Ventil10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNJ1Ventil10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelNJ1Ventil10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNJ1Ventil10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNJ1Ventil10);
        jLabelNJ1Ventil10.setBounds(1380, 270, 50, 60);

        jLabelProtokNeutralnaBr2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokNeutralnaBr2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokNeutralnaBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokNeutralnaBr2.setText("***");
        getContentPane().add(jLabelProtokNeutralnaBr2);
        jLabelProtokNeutralnaBr2.setBounds(620, 680, 100, 19);

        jLabelProtokNeutralnaBr3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokNeutralnaBr3.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokNeutralnaBr3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokNeutralnaBr3.setText("***");
        getContentPane().add(jLabelProtokNeutralnaBr3);
        jLabelProtokNeutralnaBr3.setBounds(220, 680, 100, 19);

        jLabelProtokNeutralnaBr1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokNeutralnaBr1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokNeutralnaBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProtokNeutralnaBr1.setText("***");
        getContentPane().add(jLabelProtokNeutralnaBr1);
        jLabelProtokNeutralnaBr1.setBounds(1020, 680, 100, 19);

        jLabelNeutralnaBr1Kumulativno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNeutralnaBr1Kumulativno.setText("***");
        getContentPane().add(jLabelNeutralnaBr1Kumulativno);
        jLabelNeutralnaBr1Kumulativno.setBounds(1140, 210, 150, 16);

        jLabelNeutralnaBr2Kumulativno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNeutralnaBr2Kumulativno.setText("***");
        getContentPane().add(jLabelNeutralnaBr2Kumulativno);
        jLabelNeutralnaBr2Kumulativno.setBounds(730, 210, 150, 16);

        jLabelNeutralnaBr3Kumulativno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNeutralnaBr3Kumulativno.setText("***");
        getContentPane().add(jLabelNeutralnaBr3Kumulativno);
        jLabelNeutralnaBr3Kumulativno.setBounds(330, 210, 150, 16);

        jLabelPritisakIInzmena4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakIInzmena4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakIInzmena4.setText("jLabel15");
        getContentPane().add(jLabelPritisakIInzmena4);
        jLabelPritisakIInzmena4.setBounds(1160, 270, 90, 40);

        jLabelPritisakIOutzmena4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakIOutzmena4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakIOutzmena4.setText("jLabel15");
        getContentPane().add(jLabelPritisakIOutzmena4);
        jLabelPritisakIOutzmena4.setBounds(1260, 270, 90, 40);

        jLabelPritisakIInzmena5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakIInzmena5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakIInzmena5.setText("jLabel15");
        getContentPane().add(jLabelPritisakIInzmena5);
        jLabelPritisakIInzmena5.setBounds(750, 270, 90, 40);

        jLabelPritisakIOutzmena5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakIOutzmena5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakIOutzmena5.setText("jLabel15");
        getContentPane().add(jLabelPritisakIOutzmena5);
        jLabelPritisakIOutzmena5.setBounds(850, 270, 90, 40);

        jLabelPritisakIInzmena6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakIInzmena6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakIInzmena6.setText("jLabel15");
        getContentPane().add(jLabelPritisakIInzmena6);
        jLabelPritisakIInzmena6.setBounds(340, 270, 90, 40);

        jLabelPritisakIOutzmena6.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabelPritisakIOutzmena6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPritisakIOutzmena6.setText("jLabel15");
        getContentPane().add(jLabelPritisakIOutzmena6);
        jLabelPritisakIOutzmena6.setBounds(450, 270, 80, 40);

        jLabelKumulativnoMagistralniVod.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelKumulativnoMagistralniVod.setText("***");
        getContentPane().add(jLabelKumulativnoMagistralniVod);
        jLabelKumulativnoMagistralniVod.setBounds(470, 816, 130, 30);

        jLabelProtokNeutralnaMagistralniVod.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokNeutralnaMagistralniVod.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokNeutralnaMagistralniVod.setText("***");
        getContentPane().add(jLabelProtokNeutralnaMagistralniVod);
        jLabelProtokNeutralnaMagistralniVod.setBounds(470, 780, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/statImg/3 Neutralna jonska_1.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1740, 970);

        setBounds(170, 35, 1745, 1005);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelGP01kaNIVentil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGP01kaNIVentil01MouseClicked
        allPopUpWindow.ProzorGP01kaNeutralnojJonskoj01();        

    }//GEN-LAST:event_jLabelGP01kaNIVentil01MouseClicked

    private void jLabelGP01kaNIVentil02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGP01kaNIVentil02MouseClicked
        allPopUpWindow.ProzorGP01kaNeutralnojJonskoj02(); 
    }//GEN-LAST:event_jLabelGP01kaNIVentil02MouseClicked

    private void jLabelGP01kaNIVentil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGP01kaNIVentil03MouseClicked
        allPopUpWindow.ProzorGP01kaNeutralnojJonskoj03(); 
    }//GEN-LAST:event_jLabelGP01kaNIVentil03MouseClicked

    private void jLabelPumpaKaNeutralnojIzmeniBr01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaNeutralnojIzmeniBr01MouseClicked
        allPopUpWindow.ProzorPumpaKaNI01(); 
    }//GEN-LAST:event_jLabelPumpaKaNeutralnojIzmeniBr01MouseClicked

    private void jLabelPumpaKaNeutralnojIzmeniBr02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaNeutralnojIzmeniBr02MouseClicked
        allPopUpWindow.ProzorPumpaKaNI02();
    }//GEN-LAST:event_jLabelPumpaKaNeutralnojIzmeniBr02MouseClicked

    private void jLabelPumpaKaNeutralnojIzmeniBr03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPumpaKaNeutralnojIzmeniBr03MouseClicked
        allPopUpWindow.ProzorPumpaKaNI03(); 
    }//GEN-LAST:event_jLabelPumpaKaNeutralnojIzmeniBr03MouseClicked

    private void jLabelNJ3RegVent01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ3RegVent01MouseClicked
        allPopUpWindow.ProzorNJ301(); 
    }//GEN-LAST:event_jLabelNJ3RegVent01MouseClicked

    private void jLabelNJ3Ventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ3Ventil07MouseClicked
        allPopUpWindow.ProzorNJ307();
    }//GEN-LAST:event_jLabelNJ3Ventil07MouseClicked

    private void jLabelNJ3Ventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ3Ventil03MouseClicked
        allPopUpWindow.ProzorNJ303();
    }//GEN-LAST:event_jLabelNJ3Ventil03MouseClicked

    private void jLabelNJ3Ventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ3Ventil05MouseClicked
       allPopUpWindow.ProzorNJ305();
    }//GEN-LAST:event_jLabelNJ3Ventil05MouseClicked

    private void jLabelNJ3Ventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ3Ventil08MouseClicked
        allPopUpWindow.ProzorNJ308();
    }//GEN-LAST:event_jLabelNJ3Ventil08MouseClicked

    private void jLabelNJ3Ventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ3Ventil04MouseClicked
       allPopUpWindow.ProzorNJ304();
    }//GEN-LAST:event_jLabelNJ3Ventil04MouseClicked

    private void jLabelNJ3Ventil09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ3Ventil09MouseClicked
       allPopUpWindow.ProzorNJ309();
    }//GEN-LAST:event_jLabelNJ3Ventil09MouseClicked

    private void jLabelNJ3Ventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ3Ventil06MouseClicked
       allPopUpWindow.ProzorNJ306();
    }//GEN-LAST:event_jLabelNJ3Ventil06MouseClicked

    private void jLabelNJ3Ventil10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ3Ventil10MouseClicked
        allPopUpWindow.ProzorNJ310();
    }//GEN-LAST:event_jLabelNJ3Ventil10MouseClicked

    private void jLabelNJ2RegVent01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ2RegVent01MouseClicked
        allPopUpWindow.ProzorNJ201();
    }//GEN-LAST:event_jLabelNJ2RegVent01MouseClicked

    private void jLabelNJ2Ventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ2Ventil07MouseClicked
        allPopUpWindow.ProzorNJ207();
    }//GEN-LAST:event_jLabelNJ2Ventil07MouseClicked

    private void jLabelNJ2Ventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ2Ventil03MouseClicked
        allPopUpWindow.ProzorNJ203();
    }//GEN-LAST:event_jLabelNJ2Ventil03MouseClicked

    private void jLabelNJ2Ventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ2Ventil05MouseClicked
        allPopUpWindow.ProzorNJ205();
    }//GEN-LAST:event_jLabelNJ2Ventil05MouseClicked

    private void jLabelNJ2Ventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ2Ventil08MouseClicked
        allPopUpWindow.ProzorNJ208();
    }//GEN-LAST:event_jLabelNJ2Ventil08MouseClicked

    private void jLabelNJ2Ventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ2Ventil04MouseClicked
        allPopUpWindow.ProzorNJ204();
    }//GEN-LAST:event_jLabelNJ2Ventil04MouseClicked

    private void jLabelNJ2Ventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ2Ventil06MouseClicked
        allPopUpWindow.ProzorNJ206();
    }//GEN-LAST:event_jLabelNJ2Ventil06MouseClicked

    private void jLabelNJ2Ventil09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ2Ventil09MouseClicked
        allPopUpWindow.ProzorNJ209();
    }//GEN-LAST:event_jLabelNJ2Ventil09MouseClicked

    private void jLabelNJ2Ventil10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ2Ventil10MouseClicked
       allPopUpWindow.ProzorNJ210();
    }//GEN-LAST:event_jLabelNJ2Ventil10MouseClicked

    private void jLabelNJ1RegVent01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ1RegVent01MouseClicked
        allPopUpWindow.ProzorNJ101();
    }//GEN-LAST:event_jLabelNJ1RegVent01MouseClicked

    private void jLabelNJ1Ventil07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ1Ventil07MouseClicked
        allPopUpWindow.ProzorNJ107();
    }//GEN-LAST:event_jLabelNJ1Ventil07MouseClicked

    private void jLabelNJ1Ventil03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ1Ventil03MouseClicked
       allPopUpWindow.ProzorNJ103();
    }//GEN-LAST:event_jLabelNJ1Ventil03MouseClicked

    private void jLabelNJ1Ventil05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ1Ventil05MouseClicked
       allPopUpWindow.ProzorNJ105();
    }//GEN-LAST:event_jLabelNJ1Ventil05MouseClicked

    private void jLabelNJ1Ventil08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ1Ventil08MouseClicked
        allPopUpWindow.ProzorNJ108();
    }//GEN-LAST:event_jLabelNJ1Ventil08MouseClicked

    private void jLabelNJ1Ventil09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ1Ventil09MouseClicked
       allPopUpWindow.ProzorNJ109();
    }//GEN-LAST:event_jLabelNJ1Ventil09MouseClicked

    private void jLabelNJ1Ventil04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ1Ventil04MouseClicked
       allPopUpWindow.ProzorNJ104();
    }//GEN-LAST:event_jLabelNJ1Ventil04MouseClicked

    private void jLabelNJ1Ventil06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ1Ventil06MouseClicked
      allPopUpWindow.ProzorNJ106();
    }//GEN-LAST:event_jLabelNJ1Ventil06MouseClicked

    private void jLabelNJ1Ventil10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNJ1Ventil10MouseClicked
        allPopUpWindow.ProzorNJ110();
    }//GEN-LAST:event_jLabelNJ1Ventil10MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelGP01kaNIVentil01;
    private javax.swing.JLabel jLabelGP01kaNIVentil02;
    private javax.swing.JLabel jLabelGP01kaNIVentil03;
    private javax.swing.JLabel jLabelKompenzacioniRezervoar500m3;
    private javax.swing.JLabel jLabelKumulativnoMagistralniVod;
    private javax.swing.JLabel jLabelNJ1RegVent01;
    private javax.swing.JLabel jLabelNJ1RegVent01Vrednost;
    private javax.swing.JLabel jLabelNJ1Ventil03;
    private javax.swing.JLabel jLabelNJ1Ventil04;
    private javax.swing.JLabel jLabelNJ1Ventil05;
    private javax.swing.JLabel jLabelNJ1Ventil06;
    private javax.swing.JLabel jLabelNJ1Ventil07;
    private javax.swing.JLabel jLabelNJ1Ventil08;
    private javax.swing.JLabel jLabelNJ1Ventil09;
    private javax.swing.JLabel jLabelNJ1Ventil10;
    private javax.swing.JLabel jLabelNJ2RegVent01;
    private javax.swing.JLabel jLabelNJ2RegVent01Vrednost;
    private javax.swing.JLabel jLabelNJ2Ventil03;
    private javax.swing.JLabel jLabelNJ2Ventil04;
    private javax.swing.JLabel jLabelNJ2Ventil05;
    private javax.swing.JLabel jLabelNJ2Ventil06;
    private javax.swing.JLabel jLabelNJ2Ventil07;
    private javax.swing.JLabel jLabelNJ2Ventil08;
    private javax.swing.JLabel jLabelNJ2Ventil09;
    private javax.swing.JLabel jLabelNJ2Ventil10;
    private javax.swing.JLabel jLabelNJ3RegVent01;
    private javax.swing.JLabel jLabelNJ3RegVent01Vrednost;
    private javax.swing.JLabel jLabelNJ3Ventil03;
    private javax.swing.JLabel jLabelNJ3Ventil04;
    private javax.swing.JLabel jLabelNJ3Ventil05;
    private javax.swing.JLabel jLabelNJ3Ventil06;
    private javax.swing.JLabel jLabelNJ3Ventil07;
    private javax.swing.JLabel jLabelNJ3Ventil08;
    private javax.swing.JLabel jLabelNJ3Ventil09;
    private javax.swing.JLabel jLabelNJ3Ventil10;
    private javax.swing.JLabel jLabelNeutralnaBr1Kumulativno;
    private javax.swing.JLabel jLabelNeutralnaBr2Kumulativno;
    private javax.swing.JLabel jLabelNeutralnaBr3Kumulativno;
    private javax.swing.JLabel jLabelPritisakIInzmena4;
    private javax.swing.JLabel jLabelPritisakIInzmena5;
    private javax.swing.JLabel jLabelPritisakIInzmena6;
    private javax.swing.JLabel jLabelPritisakIOutzmena4;
    private javax.swing.JLabel jLabelPritisakIOutzmena5;
    private javax.swing.JLabel jLabelPritisakIOutzmena6;
    private javax.swing.JLabel jLabelProtokNeutralnaBr1;
    private javax.swing.JLabel jLabelProtokNeutralnaBr2;
    private javax.swing.JLabel jLabelProtokNeutralnaBr3;
    private javax.swing.JLabel jLabelProtokNeutralnaMagistralniVod;
    private javax.swing.JLabel jLabelPumpaKaNeutralnojIzmeniBr01;
    private javax.swing.JLabel jLabelPumpaKaNeutralnojIzmeniBr02;
    private javax.swing.JLabel jLabelPumpaKaNeutralnojIzmeniBr03;
    private javax.swing.JProgressBar jProgressBarKompenzacioniRezervoar500m3;
    // End of variables declaration//GEN-END:variables

    private final ProtociNeutralna protociNeutralna;
    private final RezervoariMerenja rezervoariMerenja;
    private final NeutralnaJonskaMerenjaKonstruktor njMerenja;
    private final VentiliGrupaPumpi ventiliGP01;
    private final PumpeDekaFiltriraneKaNeutralnojIzmeni pumpeDekaFiltriraneKaNeutralnojIzmeni;
    private final JonskaIzmena jonskaIzmena;
    private final AllPopUpWindow allPopUpWindow;
    public Timer timer;
    private final Img img;
    
     public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                //Date date = new Date();
                refreshIzmenaMerenja();
                refreshNJ1();
                refreshNJ2();
                refreshNJ3();
                refreshVentiliGP();
                refreshPumpeDekaFiltriraneKaNeutralnojIzmeni();
                refreshRezervoariMerenja();
                refreshProtoci();
            }
        });
    }

    private void setMinMax() {
       
        jProgressBarKompenzacioniRezervoar500m3.setMinimum(rezervoariMerenja.getNivoRezervoarKompenzacioni500m3().getMin());
        jProgressBarKompenzacioniRezervoar500m3.setMaximum(rezervoariMerenja.getNivoRezervoarKompenzacioni500m3().getMax());
        jProgressBarKompenzacioniRezervoar500m3.setForeground(Color.ORANGE);

    }


    private void refreshIzmenaMerenja() {

        jLabelPritisakIInzmena4.setText(ShiftPoint.shiftonePoint(njMerenja.getNjMerenjaL3().getPritisakInNJ().getVrednostRegistra(), 2) + " bar");
        jLabelPritisakIOutzmena4.setText(ShiftPoint.shiftonePoint(njMerenja.getNjMerenjaL3().getPritisakOutNJ().getVrednostRegistra(), 2) + " bar");

        jLabelPritisakIInzmena5.setText(ShiftPoint.shiftonePoint(njMerenja.getNjMerenjaL2().getPritisakInNJ().getVrednostRegistra(), 2) + " bar");
        jLabelPritisakIOutzmena5.setText(ShiftPoint.shiftonePoint(njMerenja.getNjMerenjaL2().getPritisakOutNJ().getVrednostRegistra(), 2) + " bar");

        jLabelPritisakIInzmena6.setText(ShiftPoint.shiftonePoint(njMerenja.getNjMerenjaL1().getPritisakInNJ().getVrednostRegistra(), 2) + " bar");
        jLabelPritisakIOutzmena6.setText(ShiftPoint.shiftonePoint(njMerenja.getNjMerenjaL1().getPritisakOutNJ().getVrednostRegistra(), 2) + " bar");
        
        jLabelKumulativnoMagistralniVod.setText(intToLong(protociNeutralna.getMagistralniVod().getKumulativnoVisiVrednost(), protociNeutralna.getMagistralniVod().getKumulativnoNiziVrednost()));
        jLabelProtokNeutralnaMagistralniVod.setText("Q= " + Integer.toString(protociNeutralna.getMagistralniVod().getProtok().getVrednostRegistra()) + " m3/h");
        
    }

   

    private void refreshVentiliGP() {
        img.setImgVertikalno(jLabelGP01kaNIVentil01, ventiliGP01.getGP01_potisJonska1());
        img.setImgVertikalno(jLabelGP01kaNIVentil02, ventiliGP01.getGP01_potisJonska2());
        img.setImgVertikalno(jLabelGP01kaNIVentil03, ventiliGP01.getGP01_potisJonska3());
    }

  
  

    private void refreshNJ1() {
        try {
            int a = jonskaIzmena.getJonskaIzmena01().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelNJ1RegVent01, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelNJ1RegVent01Vrednost.setText(ShiftPoint.shiftonePoint(a, jonskaIzmena.getJonskaIzmena01().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
        img.setImgHorizontalno(jLabelNJ1Ventil03, jonskaIzmena.getJonskaIzmena01().getVent03());
        img.setImgHorizontalno(jLabelNJ1Ventil04, jonskaIzmena.getJonskaIzmena01().getVent04());
        img.setImgHorizontalno(jLabelNJ1Ventil05, jonskaIzmena.getJonskaIzmena01().getVent05());
        img.setImgHorizontalno(jLabelNJ1Ventil06, jonskaIzmena.getJonskaIzmena01().getVent06());
        img.setImgHorizontalno(jLabelNJ1Ventil07, jonskaIzmena.getJonskaIzmena01().getVent07());
        img.setImgHorizontalno(jLabelNJ1Ventil08, jonskaIzmena.getJonskaIzmena01().getVent08());
        img.setImgHorizontalno(jLabelNJ1Ventil09, jonskaIzmena.getJonskaIzmena01().getVent09());
        img.setImgVertikalno(jLabelNJ1Ventil10, jonskaIzmena.getJonskaIzmena01().getVent10());
    }

    private void refreshNJ2() {
        try {
            int a = jonskaIzmena.getJonskaIzmena02().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelNJ2RegVent01, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelNJ2RegVent01Vrednost.setText(ShiftPoint.shiftonePoint(a, jonskaIzmena.getJonskaIzmena02().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
        img.setImgHorizontalno(jLabelNJ2Ventil03, jonskaIzmena.getJonskaIzmena02().getVent03());
        img.setImgHorizontalno(jLabelNJ2Ventil04, jonskaIzmena.getJonskaIzmena02().getVent04());
        img.setImgHorizontalno(jLabelNJ2Ventil05, jonskaIzmena.getJonskaIzmena02().getVent05());
        img.setImgHorizontalno(jLabelNJ2Ventil06, jonskaIzmena.getJonskaIzmena02().getVent06());
        img.setImgHorizontalno(jLabelNJ2Ventil07, jonskaIzmena.getJonskaIzmena02().getVent07());
        img.setImgHorizontalno(jLabelNJ2Ventil08, jonskaIzmena.getJonskaIzmena02().getVent08());
        img.setImgHorizontalno(jLabelNJ2Ventil09, jonskaIzmena.getJonskaIzmena02().getVent09());
        img.setImgVertikalno(jLabelNJ2Ventil10, jonskaIzmena.getJonskaIzmena02().getVent10());
    }

    private void refreshNJ3() {
        try {
            int a = jonskaIzmena.getJonskaIzmena03().getRegVent01().getVrednosti().getPolozajVrednost();
            img.setImgHorizontalno(jLabelNJ3RegVent01, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelNJ3RegVent01Vrednost.setText(ShiftPoint.shiftonePoint(a, jonskaIzmena.getJonskaIzmena03().getRegVent01().getBrDecimala()));
        } catch (Exception e) {

        }
        img.setImgHorizontalno(jLabelNJ3Ventil03, jonskaIzmena.getJonskaIzmena03().getVent03());
        img.setImgHorizontalno(jLabelNJ3Ventil04, jonskaIzmena.getJonskaIzmena03().getVent04());
        img.setImgHorizontalno(jLabelNJ3Ventil05, jonskaIzmena.getJonskaIzmena03().getVent05());
        img.setImgHorizontalno(jLabelNJ3Ventil06, jonskaIzmena.getJonskaIzmena03().getVent06());
        img.setImgHorizontalno(jLabelNJ3Ventil07, jonskaIzmena.getJonskaIzmena03().getVent07());
        img.setImgHorizontalno(jLabelNJ3Ventil08, jonskaIzmena.getJonskaIzmena03().getVent08());
        img.setImgHorizontalno(jLabelNJ3Ventil09, jonskaIzmena.getJonskaIzmena03().getVent09());
        img.setImgVertikalno(jLabelNJ3Ventil10, jonskaIzmena.getJonskaIzmena03().getVent10());

    }


    private void refreshProtoci() {
        jLabelProtokNeutralnaBr1.setText(Integer.toString(protociNeutralna.getProtokNJ1().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokNeutralnaBr2.setText(Integer.toString(protociNeutralna.getProtokNJ2().getProtok().getVrednostRegistra()) + " m3/h");
        jLabelProtokNeutralnaBr3.setText(Integer.toString(protociNeutralna.getProtokNJ3().getProtok().getVrednostRegistra()) + " m3/h");

        jLabelNeutralnaBr1Kumulativno.setText(intToLong(protociNeutralna.getProtokNJ1().getKumulativnoVisiVrednost(), protociNeutralna.getProtokNJ1().getKumulativnoNiziVrednost()));
        jLabelNeutralnaBr2Kumulativno.setText(intToLong(protociNeutralna.getProtokNJ2().getKumulativnoVisiVrednost(), protociNeutralna.getProtokNJ2().getKumulativnoNiziVrednost()));
        jLabelNeutralnaBr3Kumulativno.setText(intToLong(protociNeutralna.getProtokNJ3().getKumulativnoVisiVrednost(), protociNeutralna.getProtokNJ3().getKumulativnoNiziVrednost()));
    }


    private void refreshPumpeDekaFiltriraneKaNeutralnojIzmeni() {
        img.setPumpIcon(jLabelPumpaKaNeutralnojIzmeniBr01, pumpeDekaFiltriraneKaNeutralnojIzmeni.getPumpaBr1().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaNeutralnojIzmeniBr02, pumpeDekaFiltriraneKaNeutralnojIzmeni.getPumpaBr2().getVrednosti().isUkljucen());
        img.setPumpIcon(jLabelPumpaKaNeutralnojIzmeniBr03, pumpeDekaFiltriraneKaNeutralnojIzmeni.getPumpaBr3().getVrednosti().isUkljucen());

    }

    

    private void refreshRezervoariMerenja() {
        int d = rezervoariMerenja.getNivoRezervoarKompenzacioni500m3().getVrednostRegistra();
        jProgressBarKompenzacioniRezervoar500m3.setValue(d);
        jLabelKompenzacioniRezervoar500m3.setText("L= " + Integer.toString(d) + " cm");

    }
}
