/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.frame;

import constant.Img;
import field.merenja.protoci.ProtociRegeneracija;
import field.ventili.Regeneracija;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import popup.AllPopUpWindow;
import tools.AnalogToDigital;
import tools.ShiftPoint;

/**
 *
 * @author branko.scekic
 */
public class RegeneracijaFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegeneracijaFrame
     * @param regeneracija
     * @param protociRegeneracija
     * @param img
     * @param allPopUpWindow
     */
    public RegeneracijaFrame(Regeneracija regeneracija, ProtociRegeneracija protociRegeneracija,
            Img img, AllPopUpWindow allPopUpWindow) {
        initComponents();
        
        this.regeneracija = regeneracija;
        this.protociRegeneracija = protociRegeneracija;
        this.img = img;
        this.allPopUpWindow = allPopUpWindow;
        
        screenRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHClRegVentil01 = new javax.swing.JLabel();
        jLabelHClRegVentil01Vrednost = new javax.swing.JLabel();
        jLabelNaOHRegVentil = new javax.swing.JLabel();
        jLabelNaOHRegVentil01Vrednost = new javax.swing.JLabel();
        jLabelProtokRazredjivanjeHCL = new javax.swing.JLabel();
        jLabelProtokRazredjivanjeNaOH = new javax.swing.JLabel();
        jLabelProtokNaOH = new javax.swing.JLabel();
        jLabelProtokHCl = new javax.swing.JLabel();
        jLabelVentilHClUsisPumpeBr1 = new javax.swing.JLabel();
        jLabelVentilHClUsisPumpeBr2 = new javax.swing.JLabel();
        jLabelVentilHClPotisPumpeBr1 = new javax.swing.JLabel();
        jLabelVentilHClPotisPumpeBr2 = new javax.swing.JLabel();
        jLabelVentilNaOHUsisPumpeBr1 = new javax.swing.JLabel();
        jLabelVentilNaOHPotisPumpeBr1 = new javax.swing.JLabel();
        jLabelVentilNaOHPotisPumpeBr2 = new javax.swing.JLabel();
        jLabelVentilNaOHUsisPumpeBr2 = new javax.swing.JLabel();
        jLabelVentilHClZajednickiPotis = new javax.swing.JLabel();
        jLabelVentilNaOHZajednickiPotis = new javax.swing.JLabel();
        jLabelVentilHClZajednickiUsis = new javax.swing.JLabel();
        jLabelVentilNaOHZajednickiUsis = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabelHClRegVentil01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHClRegVentil01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelHClRegVentil01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHClRegVentil01MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelHClRegVentil01);
        jLabelHClRegVentil01.setBounds(800, 570, 40, 40);

        jLabelHClRegVentil01Vrednost.setText("***");
        getContentPane().add(jLabelHClRegVentil01Vrednost);
        jLabelHClRegVentil01Vrednost.setBounds(840, 580, 50, 16);

        jLabelNaOHRegVentil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNaOHRegVentil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelNaOHRegVentil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNaOHRegVentilMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNaOHRegVentil);
        jLabelNaOHRegVentil.setBounds(950, 570, 40, 40);

        jLabelNaOHRegVentil01Vrednost.setText("***");
        getContentPane().add(jLabelNaOHRegVentil01Vrednost);
        jLabelNaOHRegVentil01Vrednost.setBounds(990, 580, 50, 16);

        jLabelProtokRazredjivanjeHCL.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokRazredjivanjeHCL.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokRazredjivanjeHCL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelProtokRazredjivanjeHCL.setText("***");
        getContentPane().add(jLabelProtokRazredjivanjeHCL);
        jLabelProtokRazredjivanjeHCL.setBounds(720, 510, 90, 16);

        jLabelProtokRazredjivanjeNaOH.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokRazredjivanjeNaOH.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokRazredjivanjeNaOH.setText("***");
        getContentPane().add(jLabelProtokRazredjivanjeNaOH);
        jLabelProtokRazredjivanjeNaOH.setBounds(980, 510, 90, 16);

        jLabelProtokNaOH.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokNaOH.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokNaOH.setText("***");
        getContentPane().add(jLabelProtokNaOH);
        jLabelProtokNaOH.setBounds(1080, 380, 90, 16);

        jLabelProtokHCl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelProtokHCl.setForeground(new java.awt.Color(255, 0, 0));
        jLabelProtokHCl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelProtokHCl.setText("***");
        getContentPane().add(jLabelProtokHCl);
        jLabelProtokHCl.setBounds(560, 380, 90, 16);

        jLabelVentilHClUsisPumpeBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilHClUsisPumpeBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilHClUsisPumpeBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilHClUsisPumpeBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilHClUsisPumpeBr1);
        jLabelVentilHClUsisPumpeBr1.setBounds(550, 730, 30, 40);

        jLabelVentilHClUsisPumpeBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilHClUsisPumpeBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilHClUsisPumpeBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilHClUsisPumpeBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilHClUsisPumpeBr2);
        jLabelVentilHClUsisPumpeBr2.setBounds(420, 730, 30, 40);

        jLabelVentilHClPotisPumpeBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilHClPotisPumpeBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilHClPotisPumpeBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilHClPotisPumpeBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilHClPotisPumpeBr1);
        jLabelVentilHClPotisPumpeBr1.setBounds(550, 540, 30, 50);

        jLabelVentilHClPotisPumpeBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilHClPotisPumpeBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilHClPotisPumpeBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilHClPotisPumpeBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilHClPotisPumpeBr2);
        jLabelVentilHClPotisPumpeBr2.setBounds(420, 540, 30, 50);

        jLabelVentilNaOHUsisPumpeBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilNaOHUsisPumpeBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilNaOHUsisPumpeBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilNaOHUsisPumpeBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilNaOHUsisPumpeBr1);
        jLabelVentilNaOHUsisPumpeBr1.setBounds(1160, 730, 30, 40);

        jLabelVentilNaOHPotisPumpeBr1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilNaOHPotisPumpeBr1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilNaOHPotisPumpeBr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilNaOHPotisPumpeBr1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilNaOHPotisPumpeBr1);
        jLabelVentilNaOHPotisPumpeBr1.setBounds(1160, 540, 30, 50);

        jLabelVentilNaOHPotisPumpeBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilNaOHPotisPumpeBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilNaOHPotisPumpeBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilNaOHPotisPumpeBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilNaOHPotisPumpeBr2);
        jLabelVentilNaOHPotisPumpeBr2.setBounds(1290, 540, 30, 50);

        jLabelVentilNaOHUsisPumpeBr2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilNaOHUsisPumpeBr2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilNaOHUsisPumpeBr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilNaOHUsisPumpeBr2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilNaOHUsisPumpeBr2);
        jLabelVentilNaOHUsisPumpeBr2.setBounds(1290, 730, 30, 40);

        jLabelVentilHClZajednickiPotis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilHClZajednickiPotis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilHClZajednickiPotis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilHClZajednickiPotisMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilHClZajednickiPotis);
        jLabelVentilHClZajednickiPotis.setBounds(480, 400, 40, 50);

        jLabelVentilNaOHZajednickiPotis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilNaOHZajednickiPotis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/vertikalni/pregradni ventil - Greska vertikalno.png"))); // NOI18N
        jLabelVentilNaOHZajednickiPotis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilNaOHZajednickiPotisMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilNaOHZajednickiPotis);
        jLabelVentilNaOHZajednickiPotis.setBounds(1220, 400, 40, 50);

        jLabelVentilHClZajednickiUsis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilHClZajednickiUsis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelVentilHClZajednickiUsis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilHClZajednickiUsisMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilHClZajednickiUsis);
        jLabelVentilHClZajednickiUsis.setBounds(290, 790, 50, 40);

        jLabelVentilNaOHZajednickiUsis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVentilNaOHZajednickiUsis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ventil/horizontalni/pregradni ventil - Greska horizontalno.png"))); // NOI18N
        jLabelVentilNaOHZajednickiUsis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVentilNaOHZajednickiUsisMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelVentilNaOHZajednickiUsis);
        jLabelVentilNaOHZajednickiUsis.setBounds(1410, 790, 50, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/statImg/7 regeneracija.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1740, 980);

        setBounds(170, 35, 1724, 1015);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHClRegVentil01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHClRegVentil01MouseClicked
        allPopUpWindow.ProzorHClvoda();
    }//GEN-LAST:event_jLabelHClRegVentil01MouseClicked

    private void jLabelNaOHRegVentilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNaOHRegVentilMouseClicked
        allPopUpWindow.ProzorNaOHvoda();
    }//GEN-LAST:event_jLabelNaOHRegVentilMouseClicked

    private void jLabelVentilHClUsisPumpeBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilHClUsisPumpeBr1MouseClicked
         allPopUpWindow.ProzorHClUsisPumpeBr1();
    }//GEN-LAST:event_jLabelVentilHClUsisPumpeBr1MouseClicked

    private void jLabelVentilHClUsisPumpeBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilHClUsisPumpeBr2MouseClicked
        allPopUpWindow.ProzorHClUsisPumpeBr2();
    }//GEN-LAST:event_jLabelVentilHClUsisPumpeBr2MouseClicked

    private void jLabelVentilHClPotisPumpeBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilHClPotisPumpeBr1MouseClicked
        allPopUpWindow.ProzorHClPotisPumpeBr1();       
    }//GEN-LAST:event_jLabelVentilHClPotisPumpeBr1MouseClicked

    private void jLabelVentilHClPotisPumpeBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilHClPotisPumpeBr2MouseClicked
        allPopUpWindow.ProzorHClPotisPumpeBr2();
    }//GEN-LAST:event_jLabelVentilHClPotisPumpeBr2MouseClicked

    private void jLabelVentilNaOHUsisPumpeBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilNaOHUsisPumpeBr1MouseClicked
        allPopUpWindow.ProzorNaOHUsisPumpeBr1();
    }//GEN-LAST:event_jLabelVentilNaOHUsisPumpeBr1MouseClicked

    private void jLabelVentilNaOHPotisPumpeBr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilNaOHPotisPumpeBr1MouseClicked
        allPopUpWindow.ProzorNaOHPotisPumpeBr1();
    }//GEN-LAST:event_jLabelVentilNaOHPotisPumpeBr1MouseClicked

    private void jLabelVentilNaOHPotisPumpeBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilNaOHPotisPumpeBr2MouseClicked
        allPopUpWindow.ProzorNaOHPotisPumpeBr2();
    }//GEN-LAST:event_jLabelVentilNaOHPotisPumpeBr2MouseClicked

    private void jLabelVentilNaOHUsisPumpeBr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilNaOHUsisPumpeBr2MouseClicked
        allPopUpWindow.ProzorNaOHUsisPumpeBr2();
    }//GEN-LAST:event_jLabelVentilNaOHUsisPumpeBr2MouseClicked

    private void jLabelVentilHClZajednickiPotisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilHClZajednickiPotisMouseClicked
        allPopUpWindow.ProzorHClZajednickiPotis();
    }//GEN-LAST:event_jLabelVentilHClZajednickiPotisMouseClicked

    private void jLabelVentilNaOHZajednickiPotisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilNaOHZajednickiPotisMouseClicked
        allPopUpWindow.ProzorNaOHZajednickiPotis();
    }//GEN-LAST:event_jLabelVentilNaOHZajednickiPotisMouseClicked

    private void jLabelVentilHClZajednickiUsisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilHClZajednickiUsisMouseClicked
        allPopUpWindow.ProzorHClZajednickiUsisni();
    }//GEN-LAST:event_jLabelVentilHClZajednickiUsisMouseClicked

    private void jLabelVentilNaOHZajednickiUsisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVentilNaOHZajednickiUsisMouseClicked
        allPopUpWindow.ProzorNaOHZajednickiUsisni();
    }//GEN-LAST:event_jLabelVentilNaOHZajednickiUsisMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHClRegVentil01;
    private javax.swing.JLabel jLabelHClRegVentil01Vrednost;
    private javax.swing.JLabel jLabelNaOHRegVentil;
    private javax.swing.JLabel jLabelNaOHRegVentil01Vrednost;
    private javax.swing.JLabel jLabelProtokHCl;
    private javax.swing.JLabel jLabelProtokNaOH;
    private javax.swing.JLabel jLabelProtokRazredjivanjeHCL;
    private javax.swing.JLabel jLabelProtokRazredjivanjeNaOH;
    private javax.swing.JLabel jLabelVentilHClPotisPumpeBr1;
    private javax.swing.JLabel jLabelVentilHClPotisPumpeBr2;
    private javax.swing.JLabel jLabelVentilHClUsisPumpeBr1;
    private javax.swing.JLabel jLabelVentilHClUsisPumpeBr2;
    private javax.swing.JLabel jLabelVentilHClZajednickiPotis;
    private javax.swing.JLabel jLabelVentilHClZajednickiUsis;
    private javax.swing.JLabel jLabelVentilNaOHPotisPumpeBr1;
    private javax.swing.JLabel jLabelVentilNaOHPotisPumpeBr2;
    private javax.swing.JLabel jLabelVentilNaOHUsisPumpeBr1;
    private javax.swing.JLabel jLabelVentilNaOHUsisPumpeBr2;
    private javax.swing.JLabel jLabelVentilNaOHZajednickiPotis;
    private javax.swing.JLabel jLabelVentilNaOHZajednickiUsis;
    // End of variables declaration//GEN-END:variables

    private final AllPopUpWindow allPopUpWindow;
    private final Regeneracija regeneracija;
    private final ProtociRegeneracija protociRegeneracija;
    private final Img img;
    public Timer timer;
    
    
     public void screenRefresh() {
        timer = new Timer(200, new ActionListener() {  //1000 1 sec
            @Override
            public void actionPerformed(ActionEvent e) {
                refreshRegeneracija();
            }
        });

    }

    
     private void refreshRegeneracija(){
        try {
            int a = regeneracija.getRegVentHCl().getVrednosti().getPolozajVrednost();
            img.setImgVertikalno(jLabelHClRegVentil01, AnalogToDigital.isOpen(a), AnalogToDigital.isClose(a));
            jLabelHClRegVentil01Vrednost.setText(ShiftPoint.shiftonePoint(a, regeneracija.getRegVentHCl().getBrDecimala()));
            
            int b = regeneracija.getRegVentNaOH().getVrednosti().getPolozajVrednost();
            img.setImgVertikalno(jLabelNaOHRegVentil, AnalogToDigital.isOpen(b), AnalogToDigital.isClose(b));
            jLabelNaOHRegVentil01Vrednost.setText(ShiftPoint.shiftonePoint(b, regeneracija.getRegVentNaOH().getBrDecimala()));
                        
        } catch (Exception e) {

        }
        
        
        jLabelProtokRazredjivanjeHCL.setText(ShiftPoint.shiftonePoint(protociRegeneracija.getProtokDemiVodeRazblazivanjeHCL().getProtok().getVrednostRegistra(), protociRegeneracija.getProtokDemiVodeRazblazivanjeHCL().getProtok().getBrDec()) + " m3/h");
        jLabelProtokRazredjivanjeNaOH.setText(ShiftPoint.shiftonePoint(protociRegeneracija.getProtokDemiVodeRazblazivanjeNaOH().getProtok().getVrednostRegistra(), protociRegeneracija.getProtokDemiVodeRazblazivanjeNaOH().getProtok().getBrDec()) + " m3/h");
        jLabelProtokNaOH.setText(ShiftPoint.shiftonePoint(protociRegeneracija.getProtokNaOHRegeneracija().getProtok().getVrednostRegistra(), protociRegeneracija.getProtokNaOHRegeneracija().getProtok().getBrDec()) + " m3/h");
        jLabelProtokHCl.setText(ShiftPoint.shiftonePoint(protociRegeneracija.getProtokHClPotisDozirPumpi().getProtok().getVrednostRegistra(), protociRegeneracija.getProtokHClPotisDozirPumpi().getProtok().getBrDec()) + " m3/h");
    
        img.setImgVertikalno(jLabelVentilHClUsisPumpeBr1, regeneracija.getVentHCLusisPumpeBr1());
        img.setImgVertikalno(jLabelVentilHClUsisPumpeBr2, regeneracija.getVentHCLusisPumpeBr2());
        img.setImgVertikalno(jLabelVentilHClPotisPumpeBr1, regeneracija.getVentHCLpotisPumpeBr1());
        img.setImgVertikalno(jLabelVentilHClPotisPumpeBr2, regeneracija.getVentHCLpotisPumpeBr2());
        
        img.setImgVertikalno(jLabelVentilNaOHUsisPumpeBr1, regeneracija.getVentNaOHusisPumpeBr1());
        img.setImgVertikalno(jLabelVentilNaOHUsisPumpeBr2, regeneracija.getVentNaOHusisPumpeBr2());
        img.setImgVertikalno(jLabelVentilNaOHPotisPumpeBr1, regeneracija.getVentNaOHpotisPumpeBr1());
        img.setImgVertikalno(jLabelVentilNaOHPotisPumpeBr2, regeneracija.getVentNaOHpotisPumpeBr2());
        
        img.setImgVertikalno(jLabelVentilHClZajednickiPotis, regeneracija.getVentHCLzajednickiPotis());
        img.setImgVertikalno(jLabelVentilNaOHZajednickiPotis, regeneracija.getVentNaOHzajednickiPotis());
        img.setImgHorizontalno(jLabelVentilHClZajednickiUsis, regeneracija.getVentHCLzajednickiUsis());
        img.setImgHorizontalno(jLabelVentilNaOHZajednickiUsis, regeneracija.getVentNaOHzajednickiUsis());
    }
}
